/*
 * JDlgSelAutobus.java
 *
 * Created on 26 de octubre de 2007, 01:52 PM
 */

package tms_accesoubicacionesX;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import tms_psd.SesionVenta;
import tms_psd.util.BarraMensajes;
import tms_psd.util.JDlgAceptar;

/**
 *
 * @author  ocruz
 */
public class JDlgSelAutobus extends javax.swing.JDialog {
    
    /** Creates new form JDlgSelAutobus */
    public JDlgSelAutobus(SesionVenta pSesionVenta) {
        this.sesionVenta = pSesionVenta;
        initComponents();
        this.setModal(true);
        this.setTitle("Busqueda de Autobus");
        centrarJDialogo();
        inhabilitarF10();
    }
    
    public int getFilaAutobusSeleccionado(){ return this.Fila; }
    
    private void inhabilitarF10() {
        this.jTxtEco.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
        this.jTblAutobuses.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
    }
    
    private void AnchoColumnas(){
        TableColumn column = null;
        int anchoContenedor = jScpAutobuses.getWidth();
        for (int i = 0; i < 4; i++) {
            column = jTblAutobuses.getColumnModel().getColumn(i);
            // "Numero", "Descripcion", "Estado", "Ubicacion", "Actividad"
            switch(i){
                case 0:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.13)); break;
                case 1:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.29)); break;
                case 2:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.29)); break;
                case 3:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.29)); break;
            }
            column.setResizable(false);
        }
    }
    
    private void centrarJDialogo(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, ( screenSize.height - frameSize.height ) / 2 );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLblEco = new javax.swing.JLabel();
        jTxtEco = new javax.swing.JTextField();
        jScpAutobuses = new javax.swing.JScrollPane();
        jTblAutobuses = new javax.swing.JTable();
        jLblBarraEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLblEco.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLblEco.setText("Numero Economico:");

        jTxtEco.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTxtEco.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtEco.setText("%");
        jTxtEco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtEcoKeyPressed(evt);
            }
        });

        jScpAutobuses.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Autobuses", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), java.awt.Color.black));
        jTblAutobuses.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTblAutobuses.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTblAutobuses.setModel(xListado);
        jTblAutobuses.setFocusTraversalKeysEnabled(false);
        jTblAutobuses.getTableHeader().setReorderingAllowed(false);
        jTblAutobuses.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jTblAutobuses.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTblAutobusesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTblAutobusesKeyReleased(evt);
            }
        });

        jScpAutobuses.setViewportView(jTblAutobuses);

        jLblBarraEstado.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLblBarraEstado.setText("ok");
        jLblBarraEstado.setFocusable(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLblBarraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScpAutobuses, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLblEco)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTxtEco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 68, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLblEco)
                    .add(jTxtEco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScpAutobuses, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLblBarraEstado))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTblAutobusesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblAutobusesKeyReleased
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_UP: case KeyEvent.VK_DOWN: 
                case KeyEvent.VK_PAGE_UP: case KeyEvent.VK_PAGE_DOWN: 
                    this.Fila=jTblAutobuses.getSelectedRow();
                break;
        }
    }//GEN-LAST:event_jTblAutobusesKeyReleased

    private void jTxtEcoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtEcoKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE: this.Fila=-1; this.dispose(); break;
            case KeyEvent.VK_ENTER: 
                if(jTxtEco.getText().equals("")){
                    DialogoAceptar = new JDlgAceptar("¡Ingrese un criterio de busqueda!", "Si desea cancelar presione ESC.", Color.RED);
                    return;
                }
                datos = sesionVenta.busquedaAutobus(jTxtEco.getText());
                if(datos==null){
                    DialogoAceptar = new JDlgAceptar("¡La consulta no genero resultados!", "Intentelo con otro criterio.", Color.RED);
                    jTxtEco.selectAll();
                    jTxtEco.requestFocusInWindow();
                    return;
                }
                xListado.setDataVector(datos, encabezado);
                AnchoColumnas();
                jLblBarraEstado.setText(barraMensajes.getMsgAcceso(2));
                this.Fila=0;
                jTblAutobuses.setColumnSelectionInterval(0,0);
                jTblAutobuses.setRowSelectionInterval(0,0);
                jTblAutobuses.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jTxtEcoKeyPressed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
// TODO add your handling code here:
        jLblBarraEstado.setText(barraMensajes.getMsgAcceso(1));
        AnchoColumnas();
        jTxtEco.setText("%");
        jTxtEco.selectAll();
        jTxtEco.requestFocusInWindow();
    }//GEN-LAST:event_formComponentShown

    private void jTblAutobusesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblAutobusesKeyPressed
// TODO add your handling code here:
        if(jTblAutobuses.getSelectedRow()==-1) return;
        switch(evt.getKeyCode()){
            case KeyEvent.VK_F8: this.dispose(); break;
            case KeyEvent.VK_ESCAPE: this.Fila=-1; this.dispose(); break;
            case KeyEvent.VK_ENTER:
                xListado.setDataVector(null, encabezado);
                AnchoColumnas();
                this.Fila=-1;
                jLblBarraEstado.setText(barraMensajes.getMsgAcceso(1));
                jTxtEco.setText("%");
                jTxtEco.selectAll();
                jTxtEco.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jTblAutobusesKeyPressed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLblBarraEstado;
    private javax.swing.JLabel jLblEco;
    private javax.swing.JScrollPane jScpAutobuses;
    private javax.swing.JTable jTblAutobuses;
    private javax.swing.JTextField jTxtEco;
    // End of variables declaration//GEN-END:variables
    private Object[] encabezado = {"Numero", "Estado", "Ubicacion", "Actividad"};
    private DefaultTableModel xListado = new DefaultTableModel(null, encabezado){
            public boolean isCellEditable(int row, int col) {
                return false;
            }   
    };
    private Object[][] datos;
    private SesionVenta sesionVenta;
    private BarraMensajes barraMensajes = new BarraMensajes();

    private JDlgAceptar DialogoAceptar;
    private int Fila=-1;
}
