/*
 * jdlDetalleCorte.java
 *
 * Created on 16 de agosto de 2007, 11:53 AM
 */

package corterecaudacion;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.sql.Timestamp;
import java.util.Vector;
import javax.swing.JComponent;
import javax.swing.JRootPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import xertmsCorteReca.entidad.TmsActividadesSesionTbl;
import xertmsCorteReca.entidad.TmsCortesTbl;
import xertmsCorteReca.entidad.TmsRecoleccionesTbl;
import xertmsCorteReca.entidad.TmsSesionActividadesTbl;
import xertmsCorteReca.entidad.TmsVtaTiposPagoTbl;

/**
 *
 * @author  vgonzalez
 */
public class jdlDetalleCorte extends javax.swing.JDialog {
    
    /**
     * Creates new form jdlDetalleCorte
     */
    public jdlDetalleCorte(String title, long us, TMSCorteRecManagedBean busq, BigDecimal corId, String usc, JIFCorteRecaudacion pprincipal) {
        this.setTitle(title);
        this.setModal(true);
        this.setResizable(false);
        this.usuario = us;
        this.busquedas = busq;
        this.corteId = corId;
        this.usuario_corte = usc;
        this.principal = pprincipal;
        initComponents();
        this.setDefaultLookAndFeelDecorated(true);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension DilaogSize = this.getSize();
        if (DilaogSize.height > screenSize.height) DilaogSize.height = screenSize.height;
        if (DilaogSize.width > screenSize.width) DilaogSize.width = screenSize.width;
        this.setLocation( ( screenSize.width - DilaogSize.width ) / 2, ( screenSize.height - DilaogSize.height ) / 2 );
        Vector recolecciones =(Vector) busquedas.usuariosTblFacadeRemote.buscarRecolecciones(usuario_corte,corId);
        if(Integer.parseInt(recolecciones.get(0).toString())>0)
        {
         jtxt_recsCantidad.setText(recolecciones.get(0).toString());
         jtxt_recsMonto.setText(recolecciones.get(1).toString()+".00");
        }
        System.out.println("Recolecciones para e usuario "+usuario_corte+" con el corte "+corteId+" son: "+recolecciones);
        corte =  busquedas.cortesTblFacadeRemote.find(corteId);
         corte.setEstadoCorte("E");
         corte.setUltimaActualizacionPor(Integer.parseInt(""+usuario));
         Vector x = (Vector) busquedas.cortesTblFacadeRemote.fechaServidor();
         fecha_servidor = fecha_servidor.valueOf(x.get(0).toString());
         corte.setUltimaFechaActualizacion(fecha_servidor);
            //Pone el Corte en estado en Proceso
        busquedas.cortesTblFacadeRemote.edit(corte);
        jlbl_barraEstado.setText("<html>  <font color=FF0000>ESC </font> Cancelar <font color=FF0000> F10 </font> Realizar Corte </html>");
        jlbl_barraEstado.setHorizontalAlignment( JTextField.CENTER );
        jtxt_recMonto.selectAll();
        jtxt_recMonto.requestFocus();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxt_recsCantidad = new tms_TextFields.JNumberTextField();
        jtxt_recsMonto = new tms_TextFields.JCuantityTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jtxt_recCantidad = new tms_TextFields.JNumberTextField();
        jtxt_recMonto = new tms_TextFields.JCuantityTextField();
        jlbl_barraEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cantidades Entregadas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("RECOLECCIONES:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel2.setText("Cantidad");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel3.setText("Monto");

        jtxt_recsCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_recsCantidad.setText("0");
        jtxt_recsCantidad.setEnabled(false);
        jtxt_recsCantidad.setFocusable(false);

        jtxt_recsMonto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxt_recsMonto.setText("0.0");
        jtxt_recsMonto.setEnabled(false);
        jtxt_recsMonto.setFocusable(false);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(154, 154, 154)
                        .add(jLabel2)
                        .add(59, 59, 59)
                        .add(jLabel3))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel1)
                        .add(30, 30, 30)
                        .add(jtxt_recsCantidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 92, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jtxt_recsMonto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(12, 12, 12)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jtxt_recsCantidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jtxt_recsMonto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Formas de Pago", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel4.setText("Tipo de Pago");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel5.setText("Cantidad");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12));
        jLabel6.setText("Monto");

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTextField3.setText("EFECTIVO");

        jtxt_recCantidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxt_recCantidad.setText("1");
        jtxt_recCantidad.setEnabled(false);
        jtxt_recCantidad.setFocusable(false);

        jtxt_recMonto.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxt_recMonto.setText("0.0");
        jtxt_recMonto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_recMontoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxt_recMontoFocusLost(evt);
            }
        });
        jtxt_recMonto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_recMontoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxt_recMontoKeyReleased(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(13, 13, 13)
                        .add(jLabel4)
                        .add(46, 46, 46)
                        .add(jLabel5)
                        .add(63, 63, 63)
                        .add(jLabel6))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 99, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jtxt_recCantidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jtxt_recMonto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(23, 23, 23)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(jLabel5)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtxt_recCantidad, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jtxt_recMonto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jlbl_barraEstado.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlbl_barraEstado.setText("jLabel7");
        jlbl_barraEstado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 487, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(layout.createSequentialGroup()
                .add(35, 35, 35)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(14, 14, 14)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 31, Short.MAX_VALUE)
                .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_recMontoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_recMontoFocusLost
        jtxt_recMonto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_jtxt_recMontoFocusLost

    private void jtxt_recMontoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_recMontoFocusGained
        jtxt_recMonto.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 88, 236)));
    }//GEN-LAST:event_jtxt_recMontoFocusGained

    private void f10_Enable() {
        jtxt_recMonto.registerKeyboardAction( new ActionListener() { public void actionPerformed(ActionEvent e) { ; }},KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0),JComponent.WHEN_FOCUSED);
        jlbl_barraEstado.registerKeyboardAction( new ActionListener() { public void actionPerformed(ActionEvent e) { ; }},KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0),JComponent.WHEN_FOCUSED);
    }    
    
    private void jtxt_recMontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_recMontoKeyReleased
        if(evt.getKeyCode() == evt.VK_ESCAPE)
          salir();

    }//GEN-LAST:event_jtxt_recMontoKeyReleased

    private void jtxt_recMontoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_recMontoKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER || evt.getKeyCode() == evt.VK_DOWN)
            jtxt_recMonto.requestFocus();

        if(evt.getKeyCode() == evt.VK_UP || evt.getKeyCode() == evt.VK_TAB)
            jtxt_recMonto.requestFocus();

        if(evt.getKeyCode() == evt.VK_F10)
            realizarCorte();        
    }//GEN-LAST:event_jtxt_recMontoKeyPressed

    private void jbtn_realizarCorteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtn_realizarCorteKeyPressed
    }//GEN-LAST:event_jbtn_realizarCorteKeyPressed

    private void jbtn_cancelarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtn_cancelarKeyPressed
    }//GEN-LAST:event_jbtn_cancelarKeyPressed

    private void jbtn_realizarCorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_realizarCorteActionPerformed

    }//GEN-LAST:event_jbtn_realizarCorteActionPerformed

    private void jbtn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_cancelarActionPerformed

    }//GEN-LAST:event_jbtn_cancelarActionPerformed
    
    private void salir(){
         jdlg_pregunta_SN psn =  new jdlg_pregunta_SN("Confirmacion de salida ", "¿Seguro que desea salir sin realizar el corte?");
         psn.setVisible(true);
         if(respuestaSN)
        {
         corte.setEstadoCorte("P");
         corte.setUltimaActualizacionPor(Integer.parseInt(""+usuario));
         Vector x = (Vector) busquedas.cortesTblFacadeRemote.fechaServidor();
         fecha_servidor = fecha_servidor.valueOf(x.get(0).toString());
         corte.setUltimaFechaActualizacion(fecha_servidor);
            //Regresa el Corte a estado Pendiente
         busquedas.cortesTblFacadeRemote.edit(corte);
            this.accionCompleta = false;
            this.dispose();            
         }        
    }
    
    private void realizarCorte(){
       if(jtxt_recMonto.getText().equals(".") || (Double.valueOf(jtxt_recCantidad.getText()) > 0 && Double.valueOf(jtxt_recMonto.getText()) == 0 ) || (Double.valueOf(jtxt_recMonto.getText()) > 0 && Double.valueOf(jtxt_recCantidad.getText()) == 0 ))
          //JOptionPane.showMessageDialog(this,"¡Debes introducir montos validos!","Error de Monto",JOptionPane.ERROR_MESSAGE);
          new jdlg_error("¡Debes introducir montos validos!","","Error de Monto").setVisible(true);
       else
       {
//        Jdlg_Pregunta jdp =  new Jdlg_Pregunta("Confirmacion", "¿Seguro que desea realizar el corte?");
//        jdp.setVisible(true);
//        if(jdp.getRespuesta()) 
            Vector TER = (Vector)busquedas.recoleccionesTblFacadeRemote.queryBuscaIdTerminal();
            idTerminal = TER.get(0).toString();
            String te = idTerminal;
            if(idTerminal.length()<3)
            {
               for(int i=idTerminal.length(); i<3;i++)
                   te = te+"0";
            }
            if(idTerminal.length()>=3)
             te = idTerminal.substring(0,2);
                
            idTerminal = te;
           
         jdlg_pregunta_SN psn =  new jdlg_pregunta_SN("Confirmacion", "¿Seguro que desea realizar el corte?");
         psn.setVisible(true);
         if(respuestaSN)
        {
         TmsActividadesSesionTbl actividad = busquedas.actividadesSesionTblFacadeRemote.buscarActividadPorClave("CORTE");
         System.out.println("La actividad es: "+actividad.getNombreActividad());
         TmsVtaTiposPagoTbl tipoPago = busquedas.vtaTiposPagoTblFacadeRemote.buscarTipoPagoPorClave("EFE");
         System.out.println("El tipo de pago es: "+tipoPago.getNombre());
         corte.setEstadoCorte("R");
         corte.setUltimaActualizacionPor(Integer.parseInt(""+usuario));
         Vector x = (Vector) busquedas.cortesTblFacadeRemote.fechaServidor();
         fecha_servidor = fecha_servidor.valueOf(x.get(0).toString());
         corte.setUltimaFechaActualizacion(fecha_servidor);
            //Actualiza el Corte
            busquedas.cortesTblFacadeRemote.edit(corte);
         TmsSesionActividadesTbl sesionActividad = new TmsSesionActividadesTbl();
         sesionActividad.setCorteId(corte);
         sesionActividad.setActividadSesionId(actividad);
         Vector vnfol = (Vector)busquedas.cortesTblFacadeRemote.buscaFolioCorte(usuario_corte);
        Vector npaq = (Vector)busquedas.cortesTblFacadeRemote.queryBuscaNumeroPaqueteActual();
         long nfol = Long.valueOf(vnfol.get(0).toString());
         sesionActividad.setValorActividad(""+(Integer.valueOf(npaq.get(0).toString()) + 1));
         sesionActividad.setValorSecuencial(""+(nfol + 1));
         sesionActividad.setFechaHoraActividad(fecha_servidor);
         sesionActividad.setAutorizadoPor(BigInteger.valueOf(usuario));
         sesionActividad.setCreadoPor(usuario);
         sesionActividad.setFechaCreacion(fecha_servidor);
         sesionActividad.setUltimaActualizacionPor(usuario);
         sesionActividad.setUltimaFechaActualizacion(fecha_servidor);
         TmsSesionActividadesTbl sesionNuevaActividad = busquedas.sesionActividadesTblFacadeRemote.create(sesionActividad, idTerminal);
         TmsRecoleccionesTbl recolecciones = new TmsRecoleccionesTbl();
         TmsRecoleccionesTbl ultimaRecoleccion = new TmsRecoleccionesTbl();
         recolecciones.setSesionActividadId(BigInteger.valueOf(Long.valueOf(""+sesionNuevaActividad.getSesionActividadId())));
         recolecciones.setReferencia("RECOLECCIONES");
         if(jtxt_recsCantidad.getText().equals("") || jtxt_recsCantidad.getText().equals("0"))
          ;
         else
           recolecciones.setCantidad(BigInteger.valueOf(Long.valueOf(jtxt_recsCantidad.getText())));
         if(jtxt_recsMonto.getText().equals("") || jtxt_recsMonto.getText().equals("0.0") || jtxt_recsMonto.getText().equals(".0") || jtxt_recsMonto.getText().equals("0."))
           ;
         else
            recolecciones.setMonto(BigDecimal.valueOf(Double.valueOf(jtxt_recsMonto.getText())));
         recolecciones.setAutorizadoPor(BigInteger.valueOf(usuario));
         recolecciones.setCreadoPor(BigInteger.valueOf(usuario));
         recolecciones.setFechaCreacion(fecha_servidor);
         recolecciones.setUltimaActualizacionPor(BigInteger.valueOf(usuario));
         recolecciones.setUltimaFechaActualizacion(fecha_servidor);
         //Agrega la informacion de las recolecciones 
            busquedas.recoleccionesTblFacadeRemote.create(recolecciones,idTerminal);
         ultimaRecoleccion.setSesionActividadId(BigInteger.valueOf(Long.valueOf(""+sesionNuevaActividad.getSesionActividadId())));
         ultimaRecoleccion.setTipoPagoId(tipoPago);
         ultimaRecoleccion.setReferencia(tipoPago.getClave());
         if(jtxt_recCantidad.getText().equals("") || jtxt_recCantidad.getText().equals("0"))
          ultimaRecoleccion.setCantidad(BigInteger.valueOf((long)0));
         else
           ultimaRecoleccion.setCantidad(BigInteger.valueOf(Long.valueOf(jtxt_recCantidad.getText())));
         if(jtxt_recMonto.getText().equals("") || jtxt_recMonto.getText().equals("0.0") || jtxt_recMonto.getText().equals("0") || jtxt_recMonto.getText().equals(".0") || jtxt_recMonto.getText().equals("0."))
           ultimaRecoleccion.setMonto(BigDecimal.valueOf((long)0));
         else
            ultimaRecoleccion.setMonto(BigDecimal.valueOf(Double.valueOf(jtxt_recMonto.getText())));
         ultimaRecoleccion.setAutorizadoPor(BigInteger.valueOf(usuario));
         ultimaRecoleccion.setCreadoPor(BigInteger.valueOf(usuario));
         ultimaRecoleccion.setFechaCreacion(fecha_servidor);
         ultimaRecoleccion.setUltimaActualizacionPor(BigInteger.valueOf(usuario));
         ultimaRecoleccion.setUltimaFechaActualizacion(fecha_servidor);
         //Agrega la ultima recoleccion
            busquedas.recoleccionesTblFacadeRemote.create(ultimaRecoleccion,idTerminal);
        //JOptionPane.showMessageDialog(this,"¡El corte se realizo satisfactoriamente!","Corte Realizado",JOptionPane.INFORMATION_MESSAGE);
        new jdlg_informacion("¡El corte se realizo satisfactoriamente! ","El corte se mostrará a continuacion","Corte Realizado").setVisible(true);
        //Jdlg_Pregunta jdpimp =  new Jdlg_Pregunta("Corte Realizado", "¡Corte realizado!. ¿Desea imprimir el corte?");
        //jdpimp.setVisible(true);
        //if(jdpimp.getRespuesta()) 
        //{
           System.out.println("Se imprime el corte....."); 
        //}         
         this.accionCompleta = true;
         principal.mandaImprimirCorte();
         this.dispose();
       }
     }//if(cantidades validas)    
    }
    
 public boolean getAccionCompleta(){
     return this.accionCompleta;
 }   
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel jlbl_barraEstado;
    private tms_TextFields.JNumberTextField jtxt_recCantidad;
    private tms_TextFields.JCuantityTextField jtxt_recMonto;
    private tms_TextFields.JNumberTextField jtxt_recsCantidad;
    private tms_TextFields.JCuantityTextField jtxt_recsMonto;
    // End of variables declaration//GEN-END:variables
    private BigDecimal corteId;
    private boolean accionCompleta= false;
    private long usuario;
    private TMSCorteRecManagedBean busquedas;
    String usuario_corte= "";
    private boolean respuestaSN;
    private Timestamp fecha_servidor;
    private TmsCortesTbl corte;
    private String idTerminal;
    private JIFCorteRecaudacion principal;

 class jdlg_pregunta_SN extends javax.swing.JDialog {
    
    /**
     * Creates new form jdlg_pregunta_SN
     */
    public jdlg_pregunta_SN(String titulo, String pregunta){
        this.setTitle(titulo);
        this.setModal(true);
        this.setDefaultLookAndFeelDecorated(true);
        this.setUndecorated(true);
        this.getRootPane().setWindowDecorationStyle(JRootPane.QUESTION_DIALOG);
        this.setAlwaysOnTop(true);
        initComponents();
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);        
        this.setResizable(false);
        jlbl_mensaje.setText(pregunta);
        jlbl_barraEstado.setText("<html>  <font color=FF0000>ENTER: </font> Si                 <font color=FF0000>             ESC: </font> No  </html>");
        jlbl_barraEstado.setHorizontalAlignment( JTextField.CENTER );
        int nletras = pregunta.length();
        this.setSize((nletras * 6) + 80,150);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            Dimension DilaogSize = this.getSize();
            if (DilaogSize.height > screenSize.height) {
                DilaogSize.height = screenSize.height;
            }
            if (DilaogSize.width > screenSize.width) {
                DilaogSize.width = screenSize.width;
            }
            this.setLocation( ( screenSize.width - DilaogSize.width ) / 2, ( screenSize.height - DilaogSize.height ) / 2 );            this.setDefaultLookAndFeelDecorated(true);
            //this.setUndecorated(true);
            this.getRootPane().setWindowDecorationStyle(JRootPane.QUESTION_DIALOG);
            jlbl_mensaje.requestFocus();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jlbl_barraEstado = new javax.swing.JLabel();
        jlbl_mensaje = new javax.swing.JLabel();
        jlbl_mensaje.setFocusTraversalKeysEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\NetBeansProyects\\TMSRecaudacion\\TMSRecaudacion-app-client\\src\\java\\tmsrecaudacion\\images\\pregunta.gif"));

        jlbl_barraEstado.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlbl_barraEstado.setForeground(new java.awt.Color(153, 153, 153));
        jlbl_barraEstado.setText(" ENTER: Si                ESC: No");
        jlbl_barraEstado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jlbl_mensaje.setFont(new java.awt.Font("Arial", 1, 12));
        jlbl_mensaje.setText("sdfsdsdfsdfsdfsdfsdf");
        jlbl_mensaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jlbl_mensajekeyReleased(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(14, 14, 14)
                .add(jlbl_mensaje, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .add(424, 424, 424))
            .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlbl_mensaje))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 59, Short.MAX_VALUE)
                .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>                           

    private void jlbl_mensajekeyReleased(java.awt.event.KeyEvent evt) {                                        
      if(evt.getKeyCode() == evt.VK_ESCAPE)
      {
          respuestaSN = false;
          this.dispose();
      }
      if(evt.getKeyCode() == evt.VK_ENTER)
      {
          respuestaSN = true;
          this.dispose();
      }
      
    }                                       
    
    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlbl_barraEstado;
    private javax.swing.JLabel jlbl_mensaje;
    // End of variables declaration                   
    
}       
}
