/*
 * JPnlVDM.java
 *
 * Created on 25 de septiembre de 2008, 11:29 AM
 */

package xer_emv_dll.Paneles;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import subProcesos.JNumberTextFieldMaxDig;
import subProcesos.JTextTextFieldMaxCharAlfa;
import tms_venta.JClsColoresInterfaz;

/**
 *
 * @author  ocruz
 */
public class JPnlVDM extends javax.swing.JPanel {
    
    /**
     * Creates new form JPnlVDM
     */
    public JPnlVDM(KeyListener pKl) {
        this.kl = pKl;
        this.addKeyListener(kl);
        initComponents();
        interfazColor();
        this.setVisible(true);
    }
    
    private void interfazColor(){
        this.setBackground(ColoresInterfaz.cFondoPieEncabezado);
        
        this.jLabel1.setForeground(ColoresInterfaz.cTexto1);
        this.jLabel2.setForeground(ColoresInterfaz.cTexto1);
        this.jLabel3.setForeground(ColoresInterfaz.cTexto1);
        this.jLabel4.setForeground(ColoresInterfaz.cTexto1);
        this.jLabel5.setForeground(ColoresInterfaz.cTexto1);
        
        this.jTextField1.setForeground(ColoresInterfaz.cFondoPieEncabezado);
        this.jTextField2.setForeground(ColoresInterfaz.cFondoPieEncabezado);
        this.jTextField3.setForeground(ColoresInterfaz.cFondoPieEncabezado);
        this.jTextField4.setForeground(ColoresInterfaz.cFondoPieEncabezado);
        this.jTextField5.setForeground(ColoresInterfaz.cFondoPieEncabezado);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new JTextTextFieldMaxCharAlfa(40);
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new JNumberTextFieldMaxDig(16);
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new JNumberTextFieldMaxDig(2);
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new JNumberTextFieldMaxDig(2);
        jTextField5 = new JNumberTextFieldMaxDig(4);
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese los siguientes valores:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Calibri", 1, 16), java.awt.Color.white));
        setFocusable(false);
        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14));
        jLabel1.setText("Nombre del Tarjetahabiente:");
        jLabel1.setFocusable(false);
        this.jLabel1.addKeyListener(kl);

        jTextField1.setFont(new java.awt.Font("Calibri", 1, 14));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        this.jTextField1.addKeyListener(kl);
        this.jTextField1.setFocusTraversalKeysEnabled(false);
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14));
        jLabel2.setText("N\u00famero de Tarjeta:");
        jLabel2.setFocusable(false);
        this.jLabel2.addKeyListener(kl);

        jTextField2.setFont(new java.awt.Font("Calibri", 1, 14));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        this.jTextField2.addKeyListener(kl);
        this.jTextField2.setFocusTraversalKeysEnabled(false);
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14));
        jLabel3.setText("Mes de Expiraci\u00f3n:");
        jLabel3.setFocusable(false);
        this.jLabel3.addKeyListener(kl);

        jTextField3.setFont(new java.awt.Font("Calibri", 1, 14));
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        this.jTextField3.addKeyListener(kl);
        this.jTextField3.setFocusTraversalKeysEnabled(false);
        jTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField3FocusLost(evt);
            }
        });
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Calibri", 1, 14));
        jLabel4.setText("A\u00f1o de Expiraci\u00f3n:");
        jLabel4.setFocusable(false);
        this.jLabel4.addKeyListener(kl);

        jTextField4.setFont(new java.awt.Font("Calibri", 1, 14));
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        this.jTextField4.addKeyListener(kl);
        this.jTextField4.setFocusTraversalKeysEnabled(false);
        jTextField4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField4KeyPressed(evt);
            }
        });

        jTextField5.setFont(new java.awt.Font("Calibri", 1, 14));
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        this.jTextField5.addKeyListener(kl);
        this.jTextField5.setFocusTraversalKeysEnabled(false);
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField5KeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Calibri", 1, 14));
        jLabel5.setText("C\u00f3digo de Seguridad:");
        jLabel5.setFocusable(false);
        this.jLabel5.addKeyListener(kl);

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 12));
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Dato obligatorio");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(39, 39, 39)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel4)
                            .add(jLabel3)
                            .add(jLabel2)
                            .add(jLabel5)))
                    .add(jLabel1))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 146, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jTextField4)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jTextField3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE))
                    .add(jTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(205, 205, 205)
                .add(jLabel6)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jTextField2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jTextField3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jTextField4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jLabel6)
                    .add(jTextField5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField5KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_UP: jTextField4.selectAll(); jTextField4.requestFocusInWindow(); break;
            case KeyEvent.VK_DOWN: case KeyEvent.VK_ENTER: jTextField1.selectAll(); jTextField1.requestFocusInWindow(); break;
        }
    }//GEN-LAST:event_jTextField5KeyPressed

    private void jTextField4KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField4KeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_UP: jTextField3.selectAll(); jTextField3.requestFocusInWindow(); break;
            case KeyEvent.VK_DOWN: case KeyEvent.VK_ENTER: jTextField5.selectAll(); jTextField5.requestFocusInWindow(); break;
        }
    }//GEN-LAST:event_jTextField4KeyPressed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_UP: jTextField2.selectAll(); jTextField2.requestFocusInWindow(); break;
            case KeyEvent.VK_DOWN: case KeyEvent.VK_ENTER: jTextField4.selectAll(); jTextField4.requestFocusInWindow(); break;
        }
    }//GEN-LAST:event_jTextField3KeyPressed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_UP: jTextField1.selectAll(); jTextField1.requestFocusInWindow(); break;
            case KeyEvent.VK_DOWN: case KeyEvent.VK_ENTER: jTextField3.selectAll(); jTextField3.requestFocusInWindow(); break;
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_UP: jTextField5.selectAll(); jTextField5.requestFocusInWindow(); break;
            case KeyEvent.VK_DOWN: case KeyEvent.VK_ENTER: jTextField2.selectAll(); jTextField2.requestFocusInWindow(); break;
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField3FocusLost
// TODO add your handling code here:
        if(!jTextField3.getText().equals("")){
            int n = Integer.valueOf(jTextField3.getText());
            if(0<n && n<13){
                if(jTextField3.getText().length()==1){
                    jTextField3.setText("0"+jTextField3.getText());
                }
                datosIngresados = true;
                jTextField3.setBackground(Color.YELLOW);
                return;
            }
        }
        else{
            datosIngresados = false;
            return;
        }
        jTextField3.setBackground(Color.RED);
        datosIngresados = false;
    }//GEN-LAST:event_jTextField3FocusLost
    public void setNombreTH(String string){ jTextField1.setText(string); }
    
    public void setNumeroTarjeta(String string){ jTextField2.setText(string); }
    
    public void setMes(String string){ jTextField3.setText(string); }
    
    public void setAnio(String string){ jTextField4.setText(string); }
    
    public void setCodigoSeg(String string){ jTextField5.setText(string); }
    
    public String getNombreTH(){ return jTextField1.getText(); }
    
    public String getNumeroTarjeta(){ return jTextField2.getText(); }
    
    public String getMes(){ return jTextField3.getText(); }
    
    public String getAnio(){ return jTextField4.getText(); }
    
    public String getCodigoSeg(){ return jTextField5.getText(); }
    
    public void setFoco(){ 
        System.out.println("Entra a poner el foco");
        jTextField1.requestFocusInWindow(); }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
    private JClsColoresInterfaz ColoresInterfaz = new JClsColoresInterfaz();
    private KeyListener kl;
    private boolean datosIngresados;
}
