/*
 * JDLG_Refoliar.java
 *
 * Created on 12 de enero de 2009, 05:43 PM
 */

package tmsfacturarcodigobarras;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author  asolis
 */
public class JDLG_Refoliar extends javax.swing.JDialog {
   public int fol_ini = 0;
   public int fol_fin = 0;
   public String prefijo_ini = "";
   public String prefijo_fin = "";
   public String prefijo ="";
   private int fol_ini_inicial = 0;
   private String series[] = {"CAPU", "TCU","TAPO","TTA","CAR","TCM","ANIMAS","TLA","4PTE","TCP","AERO","TTU","AERO","TTD"};//4PTE","T4P","AERO","TT1","AERO","TT2"};
   public boolean ban = true;
   int longFactura = 8;
   int num_terminales = 7;
   String terminal = "";
   
    /** Creates new form JDLG_Refoliar */
    public JDLG_Refoliar(java.awt.Frame parent, int fin, int ini, boolean ban, String terminal) {
        initComponents();
        fol_fin = fin;
        fol_ini = ini;
        this.ban = ban;
        jtxt_fonfinal.setText(String.valueOf(fin));
        jtxt_fonini.setText(String.valueOf(ini));
        jtxt_fonfinal.setEditable(false);
        jtxt_fonini.setEditable(false);
        jtxt_fonini.setBackground(new Color(192,190,207));
        jtxt_fonini.requestFocus();
        this.terminal = terminal;
        System.out.println("TERMINAL "+terminal);
        if(ban)
            jlbl_barraEstado.setText("<html>  <font color=FF0000>  ESC </font> Salir de Facturar Boleto | <font color=FF0000> F5 </font> Introducir Folios de Facturas | <font color=FF0000> ENTER </font> Refoliar| <font color=FF0000> ARRIBA/ABAJO </font> Moverse entre campos</html>");
        else
            jlbl_barraEstado.setText("<html>  <font color=FF0000> F5 </font> Introducir Folios de Facturas | <font color=FF0000> ENTER </font> Refoliar | <font color=FF0000> ARRIBA/ABAJO </font> Moverse entre campos</html>");
    }
    
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jlbl_barraEstado = new javax.swing.JLabel();
        jlbl_folini = new javax.swing.JLabel();
        jlbl_folfinal = new javax.swing.JLabel();
        jtxt_fonini = new tms_TextFields.JTextTextField();
        jtxt_fonfinal = new tms_TextFields.JTextTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Refoliar Facturas");
        setModal(true);
        setResizable(false);

        jlbl_folini.setText("Folio Inicial:");

        jlbl_folfinal.setText("Folio Final:");

        jtxt_fonini.setEditable(false);
        jtxt_fonini.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_foniniFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxt_foniniFocusLost(evt);
            }
        });
        jtxt_fonini.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_foniniKeyPressed(evt);
            }
        });

        jtxt_fonfinal.setEditable(false);
        jtxt_fonfinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_fonfinalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxt_fonfinalFocusLost(evt);
            }
        });
        jtxt_fonfinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_fonfinalKeyPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 503, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jlbl_folini, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jtxt_fonini, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(39, 39, 39)
                .add(jlbl_folfinal)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jtxt_fonfinal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(34, 34, 34)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jlbl_folini)
                        .add(jtxt_fonini, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jlbl_folfinal)
                        .add(jtxt_fonfinal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 40, Short.MAX_VALUE)
                .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_foniniFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_foniniFocusGained
        jtxt_fonini.setBackground(new Color(192,190,207));
    }//GEN-LAST:event_jtxt_foniniFocusGained

    private void jtxt_fonfinalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_fonfinalFocusLost
        jtxt_fonfinal.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jtxt_fonfinalFocusLost

    private void jtxt_foniniFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_foniniFocusLost
        jtxt_fonini.setBackground(new Color(255,255,255));
    }//GEN-LAST:event_jtxt_foniniFocusLost

    private void jtxt_fonfinalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_fonfinalFocusGained
        jtxt_fonfinal.setBackground(new Color(192,190,207));
    }//GEN-LAST:event_jtxt_fonfinalFocusGained

    private void jtxt_fonfinalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_fonfinalKeyPressed
        if((evt.getKeyCode() == evt.VK_DOWN)||(evt.getKeyCode() == evt.VK_UP)) {
            jtxt_fonini.setBackground(new Color(192,190,207));
            jtxt_fonini.requestFocus();
        }
        evento(evt);
    }//GEN-LAST:event_jtxt_fonfinalKeyPressed

    private void jtxt_foniniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_foniniKeyPressed
        if((evt.getKeyCode() == evt.VK_DOWN)||(evt.getKeyCode() == evt.VK_UP))
            jtxt_fonfinal.requestFocus();
        evento(evt);
    }//GEN-LAST:event_jtxt_foniniKeyPressed

    private void evento(KeyEvent evt) {
        if((evt.getKeyCode() == evt.VK_ESCAPE) && (ban == true)) {
            /*int result = JOptionPane.showOptionDialog(this, "¿Desea cerrar Refoliar Facturas?",
                    "TMS-Refoliar Facturas", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if(result == JOptionPane.YES_OPTION)*/
                this.dispose();
        }
        
        if(evt.getKeyCode() == evt.VK_F5) {
            jtxt_fonfinal.setText("");
            jtxt_fonini.setText("");
            jtxt_fonfinal.setEditable(true);
            jtxt_fonini.setEditable(true);
            jtxt_fonini.setBackground(new Color(192,190,207));
            jtxt_fonini.requestFocus();
        }
   
        if(evt.getKeyCode() == evt.VK_ENTER) {
           System.out.println("Terminal  "+terminal); 
          System.out.println("jtxt_fonini.getText().length() "+jtxt_fonini.getText().length() + " jtxt_fonfinal.getText().length() "+jtxt_fonfinal.getText().length());  
          if((!jtxt_fonfinal.getText().equals("")&& !jtxt_fonini.getText().equals("")) && (jtxt_fonini.getText().length() == longFactura)&&(jtxt_fonfinal.getText().length() == longFactura)) {
              prefijo_fin = jtxt_fonfinal.getText().substring(0,3);
              prefijo_ini = jtxt_fonini.getText().substring(0,3);
              boolean bienFormado = true;
              for(int i = 0; i < 2; i++)
                if((prefijo_ini.charAt(i) < 'A') || (prefijo_ini.charAt(i) > 'Z')||(prefijo_fin.charAt(i) < 'A') || (prefijo_fin.charAt(i) > 'Z')) {
                    bienFormado = false;
                    break;
                }
              if((jtxt_fonfinal.getText().charAt(3) != ' ')) {
                  jtxt_fonini.setBackground(new Color(192,190,207));
                  jtxt_fonfinal.setText("");
                  jtxt_fonini.setText("");
                  jtxt_fonini.requestFocus();
                  bienFormado = false;
              }
              
              try {
                  fol_fin = Integer.parseInt(jtxt_fonfinal.getText().substring(4,jtxt_fonfinal.getText().length()));
                  fol_ini = Integer.parseInt(jtxt_fonini.getText().substring(4,jtxt_fonfinal.getText().length()));
                  System.out.println(" fol_fin  "+fol_fin);
                  System.out.println(" fol_ini  "+fol_ini);
              }catch(Exception e)
              {   
                 jtxt_fonini.setBackground(new Color(192,190,207));
                 jtxt_fonfinal.setText("");
                 jtxt_fonini.setText("");
                 jtxt_fonini.requestFocus();
                 bienFormado = false;
              }
              if(bienFormado) {
                  System.out.println ("Bien Formado");
              System.out.println("prefijo_ini "+prefijo_ini +" prefijo_fin "+prefijo_fin);
              if(prefijo_ini.equals(prefijo_fin)) {
                  String prefijoTerminal_act = "nada";
                  for(int j = 1; j < num_terminales*2; j+=2){
                        if(prefijo_ini.equals(series[j]))
                          prefijoTerminal_act = series[j-1];
                  System.out.println("series[j] "+series[j]);
                  }
                  System.out.println("prefijoTerminal_act "+prefijoTerminal_act);
                  
                  if(!prefijoTerminal_act.equals("nada")) {
                      if(prefijoTerminal_act.equals(terminal)) {
                          /*fol_fin = Integer.parseInt(jtxt_fonfinal.getText().substring(4,jtxt_fonfinal.getText().length()));
                          fol_ini = Integer.parseInt(jtxt_fonini.getText().substring(4,jtxt_fonfinal.getText().length()));*/
                        if(fol_fin < fol_ini)
                            JOptionPane.showMessageDialog( this, "El folio final es menor que el inicial",
                                    "TMS - Refoliar Facturas", JOptionPane.ERROR_MESSAGE );
                        else   
                            if(fol_fin == 0 || fol_ini == 0) {
                                JOptionPane.showMessageDialog( this, "No ha cambiado los folios. Por favor verifique el número de folios nuevamente",
                                    "TMS - Refoliar Facturas", JOptionPane.ERROR_MESSAGE );
                                 jtxt_fonini.setBackground(new Color(192,190,207));
                                 jtxt_fonini.requestFocus();
                            }
                            else {
                                        prefijo = prefijo_ini;
                                        JOptionPane.showMessageDialog( this, "Los folios fueron cambiados correctamente",
                                            "TMS - Refoliar Facturas", JOptionPane.WARNING_MESSAGE );
                                        this.dispose();
                           }
                      }else {
                          JOptionPane.showMessageDialog( this, "La serie de la factura no coincide con la terminal en la que se encuentra, por favor verifique nuevamente",
                            "TMS - Refoliar Facturas", JOptionPane.ERROR_MESSAGE );
                          jtxt_fonini.setBackground(new Color(192,190,207));
                          /*jtxt_fonfinal.setText("");
                          jtxt_fonini.setText("");*/
                          jtxt_fonini.requestFocus();
                      }
                }else {
                    JOptionPane.showMessageDialog( this, "La serie de la factura que ingresó no coincide con ninguna terminal",
                            "TMS - Refoliar Facturas", JOptionPane.ERROR_MESSAGE );
                    jtxt_fonini.setBackground(new Color(192,190,207));
                    jtxt_fonfinal.setText("");
                    jtxt_fonini.setText("");
                    jtxt_fonini.requestFocus();
                    //jtxt_fonini.setBackground(new Color(192,190,207));
                }
              }else{
                  JOptionPane.showMessageDialog( this, "La serie de la factura que ingresó como folio de inicio no coincide con la serie del folio final, por favor verifique e intente nuevamente",
                            "TMS - Refoliar Facturas", JOptionPane.ERROR_MESSAGE );
                    jtxt_fonini.setBackground(new Color(192,190,207));
                    /*jtxt_fonfinal.setText("");
                    jtxt_fonini.setText("");*/
                    jtxt_fonini.requestFocus();
              } 
             }else {
                    JOptionPane.showMessageDialog( this, "El folio de la factura no coincide con el prototipo del mismo. Verifique e intente nuevamente",
                            "TMS - Refoliar Facturas", JOptionPane.ERROR_MESSAGE );
                    jtxt_fonini.setBackground(new Color(192,190,207));
                    jtxt_fonfinal.setText("");
                    jtxt_fonini.setText("");
                    jtxt_fonini.requestFocus();
             }
            }else{
                   JOptionPane.showMessageDialog( this, "Alguno de los campos folio inicial o final no tiene la longitud esperada",
                            "TMS - Refoliar Facturas", JOptionPane.ERROR_MESSAGE );
                    jtxt_fonini.setBackground(new Color(192,190,207));
                    /*jtxt_fonfinal.setText("");
                    jtxt_fonini.setText("");*/
                    jtxt_fonini.requestFocus();
              }
                
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbl_barraEstado;
    private javax.swing.JLabel jlbl_folfinal;
    private javax.swing.JLabel jlbl_folini;
    private tms_TextFields.JTextTextField jtxt_fonfinal;
    private tms_TextFields.JTextTextField jtxt_fonini;
    // End of variables declaration//GEN-END:variables
    
}
