/*
 * JDlgPMT.java
 *
 * Created on 7 de octubre de 2008, 09:24 AM
 */

package tms_incidencias.rol;

import DialogosIncidencias.JDlgAceptar;
import DialogosIncidencias.JDlgSiNo;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.FileOutputStream;
import java.io.PrintStream;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.StringTokenizer;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import tms_incidencias.SesionVenta;

/**
 *
 * @author  ocruz
 */
public class JDlgPMT extends javax.swing.JDialog implements KeyListener, ListSelectionListener{
    
    /* Creates new form JDlgPMT */
    private Object[] anhos = new Object[5];
     int xA = 0;
     int xM = 0;
    public  static Cursor busyCursor = Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR);
    public  static Cursor defaultCursor = Cursor.getDefaultCursor();

    public JDlgPMT(SesionVenta pSesionVenta) {
        System.out.println(" ENTRANDO a JDlgPMT");
        this.sesionVenta = pSesionVenta;
        this.setModal(true);
        initComponents();
        insertaJTableInOtherJTable();
        AnchoColumnas1(); //AnchoColumnas2();
        estableceViewPort();
        centrarJDialog();
       
        for(int i=0; i<sesionVenta.getTmsServiciosTbl().size(); i++)
            jCboServicio.addItem(sesionVenta.getTmsServiciosTbl().get(i).getServicioNombre());
        for(int i=0; i<sesionVenta.getTmsEmpresasTbl().size(); i++)
            jCboEmpresa.addItem(sesionVenta.getTmsEmpresasTbl().get(i).getEmpresaNombre());
        jCboServicio.setSelectedIndex(0);
        jCboEmpresa.setSelectedIndex(0);
        jScpPMT.setName("-1");
        this.jCboServicio.requestFocusInWindow();
        
        String date=sesionVenta.getToDate();
     
         xA = Integer.valueOf(date.substring(6,10));
         xM = Integer.valueOf(date.substring(4,5));
        
       // System.out.println("xA    **************  "+xA +"   MES "+xM);
        for(int i=-1; i<4; i++)
            anhos[i+1] = xA+i;   
        jCboAgno.removeAllItems();
        
        DefaultComboBoxModel  defaultModel =new DefaultComboBoxModel(anhos);
        jCboAgno.setModel(defaultModel);
        jCboAgno.setSelectedItem(xA);
        datosGralFecha();
        
        
         jCboMes.setSelectedIndex(xM-1);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jCboServicio = new javax.swing.JComboBox();
        jCboServicio.addKeyListener(this);
        jCboServicio.setFocusTraversalKeysEnabled(false);
        jLabel2 = new javax.swing.JLabel();
        jCboEmpresa = new javax.swing.JComboBox();
        jCboEmpresa.addKeyListener(this);
        jCboEmpresa.setFocusTraversalKeysEnabled(false);
        jLabel3 = new javax.swing.JLabel();
        jCboMes = new javax.swing.JComboBox();
        jCboMes.addKeyListener(this);
        jCboMes.setFocusTraversalKeysEnabled(false);
        jScpPMT = new javax.swing.JScrollPane();
        jScpPMT.addKeyListener(this);
        jScpPMT.setFocusTraversalKeysEnabled(false);
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCboAgno = new javax.swing.JComboBox();
        jCboAgno.addKeyListener(this);
        jCboAgno.setFocusTraversalKeysEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Programa Mensual de Trabajo");
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Servicio:");

        jCboServicio.setFont(new java.awt.Font("Tahoma", 1, 11));
        jCboServicio.setName("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Empresa:");

        jCboEmpresa.setFont(new java.awt.Font("Tahoma", 1, 11));
        jCboEmpresa.setName("0");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Mes:");

        jCboMes.setFont(new java.awt.Font("Tahoma", 1, 11));
        jCboMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jCboMes.setName("0");
        jCboMes.setSelectedIndex(0);

        jScpPMT.setName("-2");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("<HTML><FONT COLOR=FF0000>F3</FONT> Generar Programa Mensual de Trabajo | <FONT COLOR=FF0000>Doble Clic</FONT> Mostrar observaciones | <FONT COLOR=FF0000>F5</FONT> Exportar datos a Excel | <FONT COLOR=FF0000>ESC</FONT> Cerrar Ventana</HTML>");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("A\u00f1o:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jScpPMT, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 852, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCboServicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 222, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCboEmpresa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCboMes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 142, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(16, 16, 16)
                        .add(jLabel5)
                        .add(16, 16, 16)
                        .add(jCboAgno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jCboServicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(jCboEmpresa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jCboMes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5)
                    .add(jCboAgno, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScpPMT, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void insertaJTableInOtherJTable() {
        jTblPMT2 = new JTable();
        jTblPMT2.setName("-1");
        jTblPMT2.setDefaultRenderer(Object.class, new colorOperadoresRenderer1());
        jTblPMT2.addKeyListener(this);
        jTblPMT2.setFocusTraversalKeysEnabled(false);
        jTblPMT2.setModel(xTabla2);
        jTblPMT2.setRowHeight(36);
        jTblPMT1 = new JTable();
        jTblPMT1.setName("-1");
        jTblPMT1.setRowHeight(36);
        jTblPMT1.setDefaultRenderer(Object.class, new colorOperadoresRenderer());
        jTblPMT1.addKeyListener(this);
        jTblPMT1.setFocusTraversalKeysEnabled(false);
        jTblPMT1.setModel(xTabla1);
        jTblPMT2.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                jTblPMT2_mouseClicked(e);
            }
        });
        jTblPMT1.setFont(new Font("Dialog", 1, 11));
        jTblPMT2.setFont(new Font("Dialog", 1, 11));
        jTblPMT1.setBackground(new Color(251,251,251));
        jTblPMT2.setBackground(Color.WHITE);
        jTblPMT1.getTableHeader().setFont(new Font("Dialog", 1, 11));
        jTblPMT2.getTableHeader().setFont(new Font("Dialog", 1, 11));
        jTblPMT1.getTableHeader().setBackground(new Color(236,233,216));//new Color(255,182,108));
        jTblPMT2.getTableHeader().setBackground(new Color(236,233,216));//new Color(255,207,159));
        jTblPMT1.getTableHeader().setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTblPMT2.getTableHeader().setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTblPMT1.getTableHeader().setReorderingAllowed(false);
        jTblPMT2.getTableHeader().setReorderingAllowed(false);
        jTblPMT1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTblPMT2.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        jTblPMT1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTblPMT2.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTblPMT1.getSelectionModel().addListSelectionListener(this);
        jTblPMT2.getSelectionModel().addListSelectionListener(this);
        
        jScpPMT.getViewport().add(jTblPMT2, null);
        viewport = new JViewport();
        viewport.setView(jTblPMT1);
        viewport.setPreferredSize(jTblPMT1.getPreferredSize());
        viewport.setMaximumSize(jTblPMT1.getPreferredSize());
        
        jScpPMT.setRowHeaderView(viewport);
        jScpPMT.setCorner(JScrollPane.UPPER_LEFT_CORNER, jTblPMT1.getTableHeader());
    }
    
    private void estableceViewPort(){
        viewport.setView(jTblPMT1);
        viewport.setPreferredSize(jTblPMT1.getPreferredSize());
        jScpPMT.setRowHeaderView(viewport);
        jScpPMT.setCorner(JScrollPane.UPPER_LEFT_CORNER, jTblPMT1.getTableHeader());
    }
        
    private void jTblPMT2_mouseClicked(MouseEvent e) {
        if(e.getButton()==MouseEvent.BUTTON1){
            if(e.getClickCount()==2){
                jwinDetRol = new JDlgComentarios(comentario[jTblPMT2.getSelectedRow()][jTblPMT2.getSelectedColumn()]);
            }
        }
    }
    
    private void AnchoColumnas1() {
        int anchoContenedor = (int)(jScpPMT.getWidth()*0.40);
        TableColumn column;        
        for (int i = 0; i < jTblPMT1.getColumnCount(); i++) {
            column = jTblPMT1.getColumnModel().getColumn(i);
            switch (i) {
                case 0: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.18)); break;
                case 1: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.66)); break;
                case 2: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.16)); break;
            }
        }
    }
    
    /*private void AnchoColumnas2() {
        int anchoContenedor = (int)(jScpPMT.getWidth()*0.65);
        TableColumn column;
        
        if(jTblPMT2.getColumnCount()==1){
            column = jTblPMT1.getColumnModel().getColumn(0);
            column.setPreferredWidth(anchoContenedor);
            return;
        }

        float p = (1/ultimo_dia_mes)*10;
        for (int i = 0; i < ultimo_dia_mes; i++) {
            column = jTblPMT2.getColumnModel().getColumn(i);
            column.setPreferredWidth(Math.round(anchoContenedor*p));
        }
    }*/
    
    public void construyeEncabezadoDias(){
        encabezado2 = new Object[ultimo_dia_mes];
        for(int i=0; i<ultimo_dia_mes; i++)
            encabezado2[i] = i+1;
    }
    
    private void centrarJDialog(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, ( screenSize.height - frameSize.height ) / 2 );
    }
    
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JDlgPMT(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }*/

    private void datosGralFecha() {
        cal = GregorianCalendar.getInstance();
        // BRA anho = cal.get(GregorianCalendar.YEAR);
        anho = Integer.parseInt(jCboAgno.getSelectedItem().toString());
    }
    
    private void ultimoDiaMes(int mes) {
        if(cal==null) return;
        anho = Integer.parseInt(jCboAgno.getSelectedItem().toString());
        mes = ( mes<0 ? 0  :mes); 
        cal.set(anho, mes, 1);
        ultimo_dia_mes = cal.getActualMaximum(GregorianCalendar.DAY_OF_MONTH);
     
        vMes = String.valueOf(mes + 1);
        
        vMes = (vMes.length()==1? ("0"+vMes):vMes )+"/"+anho;
     //   System.out.println("ultimoDiaMes.Anho/mes: "+anho+" "+vMes+" - ultimo_dia_mes: "+ultimo_dia_mes);
    }

    public void keyTyped(KeyEvent e) {
    }

    public void keyPressed(KeyEvent e) {
        int compo = (e.getComponent()==null || e.getComponent().getName()==null ? -3 : Integer.valueOf(e.getComponent().getName()));
   //    System.out.println("keyPressed en JPMT   "+e.getKeyCode());
        switch(e.getKeyCode()){
            case KeyEvent.VK_F3  :   
                switch(compo){ 
                    case 0:
                        generaReporte();
                        break;
                    
                }  // 
            break;
            case 123:
                        generaReporte();
                        break;   
            case KeyEvent.VK_RIGHT:
                switch(compo){
                    case 0:
                        if(jCboServicio.isFocusOwner())
                            jCboEmpresa.requestFocusInWindow();
                        else if(jCboEmpresa.isFocusOwner())
                                 jCboMes.requestFocusInWindow();
                        else if(jCboMes.isFocusOwner())  
                                 jCboAgno.requestFocusInWindow();
                        else if(jCboAgno.isFocusOwner())
                                 jCboServicio.requestFocusInWindow();
                        break;
                }
            break;
/*            case KeyEvent.VK_UP: case KeyEvent.VK_DOWN:
                switch(compo){
                    case -1:
                        if (jTblPMT1.isFocusOwner()){
                            int row = jTblPMT1.getSelectedRow();
                            if(row<0) return;
                            jTblPMT2.setRowSelectionInterval(row, row);
                        }
                        else if (jTblPMT2.isFocusOwner()){
                            int row = jTblPMT2.getSelectedRow();
                            if(row<0) return;
                            jTblPMT1.setRowSelectionInterval(row, row);
                        }
                    break;
                }
            break;*/
            case KeyEvent.VK_F5:
                switch(compo){
                    case -1:
                        ExportarAExcel();
                    break;
                }
            break;
            case KeyEvent.VK_LEFT:
                switch(compo){
                    case 0:
                        if(jCboServicio.isFocusOwner())
                            jCboAgno.requestFocusInWindow();
                        else if(jCboEmpresa.isFocusOwner())
                                 jCboServicio.requestFocusInWindow();
                        else if(jCboMes.isFocusOwner())
                                 jCboEmpresa.requestFocusInWindow();
                        else  if(jCboAgno.isFocusOwner())
                            jCboMes.requestFocusInWindow();
                        break;
                        
                }
            break;
            case KeyEvent.VK_ESCAPE:
                if(compo==0){
                    DialogoSiNo = new JDlgSiNo("TMS Venta.", "<html>Confirme,<br>¿Desea cerrar la ventana?</html>");
                    if(!DialogoSiNo.getResultado()) return;
                    this.dispose();
                    return;
                }
                limpiaPMT();  
            break;
        }
    }
    public  void generaReporte()
    {
        DialogoSiNo = new JDlgSiNo("TMS Venta.","<html>Confirme,<br>¿Desea calcular el programa mensual de trabajo?</html>");
        if(!DialogoSiNo.getResultado()) return;

        this.setCursor(busyCursor);
        if(jCboEmpresa.getSelectedIndex()<0 || jCboServicio.getSelectedIndex()<0 || jCboMes.getSelectedIndex()<0){
            DialogoAceptar = new JDlgAceptar("TMS Venta.", "La consulta no genero resultados.", Color.RED);
            this.setCursor(defaultCursor);
            return;
        }
        ultimoDiaMes(jCboMes.getSelectedIndex());
        String x = sesionVenta.obtenerPMT(vMes,jCboEmpresa.getSelectedItem().toString(),jCboServicio.getSelectedItem().toString());
      
        if(!ConstruyePMT(x)){
            limpiaPMT();
            DialogoAceptar = new JDlgAceptar("TMS Venta.", "La consulta no genero resultados.", Color.RED);
            this.setCursor(defaultCursor);
            return;
        }
        AnchoColumnas1(); //AnchoColumnas2();
        estableceViewPort();
        if(jTblPMT2.getModel().getRowCount() >0)
            jTblPMT2.setRowSelectionInterval(0,0);
        jTblPMT2.requestFocusInWindow();
        this.setCursor(defaultCursor);
    }
    
    public void keyReleased(KeyEvent e) {
    }

    private void limpiaPMT(){
        encabezado1[0] = "Operador";
        encabezado1[1] = "Nombre";
        encabezado1[2] = "Autobus";
        xTabla1.setDataVector(null,encabezado1);
        encabezado2 = new Object[1];
        encabezado2[0] = "Dias";
        xTabla2.setDataVector(null,encabezado2);
        AnchoColumnas1();
        estableceViewPort();
        jCboServicio.setSelectedIndex(0);
        jCboEmpresa.setSelectedIndex(0);
        jCboAgno.setSelectedItem(xA);
        jCboMes.setSelectedIndex(xM-1);
      
    }   // 
    
    private boolean ConstruyePMT(String strMpt) {
        
        if(strMpt==null||strMpt.trim().length() == 0 ) return false;
        
        System.out.println("-*************** Si hay datos para el reporte mensual " );
        strMpt=strMpt.replaceAll("null","");
        //     System.out.println("2.- "+strMpt);
        try{
            StringTokenizer tfilas, tdato, tenc, tdet, tact;
            String enc, det, operador, autobus, inci, ccor, detdia, categoria;
            
            tfilas = new StringTokenizer(strMpt,"|");
            //System.out.println("Filas = "+tfilas.countTokens());
            
            dato1 = new Object[tfilas.countTokens()][4]; // pos 3 - categoria operador.
            dato2 = new Object[tfilas.countTokens()][ultimo_dia_mes];
            comentario = new String[tfilas.countTokens()][ultimo_dia_mes];
            int j, i;
             for(i=0; i<comentario.length; i++)
                for(j=0; j<ultimo_dia_mes; j++)
                    comentario[i][j] = "";
          
            String[] z = null;
            i=0;
            while(tfilas.hasMoreTokens()){
                tdato = new StringTokenizer(tfilas.nextToken(),"&");
            //    System.out.println("Datos = "+tdato.countTokens()+" FILA "+i);
                enc = tdato.nextToken();
                if(!tdato.hasMoreTokens()) return false;
                det = tdato.nextToken();
                tenc = new StringTokenizer(enc,","); 
                operador = tenc.nextToken();
                autobus = tenc.nextToken();
                categoria = tenc.nextToken();
                dato1[i][0] = operador;
                dato1[i][1] = sesionVenta.getNombreOperador(operador);
                dato1[i][2] = autobus;
                dato1[i][3] = categoria;
              //      System.out.println("Datos1 = "+dato1[i][0]+" "+dato1[i][1]+"  "+ dato1[i][2]+"  "+dato1[i][3]);
                tdet = new StringTokenizer(det,",");
                //System.out.println("det = "+tdet.countTokens());
                j=0;
                while(j<ultimo_dia_mes){
                    detdia = tdet.nextToken();
                    tact = new StringTokenizer(detdia,";");
                    //System.out.println("act = "+tact.countTokens()+" dia "+detdia);
                    inci = tact.nextToken();
                    ccor = tact.nextToken(); 
               //     System.out.println("  inci  "+inci+"   ccor  "+ccor);
                    if(!inci.equals("SINC")){
                        z = obtieneIncDia(inci);
                   //     System.out.println("z  "+z);
                        dato2[i][j] = sesionVenta.getActividad(Long.valueOf(z[0].toString()));
                        comentario[i][j] += z[1].toString();
                    }
                    else
                        dato2[i][j] = "-";  
                   
                    if(!ccor.equals("SCOR")){
                        z = obtieneCCorDia(ccor);
                        dato2[i][j] = (dato2[i][j].toString().equals("-") ? z[0].toString() : dato2[i][j].toString() + "<br>" + z[0].toString());
                        comentario[i][j] += (comentario[i][j].equals("-") ? z[1].toString() : comentario[i][j] +"<br>" + z[1].toString());
                        
                    }  
                 //   System.out.println("---> "+dato2[i][j]+" --->>> comentario: "+comentario[i][j]);
                    dato2[i][j] = (dato2[i][j].toString().equals("-") ? "-" : "<html>"+dato2[i][j].toString()+"</html>");
                   // System.out.println("---------> "+dato2[i][j]);
                    j++;
                }
                
                i++;
            }
            construyeEncabezadoDias();
            xTabla1.setDataVector(dato1,encabezado1);
            xTabla2.setDataVector(dato2,encabezado2);
        }catch(Exception ex){
            ex.printStackTrace();
            return false;
        }
        
        return true;
    }
    
    private String[] obtieneIncDia(String info){
        String[] x = new String[3];
        StringTokenizer inci = new StringTokenizer(info,"-");
        //System.out.println("inci = "+inci.countTokens()+" --- info--- "+info);
        x[0] = inci.nextToken();
        x[1] = inci.nextToken();
        x[2] = inci.nextToken();
        if(x[1].equals("VACIO") && x[2].equals("VACIO")){
            x[1]="";
            return x;
        }
        if(x[1].equals("VACIO")) x[1]="";
        if(x[2].equals("VACIO")) x[2]="";
        else x[1]=(x[1].equals("")?x[2]:x[1]+"<br>"+x[2]);
        return x;
    }
    
    private String[] obtieneCCorDia(String info){
        StringTokenizer ccor = new StringTokenizer(info,"-");
        //System.out.println("ccor = "+ccor.countTokens());
        String[] x = new String[2];
        if(ccor.countTokens()<=0){
            x[0] = ""; x[1] = "";
        }
        else{
            x[0] = ccor.countTokens()+" corridas";
            x[1] = "";
            while(ccor.hasMoreTokens()){
                x[1] = x[1]+ccor.nextToken()+", ";
                //System.out.println(x[1]);
            }
            x[1] = x[1].substring(0,x[1].length()-2);
        }
        return x;
    }

    private void ExportarAExcel() {
        if(jTblPMT2.getRowCount()<=0){
            DialogoAceptar = new JDlgAceptar("TMS Venta.", "No existen datos a exportar.", Color.RED);
            return;
        }
        
       this.setCursor(busyCursor); 
        String sCad = "", valor1, valor2;
        int i, j;
        sCad += "Operador \t"+"Nombre \t"+"Autobus \t";
        for (int k = 0; k < encabezado2.length; k++) 
            sCad += encabezado2[k]+"\t";
       sCad += "\n";
         
        for(i=0; i<jTblPMT2.getRowCount(); i++){
            for(j=0; j<jTblPMT1.getColumnCount(); j++)
                sCad += jTblPMT1.getValueAt(i,j)+"\t";
            for(j=0; j<jTblPMT2.getColumnCount(); j++){
                valor1 = jTblPMT2.getValueAt(i,j).toString().replaceAll("<html>","").replaceAll("</html>","").replaceAll("<br>","-");
                valor2 = comentario[i][j].replaceAll("<br>","-");
                valor1 += " "+valor2;
                sCad += valor1+"\t";
            }
            sCad += "\n";
        }
     //   System.out.println("encabezado2 "+encabezado2.length);
     //   System.out.println("jTblPMT2.getColumnCount() "+jTblPMT2.getColumnCount());
        
        String lastfile_name = "\\PMT_Mes_"+(this.vMes.replace("/","_"))+".xls";
      //  System.out.println("lastfile_name "+lastfile_name);
        String curDir = System.getProperty("user.home");
       // BRA String SalidaImpresion = "C:\\PMT_Mes_"+lastfile_name;
        String SalidaImpresion = curDir+lastfile_name;
       // System.out.println("SalidaImpresion "+SalidaImpresion);
        boolean bandera=false;
        try{
            FileOutputStream os = new FileOutputStream(SalidaImpresion); // LPT / C:\\ARCHIVO.TXT / COM
            PrintStream ps = new PrintStream(os); 
            
            ps.print(sCad); // CADENA A IMPRIMIR
            ps.flush();
            os.close();
            bandera = true;
        }catch(java.io.FileNotFoundException fsctex){
            fsctex.printStackTrace();
        }catch(Exception sctex){
            sctex.printStackTrace();
        }
        
        if(!bandera){
            DialogoAceptar = new JDlgAceptar("TMS Venta.","No fue posible crear el archivo de Excel.", Color.RED);
            return;
        }
        
        DialogoAceptar = new JDlgAceptar("TMS Venta.","<HTML>Los datos fueron exportados en  "+SalidaImpresion+"<br> correctamente.</HTML>", Color.BLACK);
        this.setCursor(defaultCursor);
    }

    public void valueChanged(ListSelectionEvent e) {
        ListSelectionModel source = (ListSelectionModel) e.getSource();
        if (source==jTblPMT1.getSelectionModel()){
            int row = jTblPMT1.getSelectedRow();
            if(row<0) return;
            jTblPMT2.setRowSelectionInterval(row, row);
        }
        else{
            int row = jTblPMT2.getSelectedRow();
            if(row<0) return;
            jTblPMT1.setRowSelectionInterval(row, row);
        }
    }
    
    private class colorOperadoresRenderer extends DefaultTableCellRenderer{
        public Component getTableCellRendererComponent(JTable table, Object value, boolean selected,
            boolean focused, int row, int column){
            super.getTableCellRendererComponent(table, value, selected, focused, row, column);
            
            if(dato1[row][3].equals("0")) setBackground(new Color(251,251,251));
            else if(dato1[row][3].equals("1")) setBackground(new Color(51,255,51)); // verde
            else if(dato1[row][3].equals("2")) setBackground(new Color(255,51,51));  // rojo
            else setBackground(new Color(251,251,251));  // Blanco
            setHorizontalAlignment(JLabel.CENTER);
            
            if(row==jTblPMT1.getSelectedRow()) setBorder(lb);
            
            return this;
        }
    }

    private class colorOperadoresRenderer1 extends DefaultTableCellRenderer{
        public Component getTableCellRendererComponent(JTable table, Object value, boolean selected,
            boolean focused, int row, int column){
            super.getTableCellRendererComponent(table, value, selected, focused, row, column);
            
            if(dato1[row][3].equals("0")) setBackground(Color.WHITE);
            else if(dato1[row][3].equals("1")) setBackground(new Color(153,255,153));
            else if(dato1[row][3].equals("2")) setBackground(new Color(255,153,153));
            else setBackground(Color.WHITE);
            
            if(row==jTblPMT2.getSelectedRow() && column ==jTblPMT2.getSelectedColumn()){
                setBackground(colorDialogoActivo);
                setForeground(Color.WHITE);
            }
            else{
                setForeground(Color.BLACK);
                if(row==jTblPMT2.getSelectedRow()) setBorder(lb);
            }
            
            return this;
        }
    }//  
      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCboAgno;
    private javax.swing.JComboBox jCboEmpresa;
    private javax.swing.JComboBox jCboMes;
    private javax.swing.JComboBox jCboServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScpPMT;
    // End of variables declaration//GEN-END:variables
    private JTable jTblPMT2 = null;
    private JViewport viewport = null;
    private JTable jTblPMT1 = null;
    
    private Object[] encabezado1 = {"Operador", "Nombre", "Autobus"};
    private Object[][] dato1 = null;
    private DefaultTableModel xTabla1 = new DefaultTableModel(null,encabezado1){
        public boolean isCellEditable(int row, int col){
            return false;
        }
    };
    private Object[] encabezado2 = {"Dias"};
    private Object[][] dato2 = null;
    private DefaultTableModel xTabla2 = new DefaultTableModel(null,encabezado2){
        public boolean isCellEditable(int row, int col){
            return false;
        }
    };
    private String[][] comentario = null;
    private Calendar cal;
    private int ultimo_dia_mes;
    private int anho;
    private String vMes;
    private JDlgComentarios jwinDetRol;
    private SesionVenta sesionVenta;
    private JDlgSiNo DialogoSiNo = null;
    private JDlgAceptar DialogoAceptar = null;
    private Color colorDialogoActivo = new Color(96,192,255);
    private javax.swing.border.LineBorder lb = new javax.swing.border.LineBorder(colorDialogoActivo, 1, false);
}
