/*
 * JDlgOperador.java
 *
 * Created on 19 de noviembre de 2007, 12:20 PM
 */

package DialogosIncidencias;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import tms_incidencias.SesionVenta;

/**
 *
 * @author  ocruz
 */
public class JDlgOperador extends javax.swing.JDialog {
    
    /** Creates new form JDlgOperador */
    public JDlgOperador(SesionVenta pSesionVenta) {
        this.sesionVenta = pSesionVenta;
        this.setModal(true);
        initComponents();
        centrarJDialog();
    }
    
    private void AnchoColumnas() {
        int anchoContenedor = jScrollPane1.getWidth();
        TableColumn column;
        for (int i = 0; i < jTable1.getColumnCount(); i++) {
            column = jTable1.getColumnModel().getColumn(i);
            switch (i) {
                case 0: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.10)); break;
                case 1: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.45)); break;
                case 2: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.15)); break;
                case 3: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.15)); break;
                case 4: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.15)); break;
            }
        }
    }
    
    private void centrarJDialog(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, ( screenSize.height - frameSize.height ) / 2 );
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setFocusTraversalKeysEnabled(false);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTable1.setFocusTraversalKeysEnabled(false);
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Seleccionar Operador");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Numero Operador:");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("%");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable1.setModel(xTabla);
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });

        jScrollPane1.setViewportView(jTable1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("<html><font color=ff0000>ENTER</font> Buscar Operador | <font color=ff0000>F5</font> Aceptar Operador | <font color=ff0000>ESC</font> Cancelar</html>");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 96, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ENTER:
                jTable1.requestFocusInWindow();
                break;
            case KeyEvent.VK_ESCAPE:
                xTabla.setDataVector(null,encabezado);
                AnchoColumnas();
                jTextField1.setText("%");
                jTextField1.selectAll();
                jTextField1.requestFocusInWindow();
                break;
            case KeyEvent.VK_F5:
                /*if(xTabla.getValueAt(jTable1.getSelectedRow(),2).toString().equals("FUERA DE ROL")){
                    DialogoAceptar = new JDlgAceptar("¡Este operador no esta disponible!", "Seleccione otro si lo desea.", Color.RED);
                    return;
                }*/
                sesionVenta.setFilaOperadorSeleccionado(jTable1.getSelectedRow());
                Evento = true;
                this.dispose();
                break;
        }
    }//GEN-LAST:event_jTable1KeyPressed
    
    public boolean getEvento(){ return this.Evento; }
    
    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ENTER:
                if(jTextField1.getText().equals("")){
                    DialogoAceptar = new JDlgAceptar("Ingrese Criterio de busqueda", "Presione Enter para continuar", Color.RED);
                    jTextField1.setText("%");
                    jTextField1.selectAll();
                    return;
                }
                datos=sesionVenta.buscarOperador(jTextField1.getText());
                if(datos==null){
                    DialogoAceptar = new JDlgAceptar("¡No existen operadores!", "El criterio de busqueda no genero resultados", Color.RED);
                    jTextField1.setText("%");
                    jTextField1.selectAll();
                    return;
                }
                xTabla.setDataVector(datos,encabezado);
                AnchoColumnas();
                jTable1.setRowSelectionInterval(0,0);
                jTable1.requestFocusInWindow();
                break;
            case KeyEvent.VK_ESCAPE:
                Evento = false;
                this.dispose();
                break;
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
// TODO add your handling code here:
        xTabla.setDataVector(null, encabezado);
        AnchoColumnas();
        jTextField1.selectAll();
        jTextField1.requestFocusInWindow();
    }//GEN-LAST:event_formComponentShown
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
    private boolean Evento;
    private Object[] encabezado = {"Numero", "Nombre", "Estado", "Ubicacion", "Actividad"};
    private DefaultTableModel xTabla = new DefaultTableModel(null,encabezado){
        public boolean isCellEditable(int row, int col){
            return false;
        }
    };
    private Object[][] datos = null;
    private SesionVenta sesionVenta;

    private JDlgAceptar DialogoAceptar;
}
