/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
 
/*
 * JdlgChecadasBiometrico.java
 *
 * Created on 28/03/2014, 07:07:47 PM
 */

package tms_guardias;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.lang.Object;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;

/**
 *
 * @author vgonzalez
 */
public class JdlgViajesRealizados extends javax.swing.JDialog {

    /** Creates new form JdlgChecadasBiometrico */
    public JdlgViajesRealizados(java.awt.Frame parent, boolean modal, String registros,String operador, String titulo) {
        super(parent, modal);
        initComponents();
        jLabel1.setText(titulo);
         //System.out.println("registros: "+registros);
        String[] res = registros.split("\\|");
        DefaultTableModel  model = (DefaultTableModel )jtblRegistros.getModel();
        for(int i=1; i<res.length; i++ )
        {
            //System.out.println("res["+i+"]: "+res[i]);
            String[] row = res[i].split(",");
            Vector v = new Vector();
            v.add(row[0].toString());
            v.add(row[1].toString());
            v.add(row[2].toString());
            v.add(row[3].toString());
            v.add(row[4].toString());
            v.add(row[5].toString());
            v.add(row[6].toString());
            v.add(row[7].toString());
            v.add(row[8].toString());
            model.addRow(v);
        }

        jLabel2.setText(operador);
        jtblRegistros.setModel(model);
        AnchoColumnas();
        jtblRegistros.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jtblRegistros.setDefaultRenderer(Object.class, new CustomTableCellRenderer());
        jbtnCerrar.requestFocusInWindow();

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblRegistros = new javax.swing.JTable();
        jbtnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VIAJES REALIZADOS");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("OPERADOR");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Viajes Realizados", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jtblRegistros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FECHA CORRIDA", "CLAVE CORRIDA", "FOLIO TARJETA", "ORIGEN", "DESTINO", "OPERADOR", "AUTOBUS", "SERVICIO", "EMPRESA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtblRegistros.setRowHeight(24);
        jScrollPane1.setViewportView(jtblRegistros);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jbtnCerrar.setText("Cerrar");
        jbtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCerrarActionPerformed(evt);
            }
        });
        jbtnCerrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jbtnCerrarKeyPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
                .addContainerGap())
            .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 856, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(396, 396, 396)
                .add(jbtnCerrar)
                .addContainerGap(395, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel2)
                .add(18, 18, 18)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jbtnCerrar)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbtnCerrarActionPerformed

    private void jbtnCerrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtnCerrarKeyPressed
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ENTER: this.dispose(); break;
        }
    }//GEN-LAST:event_jbtnCerrarKeyPressed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
    }

    private void AnchoColumnas(){
        TableColumn column = null;
        int anchoContenedor = (int)jScrollPane1.getWidth();
        for (int i = 0; i < 9; i++) {
            column = jtblRegistros.getColumnModel().getColumn(i);
            switch(i){
                case 0:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.15)); break;
                case 1:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.15)); break;
                case 2:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.15)); break;
                case 3:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.10)); break;
                case 4:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.10)); break;
                case 5:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.10)); break;
                case 6:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.10)); break;
                case 7:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.10)); break;
                case 8:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.10)); break;
            }
            column.setResizable(false);
        }
    }

    class CustomTableCellRenderer extends DefaultTableCellRenderer{

    public Component getTableCellRendererComponent (JTable table,Object obj, boolean isSelected, boolean hasFocus, int row, int column) {
        Component cell = super.getTableCellRendererComponent(table, obj, isSelected, hasFocus, row, column);
        //System.out.println("Row("+row+") ServSinRet: "+((Guia)FacturasPendientesTableModel.guias.get(row)).getServicioSinRet());
        if (isSelected) {
            cell.setBackground(new Color(0,175,255));
            cell.setForeground(Color.WHITE);
        }
        else {
            cell.setForeground(Color.BLACK);
            if (row % 2 == 0) {
                cell.setBackground(new Color(217,229,241));
            }
            else {
                cell.setBackground(Color.WHITE);
            }
        }
 /*           if (isSelected) {
                cell.setBackground(new Color(184,207,229));
                cell.setForeground(Color.BLACK);
            }
            else
            {

                    cell.setBackground(Color.WHITE);
                    cell.setForeground(Color.BLACK);
            }
  *
  */
            setHorizontalAlignment(JTextField.LEFT);

        return cell;
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnCerrar;
    private javax.swing.JTable jtblRegistros;
    // End of variables declaration//GEN-END:variables

}
