/*
 * JDlgVentaRuta.java
 *
 * Created on 19 de mayo de 2008, 11:34 AM
 */

package Reportes.VentaDiaria;

import DialogosExeRrp.JClsImpresionReporte;
import DialogosExeRrp.JDlgAceptar;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.JDialog;
import tms_ejecutarreportes.modelo.EmpresasComboBoxModel;
import tms_ejecutarreportes.modelo.ServiciosComboBoxModel;
import tms_exerpt.entidad.TmsEmpresasTbl;
import tms_exerpt.entidad.TmsServiciosTbl;
import tms_exerpt.solicitud.TmsEmpresasTblFacadeRemote;
import tms_exerpt.solicitud.TmsServiciosTblFacadeRemote;

/**
 *
 * @author  ocruz
 */
public class JDlgVentaRuta extends JDialog implements KeyListener {
    
    /** Creates new form JDlgVentaRuta */
    public JDlgVentaRuta(String tltReporte, JClsImpresionReporte jClsImpresionReporte, String preporte, boolean ocultar) {
        this.setModal(true);
        initComponents();
        this.setTitle(tltReporte);
        this.jClsImpresionReporte = jClsImpresionReporte;
        this.reporte = preporte;
        
        servicioFacadeRemote = lookupTmsServiciosTblFacade();
        empresaFacateRemote = lookupTmsEmpresasTblFacade();
        cargarServicios();
        cargarEmpresas();
        jTxtFi.dateEditor.addKeyListener1(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtFiKeyPressed2(evt);
            }
        });
        jTxtFf.dateEditor.addKeyListener1(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtFfKeyPressed2(evt);
            }
        });
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension DilaogSize = this.getSize();
        if (DilaogSize.height > screenSize.height) {
            DilaogSize.height = screenSize.height;
        }
        if (DilaogSize.width > screenSize.width) {
            DilaogSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - DilaogSize.width ) / 2, ( screenSize.height - DilaogSize.height ) / 2 );  
        jLabel5.setVisible(!ocultar);
        jLabel6.setVisible(!ocultar);
        jLabel7.setVisible(!ocultar);
        jCmbEmpresa.setVisible(!ocultar);
        jTxtOperador.setVisible(!ocultar);
        jTxtAutobus.setVisible(!ocultar);
        jTxtFi.dateEditor.setFoco();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtOperador = new tms_TextFields.JTextTextField();
        jTxtOperador.addKeyListener(this);
        jTxtAutobus = new tms_TextFields.JTextTextField();
        jTxtAutobus.addKeyListener(this);
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jCmbServicio = new javax.swing.JComboBox();
        jCmbServicio.addKeyListener(this);
        jTxtFi = new tms_calendario.JDateChooser();
        jTxtFi.addKeyListener(this);
        jTxtFf = new tms_calendario.JDateChooser();
        jTxtFf.addKeyListener(this);
        jCmbEmpresa = new javax.swing.JComboBox();
        jCmbEmpresa.addKeyListener(this);
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ingrese par\u00e1metros: ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), java.awt.Color.black));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Fecha Inicial:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Servicio:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Fecha Final:");

        jTxtOperador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtOperadorKeyPressed(evt);
            }
        });

        jTxtAutobus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtAutobusKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("Empresa:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("Operador:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setText("Autobus:");

        jCmbServicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1" }));
        jCmbServicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCmbServicioKeyPressed(evt);
            }
        });

        jTxtFi.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTxtFiAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jCmbEmpresa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1" }));
        jCmbEmpresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCmbEmpresaKeyPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(26, 26, 26)
                                .add(jLabel2)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jCmbServicio, 0, 227, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel1)
                                    .add(jPanel1Layout.createSequentialGroup()
                                        .add(8, 8, 8)
                                        .add(jLabel3)))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 91, Short.MAX_VALUE)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                    .add(jTxtFf, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jTxtFi, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))))
                        .add(0, 0, 0))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel6)
                            .add(jLabel5)
                            .add(jLabel7))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jCmbEmpresa, 0, 227, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, jTxtAutobus, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, jTxtOperador, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1)
                    .add(jTxtFi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(9, 9, 9)
                        .add(jLabel3))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTxtFf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(12, 12, 12)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCmbServicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCmbEmpresa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(jTxtOperador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(jTxtAutobus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("<html><font color=ff0000>F10</font> Ejecutar Reporte | <font color=ff0000>ESC</font> Cerrar</html>");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtAutobusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtAutobusKeyPressed
        if(evt.getKeyCode() == evt.VK_DOWN)
            jTxtFi.dateEditor.setFoco();
        
        if(evt.getKeyCode() == evt.VK_UP)
            jTxtOperador.requestFocus(); 
    }//GEN-LAST:event_jTxtAutobusKeyPressed

    private void jTxtOperadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtOperadorKeyPressed
        if(evt.getKeyCode() == evt.VK_DOWN)
            jTxtAutobus.requestFocus();
        
        if(evt.getKeyCode() == evt.VK_UP)
            jCmbEmpresa.requestFocus();        
    }//GEN-LAST:event_jTxtOperadorKeyPressed

    private void jCmbEmpresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCmbEmpresaKeyPressed
        if(evt.getKeyCode() == evt.VK_RIGHT)
            jTxtOperador.requestFocus();
        
        if(evt.getKeyCode() == evt.VK_LEFT)
            jCmbServicio.requestFocus();
    }//GEN-LAST:event_jCmbEmpresaKeyPressed

    private void jCmbServicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCmbServicioKeyPressed
        if(evt.getKeyCode() == evt.VK_RIGHT)
        {
            if(jCmbEmpresa.isVisible())
              jCmbEmpresa.requestFocus();
            else
                jTxtFi.dateEditor.setFoco();
        }
        
        if(evt.getKeyCode() == evt.VK_LEFT)
            jTxtFf.dateEditor.setFoco();    
    }//GEN-LAST:event_jCmbServicioKeyPressed

    private void jTxtFiAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTxtFiAncestorAdded
// TODO add your handling code here:
    }//GEN-LAST:event_jTxtFiAncestorAdded


    private void jTxtFiKeyPressed2(java.awt.event.KeyEvent evt) {                                  
        if(evt.getKeyCode() == evt.VK_DOWN)
            jTxtFf.dateEditor.setFoco();
        
        if(evt.getKeyCode() == evt.VK_UP)
            jTxtAutobus.requestFocus();
    } 
    
     private void jTxtFfKeyPressed2(java.awt.event.KeyEvent evt) {                                  
        if(evt.getKeyCode() == evt.VK_DOWN)
            jCmbServicio.requestFocus();
        
        if(evt.getKeyCode() == evt.VK_UP)
            jTxtFi.dateEditor.setFoco();
    }            
    private boolean ejecutaReporteJasper(){
        Map param = new HashMap();
        param.put("FechaInicial",jTxtFi.dateEditor.getTexto());        
        param.put("FechaFinal",jTxtFf.dateEditor.getTexto());   
        System.out.println("Fecha Inicial:"+jTxtFi.dateEditor.getTexto());
        System.out.println("Fecha Inicial:"+jTxtFf.dateEditor.getTexto());
        if(jCmbServicio.getSelectedItem().toString().equals("Todos"))
        {
            System.out.println("Manda el servcio null");
            param.put("NumeroServicio",null);
        }
        else
            param.put("NumeroServicio",((ServiciosComboBoxModel)jCmbServicio.getModel()).getServicio(jCmbServicio.getSelectedIndex()).getServicioNumero());
        if(jCmbEmpresa.getSelectedItem().toString().equals("Todas"))
        {
            System.out.println("Manda empresa null");
           param.put("NombreEmpresa",null);
        }
        else
            param.put("NombreEmpresa",((EmpresasComboBoxModel)jCmbEmpresa.getModel()).getEmpresa(jCmbEmpresa.getSelectedIndex()).getEmpresaNombre());            
        
        if (jTxtAutobus.getText().equals("")) {
            System.out.println("AutobusId: "+null);
            param.put("AutobusId",null);
        }
        else {
            Vector autobusId = servicioFacadeRemote.getAutobusId(jTxtAutobus.getText());
            if (autobusId.size() == 0) {
                new JDlgAceptar("Ejecución de Reportes","El número de autobús no existe.",Color.RED).setVisible(true);
                jTxtAutobus.requestFocus();
                return false;
            }
            else{
                Vector autobus = (Vector)autobusId.get(0);
                param.put("AutobusId",autobus.get(0).toString());
            }
        }
         
        if (jTxtOperador.getText().equals("")){
            System.out.println("OperadorId: "+null);
            param.put("OperadorId",null);
        }
        else {
            Vector operadorId = servicioFacadeRemote.getOperadorId(jTxtOperador.getText());
            if (operadorId.size() == 0) {
                new JDlgAceptar("Ejecución de Reportes","La clave de operador no existe.",Color.RED).setVisible(true);
                jTxtOperador.requestFocus();
                return false;
            }
            else{
                Vector operador = (Vector)operadorId.get(0);
                param.put("OperadorId",operador.get(0).toString());
            }
        }
       boolean regresa = true;
        if(reporte.equals("Monitor: Venta por Ruta"))
        {
           System.out.println("ejecuta el reporte: Monitor: Venta por Ruta");
           regresa = jClsImpresionReporte.imprimirReporte((HashMap) param, "Reportes/VentaDiaria/VentasXserviciosXruta.jasper");
        }
        if(reporte.equals("Monitor: FIK"))
        {
           System.out.println("ejecuta el reporte: Monitor: FIK");
           regresa = jClsImpresionReporte.imprimirReporte((HashMap) param, "Reportes/Fik/FIK_full.jasper");
        }
        
       return regresa;
    }

    private boolean validaParametros() {
        if (jTxtFi.dateEditor.getTexto().equals("") || jTxtFf.dateEditor.getTexto().equals("")){
            JDlgAceptar error1Dlg = new JDlgAceptar("Ejecución de Reportes","La valores de Fecha Inicial y Fecha Final son obligatorios.",Color.RED);
            error1Dlg.setVisible(true);
            return false;
        }
        if (jTxtFi.getDate().getTime() > jTxtFf.getDate().getTime()){
            JDlgAceptar error2Dlg = new JDlgAceptar("Ejecución de Reportes","La Fecha Inicial debe ser menor a la Fecha Final.",Color.RED);
            error2Dlg.setVisible(true);
            return false;
        }
        return true;
    }
    
    private TmsServiciosTblFacadeRemote lookupTmsServiciosTblFacade() {
        try {
            Context c = new InitialContext();
            return (TmsServiciosTblFacadeRemote) c.lookup("tms_exerpt.solicitud.TmsServiciosTblFacadeRemote");
        }
        catch(NamingException ne) {
            Logger.getLogger(getClass().getName()).log(Level.SEVERE,"exception caught" ,ne);
            throw new RuntimeException(ne);
        }
    }

    private TmsEmpresasTblFacadeRemote lookupTmsEmpresasTblFacade() {
        try {
            Context c = new InitialContext();
            return (TmsEmpresasTblFacadeRemote) c.lookup("tms_exerpt.solicitud.TmsEmpresasTblFacadeRemote");
        }
        catch(NamingException ne) {
            Logger.getLogger(getClass().getName()).log(Level.SEVERE,"exception caught" ,ne);
            throw new RuntimeException(ne);
        }
    }

    private void cargarServicios() {
        List<TmsServiciosTbl> servicios = new ArrayList<TmsServiciosTbl>();
        servicios = servicioFacadeRemote.findAll();
        TmsServiciosTbl ser = new TmsServiciosTbl();
        ser.setServicioId(new BigDecimal("9999"));
        ser.setServicioNombre("Todos");
        ser.setDescripcion("Todos");
        servicios.add(0,ser);
        ServiciosComboBoxModel servicioModelo = new ServiciosComboBoxModel(servicios);
        setServiciosModelo(servicioModelo);
    }

    private void setServiciosModelo(ServiciosComboBoxModel servicioModelo) {
        jCmbServicio.setModel(servicioModelo);
        jCmbServicio.setSelectedIndex(0);
    }

    public void keyTyped(KeyEvent e) {
    }

    public void keyPressed(KeyEvent e) {
        if (e.getKeyCode() == KeyEvent.VK_F10){
            if (!validaParametros()) return;                
                ejecutaReporteJasper();
                this.dispose();
        }else if (e.getKeyCode() == KeyEvent.VK_ESCAPE){
            this.dispose();
        }
    }

    public void keyReleased(KeyEvent e) {
    }

    private void cargarEmpresas() {
        List<TmsEmpresasTbl> empresas = new ArrayList<TmsEmpresasTbl>();
        empresas = empresaFacateRemote.findAll();
        TmsEmpresasTbl em = new TmsEmpresasTbl();
        em.setEmpresaId(new BigDecimal("99999"));
        em.setEmpresaNombre("Todas");
        em.setEmpresaNombreCorto("Todas");
        em.setDescripcion("Todas");
        empresas.add(0,em);
        EmpresasComboBoxModel empresaModelo = new EmpresasComboBoxModel(empresas);
        setEmpresasModelo(empresaModelo);
    }

    private void setEmpresasModelo(EmpresasComboBoxModel empresaModelo) {
        jCmbEmpresa.setModel(empresaModelo);
        jCmbEmpresa.setSelectedIndex(0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCmbEmpresa;
    private javax.swing.JComboBox jCmbServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private tms_TextFields.JTextTextField jTxtAutobus;
    private tms_calendario.JDateChooser jTxtFf;
    private tms_calendario.JDateChooser jTxtFi;
    private tms_TextFields.JTextTextField jTxtOperador;
    // End of variables declaration//GEN-END:variables
    private JClsImpresionReporte jClsImpresionReporte;

    TmsServiciosTblFacadeRemote servicioFacadeRemote;
    TmsEmpresasTblFacadeRemote empresaFacateRemote;

    private String reporte;

}
