/*
 * JDlgActualizacionesVarias.java
 *
 * Created on 4 de marzo de 2008, 12:05 AM
 */

package tms_psd;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.NoSuchElementException;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import tms_psd.util.JDlgAceptar;
import tms_psd.util.JNumberTextFieldMaxDig;

/**
 *
 * @author  ocruz
 */
public class JDlgActualizacionesVarias extends javax.swing.JDialog {
    
    /** Creates new form JDlgActualizacionesVarias */
    public JDlgActualizacionesVarias(SesionVenta pSesionVenta, int pFila) {
        inicioGral=true;
        sesionVenta = pSesionVenta;
        fila= pFila;
        cbmValores = new DefaultComboBoxModel(sesionVenta.getVectorPlantillas());
        initComponents();
        this.setModal(true);
        this.setTitle("Corrida "+sesionVenta.getMaestro()[fila][0].toString());
        this.jCboNuevoValor.setModel(cbmValores);
        centrarJDialog();
        plantillaId=sesionVenta.obtienePlantillaCorrida(sesionVenta.getTmsMonitorCorridaV().get(fila).getCorridaId());
        CapMaxPlantilla = 0;
        if(plantillaId!=-1){
            this.jTxtValorActual.setText(sesionVenta.getPlantilla(plantillaId));
            CapMaxPlantilla = sesionVenta.getPlantillaCapacidad(plantillaId);
        }
        limites=sesionVenta.obtieneLimitesPasajeCorrida(sesionVenta.getTmsMonitorCorridaV().get(fila).getCorridaId());
        if(limites.equals("")){
            inicioGral=false;
            return;
        }
        
         rutaNombre= sesionVenta.getRutaNombreCambio(sesionVenta.getTmsMonitorCorridaV().get(fila).getRutaId());
         rutaExcluye = rutaNombre;
        StringTokenizer strTok = new StringTokenizer(limites, "-");
        try{
            aSen  = strTok.nextToken();
            aProf = strTok.nextToken();
            aEst  = strTok.nextToken();
            aEsp  = strTok.nextToken();
        }catch (NoSuchElementException nsex){
            nsex.printStackTrace();
            aEst = "0"; aProf = "0"; aSen = "0"; aEsp = "0";
        }
        this.jPnlLimites.setVisible(false);
        vIndices = null;
            
    }
    
    public JDlgActualizacionesVarias(SesionVenta pSesionVenta, Vector pVIndices) {
        inicioGral=true;
        sesionVenta = pSesionVenta;
        vIndices = pVIndices;
        cbmValores = new DefaultComboBoxModel(sesionVenta.getVectorPlantillas());
        initComponents();
        this.setModal(true);
        this.setTitle("Multiples corridas seleccionadas");
        this.jCboNuevoValor.setModel(cbmValores);
        centrarJDialog();
        plantillaId=-1;
        rutaNombre="";
        rutaExcluye= sesionVenta.getRutaNombreCambio(sesionVenta.getTmsMonitorCorridaV().get(fila).getRutaId());
        limites="";
        aEst = "0"; aProf = "0"; aSen = "0"; aEsp = "0";
        CapMaxPlantilla = 47;
        this.jPnlLimites.setVisible(false);
    }
    
    private void centrarJDialog(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, ( screenSize.height - frameSize.height ) / 2 );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jCboCampo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTxtValorActual = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCboNuevoValor = new javax.swing.JComboBox(cbmValores);
        jLabel4 = new javax.swing.JLabel();
        jPnlLimites = new javax.swing.JPanel();
        jTxtEst = new JNumberTextFieldMaxDig(2);
        jTxtProf = new JNumberTextFieldMaxDig(2);
        jTxtSen = new JNumberTextFieldMaxDig(2);
        jTxtEsp = new JNumberTextFieldMaxDig(2);
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Campo");

        jCboCampo.setFont(new java.awt.Font("Tahoma", 1, 11));
        jCboCampo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Plantilla", "Empresa", "Limites tipo de pasaje", "Ruta" }));
        jCboCampo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCboCampoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCboCampoKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Valor Actual");

        jTxtValorActual.setEditable(false);
        jTxtValorActual.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTxtValorActual.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Nuevo Valor");

        jCboNuevoValor.setFont(new java.awt.Font("Tahoma", 1, 11));
        jCboNuevoValor.setModel(cbmValores);
        jCboNuevoValor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCboNuevoValorKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("<html><font color=ff0000>IZQDER</font> Ingresar datos | <font color=ff0000>F9</font> Actualizar | <font color=ff0000>ESC</font> Cerrar ventana</html>");

        jPnlLimites.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTxtEst.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTxtEst.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtEst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtEstKeyPressed(evt);
            }
        });

        jTxtProf.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTxtProf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtProf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtProfKeyPressed(evt);
            }
        });

        jTxtSen.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTxtSen.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtSen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtSenKeyPressed(evt);
            }
        });

        jTxtEsp.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTxtEsp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtEsp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtEspKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("Estudiantes");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("Profesores");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setText("Senectud");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setText("Especial");

        org.jdesktop.layout.GroupLayout jPnlLimitesLayout = new org.jdesktop.layout.GroupLayout(jPnlLimites);
        jPnlLimites.setLayout(jPnlLimitesLayout);
        jPnlLimitesLayout.setHorizontalGroup(
            jPnlLimitesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPnlLimitesLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTxtEst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(33, 33, 33)
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTxtProf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(33, 33, 33)
                .add(jLabel7)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTxtSen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 44, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 57, Short.MAX_VALUE)
                .add(jLabel8)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTxtEsp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPnlLimitesLayout.setVerticalGroup(
            jPnlLimitesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPnlLimitesLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPnlLimitesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jTxtEsp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8)
                    .add(jTxtEst, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6)
                    .add(jTxtProf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7)
                    .add(jTxtSen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPnlLimites, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jCboCampo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 104, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTxtValorActual, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 191, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLabel3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 178, Short.MAX_VALUE))
                            .add(jCboNuevoValor, 0, 245, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jLabel2)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCboCampo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTxtValorActual, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jCboNuevoValor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPnlLimites, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtEspKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtEspKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE: queOnda=false; this.dispose(); break;
            case KeyEvent.VK_F9: if(!validaDatos())return;if(vIndices==null) this.actualizar(); else this.actualizarPorLotes(); break;
            case KeyEvent.VK_RIGHT:
                jCboCampo.requestFocusInWindow();
                break;
            case KeyEvent.VK_LEFT:
                jTxtSen.selectAll();
                jTxtSen.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jTxtEspKeyPressed

    private void jTxtSenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtSenKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE: queOnda=false; this.dispose(); break;
            case KeyEvent.VK_F9: if(!validaDatos())return;if(vIndices==null) this.actualizar(); else this.actualizarPorLotes(); break;
            case KeyEvent.VK_RIGHT:
                jTxtEsp.selectAll();
                jTxtEsp.requestFocusInWindow();
                break;
            case KeyEvent.VK_LEFT:
                jTxtProf.selectAll();
                jTxtProf.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jTxtSenKeyPressed

    private void jTxtProfKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtProfKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE: queOnda=false; this.dispose(); break;
            case KeyEvent.VK_F9: if(!validaDatos())return;if(vIndices==null) this.actualizar(); else this.actualizarPorLotes(); break;
            case KeyEvent.VK_RIGHT:
                jTxtSen.selectAll();
                jTxtSen.requestFocusInWindow();
                break;
            case KeyEvent.VK_LEFT:
                jTxtEst.selectAll();
                jTxtEst.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jTxtProfKeyPressed

    private void jTxtEstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtEstKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE: queOnda=false; this.dispose(); break;
            case KeyEvent.VK_F9: if(!validaDatos())return;if(vIndices==null) this.actualizar(); else this.actualizarPorLotes(); break;
            case KeyEvent.VK_RIGHT:
                jTxtProf.selectAll();
                jTxtProf.requestFocusInWindow();
                break;
            case KeyEvent.VK_LEFT:
                jCboCampo.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jTxtEstKeyPressed

    private void jCboCampoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCboCampoKeyReleased
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_UP:
                    CargaValores();
                    break;
                case KeyEvent.VK_DOWN:
                    CargaValores();
                    break;
        }
    }//GEN-LAST:event_jCboCampoKeyReleased

    private void jCboNuevoValorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCboNuevoValorKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE: queOnda=false; this.dispose(); break;
            case KeyEvent.VK_F9: if(!validaDatos())return;if(vIndices==null) this.actualizar(); else this.actualizarPorLotes(); break;
            case KeyEvent.VK_RIGHT: case KeyEvent.VK_LEFT:
                jCboCampo.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jCboNuevoValorKeyPressed

    private void jCboCampoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCboCampoKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE: queOnda=false; this.dispose(); break;
            case KeyEvent.VK_F9: if(!validaDatos())return;if(vIndices==null) this.actualizar(); else this.actualizarPorLotes(); break;
            case KeyEvent.VK_RIGHT:
                if(jPnlLimites.isVisible()){
                    jTxtEst.selectAll();
                    jTxtEst.requestFocusInWindow();
                }
                else jCboNuevoValor.requestFocusInWindow();
                break;
            case KeyEvent.VK_LEFT:
                if(jPnlLimites.isVisible()){
                    jTxtEsp.selectAll();
                    jTxtEsp.requestFocusInWindow();
                }
                else jCboNuevoValor.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jCboCampoKeyPressed

    private boolean validaDatos(){
        if(jCboNuevoValor.getSelectedIndex()==-1)
        {
            DialogoAceptar = new JDlgAceptar("¡No hay datos para actualizar!", "Favor de hacer otra seleccion.", Color.RED);
            return false;
        }
        else
            return true;
        
    }
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
// TODO add your handling code here:
        jCboCampo.requestFocusInWindow();
    }//GEN-LAST:event_formComponentShown

    private void actualizar() {
        if(jCboCampo.getSelectedItem().toString().equals("Plantilla")){
            nuevoValorId = sesionVenta.getPlantillaId(jCboNuevoValor.getSelectedItem().toString());
            int res=validaCapacidadAsientosOcupadosDisponibles(fila, sesionVenta.getTmsMonitorCorridaV().get(fila).getClaveCorrida(),nuevoValorId);
            if(res==0 || res==-1){ this.dispose(); return; }
            regSust=sesionVenta.actualizacionesVarias_Plantillas(sesionVenta.getTmsMonitorCorridaV().get(fila).getCorridaId(), nuevoValorId);
        }
        else{
            if(jCboCampo.getSelectedItem().toString().equals("Empresa")){
                if(sesionVenta.validaServicioEmpresa(sesionVenta.getTmsMonitorCorridaV().get(fila).getServicio(), sesionVenta.getTmsMonitorCorridaV().get(fila).getRutaId(), jCboNuevoValor.getSelectedItem().toString())){
                    nuevoValorId = sesionVenta.getEmpresaId(jCboNuevoValor.getSelectedItem().toString());
                    regSust=sesionVenta.actualizacionesVarias_Empresas(sesionVenta.getTmsMonitorCorridaV().get(fila).getCorridaId(), nuevoValorId, jCboNuevoValor.getSelectedItem().toString());
                }
                else regSust = -2; // no corresponde servicio-empresa
            }
            else{
                if(jCboCampo.getSelectedItem().toString().equals("Limites tipo de pasaje")){
                    if(jTxtEst.getText().equals("") || jTxtProf.getText().equals("") || jTxtSen.getText().equals("") || jTxtEsp.getText().equals("")){
                        DialogoAceptar = new JDlgAceptar("No es posible actualizar.", "Ingrese valor correcto.", Color.RED);
                        jTxtEst.requestFocusInWindow();
                        return;
                    }
                    if(!validaTipos()){
                        DialogoAceptar = new JDlgAceptar("¡Limites de pasajeros invalidos!", "Limite maximo permitido por cada tipo "+CapMaxPlantilla+".", Color.RED);
                        jTxtEst.requestFocusInWindow();
                        return;
                    }
                    //String m, String s, String e, String p, String c
                    regSust=sesionVenta.actualizacionesVarias_LimitesPasaje(sesionVenta.getTmsMonitorCorridaV().get(fila).getCorridaId(),
                            jTxtSen.getText()+"-"+jTxtProf.getText()+"-"+jTxtEst.getText()+"-"+jTxtEsp.getText(),
                            jTxtSen.getText(),jTxtEst.getText(),jTxtProf.getText(),jTxtEsp.getText());
                }
                else
                {
                        if(jCboCampo.getSelectedItem().toString().equals("Ruta")){
                                    nuevoValorId = sesionVenta.getRutaCambioId(jCboNuevoValor.getSelectedItem().toString());
                                    System.out.println("El id de la ruta nueva es(solo): "+nuevoValorId);
                                    regSust=sesionVenta.actualizacionesVarias_Rutas(sesionVenta.getTmsMonitorCorridaV().get(fila).getCorridaId(), nuevoValorId);
                            }                    
                    
                }
            }
        }
        if(this.regSust==-1 || this.regSust==-2){
            if(this.regSust==-1)
                DialogoAceptar = new JDlgAceptar("¡No fue posible actualizar la "+jCboCampo.getSelectedItem().toString()+"!", "Contacte al administrador del sistema.", Color.RED);
            else
                DialogoAceptar = new JDlgAceptar("¡No fue posible actualizar la "+jCboCampo.getSelectedItem().toString()+"!", "El servicio, ruta y empresa de esta corrida no corresponden.", Color.RED);
            queOnda=false;
        }
        else{
            if(!jPnlLimites.isVisible())
                DialogoAceptar = new JDlgAceptar("¡Actualizacion de "+jCboCampo.getSelectedItem().toString()+" correcta!", "<html>Valor Anterior: "+jTxtValorActual.getText()+"<br>Nuevo valor: "+jCboNuevoValor.getSelectedItem().toString()+"</html>", Color.RED);
            else
                DialogoAceptar = new JDlgAceptar("¡Actualizacion de "+jCboCampo.getSelectedItem().toString()+" correcta!", "<html>Valor Anterior: "+jTxtValorActual.getText()+"<br>Nuevo valor, Est: "+jTxtEst.getText()+" - Prof: "+jTxtProf.getText()+" - Sen: "+jTxtSen.getText()+" - Esp: "+jTxtEsp.getText()+"</html>", Color.RED);
            queOnda=true;
        }
        this.dispose();
    }
    
    private void actualizarPorLotes() {
        if(jCboCampo.getSelectedItem().toString().equals("Limites tipo de pasaje")){
            if(jTxtEst.getText().equals("") || jTxtProf.getText().equals("") || jTxtSen.getText().equals("") || jTxtEsp.getText().equals("")){
                DialogoAceptar = new JDlgAceptar("No es posible actualizar.", "Ingrese valor correcto.", Color.RED);
                jTxtEst.requestFocusInWindow();
                return;
            }
        }
        else{
            if(jCboCampo.getSelectedItem().toString().equals("Plantilla")){
                nuevoValorId = sesionVenta.getPlantillaId(jCboNuevoValor.getSelectedItem().toString());
            }
        }
        
        int res; boolean res1;
        
        for(int i=0; i<vIndices.size(); i++){
            fila = Integer.valueOf(vIndices.get(i).toString());
            if(jCboCampo.getSelectedItem().toString().equals("Plantilla")){
                res=validaCapacidadAsientosOcupadosDisponibles(fila, sesionVenta.getTmsMonitorCorridaV().get(fila).getClaveCorrida(),nuevoValorId);
                if(res==0 || res==-1){ 
                    vIndices.remove(i);
                    i--;
                    continue;
                }
            }
            else{
                if(jCboCampo.getSelectedItem().toString().equals("Empresa")){
                    res1=sesionVenta.validaServicioEmpresa(sesionVenta.getTmsMonitorCorridaV().get(fila).getServicio(),sesionVenta.getTmsMonitorCorridaV().get(fila).getRutaId(),jCboNuevoValor.getSelectedItem().toString());
                    if(!res1){ 
                        vIndices.remove(i);
                        i--;
                        continue;
                    }
                }
            }
        }
        
        if(vIndices.size()==0){
            DialogoAceptar = new JDlgAceptar("¡No es posible modificar el lote de corridas!", "<html>Las corridas seleccionadas no cumplen todos<br>los requisito para poder ser modificadas.</html>", Color.RED);
            dispose();
            return;
        }
        
        if(vIndices.size()>999){
            DialogoAceptar = new JDlgAceptar("Restriccion del sistema.", "<html>Se excedio el numero maximo (1000) de corridas<br>en un lote. Realice otra consulta.</html>", Color.RED);
            dispose();
            return;
        }
        System.out.println("#corridas a procesar: "+vIndices.size());
        String loteCorridasIds="";
        
        for(int i=0; i<vIndices.size(); i++){
            fila = Integer.valueOf(vIndices.get(i).toString());
            loteCorridasIds = loteCorridasIds + sesionVenta.getTmsMonitorCorridaV().get(fila).getCorridaId() + ", ";
        }
        loteCorridasIds = loteCorridasIds.substring(0,loteCorridasIds.length()-2);
            
        if(jCboCampo.getSelectedItem().toString().equals("Plantilla")){
            regSust=sesionVenta.actualizacionesVariasPorLotes_Plantillas(loteCorridasIds, nuevoValorId);
        }
        else{
            if(jCboCampo.getSelectedItem().toString().equals("Empresa")){
                nuevoValorId = sesionVenta.getEmpresaId(jCboNuevoValor.getSelectedItem().toString());
                regSust=sesionVenta.actualizacionesVariasPorLotes_Empresas(loteCorridasIds, nuevoValorId, jCboNuevoValor.getSelectedItem().toString());
            }
            else{
                if(jCboCampo.getSelectedItem().toString().equals("Limites tipo de pasaje")){
                    if(!validaTiposPorLote()){
                        DialogoAceptar = new JDlgAceptar("¡Limites de pasajeros invalidos!", "Limite maximo permitido por cada tipo "+CapMaxPlantilla+".", Color.RED);
                        jTxtEst.requestFocusInWindow();
                        return;
                    }
                    regSust=sesionVenta.actualizacionesVariasPorLotes_LimitesPasaje(loteCorridasIds,
                            jTxtSen.getText()+"-"+jTxtProf.getText()+"-"+jTxtEst.getText()+"-"+jTxtEsp.getText(),
                            jTxtSen.getText(),jTxtEst.getText(),jTxtProf.getText(),jTxtEsp.getText());
                }
                else
                {
                        if(jCboCampo.getSelectedItem().toString().equals("Ruta")){
                        nuevoValorId = sesionVenta.getRutaCambioId(jCboNuevoValor.getSelectedItem().toString());
                        System.out.println("El id de la ruta nueva es(x Lote): "+nuevoValorId);
                        //nuevoValorId = sesionVenta.getEmpresaId(jCboNuevoValor.getSelectedItem().toString());
                        regSust=sesionVenta.actualizacionesVariasPorLotes_Rutas(loteCorridasIds, nuevoValorId);
                    }
                }
                
            }
        }
        
        if(this.regSust==-1)
            DialogoAceptar = new JDlgAceptar("¡No fue posible actualizar la "+jCboCampo.getSelectedItem().toString()+"!", "Contacte al administrador del sistema.", Color.RED);
        else{
            if(!jPnlLimites.isVisible())
                DialogoAceptar = new JDlgAceptar("¡Actualizacion de "+jCboCampo.getSelectedItem().toString()+" correcta!", "<html>Valor Anterior: "+jTxtValorActual.getText()+"<br>Nuevo valor: "+jCboNuevoValor.getSelectedItem().toString()+"</html>", Color.RED);
            else
                DialogoAceptar = new JDlgAceptar("¡Actualizacion de "+jCboCampo.getSelectedItem().toString()+" correcta!", "<html>Valor Anterior: "+jTxtValorActual.getText()+"<br>Nuevo valor, Est: "+jTxtEst.getText()+" - Prof: "+jTxtProf.getText()+" - Sen: "+jTxtSen.getText()+" - Esp: "+jTxtEsp.getText()+"</html>", Color.RED);
        }
        queOnda=true;
        this.dispose();
    }

    public long getPlantillaId(){ return this.plantillaId; }
    
    public String getCampo(){ return jCboCampo.getSelectedItem().toString(); }
    
    public String getNuevoValor(){ return jCboNuevoValor.getSelectedItem().toString(); }
    
    public long getNuevoValorId(){ return nuevoValorId; }

    private void CargaValores() {
        if(jCboCampo.getSelectedItem().toString().equals("Plantilla")){
            if(jPnlLimites.isVisible()){
                this.jPnlLimites.setVisible(false);
                this.jCboNuevoValor.setVisible(true);
            }
            cbmValores = new DefaultComboBoxModel(sesionVenta.getVectorPlantillas());
            if(plantillaId!=-1) this.jTxtValorActual.setText(sesionVenta.getPlantilla(plantillaId));
            else this.jTxtValorActual.setText("");
        }
        else{
            if(jCboCampo.getSelectedItem().toString().equals("Empresa")){
                if(jPnlLimites.isVisible()){
                    this.jPnlLimites.setVisible(false);
                    this.jCboNuevoValor.setVisible(true);
                }
                cbmValores = new DefaultComboBoxModel(sesionVenta.getVectorEmpresa());
                if(plantillaId!=-1){
                    this.jTxtValorActual.setText(sesionVenta.getMaestro()[fila][4].toString());
                }
                else
                    this.jTxtValorActual.setText("");
            }
            else{
                if(jCboCampo.getSelectedItem().toString().equals("Limites tipo de pasaje")){
                    this.jCboNuevoValor.setVisible(false);
                    this.jPnlLimites.setVisible(true);
                    this.jTxtValorActual.setText("Est: "+aEst+" - Prof: "+aProf+" - Sen: "+aSen+" - Esp: "+aEsp);
                    this.jTxtEst.setText(aEst);
                    this.jTxtProf.setText(aProf);
                    this.jTxtSen.setText(aSen);
                    this.jTxtEsp.setText(aEsp);
                }
                else
                {
                            if(jCboCampo.getSelectedItem().toString().equals("Ruta")){
                            if(jPnlLimites.isVisible()){
                                this.jPnlLimites.setVisible(false);
                                this.jCboNuevoValor.setVisible(true);
                            }
                            cbmValores = new DefaultComboBoxModel(sesionVenta.getRutasCambio(sesionVenta.getTmsMonitorCorridaV().get(fila).getOrigenId(),sesionVenta.getTmsMonitorCorridaV().get(fila).getDestinoId(), sesionVenta.getTmsMonitorCorridaV().get(fila).getServicioId(), rutaExcluye ));
                            this.jTxtValorActual.setText(rutaNombre);
                        }
                }
            }
        }
        jCboNuevoValor.setModel(cbmValores);
    }

    private int validaCapacidadAsientosOcupadosDisponibles(int fSel, String claveCorrida, long plantId) {
        long ocuNuevaPlantilla = sesionVenta.getPlantillaCapacidad(plantId);
        int ocuCorrida = sesionVenta.getOcupacion(fSel);
        if(ocuCorrida==-1){
            DialogoAceptar = new JDlgAceptar("¡Esta corrida no es valida!", "Posiblemente la corrida ya no esta abierta.", Color.RED);
            return -1;
        }
       
        if(ocuCorrida>ocuNuevaPlantilla){
            DialogoAceptar = new JDlgAceptar("¡Asientos insuficientes!", "La plantilla seleccionada no cuenta con suficientes asientos.", Color.RED);
            return 0;
        }
        
        int maxAsientoOcu = sesionVenta.maxAsientoOcupado(claveCorrida);
        System.out.println("maxAsientoOcup: "+maxAsientoOcu);
        
        if(maxAsientoOcu>ocuNuevaPlantilla){
            DialogoAceptar = new JDlgAceptar("¡Asientos finales ocupados!", "<html>La corrida cuenta con asientos finales ocupados y la numeracion<br>de asientos del autobus seleccionado no los contiene.</html>", Color.RED);
            return 0;
        }
        
        return 1;
    }
    
    public boolean isQueOnda() {
        return this.queOnda;
    }

    public Vector getVIndices() {
        return this.vIndices;
    }

    private boolean validaTiposPorLote() {
        int a = Integer.valueOf(jTxtEst.getText());
        int b = Integer.valueOf(jTxtSen.getText());
        int c = Integer.valueOf(jTxtProf.getText());
        int d = Integer.valueOf(jTxtEsp.getText());
        
        /*for(int i=0; i<vIndices.size(); i++){
            fila = Integer.valueOf(vIndices.get(i).toString());
            CapMaxPlantilla+ = sesionVenta.getPlantillaCapacidad(sesionVenta.getTmsMonitorCorridaV().get(fila).getCorridaId());
        }*/
        
        if(a>CapMaxPlantilla || b>CapMaxPlantilla || c>CapMaxPlantilla || d>CapMaxPlantilla)
        return false;
        return true;
    }
    
    private boolean validaTipos() {
        int a = Integer.valueOf(jTxtEst.getText());
        int b = Integer.valueOf(jTxtSen.getText());
        int c = Integer.valueOf(jTxtProf.getText());
        int d = Integer.valueOf(jTxtEsp.getText());
        if(a>CapMaxPlantilla || b>CapMaxPlantilla || c>CapMaxPlantilla || d>CapMaxPlantilla)
        return false;
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCboCampo;
    private javax.swing.JComboBox jCboNuevoValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPnlLimites;
    private javax.swing.JTextField jTxtEsp;
    private javax.swing.JTextField jTxtEst;
    private javax.swing.JTextField jTxtProf;
    private javax.swing.JTextField jTxtSen;
    private javax.swing.JTextField jTxtValorActual;
    // End of variables declaration//GEN-END:variables
    private SesionVenta sesionVenta = null;
    private int fila;
    private long plantillaId;
    private long nuevoValorId;
    private DefaultComboBoxModel cbmValores = null;
    private JDlgAceptar DialogoAceptar;
    private int regSust;
    private boolean queOnda;
    private String limites;
    private boolean inicioGral;
    private String aEst, aProf, aSen, aEsp;
    private Vector vIndices;
    private long CapMaxPlantilla;
    private String rutaNombre="";
    private String rutaExcluye="";
}
