/*
 * Jdlg_cancelarPago.java
 *
 * Created on 4 de octubre de 2007, 09:26 PM
 */

package tmsactividadesadicionales;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.math.BigInteger;
import java.util.List;
import java.util.Vector;
import javax.swing.JRootPane;
import javax.swing.JTextField;
import tmsactividadesadicionales.entidad.TmsPagosActAdicionalesTbl;

/**
 *
 * @author  vgonzalez
 */
public class Jdlg_cancelarPago extends javax.swing.JDialog {
        private Vector funciones;
        private Vector fuaditables;
        private long idusuario;
         private long idterminal;
        private String nombreequipo;
        private long idSesion;
    /** Creates new form Jdlg_cancelarPago */
    public Jdlg_cancelarPago(String titulo, TmsActAdicionalesManagedBean busq, Vector f, Vector fa, long iusr, String nomeq, long it,long pidSesion) {
        this.setTitle(titulo);
        this.setModal(true);
        this.setDefaultLookAndFeelDecorated(true);
        this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        initComponents();
        this.setResizable(false);
        this.busquedas2 = busq;
        this.funciones = f;
        this.fuaditables = fa;
        this.idusuario = iusr;
        this.nombreequipo = nomeq;
        this.idterminal = it;
        this.idSesion=pidSesion;
        initComponents();
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        jlbl_barraEstado.setText("<html>  <font color=FF0000>ENTER: </font> Buscar Pago  |  <font color=FF0000> ESCAPE: </font> Salir </html>");
        jlbl_barraEstado.setHorizontalAlignment( JTextField.CENTER );
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension DilaogSize = this.getSize();
        if (DilaogSize.height > screenSize.height) {
            DilaogSize.height = screenSize.height;
        }
        if (DilaogSize.width > screenSize.width) {
            DilaogSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - DilaogSize.width ) / 2, ( screenSize.height - DilaogSize.height ) / 2 );            this.setDefaultLookAndFeelDecorated(true);
        this.getRootPane().setWindowDecorationStyle(JRootPane.INFORMATION_DIALOG);
        jtxt_nreferencia.requestFocus();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel2 = new javax.swing.JLabel();
        jtxt_nreferencia = new tms_TextFields.JNumberTextField();
        jtxt_nreferencia.setFocusTraversalKeysEnabled(false);
        jlbl_barraEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel2.setFont(new java.awt.Font("Arial", 1, 12));
        jLabel2.setText("Introduce el N\u00famero de  Referencia del pago a cancelar: ");

        jtxt_nreferencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_nreferenciaKeyPressed(evt);
            }
        });

        jlbl_barraEstado.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlbl_barraEstado.setForeground(new java.awt.Color(153, 153, 153));
        jlbl_barraEstado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(23, 23, 23)
                .add(jLabel2)
                .addContainerGap(22, Short.MAX_VALUE))
            .add(layout.createSequentialGroup()
                .add(118, 118, 118)
                .add(jtxt_nreferencia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 122, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .add(18, 18, 18)
                .add(jtxt_nreferencia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 23, Short.MAX_VALUE)
                .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_nreferenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_nreferenciaKeyPressed
        if(evt.getKeyCode() == evt.VK_ENTER)
        {
            if(jtxt_nreferencia.getText().equals(""))
                 ;
             else
             {
                 List<TmsPagosActAdicionalesTbl> listacancelar = busquedas2.pagosActAdicionalesTblFacadeRemote.buscaActividaesPorReferencia(BigInteger.valueOf(Long.valueOf(jtxt_nreferencia.getText())));
                 if(listacancelar.size()==0)
                 {
                     new jdlg_error("¡No se encontro ningun pago con el numero de referencia "+jtxt_nreferencia.getText()+"!  ",""," No se encontro pago").setVisible(true);
                     jtxt_nreferencia.setText("");
                 }
                 else
                 {
                     TmsPagosActAdicionalesTbl pagoCancelar = listacancelar.get(0);
                     this.dispose();
                     new vista_cancelar_pago(busquedas2, pagoCancelar, funciones, fuaditables, idusuario, nombreequipo, idterminal,idSesion).setVisible(true);
                 }
             }
        }
            
        if(evt.getKeyCode() == evt.VK_ESCAPE)
            this.dispose();        
    }//GEN-LAST:event_jtxt_nreferenciaKeyPressed
    
    /**
     * @param args the command line arguments
     
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jdlg_cancelarPago("Cancelar Pagp de Activida Adicional", new TmsActAdicionalesManagedBean());
            }
        });
    }
    */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlbl_barraEstado;
    private tms_TextFields.JNumberTextField jtxt_nreferencia;
    // End of variables declaration//GEN-END:variables
    private TmsActAdicionalesManagedBean busquedas2;
}
