/*
 * JDlgDesglose.java
 *
 * Created on 16 de agosto de 2007, 09:10 PM
 */

package tms_cortetaquilla;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.DefaultCellEditor;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.text.JTextComponent;
import tms_TextFields.JCuantityTextField;
import tms_TextFields.JNumberTextField;
import tms_cortetaquilla.util.JDlgAceptar;

/**
 *
 * @author  ocruz
 */
public class JDlgVtaManual extends javax.swing.JDialog{
    
    /** Creates new form JDlgDesglose */
    public JDlgVtaManual(javax.swing.JDialog parent) {
        super(parent, true);
        initComponents();
        jTblVtaManual.setSurrendersFocusOnKeystroke(true);
        centrar();
        xAnchoColumnas();
        CamposEspeciales();
        jTblVtaManual.getInputMap(JTable.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0),
                jTblVtaManual.getInputMap(JTable.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).get(KeyStroke.getKeyStroke(KeyEvent.VK_RIGHT, 0)));
        jTblVtaManual.requestFocusInWindow();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScpVtaManual = new javax.swing.JScrollPane();
        jTblVtaManual = new javax.swing.JTable();
        jTblVtaManual = new javax.swing.JTable()
        {
            public Component prepareEditor(
                TableCellEditor editor, int row, int column)
            {

                Component c = super.prepareEditor(editor, row, column);
                if (c instanceof JTextComponent)
                {
                    ((JTextField)c).selectAll();
                }
                return c;
            }
        };
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Venta Manual");
        setModal(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jScpVtaManual.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Folios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), java.awt.Color.darkGray));
        jTblVtaManual.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTblVtaManual.setModel(xListado);
        jTblVtaManual.setName("Tabla");
        jTblVtaManual.getTableHeader().setReorderingAllowed(false);
        jTblVtaManual.setFocusTraversalKeysEnabled(true);
        jTblVtaManual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTblVtaManualKeyPressed(evt);
            }
        });

        jScpVtaManual.setViewportView(jTblVtaManual);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("<html><font color=ff0000>Alt+F</font> Navegar en folios | <font color=ff0000>F11</font> Agregar | <font color=ff0000>F12</font> Eliminar | <font color=ff0000>ENTER</font> Aceptar</html>");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jScpVtaManual, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                .add(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jScpVtaManual, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 207, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel1))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTblVtaManualKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblVtaManualKeyPressed
// TODO add your handling code here:
        if(evt.isAltDown() && evt.getKeyCode()==KeyEvent.VK_F){
            if(jTblVtaManual.getRowCount()==0) return;
            jTblVtaManual.setRowSelectionInterval(0,0);
            jTblVtaManual.setColumnSelectionInterval(0,0);
            jTblVtaManual.requestFocusInWindow();
        }
        else{
            switch(evt.getKeyCode()){
                case KeyEvent.VK_ENTER:
                    if(!noNegativos()) return;
                    this.dispose();
                    break;
                case KeyEvent.VK_F11:
                    if(!noNegativos()) return;
                    agregar();
                    break;
                case KeyEvent.VK_F12:
                    eliminar();
                    break;
            }
        }
    }//GEN-LAST:event_jTblVtaManualKeyPressed

    private void eliminar(){
        if(jTblVtaManual.getRowCount()==0) return;
        xListado.removeRow(jTblVtaManual.getSelectedRow());
        
        if(jTblVtaManual.getRowCount()>0){
            jTblVtaManual.setRowSelectionInterval(0,0);
            jTblVtaManual.setColumnSelectionInterval(0,0);
            jTblVtaManual.requestFocusInWindow();
        }
    }
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
// TODO add your handling code here:
        jTblVtaManual.requestFocusInWindow();
    }//GEN-LAST:event_formComponentShown
    
    private void agregar(){
        Object[] valores = {"0","0","0","0"};
        xListado.addRow(valores);
        jTblVtaManual.setRowSelectionInterval(jTblVtaManual.getRowCount()-1, jTblVtaManual.getRowCount()-1);
        jTblVtaManual.setColumnSelectionInterval(0,0);
        jTblVtaManual.requestFocusInWindow();
    }
    
    private void centrar(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, ( screenSize.height - frameSize.height ) / 2 );
    }
    
    private void CamposEspeciales(){
        TableColumn Column = jTblVtaManual.getColumnModel().getColumn(0);
        JNumberTextField folioi = new JNumberTextField();
        Column.setCellEditor(new DefaultCellEditor(folioi));
        
        TableColumn Column2 = jTblVtaManual.getColumnModel().getColumn(1);
        JNumberTextField foliof = new JNumberTextField();
        Column2.setCellEditor(new DefaultCellEditor(foliof));
        
        TableColumn Column3 = jTblVtaManual.getColumnModel().getColumn(2);
        JNumberTextField cantidad = new JNumberTextField();
        Column3.setCellEditor(new DefaultCellEditor(cantidad));
        
        TableColumn Column4 = jTblVtaManual.getColumnModel().getColumn(3);
        JCuantityTextField monto = new JCuantityTextField();
        Column4.setCellEditor(new DefaultCellEditor(monto));
        
        jTblVtaManual.setOpaque(true);
        jTblVtaManual.setDefaultRenderer(Object.class, new AttributiveCellRenderer());
    }
    
    private void xAnchoColumnas(){
        TableColumn column = null;
        int anchoContenedor = jScpVtaManual.getWidth();
        for (int i = 0; i < 4; i++) {
            column = jTblVtaManual.getColumnModel().getColumn(i);
            switch(i){
                case 0: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.25)); break;
                case 1: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.25)); break;
                case 2: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.25)); break;
                case 3: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.25)); break;
            }
            column.setResizable(false);
        }
    }
    
    public Object[][] getVtaManual(){
        int i, contador=0, suma=0;
               
        for(i=0; i<jTblVtaManual.getRowCount(); i++){
            suma=suma+Integer.valueOf(jTblVtaManual.getValueAt(i,2).toString());
            if(!jTblVtaManual.getValueAt(i,2).equals("0")) contador++;
        }
        
        if(suma==0) return null;
        
        Object[][] datos = new Object[contador][3];
        for(i=0; i<jTblVtaManual.getRowCount(); i++){
            if(jTblVtaManual.getValueAt(i,0)!=null){
                datos[i][0] = "VTAMNL: "+xListado.getValueAt(i,0).toString()+"-"+xListado.getValueAt(i,1).toString();
                datos[i][1] = xListado.getValueAt(i,2);
                datos[i][2] = xListado.getValueAt(i,3);
            }
        }
        return datos;
    }
    
    private boolean noNegativos(){
        if(jTblVtaManual.getRowCount()>0){
            int i,j;
            for(i=0; i<jTblVtaManual.getRowCount(); i++)
                for(j=0; j<jTblVtaManual.getColumnCount(); j++)
                    if(Double.valueOf(jTblVtaManual.getValueAt(i,j).toString())<0){
                        jTblVtaManual.setColumnSelectionInterval(0,0);
                        jTblVtaManual.setRowSelectionInterval(i,i);
                        this.getToolkit().beep();
                        DialogoAceptar.mostrarDialogo("¡No ingrese valores negativos!","Modifique sus datos correctamente.", Color.RED);
                        jTblVtaManual.requestFocusInWindow();
                        return false;
                    }
            return true;
        }
        else return true;
    }

    public void keyReleased(KeyEvent e) {
        
    }
    
    class AttributiveCellRenderer extends JLabel  implements TableCellRenderer {
      
        public AttributiveCellRenderer() {
            setOpaque(true);
            setHorizontalAlignment( RIGHT );
        }
      
        public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
            if(value==null || value.equals("")){
                if(column!=2){
                    if(column==3) setText("0");
                    else setText("0");
                }
                else
                    setText(null);
            }
            else
              setText(String.valueOf(value));
            
            if(row == jTblVtaManual.getSelectedRow() && column == jTblVtaManual.getSelectedColumn())
                this.setBackground(SELECCION);
            else
                this.setBackground(BLANCO);
            
            if(column == 2){
                int a=0, b=0, c=0;
                try{
                    a=Integer.valueOf(jTblVtaManual.getValueAt(row, 0).toString());
                }catch(NumberFormatException nfex){
                    a=0;
                }
                try{
                    b=Integer.valueOf(jTblVtaManual.getValueAt(row, 1).toString());
                }catch(NumberFormatException nfex){
                    b=0;
                }
                c=(b-a)+1;
                setText(""+c);
                xListado.setValueAt(getText(),row,2);
            }
            
          return this;
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScpVtaManual;
    private javax.swing.JTable jTblVtaManual;
    // End of variables declaration//GEN-END:variables
    private Object[] xEncabezado = {"Folio Inicial", "Folio Final", "Cantidad", "Monto"};
    private DefaultTableModel xListado = new DefaultTableModel(null, xEncabezado){
            public boolean isCellEditable(int row, int col) {
                if(col==2) return false;
                return true;
            }
            public Class getColumnClass(int c) {
                return getValueAt(0, c).getClass();
            }
    };
    private static Color SELECCION = new Color(184, 207, 229);
    private static Color BLANCO = new Color(255, 255, 255);

    private JDlgAceptar DialogoAceptar=new JDlgAceptar();
}