/*
 * JIFCancelar.java
 *
 * Created on 6 de septiembre de 2007, 12:41 PM
 */

package DialogosX;

import AsignacionVenta.jDlgAutorizaSupervisor;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import subProcesos.JTextTextFieldMaxCharAlfa;
import subProcesos.JTxtFieldUpperCase;
import paquete.JTxtFieldTipoPasaje;
import subProcesos.Mensajes;
import subProcesos.RelojVisualVta;
import tms_venta.SesionVenta;
import tms_venta.entidad.TmsVtaRvnV;
import tms_venta.JClsColoresInterfaz;

/**
 *
 * @author  ocruz
 */
public class JDlgControlRvn extends javax.swing.JDialog{
    /* Creates new form JIFCancelar */
    public JDlgControlRvn(SesionVenta pSesionVenta, String pNombreEmpresa, Vector pOrigenes, JLabel pJLabel1, JLabel pJLabel2, RelojVisualVta pThX){
        this.thX = pThX;
        this.pOrigenes = pOrigenes;
        this.nombreEmpresa=pNombreEmpresa;
        this.sesionVenta = pSesionVenta;
        this.jLblNombreEmpresa=pJLabel1;
        this.jLblFolioActual=pJLabel2;
        initComponents();
        jLblBarraEstado.setText("<html><font color="+ColoresInterfaz.cHTML3+">IZQDER </font> Ingresar Criterios | <font color="+ColoresInterfaz.cHTML3+">ENTER</font> Buscar Reservacion | <font color="+ColoresInterfaz.cHTML3+">F8</font> Cancelar Reservacion | <font color="+ColoresInterfaz.cHTML3+">F10</font> Venta Reservacion | <font color="+ColoresInterfaz.cHTML3+">F12</font> Seleccionar linea | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Salir</html>");
        interfazColor();
        this.setModal(true);
        centrarJDialog();
        this.jTblBusqRvn.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_TAB, 0), JComponent.WHEN_FOCUSED);
        this.jTblRvn.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_TAB, 0), JComponent.WHEN_FOCUSED);
        jTxtTipoPasaje.setTipos(sesionVenta.CastTiposPasaje());
    }
    
    private void centrarJDialog(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, ( screenSize.height - frameSize.height ) / 2 );
    }
    
    private void jCkbSelItemStateChanged(java.awt.event.ItemEvent evt) {
// TODO add your handling code here:
        /*if(jTblRvn.getRowCount()>-1){
            if(evt.getStateChange()==ItemEvent.SELECTED) suma+=Double.valueOf(xRvn.getValueAt(jTblRvn.getSelectedRow(),7).toString());
            else  suma-=Double.valueOf(xRvn.getValueAt(jTblRvn.getSelectedRow(),7).toString());
        }*/
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCboOrigen = new javax.swing.JComboBox();
        jCboOrigen = new JComboBox(pOrigenes);
        jCboOrigen.setFocusTraversalKeysEnabled(false);
        jLabel2 = new javax.swing.JLabel();
        jTxtClave = new javax.swing.JTextField();
        jTxtClave.setFocusTraversalKeysEnabled(false);
        jLabel3 = new javax.swing.JLabel();
        jTxtNoResp = new javax.swing.JTextField();
        jTxtNoResp = new JTxtFieldUpperCase();
        jTxtNoResp.setFocusTraversalKeysEnabled(false);
        jScpBusq = new javax.swing.JScrollPane();
        jTblBusqRvn = new javax.swing.JTable();
        jTblBusqRvn.setFocusTraversalKeysEnabled(false);
        this.jTblBusqRvn.registerKeyboardAction(new ActionListener() {
            public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F8, 0), JComponent.WHEN_FOCUSED);
    jTblBusqRvn.getTableHeader().setReorderingAllowed(false);
    jScpRvn = new javax.swing.JScrollPane();
    jTblRvn = new javax.swing.JTable();
    jTblRvn.setFocusTraversalKeysEnabled(false);
    this.jTblRvn.registerKeyboardAction(new ActionListener() {
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F8, 0), JComponent.WHEN_FOCUSED);
jTblRvn.getTableHeader().setReorderingAllowed(false);
jLblImporte = new javax.swing.JLabel();
jLblBarraEstado = new javax.swing.JLabel();

setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
setTitle("Reservacion de Boletos");
setName("Ventana");
setResizable(false);
addComponentListener(new java.awt.event.ComponentAdapter() {
    public void componentShown(java.awt.event.ComponentEvent evt) {
        formComponentShown(evt);
    }
    });

    jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10));
    jLabel1.setText("Origen");

    jCboOrigen.setFont(new java.awt.Font("Tahoma", 1, 10));
    jCboOrigen.setName("Origen");
    jCboOrigen.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            jCboOrigenKeyPressed(evt);
        }
    });

    jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10));
    jLabel2.setText("Clave Confirmacion");

    jTxtClave.setFont(new java.awt.Font("Tahoma", 1, 10));
    jTxtClave.setName("FolioPreimpreso");
    jTxtClave.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            jTxtClaveKeyPressed(evt);
        }
    });

    jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10));
    jLabel3.setText("Nombre Responsable");

    jTxtNoResp.setFont(new java.awt.Font("Tahoma", 1, 10));
    jTxtNoResp.setName("noAsiento");
    jTxtNoResp.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            jTxtNoRespKeyPressed(evt);
        }
    });

    jScpBusq.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados Busqueda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), java.awt.Color.black));
    jScpBusq.setFocusable(false);
    jScpBusq.setFont(new java.awt.Font("Tahoma", 1, 10));
    jTblBusqRvn.setFont(new java.awt.Font("Tahoma", 1, 10));
    jTblBusqRvn.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {

        }
    ));
    jTblBusqRvn.setModel(xBusq);
    jTblBusqRvn.getInputMap(javax.swing.JTable.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT).put(KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0),"none");
    jTblBusqRvn.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    jTblBusqRvn.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            jTblBusqRvnKeyPressed(evt);
        }
        public void keyReleased(java.awt.event.KeyEvent evt) {
            jTblBusqRvnKeyReleased(evt);
        }
    });
    jTblBusqRvn.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseReleased(java.awt.event.MouseEvent evt) {
            jTblBusqRvnMouseReleased(evt);
        }
    });

    jScpBusq.setViewportView(jTblBusqRvn);

    jScpRvn.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle Reservacion Seleccionada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10), java.awt.Color.black));
    jTblRvn.setFont(new java.awt.Font("Tahoma", 1, 10));
    jTblRvn.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {

        }
    ));
    jTblRvn.setModel(xRvn);
    jTblRvn.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    jTblRvn.setRowSelectionAllowed(false);
    jTblRvn.setColumnSelectionAllowed(false);
    jTblRvn.setCellSelectionEnabled(true);
    jTblRvn.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyPressed(java.awt.event.KeyEvent evt) {
            jTblRvnKeyPressed(evt);
        }
        public void keyReleased(java.awt.event.KeyEvent evt) {
            jTblRvnKeyReleased(evt);
        }
    });

    jScpRvn.setViewportView(jTblRvn);

    jLblImporte.setFont(new java.awt.Font("Tahoma", 1, 10));
    jLblImporte.setText("Importe Reservacion: $0.00");

    jLblBarraEstado.setFont(new java.awt.Font("Tahoma", 1, 10));
    jLblBarraEstado.setText("<html><font color=\"+ColoresInterfaz.cHTML3+\">IZQDER </font> Ingresar Criterios | <font color=\"+ColoresInterfaz.cHTML3+\">ENTER</font> Buscar Reservacion | <font color=\"+ColoresInterfaz.cHTML3+\">F8</font> Cancelar Reservacion| <font color=\"+ColoresInterfaz.cHTML3+\">F10</font> Venta Reservacion | <font color=\"+ColoresInterfaz.cHTML3+\">F11</font> Seleccionar linea | <font color=\"+ColoresInterfaz.cHTML3+\">ESC</font> Salir</html>");
    jLblBarraEstado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

    org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap(584, Short.MAX_VALUE)
            .add(jLblImporte)
            .addContainerGap())
        .add(jLblBarraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        .add(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .add(jLabel1)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jCboOrigen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(16, 16, 16)
            .add(jLabel2)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jTxtClave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 119, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(16, 16, 16)
            .add(jLabel3)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jTxtNoResp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
            .addContainerGap())
        .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                .add(org.jdesktop.layout.GroupLayout.LEADING, jScpBusq, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
                .add(org.jdesktop.layout.GroupLayout.LEADING, jScpRvn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE))
            .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabel1)
                .add(jCboOrigen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel2)
                .add(jTxtClave, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jLabel3)
                .add(jTxtNoResp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jScpBusq, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jScpRvn, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jLblImporte)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jLblBarraEstado))
    );

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTblBusqRvnMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTblBusqRvnMouseReleased
// TODO add your handling code here:
        detalles(jTblBusqRvn.getSelectedRow());
        xRvn.setDataVector(Rvn, encRvn);
        AnchoColumnasRvn();
    }//GEN-LAST:event_jTblBusqRvnMouseReleased

    private void jTblRvnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblRvnKeyReleased
// TODO add your handling code here:
        /*switch(evt.getKeyCode()){
            case KeyEvent.VK_BACK_SPACE:
                        if(jTblRvn.getSelectedColumn()==8){
                            System.out.println("Boolean "+Boolean.valueOf(xRvn.getValueAt(jTblRvn.getSelectedRow(),8).toString()));
                            if(Boolean.valueOf(xRvn.getValueAt(jTblRvn.getSelectedRow(),8).toString()))
                                suma+=Double.valueOf(xRvn.getValueAt(jTblRvn.getSelectedRow(),7).toString());
                            else
                                suma-=Double.valueOf(xRvn.getValueAt(jTblRvn.getSelectedRow(),7).toString());
                            jLblImporte.setText("Importe Reservacion: $"+suma);
                        }
            break;
        }*/
    }//GEN-LAST:event_jTblRvnKeyReleased

    private void jTblBusqRvnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblBusqRvnKeyReleased
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_UP: case KeyEvent.VK_DOWN: case KeyEvent.VK_PAGE_UP: case KeyEvent.VK_PAGE_DOWN:
                    detalles(jTblBusqRvn.getSelectedRow());
                    xRvn.setDataVector(Rvn, encRvn);
                    AnchoColumnasRvn();
                break;
        }
    }//GEN-LAST:event_jTblBusqRvnKeyReleased

    private void jTblRvnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblRvnKeyPressed
// TODO add your handling code here:
        int i, cont=0;
        int rowsel = jTblRvn.getSelectedRow();
        int colsel = jTblRvn.getSelectedColumn();
        int ultimo=jTblRvn.getRowCount()-1;
        int rowsize= jTblRvn.getRowCount();
        if (rowsize > 0) {  
            double impBol=Double.parseDouble(jLblImporte.getText().replace("Importe Reservacion: $"," ").replace(",",""));
            double tarifaNueva, tarifaAnterior;
            switch (evt.getKeyCode()){
                case KeyEvent.VK_ENTER:
                    switch(colsel){
                        case 4:
                            Object objNombre;
                            if(rowsel==0) objNombre=xRvn.getValueAt(0,4);
                            else objNombre=xRvn.getValueAt(rowsel-1,4);
                            xRvn.setValueAt(objNombre,rowsel,4);
                            if(rowsel==ultimo) rowsel=-1;
                            try{
                                jTblRvn.setRowSelectionInterval(rowsel,rowsel);
                                jTblRvn.setColumnSelectionInterval(4,4);
                            }catch(IllegalArgumentException iae){
                                jTblRvn.setRowSelectionInterval(ultimo,ultimo);
                                jTblRvn.setColumnSelectionInterval(7,7);
                            }
                        break;
                        case 8:
                            if(rowsel==ultimo) rowsel=-1;
                            try{
                                jTblRvn.setRowSelectionInterval(rowsel,rowsel);
                                jTblRvn.setColumnSelectionInterval(8,8);
                            }catch(IllegalArgumentException iae){
                                jTblRvn.setRowSelectionInterval(ultimo,ultimo);
                                jTblRvn.setColumnSelectionInterval(3,3);
                            }
                        break;
                    }
                break;
                case KeyEvent.VK_ESCAPE:
                    encabezados();
                    detalles(filaBusqRvn);
                    xBusq.setDataVector(busqRvn, encBusq);
                    AnchoColumnasBusq();
                    xRvn.setDataVector(Rvn, encRvn);
                    AnchoColumnasRvn();
                    if(sesionVenta.getUserCon().getAplicacionVenta()) jLblBarraEstado.setText(mensajes.getMensajeVta(13));
                    else jLblBarraEstado.setText(mensajes.getMensajeVta(131));
                    jTblBusqRvn.setColumnSelectionInterval(0,0);
                    jTblBusqRvn.setRowSelectionInterval(filaBusqRvn,filaBusqRvn);
                    abledComponents(jTblBusqRvn);
                    jTblBusqRvn.requestFocusInWindow();
                    enabledComponents(jTblRvn);
                    break;
                case KeyEvent.VK_F8:
                    if(!sesionVenta.ValidaFuncionUsuario("5011")){
                        jDlgAutorizaSupervisor dlg = new jDlgAutorizaSupervisor(sesionVenta,"5011", "Cancelar Boleto Reservado");
                        dlg.setVisible(true);
                        if(!dlg.getRespuesta()) return;
                    }
                    for(i=0; i<xRvn.getRowCount(); i++){
                        Rvn[i][8]=xRvn.getValueAt(i,8);
                        if(Rvn[i][8].toString().equals("CN")) cont++;
                    }
                    if(cont==0){
                        DialogoAceptar.mostrarDialogo("¡No existen lineas para cancelar!","<html>Debe quitar la seleccion de aquellas lineas<br>que desee cancelar.</html>",colorDialogoActivo);
                        return;
                    }
                    
                    if(busqRvn[jTblBusqRvn.getSelectedRow()][6].toString().equals("C")){
                        DialogoSiNo = new JDlgSiNo("La reservacion es <<no cancelable>>","¿Desea cancelar las lineas marcadas como CN?", false);
                        if(!DialogoSiNo.getResultado()) return;
                    }
                    else{
                        DialogoSiNo = new JDlgSiNo("¡Cancelar reservacion!","¿Desea cancelar las lineas marcadas como CN?", false);
                        if(!DialogoSiNo.getResultado()) return;
                    }
                    if(!validaBloqueRvn(xBusq.getValueAt(jTblBusqRvn.getSelectedRow(),0).toString(),"B")) return;
                    if(sesionVenta.cancelarReservacionParcial(Rvn, this.thX.getFecha().getTime())==-1) DialogoAceptar.mostrarDialogo("¡Error!","<html>La cancelacion de la reservacion no se realizo.<br>Contacte al administrador del sistema.</html>",Color.RED);
                    else DialogoAceptar.mostrarDialogo("¡Cancelacion exitosa!","Presione enter para continuar...",colorDialogoActivo);
                    if(!validaBloqueRvn(xBusq.getValueAt(jTblBusqRvn.getSelectedRow(),0).toString(),"L")) return;
                    
                    xBusq.setDataVector(null, encBusq);
                    AnchoColumnasBusq();
                    xRvn.setDataVector(null, encRvn);
                    AnchoColumnasRvn();
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jTxtClave.setText("");
                    jTxtNoResp.setText("");
                    jLblImporte.setText("Importe Reservacion: $0.00");
                    jLblBarraEstado.setText(mensajes.getMensajeVta(12));
                    abledComponentsCriterios();
                    jCboOrigen.requestFocusInWindow();
                    enabledComponents(jTblRvn);
                    break;
                case KeyEvent.VK_F12: // VT/CN
                    if(xRvn.getValueAt(jTblRvn.getSelectedRow(),8).toString().equals("VT")){
                        xRvn.setValueAt("CN",jTblRvn.getSelectedRow(),8);
                        Rvn[jTblRvn.getSelectedRow()][8]=xRvn.getValueAt(jTblRvn.getSelectedRow(),8);
                        if(xRvn.getValueAt(jTblRvn.getSelectedRow(),9).toString().equals("R")){
                          if(jugandoImporteVentaPermiso[jTblRvn.getSelectedRow()].equals("S"))
                            tarifaNueva=Math.ceil(TarifaRedondo-(jugandoImporteVenta[jTblRvn.getSelectedRow()]*TarifaRedondo));
                          else
                          {  
                              tarifaNueva=TarifaRedondo-(jugandoImporteVenta[jTblRvn.getSelectedRow()]*TarifaRedondo);
                                double d = (tarifaNueva - (Double.valueOf(""+tarifaNueva).longValue()) );
                                if(d > 0 && d != .50)
                                    tarifaNueva =    Math.ceil(tarifaNueva);                            
                          }
                            impBol-=tarifaNueva;
                        }
                        else{
                              if(jugandoImporteVentaPermiso[jTblRvn.getSelectedRow()].equals("S"))
                                    tarifaNueva=Math.ceil(TarifaSencillo-(jugandoImporteVenta[jTblRvn.getSelectedRow()]*TarifaSencillo));
                              else
                              {
                                tarifaNueva=TarifaSencillo-(jugandoImporteVenta[jTblRvn.getSelectedRow()]*TarifaSencillo);
                                double d = (tarifaNueva - (Double.valueOf(""+tarifaNueva).longValue()) );
                                if(d > 0 && d != .50)                                
                                    tarifaNueva =    Math.ceil(tarifaNueva);                            
                              }
                            impBol-=tarifaNueva;
                        }
                    }
                    else{
                        xRvn.setValueAt("VT",jTblRvn.getSelectedRow(),8);
                        Rvn[jTblRvn.getSelectedRow()][8]=xRvn.getValueAt(jTblRvn.getSelectedRow(),8);
                        if(xRvn.getValueAt(jTblRvn.getSelectedRow(),9).toString().equals("R")){
                          if(jugandoImporteVentaPermiso[jTblRvn.getSelectedRow()].equals("S"))
                                tarifaNueva=Math.ceil(TarifaRedondo-(jugandoImporteVenta[jTblRvn.getSelectedRow()]*TarifaRedondo));
                          else
                          {  
                                tarifaNueva=TarifaRedondo-(jugandoImporteVenta[jTblRvn.getSelectedRow()]*TarifaRedondo);
                                double d = (tarifaNueva - (Double.valueOf(""+tarifaNueva).longValue()) );
                                if(d > 0 && d != .50)                                
                                    tarifaNueva =    Math.ceil(tarifaNueva);                            
                          }
                            impBol+=tarifaNueva;
                        }
                        else{
                            if(jugandoImporteVentaPermiso[jTblRvn.getSelectedRow()].equals("S"))
                                tarifaNueva=Math.ceil(TarifaSencillo-(jugandoImporteVenta[jTblRvn.getSelectedRow()]*TarifaSencillo));
                            else
                            { 
                                tarifaNueva=TarifaSencillo-(jugandoImporteVenta[jTblRvn.getSelectedRow()]*TarifaSencillo);
                                double d = (tarifaNueva - (Double.valueOf(""+tarifaNueva).longValue()) );
                                if(d > 0 && d != .50)                                
                                        tarifaNueva =    Math.ceil(tarifaNueva);                            
                            }
                            impBol+=tarifaNueva;
                        }
                    }
                    jLblImporte.setText("Importe Reservacion: $"+sesionVenta.customFormat("##,##0.00",impBol));
                    sesionVenta.setImporteVenta(impBol);
                    break;
                case KeyEvent.VK_F11: //TARIFA
                    if(!xRvn.getValueAt(jTblRvn.getSelectedRow(),8).toString().equals("VT")) return;
                    if(xRvn.getValueAt(jTblRvn.getSelectedRow(),9).toString().equals("S")){
                        if(!existeCorridaRegreso(jTblRvn.getSelectedRow())){
                            return;
                        }
                        else{
                            xRvn.setValueAt("R",jTblRvn.getSelectedRow(),9);
                            Rvn[jTblRvn.getSelectedRow()][9]=xRvn.getValueAt(jTblRvn.getSelectedRow(),9);
                            if(jugandoImporteVentaPermiso[jTblRvn.getSelectedRow()].equals("S"))
                                tarifaNueva=Math.ceil(TarifaRedondo-(jugandoImporteVenta[jTblRvn.getSelectedRow()]*TarifaRedondo));
                            else
                            {
                                tarifaNueva=TarifaRedondo-(jugandoImporteVenta[jTblRvn.getSelectedRow()]*TarifaRedondo);
                                double d = (tarifaNueva - (Double.valueOf(""+tarifaNueva).longValue()) );
                                if(d > 0 && d != .50)                                
                                    tarifaNueva =    Math.ceil(tarifaNueva);                            
                            }
                            xRvn.setValueAt(tarifaNueva, jTblRvn.getSelectedRow(), 7);
                            if(jugandoImporteVentaPermiso[jTblRvn.getSelectedRow()].equals("S"))
                                tarifaAnterior=Math.ceil(TarifaSencillo-(jugandoImporteVenta[jTblRvn.getSelectedRow()]*TarifaSencillo));
                            else
                            {
                                tarifaAnterior=TarifaSencillo-(jugandoImporteVenta[jTblRvn.getSelectedRow()]*TarifaSencillo);
                                double d = (tarifaAnterior - (Double.valueOf(""+tarifaAnterior).longValue()) );
                                if(d > 0 && d != .50)                                
                                    tarifaAnterior =    Math.ceil(tarifaAnterior);                            
                            }
                            Rvn[jTblRvn.getSelectedRow()][7]=tarifaNueva;
                            impBol = impBol-tarifaAnterior+tarifaNueva;
                        }
                    }
                    else{
                        xRvn.setValueAt("S",jTblRvn.getSelectedRow(),9);
                        Rvn[jTblRvn.getSelectedRow()][9]=xRvn.getValueAt(jTblRvn.getSelectedRow(),9);
                        if(jugandoImporteVentaPermiso[jTblRvn.getSelectedRow()].equals("S"))
                            tarifaNueva=Math.ceil(TarifaSencillo-(jugandoImporteVenta[jTblRvn.getSelectedRow()]*TarifaSencillo));
                        else
                        {
                            tarifaNueva=TarifaSencillo-(jugandoImporteVenta[jTblRvn.getSelectedRow()]*TarifaSencillo);
                                double d = (tarifaNueva - (Double.valueOf(""+tarifaNueva).longValue()) );
                                if(d > 0 && d != .50)                                
                                    tarifaNueva =    Math.ceil(tarifaNueva);                            
                        }
                        xRvn.setValueAt(tarifaNueva, jTblRvn.getSelectedRow(), 7);
                        if(jugandoImporteVentaPermiso[jTblRvn.getSelectedRow()].equals("S"))
                            tarifaAnterior=Math.ceil(TarifaRedondo-(jugandoImporteVenta[jTblRvn.getSelectedRow()]*TarifaRedondo));
                        else
                        {
                            tarifaAnterior=TarifaRedondo-(jugandoImporteVenta[jTblRvn.getSelectedRow()]*TarifaRedondo);
                                double d = (tarifaAnterior - (Double.valueOf(""+tarifaAnterior).longValue()) );
                                if(d > 0 && d != .50)                                
                                    tarifaAnterior =    Math.ceil(tarifaAnterior);                            
                        }
                        Rvn[jTblRvn.getSelectedRow()][7]=tarifaNueva;
                        impBol = impBol-tarifaAnterior+tarifaNueva;
                    }
                    jLblImporte.setText("Importe Reservacion: $"+sesionVenta.customFormat("##,##0.00",impBol));
                    sesionVenta.setImporteVenta(impBol);
                    break;
                case KeyEvent.VK_F10:
                    if(!sesionVenta.getUserCon().getAplicacionVenta()) return;
                    tpSoloVac = false;
                    for(i=0; i<xRvn.getRowCount(); i++){
                        Rvn[i][8]=xRvn.getValueAt(i,8);
                        if(Rvn[i][8].toString().equals("VT")) cont++;
                        if(Rvn[i][3].toString().equals("E") || Rvn[i][3].toString().equals("P")) tpSoloVac=true;
                    }
                    if(cont==0){
                        this.getToolkit().beep();
                        DialogoAceptar.mostrarDialogo("¡No existen lineas para vender!","<html>Debe marcar (VT) aquellas lineas<br>que desee vender.</html>",colorDialogoActivo);
                        return;
                    }
                    // AHORA, EXISTEN BOLETOS REDONDOS
                    for(i=0, contBR=0; i<jTblRvn.getRowCount(); i++){
                        if(Rvn[i][8].toString().equals("VT")){
                            if(Rvn[i][9].equals("R")){
                                contBR+=2;
                                if(!hayBoletosRedondos) hayBoletosRedondos=true;
                            }
                            else
                                contBR++;
                        }
                    }

                    if(hayBoletosRedondos) cont=contBR;
                    // EXISTE DISPONIBILIDAD DE BOLETOS PARA VENTA
                    long f1=Long.valueOf(sesionVenta.obtenerFolioActual(this.nombreEmpresa)), f2=sesionVenta.obtenerFolioFinal(this.nombreEmpresa);
                    long f3=(f2-f1)+1;
                    if(cont>f3){
                        this.getToolkit().beep();
                        DialogoAceptar.mostrarDialogo("Limite de folios.",
                                "<html>No tiene boletos suficientes para vender las reservaciones.<br>" +
                                f3+" folio(s) disponible(s).</html>", Color.RED);
                        return;
                    }
                    
                    if(tpSoloVac){
                        if(!sesionVenta.sonVacaciones()){
                            DialogoAceptar.mostrarDialogo("Venta reservacion.","<html>Seleccionó reservaciones con tipo de pasajero<br>solo habilitado en periodo vacacional.</html>", Color.RED);
                            return;
                        }
                    }
                    
                    DialogoSiNo = new JDlgSiNo("¡Confirme!","¿Desea vender las lineas marcadas como VT?", true);
                    if(!DialogoSiNo.getResultado()) return;
                    if(!sesionVenta.ValidaFuncionUsuario("5010")){
                        jDlgAutorizaSupervisor dlg = new jDlgAutorizaSupervisor(sesionVenta,"5010", "Vender Boleto Reservado");
                        dlg.setVisible(true);
                        if(!dlg.getRespuesta()) return;
                    }
                        
                    ConstruyeBoleto(cont);
                    System.out.print("Boletos[0][0] = "+Boletos[0][29]);
                    if(hayBoletosRedondos) BoletosRedondos = Boletos;
                    else BoletosRedondos=null;
                    //System.out.print("BoletosRedondos[0][0] = "+BoletosRedondos[0][29]);
                    EjecutaCobro();
                    break;
            }
        }
    }//GEN-LAST:event_jTblRvnKeyPressed

    private void jTblBusqRvnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblBusqRvnKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ENTER:
                    if(sesionVenta.getUserCon().getAplicacionVenta()) jLblBarraEstado.setText(mensajes.getMensajeVta(14));
                    else jLblBarraEstado.setText(mensajes.getMensajeVta(141));
                    filaBusqRvn=jTblBusqRvn.getSelectedRow();
                    jTblRvn.setColumnSelectionInterval(4,4);
                    jTblRvn.setRowSelectionInterval(0,0);
                    hayBoletosRedondos=false;
                    abledComponents(jTblRvn);
                    jTblRvn.requestFocusInWindow();
                    enabledComponents(jTblBusqRvn);
                break;
            case KeyEvent.VK_ESCAPE:
                    jLblBarraEstado.setText(mensajes.getMensajeVta(12));
                    xBusq.setDataVector(null, encBusq);
                    AnchoColumnasBusq();
                    xRvn.setDataVector(null, encRvn);
                    AnchoColumnasRvn();
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jTxtClave.setText("");
                    jTxtNoResp.setText("");
                    jLblImporte.setText("Importe Reservacion: $0.00");
                    abledComponentsCriterios();
                    jCboOrigen.requestFocusInWindow();
                    enabledComponents(jTblBusqRvn);
                break;
            case KeyEvent.VK_F8:
                    if(!sesionVenta.ValidaFuncionUsuario("5011")){
                        jDlgAutorizaSupervisor dlg = new jDlgAutorizaSupervisor(sesionVenta,"5011", "Cancelar Boleto Reservado");
                        dlg.setVisible(true);
                        if(!dlg.getRespuesta()) return;
                    }
                    if(busqRvn[jTblBusqRvn.getSelectedRow()][6].toString().equals("C")){
                        DialogoSiNo = new JDlgSiNo("La reservacion seleccionada es <<no cancelable>>","¿Desea cancelarla completamente?", false);
                        if(!DialogoSiNo.getResultado()) return;
                    }
                    else{
                        DialogoSiNo = new JDlgSiNo("¡Confirme!","¿Desea cancelar completamente la reservacion seleccionada?", false);
                        if(!DialogoSiNo.getResultado()) return;
                    }
                    
                    if(!validaBloqueRvn(xBusq.getValueAt(jTblBusqRvn.getSelectedRow(),0).toString(),"B")) return;
                    if(!sesionVenta.cancelarReservacionTotal(Rvn, thX.getFecha().getTime())) DialogoAceptar.mostrarDialogo("¡Error!","<html>La cancelacion de la reservacion no se realizo.<br>Contacte al administrador del sistema.</html>",Color.RED);
                    else DialogoAceptar.mostrarDialogo("¡Cancelacion exitosa!","Presione enter para continuar...",colorDialogoActivo);                    
                    if(!validaBloqueRvn(xBusq.getValueAt(jTblBusqRvn.getSelectedRow(),0).toString(),"L")) return;
                    
                    xBusq.setDataVector(null, encBusq);
                    AnchoColumnasBusq();
                    xRvn.setDataVector(null, encRvn);
                    AnchoColumnasRvn();
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jTxtClave.setText("");
                    jTxtNoResp.setText("");
                    jLblImporte.setText("Importe Reservacion: $0.00");
                    jLblBarraEstado.setText(mensajes.getMensajeVta(12));
                    abledComponentsCriterios();
                    jCboOrigen.requestFocusInWindow();
                    enabledComponents(jTblBusqRvn);
                break;
            case KeyEvent.VK_F10:
                    if(!sesionVenta.getUserCon().getAplicacionVenta()) return; 
                    tpSoloVac = false;
                    // EXISTE DISPONIBILIDAD DE BOLETOS PARA VENTA
                    long f1=Long.valueOf(sesionVenta.obtenerFolioActual(this.nombreEmpresa)), f2=sesionVenta.obtenerFolioFinal(this.nombreEmpresa);
                    long f3=(f2-f1)+1;
                    if(Integer.valueOf(busqRvn[jTblBusqRvn.getSelectedRow()][3].toString())>f3){
                        this.getToolkit().beep();
                        DialogoAceptar.mostrarDialogo("Limite de folios.",
                                "<html>No tiene boletos suficientes para vender las reservaciones.<br>" +
                                f3+" folio(s) disponible(s).</html>", Color.RED);
                        return;
                    }
                    
                    for(int i=0; i<xRvn.getRowCount(); i++){
                        if(Rvn[i][3].toString().equals("E") || Rvn[i][3].toString().equals("P")) tpSoloVac=true;
                    }
                    if(tpSoloVac){
                        if(!sesionVenta.sonVacaciones()){
                            DialogoAceptar.mostrarDialogo("Venta reservacion.","<html>Seleccionó reservaciones con tipo de pasajero<br>solo habilitado en periodo vacacional.</html>", Color.RED);
                            return;
                        }
                    }
                    //
                    DialogoSiNo = new JDlgSiNo("¡Confirme!","¿Desea vender completamente la reservacion seleccionada?", true);
                    if(!DialogoSiNo.getResultado()) return;
                    if(!sesionVenta.ValidaFuncionUsuario("5010")){
                        jDlgAutorizaSupervisor dlg = new jDlgAutorizaSupervisor(sesionVenta,"5010", "Vender Boleto Reservado");
                        dlg.setVisible(true);
                        if(!dlg.getRespuesta()) return;
                    }
                    contBR=-1;
                    ConstruyeBoleto(Integer.valueOf(busqRvn[jTblBusqRvn.getSelectedRow()][3].toString()));
                    BoletosRedondos=null;
                    EjecutaCobro();
                break;
        }
    }//GEN-LAST:event_jTblBusqRvnKeyPressed

    private void jTxtNoRespKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNoRespKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE:
                this.dispose();
                break;
            case KeyEvent.VK_ENTER:
                    if(!validaCampos()) return;
                    sesionVenta.getDBLinkClaveOrigen(jCboOrigen.getSelectedItem().toString());
                    if(jCboOrigen.getSelectedItem().toString().equals(sesionVenta.getUserCon().getTerminalNombre())) sesionVenta.setTipoTransaccion("L");
                    else sesionVenta.setTipoTransaccion("R");
                    if(jTxtClave.getText().equals("") && jTxtNoResp.getText().equals("")){
                        DialogoSiNo = new JDlgSiNo("¡Busqueda sin criterios especificos!", "<html>Esta busqueda puede tardar varios segundos.<br>¿Desea continuar?</html>", false);
                        if(!DialogoSiNo.getResultado()) return;
                    }
                    reservaciones = new ArrayList<TmsVtaRvnV>();
                    reservaciones = sesionVenta.obtenerRvnesEnc(jTxtClave.getText(), jTxtNoResp.getText());
                    //System.out.println("reservaciones size() = "+reservaciones.size());
                    
                    encabezados();
                    detalles(0);
                    xBusq.setDataVector(busqRvn, encBusq);
                    AnchoColumnasBusq();
                    xRvn.setDataVector(Rvn, encRvn);
                    AnchoColumnasRvn();
                    if(reservaciones == null || reservaciones.size()==0){
                        DialogoAceptar.mostrarDialogo("¡No existen reservaciones!","El criterio de busqueda no genero resultados.", Color.RED);
                        jTxtClave.setText("");
                        jTxtNoResp.setText("");
                        jLblImporte.setText("Importe Reservacion: $0.00");
                        jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                        jCboOrigen.requestFocusInWindow();
                        return;
                    }
                    sesionVenta.setTipoTransaccionAuxiliar(sesionVenta.getTipoTransaccion());
                    sesionVenta.setDBLinkAuxiliar(sesionVenta.getDBLink());
                    if(sesionVenta.getUserCon().getAplicacionVenta()) jLblBarraEstado.setText(mensajes.getMensajeVta(13));
                    else jLblBarraEstado.setText(mensajes.getMensajeVta(131));
                    jTblBusqRvn.setColumnSelectionInterval(0,0);
                    jTblBusqRvn.setRowSelectionInterval(0,0);
                    abledComponents(jTblBusqRvn);
                    jTblBusqRvn.requestFocusInWindow();
                    enabledComponents(jTblRvn);
                    enabledComponentsCriterios();
                break;
            case KeyEvent.VK_LEFT:
                    jTxtClave.selectAll();
                    jTxtClave.requestFocusInWindow();
                break;
            case KeyEvent.VK_RIGHT:
                    jCboOrigen.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jTxtNoRespKeyPressed

    private void jTxtClaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtClaveKeyPressed
// TODO add your handling code here:
                switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE:
                this.dispose();
                break;
            case KeyEvent.VK_ENTER:
                    if(!validaCampos()) return;
                    sesionVenta.getDBLinkClaveOrigen(jCboOrigen.getSelectedItem().toString());
                    if(jCboOrigen.getSelectedItem().toString().equals(sesionVenta.getUserCon().getTerminalNombre())) sesionVenta.setTipoTransaccion("L");
                    else sesionVenta.setTipoTransaccion("R");
                    if(jTxtClave.getText().equals("") && jTxtNoResp.getText().equals("")){
                        DialogoSiNo = new JDlgSiNo("¡Busqueda sin criterios especificos!", "<html>Esta busqueda puede tardar varios segundos.<br>¿Desea continuar?</html>", false);
                        if(!DialogoSiNo.getResultado()) return;
                    }
                    reservaciones = new ArrayList<TmsVtaRvnV>();
                    reservaciones = sesionVenta.obtenerRvnesEnc(jTxtClave.getText(), jTxtNoResp.getText());
                    encabezados();
                    detalles(0);
                    xBusq.setDataVector(busqRvn, encBusq);
                    AnchoColumnasBusq();
                    xRvn.setDataVector(Rvn, encRvn);
                    AnchoColumnasRvn();
                    if(reservaciones == null || reservaciones.size()==0){
                        DialogoAceptar.mostrarDialogo("¡No existen reservaciones!","El criterio de busqueda no genero resultados.", Color.RED);
                        jTxtClave.setText("");
                        jTxtNoResp.setText("");
                        jLblImporte.setText("Importe Reservacion: $0.00");
                        jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                        jCboOrigen.requestFocusInWindow();
                        return;
                    }
                    sesionVenta.setTipoTransaccionAuxiliar(sesionVenta.getTipoTransaccion());
                    sesionVenta.setDBLinkAuxiliar(sesionVenta.getDBLink());
                    if(sesionVenta.getUserCon().getAplicacionVenta()) jLblBarraEstado.setText(mensajes.getMensajeVta(13));
                    else jLblBarraEstado.setText(mensajes.getMensajeVta(131));
                    jTblBusqRvn.setColumnSelectionInterval(0,0);
                    jTblBusqRvn.setRowSelectionInterval(0,0);
                    abledComponents(jTblBusqRvn);
                    jTblBusqRvn.requestFocusInWindow();
                    enabledComponents(jTblRvn);
                    enabledComponentsCriterios();
                break;
            case KeyEvent.VK_LEFT:
                    jCboOrigen.requestFocusInWindow();
                break;
            case KeyEvent.VK_RIGHT:
                    jTxtNoResp.selectAll();
                    jTxtNoResp.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jTxtClaveKeyPressed

    private void jCboOrigenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCboOrigenKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE:
                this.dispose();
                break;
            case KeyEvent.VK_ENTER:
                    if(!validaCampos()) return;
                    sesionVenta.getDBLinkClaveOrigen(jCboOrigen.getSelectedItem().toString());
                    if(jCboOrigen.getSelectedItem().toString().equals(sesionVenta.getUserCon().getTerminalNombre())) sesionVenta.setTipoTransaccion("L");
                    else sesionVenta.setTipoTransaccion("R");
                    if(jTxtClave.getText().equals("") && jTxtNoResp.getText().equals("")){
                        DialogoSiNo = new JDlgSiNo("¡Busqueda sin criterios especificos!", "<html>Esta busqueda puede tardar varios segundos.<br>¿Desea continuar?</html>", false);
                        if(!DialogoSiNo.getResultado()) return;
                    }
                    reservaciones = new ArrayList<TmsVtaRvnV>();
                    reservaciones = sesionVenta.obtenerRvnesEnc(jTxtClave.getText(), jTxtNoResp.getText());
                    encabezados();
                    detalles(0);
                    xBusq.setDataVector(busqRvn, encBusq);
                    AnchoColumnasBusq();
                    xRvn.setDataVector(Rvn, encRvn);
                    AnchoColumnasRvn();
                    if(reservaciones == null || reservaciones.size()==0){
                        DialogoAceptar.mostrarDialogo("¡No existen reservaciones!","El criterio de busqueda no genero resultados.", Color.RED);
                        jTxtClave.setText("");
                        jTxtNoResp.setText("");
                        jLblImporte.setText("Importe Reservacion: $0.00");
                        jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                        jCboOrigen.requestFocusInWindow();
                        return;
                    }
                    sesionVenta.setTipoTransaccionAuxiliar(sesionVenta.getTipoTransaccion());
                    sesionVenta.setDBLinkAuxiliar(sesionVenta.getDBLink());
                    if(sesionVenta.getUserCon().getAplicacionVenta()) jLblBarraEstado.setText(mensajes.getMensajeVta(13));
                    else jLblBarraEstado.setText(mensajes.getMensajeVta(131));
                    jTblBusqRvn.setColumnSelectionInterval(0,0);
                    jTblBusqRvn.setRowSelectionInterval(0,0);
                    abledComponents(jTblBusqRvn);
                    jTblBusqRvn.requestFocusInWindow();
                    enabledComponents(jTblRvn);
                    enabledComponentsCriterios();
                break;
            case KeyEvent.VK_LEFT:
                    jTxtNoResp.selectAll();
                    jTxtNoResp.requestFocusInWindow();
                break;
            case KeyEvent.VK_RIGHT:
                    jTxtClave.selectAll();
                    jTxtClave.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jCboOrigenKeyPressed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
// TODO add your handling code here:
        xBusq.setDataVector(busqRvn,encBusq);
        AnchoColumnasBusq();
        xRvn.setDataVector(Rvn,encRvn);
        AnchoColumnasRvn();
        jLblBarraEstado.setText(mensajes.getMensajeVta(12));
        jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
        jCboOrigen.requestFocusInWindow();
    }//GEN-LAST:event_formComponentShown
    
    private void AnchoColumnasBusq() {
        int anchoContenedor = jScpBusq.getWidth();
        TableColumn column;
        for (int i = 0; i < jTblBusqRvn.getColumnCount(); i++) {
            column = jTblBusqRvn.getColumnModel().getColumn(i);
            switch (i) {
                //private Object[] encBusq = {"CLAVE", "NOMBRE", "FECHA RVN", "RVN", "CAN", "VTA", "TIPO"};
                case 0: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.18)); break;
                case 1: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.32)); break;
                case 2: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.22)); break;
                case 3: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.06)); break;
                case 4: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.06)); break;
                case 5: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.06)); break;
                case 6: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.10)); break;
            }
        }
    }
    
    private void AnchoColumnasRvn() {
        int anchoContenedor = jScpRvn.getWidth();
        TableColumn column;
        for (int i = 0; i < 10; i++) {
            column = jTblRvn.getColumnModel().getColumn(i);
            switch (i) {
                case 0: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.15)); break;
                case 1: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.11)); break;
                case 2: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.03)); break;
                case 3: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.03)); break;
                case 4: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.20)); break;
                case 5: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.17)); break;
                case 6: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.15)); break;
                case 7: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.07)); break;
                case 8: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.04)); break;
                case 9: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.05)); break;
            }
            column.setResizable(false);
        }
        TableColumn colNombre = jTblRvn.getColumnModel().getColumn(4);
        colNombre.setCellEditor(new DefaultCellEditor(jTxtNombre));
        TableColumn colSel = jTblRvn.getColumnModel().getColumn(8);
        colSel.setCellEditor(new DefaultCellEditor(jCkbSel));
        jCkbSel.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCkbSelItemStateChanged(evt);
            }
        });
    }

    private boolean validaCampos(){
        if(jCboOrigen.getSelectedItem()==null){
            DialogoAceptar.mostrarDialogo("¡Importante!","Seleccione un origen.", Color.RED);
            jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
            jCboOrigen.requestFocusInWindow(); return false;
        }
        return true;
    }
    
    private void encabezados(){
        if(reservaciones==null || reservaciones.size()==0){ Rvn=null; busqRvn=null; return; }
        int i, j=0;
        for(i=0; i<reservaciones.size(); i+=reservaciones.get(i).getTotalRvdos()) j++;
        busqRvn = new Object[j][9];
        for(i=0, j=0; i<reservaciones.size(); i+=reservaciones.get(i).getTotalRvdos(), j++){
            busqRvn[j][0] = reservaciones.get(i).getClaveReservacion();
            busqRvn[j][1] = reservaciones.get(i).getResponsableReservacion();
            System.out.println("fecha reservacion (creacion): "+reservaciones.get(i).getFechaCreacion());
            //busqRvn[j][2] = formatDateHour.format(reservaciones.get(i).getFechaCreacion());
            busqRvn[j][2] =  reservaciones.get(i).getfCreacion() + " " + reservaciones.get(i).gethCreacion();
            System.out.println("fecha reservacion (formatDateHour): "+busqRvn[j][2]);
            System.out.println("FCreacion reservacion (creacion): "+reservaciones.get(i).getfCreacion());
            System.out.println("HCreacion reservacion (formatDateHour): "+reservaciones.get(i).gethCreacion());
            busqRvn[j][3] = reservaciones.get(i).getTotalRvdos();
            busqRvn[j][4] = reservaciones.get(i).getTotalCndos();
            busqRvn[j][5] = reservaciones.get(i).getTotalVta();
            busqRvn[j][6] = reservaciones.get(i).getCancelable();
            busqRvn[j][7] = reservaciones.get(i).getReservacionId();
            busqRvn[j][8] = reservaciones.get(i).getClienteId();
        }
    }
    
    private void detalles(int indice){
        if(busqRvn==null) return;
        int i, ini=0, fin=0, j=0;
        
        for(i=0; i<indice; i++)
            ini+=Integer.valueOf(busqRvn[i][3].toString());
        System.out.println("indice "+indice+" - ini "+ini);
        fin=Integer.valueOf(busqRvn[indice][3].toString());
        Rvn = new Object[fin][17];
        fin+=ini;
        System.out.println(" - fin "+fin+" finalmente "+(fin+ini));
        System.out.println("ruta id : "+reservaciones.get(ini).getRutaId());
        //VAGL&&RAI 09/02/2009
//        TarifaSencillo = sesionVenta.getTarifaTramo(reservaciones.get(ini).getServicio()+reservaciones.get(ini).getOrigen()+reservaciones.get(ini).getDestino()+"SEN",0);
//        TarifaRedondo = sesionVenta.getTarifaTramo(reservaciones.get(ini).getServicio()+reservaciones.get(ini).getOrigen()+reservaciones.get(ini).getDestino()+"RED",0);
        TarifaSencillo = sesionVenta.getTarifaTramo(reservaciones.get(ini).getRutaId()+reservaciones.get(ini).getServicio()+reservaciones.get(ini).getOrigen()+reservaciones.get(ini).getDestino()+"SEN",0);
        TarifaRedondo = sesionVenta.getTarifaTramo(reservaciones.get(ini).getRutaId()+reservaciones.get(ini).getServicio()+reservaciones.get(ini).getOrigen()+reservaciones.get(ini).getDestino()+"RED",0);
        double tDescuento = 0, TTarifa;
        suma=0;
        long tipoId;
        //System.out.println("inicio, fin "+ini+" --- "+fin+" --- indice "+indice);
        jugandoImporteVenta = new double[Integer.valueOf(busqRvn[indice][3].toString())];
        jugandoImporteVentaPermiso = new String[Integer.valueOf(busqRvn[indice][3].toString())];
        for(i=ini; i<fin; i++){
            Rvn[j][0] = reservaciones.get(i).getClaveCorrida();
            //Rvn[j][1] = formatDate.format(reservaciones.get(i).getFechaHoraCorrida());
            Rvn[j][1] = reservaciones.get(i).getFCorrida();
             System.out.println("Fecha de la corrida de la Reservacion(Original): "+reservaciones.get(i).getFechaHoraCorrida());
             System.out.println("Fecha de la corrida de la Reservacion: "+Rvn[j][1]);
            Rvn[j][2] = reservaciones.get(i).getNoAsiento();
            Rvn[j][3] = reservaciones.get(i).getTipoPasajero();
            Rvn[j][4] = reservaciones.get(i).getResponsableReservacion();
            Rvn[j][5] = reservaciones.get(i).getServicio();
            Rvn[j][6] = reservaciones.get(i).getOrigen()+"/"+reservaciones.get(i).getDestino();
            tipoId = jTxtTipoPasaje.getTipopasajeid(reservaciones.get(i).getTipoPasajero().charAt(0), reservaciones.get(i).getRutaId());
            System.out.println("Reservacion RutaId =  "+reservaciones.get(i).getRutaId());
            this.setRutaReservacionId(reservaciones.get(i).getRutaId());
            sesionVenta.setTiposPasajeLealtad(Integer.valueOf(""+this.getRutaReservacionId()),reservaciones.get(i).getOrigen());
            tDescuento = jTxtTipoPasaje.getDescuento(tipoId);
            String redondeo =jTxtTipoPasaje.getRedondeo(tipoId);
            if(redondeo.equals("S"))
                TTarifa = Math.ceil(TarifaSencillo - (tDescuento * TarifaSencillo));
            else
            {
                TTarifa = TarifaSencillo - (tDescuento * TarifaSencillo);
                double d = (TTarifa - (Double.valueOf(""+TTarifa).longValue()) );
                if(d > 0 && d != .50)                                
                   TTarifa =    Math.ceil(TTarifa);            
            }
            suma = suma+TTarifa;
            Rvn[j][7] = TTarifa;
            Rvn[j][8] = "VT";
            Rvn[j][9] = "S";
            Rvn[j][10] = reservaciones.get(i).getReservacionId();
            Rvn[j][11] = reservaciones.get(i).getCorridaId();
            Rvn[j][12] = reservaciones.get(i).getOrigen();
            Rvn[j][13] = reservaciones.get(i).getDestino();
            Rvn[j][14] = reservaciones.get(i).getEmpresa();
            //Rvn[j][15] = formatHour.format(reservaciones.get(i).getFechaHoraCorrida());
            Rvn[j][15] =  reservaciones.get(i).getHCorrida();
            System.out.println("Hora de la corrida de la Reservacion(Original): "+reservaciones.get(i).getFechaHoraCorrida());
             System.out.println("Hora de la corrida de la Reservacion: "+Rvn[j][15]);
            System.out.println("FCorrida reservacion : "+reservaciones.get(i).getFCorrida());
            System.out.println("HCorrida reservacion : "+reservaciones.get(i).getHCorrida());
             
            Rvn[j][16] = reservaciones.get(i).getRutaId();
            jugandoImporteVenta[j]=tDescuento; // DESCUENTO
            jugandoImporteVentaPermiso[j]=redondeo; // SI APLICA REDONDEO
            j++;
        }
        jLblImporte.setText("Importe Reservacion: $" + suma);
    }
    
    private void ConstruyeBoleto(int boletos){
        int i, j=0;
        double tDescuento = 0, TTarifa, TTarifaR;
        long tipoId;
        if(contBR==-1) Boletos = new Object[boletos][37];//[32]
        else Boletos = new Object[contBR][37];//[32]
        for (i = 0,j=0; i < jTblRvn.getRowCount(); i++) {
            if(Rvn[i][8].toString().equals("VT")){
                Boletos[j][0] = Rvn[i][0]+"-"+Rvn[i][15];                               // corrida-hora
                Boletos[j][1] = Rvn[i][2];                                              // asiento
                Boletos[j][2] = Rvn[i][3];                                              // tipo pasajero
                Boletos[j][3] = jTblRvn.getValueAt(i,4).toString();//Rvn[i][4];         // nombre pasajero
                Boletos[j][4] = Rvn[i][6];                                              // origen-destino
                tipoId = jTxtTipoPasaje.getTipopasajeid(Rvn[i][3].toString().charAt(0),Long.valueOf(Rvn[i][16].toString()));
                tDescuento = jTxtTipoPasaje.getDescuento(tipoId);
                String redondeo =jTxtTipoPasaje.getRedondeo(tipoId);
                //if(( Rvn[i][5].toString().equals("DIRECTO ECONOMICO") || Rvn[i][5].toString().equals("PULLMAN PRIMERA CLASE")) && Rvn[i][9].equals("R") )
                if(( Rvn[i][16].toString().equals("19") || Rvn[i][16].toString().equals("20") || Rvn[i][16].toString().equals("225") || Rvn[i][16].toString().equals("226") || Rvn[i][16].toString().equals("241") || Rvn[i][16].toString().equals("242") || Rvn[i][16].toString().equals("219") || Rvn[i][16].toString().equals("220") || Rvn[i][16].toString().equals("292") || Rvn[i][16].toString().equals("293")) && Rvn[i][9].equals("R") )
                {
                    if(redondeo.equals("S"))
                    {
                        //TTarifa = Math.ceil(TarifaRedondo/2);
                        TTarifa = Math.ceil((TarifaRedondo-(TarifaRedondo*.5)));
                    }
                    else
                    {
                        //TTarifa = TarifaRedondo/2;
                        TTarifa = (TarifaRedondo-(TarifaRedondo*.5));
                        double d = (TTarifa - (Double.valueOf(""+TTarifa).longValue()) );
                        if(d > 0 && d != .50)                                
                            TTarifa =    Math.ceil(TTarifa);                    
                    }
                 }
                else
                {
                    if(redondeo.equals("S"))
                        TTarifa = Math.ceil(TarifaSencillo - (tDescuento * TarifaSencillo));
                    else
                    {
                        TTarifa = TarifaSencillo - (tDescuento * TarifaSencillo);
                        double d = (TTarifa - (Double.valueOf(""+TTarifa).longValue()) );
                        if(d > 0 && d != .50)                                
                            TTarifa =    Math.ceil(TTarifa);                    
                    }
                }
                Boletos[j][5] = TTarifa;                                               // importe boleto
                Boletos[j][6] = "S";                                                    // BOLETO NORMAL + BOLETO ABIERTO
                Boletos[j][7] = Rvn[i][14];                                             // empresa
                Boletos[j][8] = Rvn[i][5];                                              // servicio
                Boletos[j][9] = sesionVenta.getUserCon().getCaja();                     // caja
                Boletos[j][10] = sesionVenta.getUserCon().getCorteId();                 // corte id
                Boletos[j][11] = Rvn[i][0];                                             // clave corrida
                Boletos[j][12] = busqRvn[jTblBusqRvn.getSelectedRow()][8];              // cliente id
                Boletos[j][13] = null;                                                  // tipo pago
                Boletos[j][14] = null;                                                  // referencia pago
                Boletos[j][15] = "VT";                                                  // tipo operacion
                Boletos[j][16] = Rvn[i][10];                                             // reservacion id
                Boletos[j][17] = null;                                                  // boleto relacionado id
                Boletos[j][18] = null;                                                  // dias validez boleto abierto
                Boletos[j][19] = sesionVenta.obtenerFolioActual(this.nombreEmpresa);    // folio preimpreso
                Boletos[j][20] = sesionVenta.getUserCon().getTerminalNombre();          // ciudad Venta
                Boletos[j][21] = Rvn[i][12];                                            // origen
                Boletos[j][22] = Rvn[i][13];                                            // destino
                Boletos[j][23] = this.tipoTransaccion;                                  // tipo Transaccion
                Boletos[j][24] = sesionVenta.getUserCon().getUsuarioNum();              // cajero
                Boletos[j][25] = Rvn[i][11];                                            // corridaId
                Boletos[j][26] = Rvn[i][1];                                             // fecha
                Boletos[j][27] = Rvn[i][15];                                            // hora
                Boletos[j][28] = false;                                                 // sin numero de asiento
                Boletos[j][29] = "N";                                                   //Tipo de Venta (N = Normal, F = Referenciada)
                Boletos[j][30] = "";                                                    //Nombre del cliente autorizado 
                Boletos[j][31] = "S";                                                    //
                
                System.out.println("Indice j antes "+j+" con indice i "+i+" de "+jTblRvn.getRowCount());
                j++;
                System.out.println("Indice j despues "+j+" con indice i "+i+" de "+jTblRvn.getRowCount());
                
                if(Rvn[i][9].equals("R")){
                    Boletos[j][0] = null;                                                   // corrida-hora
                    Boletos[j][1] = null;                                                   // asiento
                    Boletos[j][2] = Rvn[i][3];                                              // tipo pasajero
                    Boletos[j][3] = jTblRvn.getValueAt(i,4).toString();//Rvn[i][4];         // nombre pasajero
                    Boletos[j][4] = Rvn[i][13]+"-"+Rvn[i][12];                              // origen-destino
                    //if(( Rvn[i][5].toString().equals("DIRECTO ECONOMICO") || Rvn[i][5].toString().equals("PULLMAN PRIMERA CLASE")) && Rvn[i][9].equals("R") )
                    if(( Rvn[i][16].toString().equals("19") || Rvn[i][16].toString().equals("20") || Rvn[i][16].toString().equals("225") || Rvn[i][16].toString().equals("226") || Rvn[i][16].toString().equals("241") || Rvn[i][16].toString().equals("242") || Rvn[i][16].toString().equals("219") || Rvn[i][16].toString().equals("220") || Rvn[i][16].toString().equals("292") || Rvn[i][16].toString().equals("293")) && Rvn[i][9].equals("R") ) 
                    {
                      if(redondeo.equals("S"))
                        //TTarifaR = Math.ceil(TarifaRedondo/2);
                          TTarifaR = Math.ceil((TarifaRedondo-(TarifaRedondo*.5)));
                      else
                      {
                            //TTarifaR = TarifaRedondo/2;
                            TTarifaR = (TarifaRedondo-(TarifaRedondo*.5));
                            double d = (TTarifaR - (Double.valueOf(""+TTarifaR).longValue()) );
                            if(d > 0 && d != .50)                                
                                TTarifaR =    Math.ceil(TTarifaR);                        
                      }
                    }
                    else
                        TTarifaR = TarifaRedondo-TarifaSencillo;                                
                    if(redondeo.equals("S"))    
                        Boletos[j][5] = Math.ceil(TTarifaR -(tDescuento*TTarifaR));                                              // importe boleto
                    else
                    {
                        Boletos[j][5] = TTarifaR -(tDescuento*TTarifaR);                                              // importe boleto
                        double d = ((TTarifaR -(tDescuento*TTarifaR)) - (Double.valueOf(""+(TTarifaR -(tDescuento*TTarifaR))).longValue()) );
                        if(d > 0 && d != .50)                                
                            Boletos[j][5] = Math.ceil(TTarifaR -(tDescuento*TTarifaR));                                              // importe boleto
                    }
                    Boletos[j][6] = "R";                                                    // BOLETO NORMAL + BOLETO ABIERTO
                    Boletos[j][7] = Rvn[i][14];                                             // empresa
                    Boletos[j][8] = Rvn[i][5];                                              // servicio
                    Boletos[j][9] = sesionVenta.getUserCon().getCaja();                     // caja
                    Boletos[j][10] = sesionVenta.getUserCon().getCorteId();                 // corte id
                    Boletos[j][11] = null;                                                  // clave corrida
                    Boletos[j][12] = busqRvn[jTblBusqRvn.getSelectedRow()][8];              // cliente id
                    Boletos[j][13] = null;                                                  // tipo pago
                    Boletos[j][14] = null;                                                  // referencia pago
                    Boletos[j][15] = "VA";                                                  // tipo operacion
                    Boletos[j][16] = Rvn[i][10];                                            // reservacion id
                    Boletos[j][17] = null;                                                  // boleto relacionado id
                    Boletos[j][18] = null;                                                  // dias validez boleto abierto
                    Boletos[j][19] = sesionVenta.obtenerFolioActual(this.nombreEmpresa);    // folio preimpreso
                    Boletos[j][20] = sesionVenta.getUserCon().getTerminalNombre();          // ciudad Venta
                    Boletos[j][21] = Rvn[i][13];                                            // origen
                    Boletos[j][22] = Rvn[i][12];                                            // destino
                    Boletos[j][23] = this.tipoTransaccion;                                  // tipo Transaccion
                    Boletos[j][24] = sesionVenta.getUserCon().getUsuarioNum();              // cajero
                    Boletos[j][25] = Rvn[i][11];                                            // corridaId
                    Boletos[j][26] = Rvn[i][1];                                             // fecha
                    Boletos[j][27] = Rvn[i][15];                                            // hora
                    Boletos[j][28] = false;                                                 // sin numero de asiento
                    Boletos[j][29] = "N";                                                   //Tipo de Venta (N = Normal, F = Referenciada)
                    Boletos[j][30] = "";                                                    //Nombre del cliente autorizado 
                    Boletos[j][31] = "R";                                                    //
                    j++;
                }
            }
            
            sesionVenta.setImporteVenta(Double.parseDouble(jLblImporte.getText().replace("Importe Reservacion: $"," ").replace(",","")));
        }
    }

    private boolean existeCorridaRegreso(int fila){
        String o, d, s;
        d = this.Rvn[fila][12].toString();  // origen invertido
        o = this.Rvn[fila][13].toString(); // destino invertido
        s = this.Rvn[fila][5].toString(); // servicio
        sesionVenta.getDBLinkClaveOrigenX(o);
        Timestamp xHoy=null;
        try {
            
            xHoy = new Timestamp(formatDate.parse(Rvn[fila][1].toString()+" "+Rvn[fila][15].toString()).getTime());
        } catch (ParseException ex) {
            DialogoAceptar.mostrarDialogo("TMS Venta.","<html>Error de configuracion en la fecha<br>de la reservacion.</html>",Color.RED);
            return false;
        }
        System.out.println(" o "+o+" d "+d+" s "+s+" ::: "+Rvn[fila][1]+" --- "+xHoy);
        int zz = sesionVenta.busqExisteCorrida(o, o, d, xHoy, s, this.nombreEmpresa);
        switch(zz){
            case -1: DialogoAceptar.mostrarDialogo("TMS Venta.","Este servicio no dispone de boleto redondo.",Color.RED); return false;
            case -2: DialogoAceptar.mostrarDialogo("TMS Venta.","La ruta de regreso no permite venta.",Color.RED); return false;
        }
        return true;
    }
    
    private void EjecutaCobro(){
       // if(!validaImporteBoletosEnCero()) return;
        llenaNombres();
        if(!validaBloqueRvn(xBusq.getValueAt(jTblBusqRvn.getSelectedRow(),0).toString(),"B")) return;
        sesionVenta.strCiudadOrigen = jCboOrigen.getSelectedItem().toString();
        System.out.println("Ciudad Origen en cambio de horario: "+sesionVenta.strCiudadOrigen);
        System.out.print("Boletos[0][0] = "+Boletos[0][29]);
        //System.out.print("BoletosRedondos[0][0] = "+BoletosRedondos[0][29]);
        DlgCobro = new JDlgCobro(Boletos, sesionVenta, busqRvn[jTblBusqRvn.getSelectedRow()][0].toString(), "VR", this.nombreEmpresa, BoletosRedondos, this.thX, "","","");
        DlgCobro.setFocusTraversalKeysEnabled(false);
        DlgCobro.setVisible(true);
        int rCobro = DlgCobro.getVentaOk();
        if(!validaBloqueRvn(xBusq.getValueAt(jTblBusqRvn.getSelectedRow(),0).toString(),"L")) return;
        switch(rCobro){
            case 1: // venta cancelada
                this.getToolkit().beep();
                DialogoAceptar.mostrarDialogo("¡Venta Cancelada!", "Presione enter para continuar...", Color.RED);
                break;
            case 2: // anterior
                if(contBR==-1){
                    this.jTblBusqRvn.requestFocusInWindow();
                    return;
                }
                this.jTblRvn.setRowSelectionInterval(0,0);
                this.jTblRvn.setColumnSelectionInterval(4,4);
                abledComponents(jTblRvn);
                this.jTblRvn.requestFocusInWindow();
                return;
            case 3: // error: no se vendio el boleto
                this.getToolkit().beep();
                DialogoAceptar.mostrarDialogo("TMS Venta.","<html>No fue posible realizar la venta.</html>",Color.RED);
                break;
            default: // venta realizada
                String folioActual=sesionVenta.obtenerFolioActual(this.nombreEmpresa);
                long f1=Long.valueOf(folioActual), f2=sesionVenta.obtenerFolioFinal(this.nombreEmpresa);
                if(f1>f2){
                    jLblFolioActual.setText("<html>Folio Actual: <font color="+ColoresInterfaz.cHTML3+">-</font></html>");
                    jLblNombreEmpresa.setText("<html>Empresa: <font color="+ColoresInterfaz.cHTML3+">"+(this.nombreEmpresa.length()>16?this.nombreEmpresa.subSequence(0,15):this.nombreEmpresa)+"</font></html>");
                    this.getToolkit().beep();
                    DialogoAceptar.mostrarDialogo("¡Boletos agotados para venta!", "<html>Realice refoliado de boletos para la empresa<br>"+this.nombreEmpresa+".</html>", Color.RED);
                }
                else{
                    jLblFolioActual.setText("<html>Folio Actual: <font color="+ColoresInterfaz.cHTML3+">"+folioActual+"</font></html>");
                    jLblNombreEmpresa.setText("<html>Empresa: <font color="+ColoresInterfaz.cHTML3+">"+(this.nombreEmpresa.length()>16?this.nombreEmpresa.subSequence(0,15):this.nombreEmpresa)+"</font></html>");
                    if(f1>f2-sesionVenta.getUserCon().getBolNvtImp()){
                        this.getToolkit().beep();
                        DialogoAceptar.mostrarDialogo("Limite de folios.", "<html>Solo restan "+ ((f2-f1)+1)+ " boletos<br>para la empresa "+this.nombreEmpresa+".</html>", Color.RED);
                    }
                }
        }
        xBusq.setDataVector(null,encBusq);
        AnchoColumnasBusq();
        xRvn.setDataVector(null,encRvn);
        AnchoColumnasRvn();
        jTxtClave.setText("");
        jTxtNoResp.setText("");
        jLblImporte.setText("Importe Reservacion: $0.00");
        jLblBarraEstado.setText(mensajes.getMensajeVta(12));
        jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
        abledComponentsCriterios();
        jCboOrigen.requestFocusInWindow();
    }
    
    private void llenaNombres(){
        String NombreAux= "";
        String NombreAuxX= "";
        NombreAux=Boletos[0][3].toString();
        if(!NombreAux.equals("")){
            Boletos[0][3]=NombreAux;
            for (int i=0;i<Boletos.length;i++){
                NombreAuxX = Boletos[i][3].toString().trim();
                if (NombreAuxX.equals(""))
                    Boletos[i][3] = NombreAux;
                else
                    Boletos[i][3] = Boletos[i][3].toString();
            }
        }
        else{
            NombreAux= "VALIDO AL PORTADOR";
            for (int i=0;i<Boletos.length;i++)
                if (Boletos[i][3].toString().equals(""))
                    Boletos[i][3] = NombreAux;
        }
    }
 
    private void interfazColor(){
        jPanel1.setBackground(ColoresInterfaz.cFondoDialogo);
        jTblBusqRvn.setBackground(ColoresInterfaz.cFondoDialogo);
        jTblRvn.setBackground(ColoresInterfaz.cFondoDialogo);
        jScpBusq.setBackground(ColoresInterfaz.cFondoDialogo);
        jScpRvn.setBackground(ColoresInterfaz.cFondoDialogo);
        jLblImporte.setForeground(ColoresInterfaz.cFondoVentana);
        jLblBarraEstado.setForeground(ColoresInterfaz.cTextoAyuda1);
        
        jLabel1.setFont(ColoresInterfaz.fuente1);
        jCboOrigen.setFont(ColoresInterfaz.fuente1);
        jLabel2.setFont(ColoresInterfaz.fuente1);
        jTxtClave.setFont(ColoresInterfaz.fuente1);
        jLabel3.setFont(ColoresInterfaz.fuente1);
        jTxtNoResp.setFont(ColoresInterfaz.fuente1);
        jTblBusqRvn.setFont(ColoresInterfaz.fuente1);
        jTblRvn.setFont(ColoresInterfaz.fuente0);
        jLblImporte.setFont(ColoresInterfaz.fuente1);
        jLblBarraEstado.setFont(ColoresInterfaz.fuente1);
    }
    
    public boolean validaBloqueRvn(String claveRvn, String valor){
        boolean pasa = sesionVenta.bloqueaRvn(claveRvn, valor);
        boolean r = false;
        if(!pasa && valor.equals("L")){ // se quedo bloqueada la reservacion
            DialogoAceptar.mostrarDialogo("Reservacion bloqueada.", "Contacte al administrador del sistema.", Color.RED);
            limpia();
            return false;
        }
        if(!pasa && valor.equals("B")){ // alguien la tiene bloqueada. Quien sera?
            String xq=sesionVenta.quienOcupaRvn(claveRvn);
            if(xq==null){
                DialogoAceptar.mostrarDialogo("Reservacion bloqueada.", "<html>Por el momento no es posible utilizar<br>la reservacion. Intentelo mas tarde.</html>", Color.RED);
                limpia();
                return false;
            }
            DialogoAceptar.mostrarDialogo("Reservacion bloqueada.",
                    (xq.equals("NADA")?"Algun usuario":"<html>El usuario "+xq)+" <br> esta ocupando esta reservacion.</html>", Color.RED);
            limpia();
            return false;
        }
        
        return true;
    }
    
    private void limpia(){
        xBusq.setDataVector(null, encBusq);
        AnchoColumnasBusq();
        xRvn.setDataVector(null, encRvn);
        AnchoColumnasRvn();
        jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
        jTxtClave.setText("");
        jTxtNoResp.setText("");
        jLblImporte.setText("Importe Reservacion: $0.00");
        jLblBarraEstado.setText(mensajes.getMensajeVta(12));
        abledComponentsCriterios();
        jCboOrigen.requestFocusInWindow();
    }
    
    void enabledComponents(JComponent jc){
        jc.setEnabled(false);
    }
    
    void abledComponents(JComponent jc){
        jc.setEnabled(true);
    }
    
    void enabledComponentsCriterios() {
        enabledComponents(jCboOrigen);
        enabledComponents(jTxtClave);
        enabledComponents(jTxtNoResp);
    }
    
    void abledComponentsCriterios() {
        abledComponents(jCboOrigen);
        abledComponents(jTxtClave);
        abledComponents(jTxtNoResp);
    }
 
    private boolean validaImporteBoletosEnCero() {
        boolean r=true;
        int i;
        for(i=0; i<Boletos.length; i++)
            if(Double.valueOf(Boletos[i][5].toString())<=0){
                r=false;
                break;
            }
        
        if(!r)
            DialogoAceptar.mostrarDialogo("Boleto con importe cero",
                "<html>Posibles causas: Tarifa no configurada o boleto redondo<br>con misma tarifa de boleto sencillo.</html>", Color.RED);
        return r;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCboOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLblBarraEstado;
    private javax.swing.JLabel jLblImporte;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScpBusq;
    private javax.swing.JScrollPane jScpRvn;
    private javax.swing.JTable jTblBusqRvn;
    private javax.swing.JTable jTblRvn;
    private javax.swing.JTextField jTxtClave;
    private javax.swing.JTextField jTxtNoResp;
    // End of variables declaration//GEN-END:variables
    private Object[] encRvn = {"CORRIDA", "FECHA", "#", "T", "NOMBRE", "SERVICIO", "ORIGEN/DESTINO", "COSTO", "TX", "VIAJE"};
    private DefaultTableModel xRvn = new DefaultTableModel(null,encRvn){
            public boolean isCellEditable(int row, int col){
                   if(col==4) return true;
                   return false;
            }
        };
    private Object[][] Rvn = null;
    private Object[] encBusq = {"CLAVE", "NOMBRE", "FECHA RVN", "RVN", "CAN", "VTA", "TIPO RVN"};
    private DefaultTableModel xBusq = new DefaultTableModel(null,encBusq){
            public boolean isCellEditable(int row, int col){
                return false;
            }
        };
    private Object[][] busqRvn = null;
    private SesionVenta sesionVenta = null;
    private JDlgAceptar DialogoAceptar = new JDlgAceptar();
    private JClsColoresInterfaz ColoresInterfaz = new JClsColoresInterfaz();
    private Color colorDialogoActivo = ColoresInterfaz.cFondoPieEncabezado;
    private List<TmsVtaRvnV> reservaciones = null;
    private JTextTextFieldMaxCharAlfa jTxtNombre = new JTextTextFieldMaxCharAlfa(30);
    private JCheckBox jCkbSel = new JCheckBox();
    private int lineasCanceladas=-2;
    private int filaBusqRvn=-1;
    private JTxtFieldTipoPasaje jTxtTipoPasaje = new JTxtFieldTipoPasaje();
    private JDlgSiNo DialogoSiNo;
    private JDlgCobro DlgCobro = null;
    private Object[][] Boletos;
    private Object[][] BoletosRedondos;
    private String nombreEmpresa;
    private String DBLink = "";
    private String DBSchema = "";
    private double suma=0;
    private String tipoTransaccion = "L";
    private SimpleDateFormat formatDate = new SimpleDateFormat("dd/MM/yyyy");
    private SimpleDateFormat formatHour = new SimpleDateFormat("HH:mm");
    private SimpleDateFormat formatDateHour = new SimpleDateFormat("dd/MM/yyyy HH:mm");
    private Mensajes mensajes = new Mensajes();
    private Vector pOrigenes;
    
    private JLabel jLblNombreEmpresa = null;
    private JLabel jLblFolioActual = null;
    private RelojVisualVta thX=null;
    private boolean tpSoloVac = false;
    private boolean hayBoletosRedondos;
    private int contBR;
    private double[] jugandoImporteVenta;
    private String[] jugandoImporteVentaPermiso;
    private double TarifaSencillo;

    private long rutaReservacionId=-1;

    private double TarifaRedondo;

    public long getRutaReservacionId() {
        return rutaReservacionId;
    }

    public void setRutaReservacionId(long rutaReservacionId) {
        this.rutaReservacionId = rutaReservacionId;
    }
}