/*
 * JDlgCancelar.java
 *
 * Created on 6 de septiembre de 2007, 12:41 PM
 */

package DialogosX;

import AsignacionVenta.jDlgAutorizaSupervisor;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import subProcesos.JClsSintaxis;
import subProcesos.JTxtFieldFolios;
import subProcesos.RelojVisualVta;
import tms_venta.SesionVenta;
import subProcesos.JTextTextFieldMaxChar;
import subProcesos.JTxtFieldAsientos;
import tms_venta.JClsColoresInterfaz;
import xer_emv_dll.JClsImprimeVoucher;
import xer_emv_dll.JClsPinPadTBRequest;
import xer_emv_dll.JClsPinPadTBResponse;
import xer_emv_dll.JDlgBProgreso;
import xer_emv_dll.JDlgSysCboStandr;
import xer_emv_dll.JObsBProgreso;
import xer_emv_dll.SwingWorker;

/**
 *
 * @author  ocruz
 */
public class JDlgCancelaMultiBoleto extends JDialog{
    /**
     * Creates new form JDlgCancelar
     */
    public JDlgCancelaMultiBoleto(SesionVenta pSesionVenta, Vector pOrigenes, Object[] pObjEmp, RelojVisualVta pThX){
        this.setModal(true);
        this.pOrigenes=pOrigenes;
        this.sesionVenta = pSesionVenta;
        this.objEmp = pObjEmp;
        this.thX = pThX;
        objEmpresas = new Object[objEmp.length];
        for(int i=0; i<objEmpresas.length; i++){
            objEmpresas[i] = sesionVenta.getEmpresasId(objEmp[i].toString()) + "-" + objEmp[i].toString();
            //System.out.println(objEmpresas[i].toString());
        }
        ordenaListaEmpresas();
        initComponents();
        jLabel4.setText("<html><font color="+ColoresInterfaz.cHTML3+">IZQ DER </font> Ingresar Criterios | <font color="+ColoresInterfaz.cHTML3+">ENTER</font> Buscar Boleto | <font color="+ColoresInterfaz.cHTML3+">F8</font> Cancelar | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Salir</html>");
        interfazColor();
        centrarJDialog();
        //((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.setTitle("Cancelar Boleto");
        jCboMotivos.setEnabled(false);
        otroMotivo.setEnabled(false);
        jClsSintaxis = new JClsSintaxis();
    }
    
    private void centrarJDialog(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, ( screenSize.height - frameSize.height ) / 2 );
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCboOrigen = new javax.swing.JComboBox();
        jCboOrigen = new JComboBox(pOrigenes);
        jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
        jCboOrigen.setFocusTraversalKeysEnabled(false);
        jTxtFolioPreimpreso = new JTxtFieldFolios();
        jTxtFolioPreimpreso.setFocusTraversalKeysEnabled(false);
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTxtNoAsiento = new JTxtFieldAsientos();
        jTxtNoAsiento.setFocusTraversalKeysEnabled(false);
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblBoletoOriginal = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jCboMotivos = new javax.swing.JComboBox();
        jCboMotivos.setFocusTraversalKeysEnabled(false);
        otroMotivo = new JTextTextFieldMaxChar(21);
        otroMotivo.setFocusTraversalKeysEnabled(false);
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCboEmpresas = new javax.swing.JComboBox();
        jCboEmpresas = new JComboBox(objEmpresas);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setName("Ventana"); // NOI18N
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel1.setText("Origen");

        jCboOrigen.setFont(new java.awt.Font("Tahoma", 1, 10));
        jCboOrigen.setName("Origen"); // NOI18N
        jCboOrigen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCboOrigenKeyPressed(evt);
            }
        });

        jTxtFolioPreimpreso.setFont(new java.awt.Font("Tahoma", 1, 10));
        jTxtFolioPreimpreso.setName("FolioPreimpreso"); // NOI18N
        jTxtFolioPreimpreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtFolioPreimpresoActionPerformed(evt);
            }
        });
        jTxtFolioPreimpreso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtFolioPreimpresoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtFolioPreimpresoFocusLost(evt);
            }
        });
        jTxtFolioPreimpreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtFolioPreimpresoKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel2.setText("Folio");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel3.setText("# Asiento");

        jTxtNoAsiento.setFont(new java.awt.Font("Tahoma", 1, 10));
        jTxtNoAsiento.setName("noAsiento"); // NOI18N
        jTxtNoAsiento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtNoAsientoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtNoAsientoFocusLost(evt);
            }
        });
        jTxtNoAsiento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtNoAsientoKeyPressed(evt);
            }
        });

        jScrollPane1.setFocusable(false);
        jScrollPane1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N

        jTblBoletoOriginal.setFont(new java.awt.Font("Tahoma", 1, 10));
        jTblBoletoOriginal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTblBoletoOriginal.setModel(xTabla);
        jTblBoletoOriginal.setFocusable(false);
        jScrollPane1.setViewportView(jTblBoletoOriginal);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel6.setText("Motivo Cancelacion");

        jCboMotivos.setFont(new java.awt.Font("Tahoma", 1, 10));
        jCboMotivos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Atencion al Cliente", "Pasajero Quedado", "Error de Impresion", "Otro" }));
        jCboMotivos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCboMotivosKeyPressed(evt);
            }
        });

        otroMotivo.setFont(new java.awt.Font("Tahoma", 1, 10));
        otroMotivo.setText("Otra Razon");
        otroMotivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                otroMotivoKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel4.setText("<html><font color=\"+ColoresInterfaz.cHTML1+\">IZQ DER </font> Ingresar Criterios | <font color=\"+ColoresInterfaz.cHTML1+\">ENTER</font> Buscar Boleto | <font color=\"+ColoresInterfaz.cHTML1+\">F8</font> Cancelar | <font color=\"+ColoresInterfaz.cHTML1+\">ESC</font> Salir</html>");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel5.setText("Empresa");

        jCboEmpresas.setFont(new java.awt.Font("Tahoma", 1, 10));
        jCboEmpresas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCboEmpresasKeyPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 746, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(4, 4, 4)
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jCboMotivos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 139, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(otroMotivo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
                .addContainerGap())
            .add(jPanel1Layout.createSequentialGroup()
                .add(4, 4, 4)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel3)
                    .add(jLabel5))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jCboEmpresas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 218, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jCboOrigen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 113, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTxtNoAsiento, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE)
                    .add(jTxtFolioPreimpreso, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 679, Short.MAX_VALUE))
                .addContainerGap())
            .add(jPanel1Layout.createSequentialGroup()
                .add(4, 4, 4)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                    .add(jLabel1)
                    .add(jLabel2))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jCboOrigen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jTxtFolioPreimpreso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jTxtNoAsiento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jCboEmpresas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(jCboMotivos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(otroMotivo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 26, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNoAsientoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtNoAsientoFocusLost
// TODO add your handling code here:
        jTxtNoAsiento.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTxtNoAsientoFocusLost

    private void jTxtFolioPreimpresoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtFolioPreimpresoFocusLost
// TODO add your handling code here:
        jTxtFolioPreimpreso.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTxtFolioPreimpresoFocusLost

    private void jTxtNoAsientoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtNoAsientoFocusGained
// TODO add your handling code here:
        jTxtNoAsiento.setBackground(xorColorFondo);
    }//GEN-LAST:event_jTxtNoAsientoFocusGained

    private void jTxtFolioPreimpresoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtFolioPreimpresoFocusGained
// TODO add your handling code here:
        jTxtFolioPreimpreso.setBackground(xorColorFondo);
    }//GEN-LAST:event_jTxtFolioPreimpresoFocusGained

    private void jCboEmpresasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCboEmpresasKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE:
                this.dispose();
                break;
            case KeyEvent.VK_ENTER:
                if(!validaCampos()) return;
                if(!valMultiTx(jTxtFolioPreimpreso.getText(), jTxtNoAsiento.getText())){
                    return;
                }
                ConstruyeMultiCancelacion();
                if(jCboOrigen.getSelectedItem().toString().equals(sesionVenta.getUserCon().getTerminalNombre())) sesionVenta.setTipoTransaccion("L");
                else sesionVenta.setTipoTransaccion("R");
                boletos = sesionVenta.buscaBoletoVendidoParaCancelar(jCboOrigen.getSelectedItem().toString(),
                        conjuntoFolios, conjuntoAsientos, jCboEmpresas.getSelectedItem().toString().substring((jCboEmpresas.getSelectedItem().toString().indexOf("-")) + 1),jClsSintaxis.getVectorFoliosBoletos().size());
                if(boletos==null){
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    DialogoAceptar.mostrarDialogo("Cancelación de boleto.","No es posible realizar la cancelación de este boleto.", Color.RED);
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                    return;
                }

                if(!sonDeLaMismaCorrida()){
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    DialogoAceptar.mostrarDialogo("Cancelación de boleto.","<html>No es posible realizar la cancelación de estos boletos.<br>No pertenecen a la misma corrida.</html>", Color.RED);
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                    return;
                }

                if(sonPromocion())
                {
                    DialogoAceptar.mostrarDialogo("Cancelación de boleto.","<html>No es posible realizar la cancelación de estos boletos.<br>Los boletos vendidos con promoción no son cancelables.</html>", Color.RED);
                    return;
                }
                                /*
                if(sonAculuacionEstrellas()){
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    DialogoAceptar.mostrarDialogo("Cancelación de boleto.","<html>No es posible realizar la cancelación de <br>Boletos con Estrellas Acumuladas.</html>", Color.RED);
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                    return;
                }*/
                
                sesionVenta.setTipoTransaccionAuxiliar(sesionVenta.getTipoTransaccion());
                sesionVenta.setDBLinkAuxiliar(sesionVenta.getDBLink());
                String FHc = sesionVenta.FechaHoraCorrida();
                //System.out.println("FECHA CORRIDA "+FHc);
                if(FHc==null){
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    DialogoAceptar.mostrarDialogo("¡Corrida sin fecha asociada!","Contacte al administrador del sistema.", Color.RED);
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                    return;
                }

                try {
                    String strDtFecha=formatoFechaHora.format(formatoDateServer2.parse(FHc).getTime());
                    fechaCorridaBoleto  = formatoFechaHora.parse(strDtFecha);
                    for(int i=0; i<boletos.length; i++){
                        boletos[i][1] = strDtFecha;
                    }
                } catch (ParseException ex) {
                    fechaCorridaBoleto = null;
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    DialogoAceptar.mostrarDialogo("¡Corrida con fecha invalida!","Contacte al administrador del sistema.", Color.RED);
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                    return;
                }
                
                xTabla.setDataVector(boletos, encabezado);
                AnchoColumnas();
                jCboMotivos.setEnabled(true);
                jCboMotivos.requestFocusInWindow();
                break;
            case KeyEvent.VK_LEFT: case KeyEvent.VK_UP:
                jTxtNoAsiento.selectAll();
                jTxtNoAsiento.requestFocusInWindow();
                break;
            case KeyEvent.VK_RIGHT:
                jCboOrigen.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jCboEmpresasKeyPressed
    
    private void otroMotivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_otroMotivoKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_LEFT:
                otroMotivo.setText("");
                otroMotivo.setEnabled(false);
                jCboMotivos.setSelectedIndex(0);
                jCboMotivos.requestFocusInWindow();
                break;
            case KeyEvent.VK_RIGHT:
                otroMotivo.setText("");
                otroMotivo.setEnabled(false);
                jCboMotivos.setSelectedIndex(0);
                jCboMotivos.setEnabled(false);
                jCboOrigen.requestFocusInWindow();
                break;
            case KeyEvent.VK_ESCAPE:
                this.dispose();
                break;
            case KeyEvent.VK_F8:
                Aprobacion = "";
                if(otroMotivo.getText().equals("")){
                    DialogoAceptar.mostrarDialogo("¡Ingrese motivo de cancelacion!","Es necesario tener motivo para cancelar.", Color.RED);
                    otroMotivo.requestFocusInWindow();
                    return;
                }
                boolean viajado = false;
                for(int i=0; i<boletos.length; i++)
                {
                    if(boletos[i][12].toString().equals("S"))
                    {
                        viajado = true;
                        break;
                    }
                }
                if(viajado){
                    DialogoAceptar.mostrarDialogo("¡No es posible cancelar el boleto!","El pasajero ya Viajó con este boleto.", Color.RED);
                    this.dispose();
                    return;
                }

                
                if(sesionVenta.getDtFechaDespachoTarjeta()!=null){
                    Date fechaActual = new Date(this.thX.getFecha().getTime());
                    long minutosDespues = sesionVenta.getUserCon().getMinDesCan()*60000;
                    Date fechaCalculada = new Date(sesionVenta.getDtFechaDespachoTarjeta().getTime()+minutosDespues);
                    if(fechaActual.getTime()>fechaCalculada.getTime()){
                        DialogoAceptar.mostrarDialogo("¡Tiempo para cancelar agotado!","Pida autorizacion del Supervisor.", Color.RED);
                        jDlgAutorizaSupervisor dlg = new jDlgAutorizaSupervisor(sesionVenta,"5005", "Cancelar Boleto");
                        dlg.setVisible(true);
                        if(!dlg.getRespuesta()) return;
                    }
                }
                //Mostrar el cargo por cancelacion
                double devuelveImporte=0;
                double devuelveImporteCompleto=0;
                double cargo=0;
                for(int i=0; i<boletos.length; i++)
                {
                    devuelveImporteCompleto+=Double.valueOf(boletos[i][7].toString());
                    devuelveImporte+=((Double.valueOf(boletos[i][7].toString()))-Double.valueOf(boletos[i][11].toString()));
                    cargo+=Double.valueOf(boletos[i][11].toString());
                }
                System.out.println("Cargo: "+String.valueOf(cargo));
                System.out.println("Reembolso: "+String.valueOf(devuelveImporte));
                System.out.println("ReembolsoComnpleto: "+String.valueOf(devuelveImporteCompleto));
                if(cargo>0)
                {
                    DialogoSiNo = new JDlgSiNo("¡Confirmacion!","<html><center><font size=+1>Se cobrara un cargo de  </font><font color="+ColoresInterfaz.cHTML3+" size=+2>$ "+sesionVenta.customFormat("##,##0.00",cargo)+"</font> <font size=+1>al cliente.   </center>Por concepto: </font><br><center><font color="+ColoresInterfaz.cHTML3+"> Cargo por Cancelación</font></center><font size=+1>¿Desa continuar con la cancelación?</font></html>",true);
                    boolean res = DialogoSiNo.getResultado();
                    if(!res)
                        return;
                }

                if(!sesionVenta.cancelaLealtad()){
                    DialogoAceptar.mostrarDialogo("Error de Cancelacion","<html>¡No fue posible cancelar las estrellas acumuladas!.<br> Contacte al Administrador del sistema.</html>", Color.RED);
                    this.dispose();
                    return;
                }
                // MOD: PARA UNA SOLA TRANSACCION BANCARIA
//                double devuelveImporte=0;
//                for(int i=0; i<boletos.length; i++)
//                    devuelveImporte+=Double.valueOf(boletos[i][7].toString());
                // CANCELACION DE TARJETA BANCARIA (NO AMEX)
                if(boletos[0][9].toString().equals("BBV")){// un boleto por boleto
                    if(!sesionVenta.getExisteImpresoraVoucher(sesionVenta.getTmsBoletosVentaTbl().getEmpresa())){
                        DialogoAceptar.mostrarDialogo("No esta disponible la impresora de vouchers.","<html>No es posible realizar la transaccion.<br>Contacte al administrador del sistema.</html>", Color.RED);
                        return;
                    }
                    if(!sesionVenta.ValidaFuncionUsuario("5016")){
                        jDlgAutorizaSupervisor dlg = new jDlgAutorizaSupervisor(sesionVenta,"5016", "Cancelar Venta Tarjeta de Credito");
                        dlg.setVisible(true);
                        if(!dlg.getRespuesta()) return;
                    }
                    if(cargo>0)
                        sesionVenta.setCobroCargo(true);
                    if (sesionVenta.isCobroCargo())
                    {
                    //      EjecutaCobro();
                        sesionVenta.setImporteVenta(cargo);
                        System.out.println("Envia el cobro de cargo por cancelacion2...");
                        JDlgCobro jDlgCobro = new JDlgCobro(boletos, sesionVenta, "", "CN","", null, this.thX);
                        if(!jDlgCobro.isCerrar())jDlgCobro.setVisible(true);
                        if(jDlgCobro.getVentaOk()!=0)
                            return;
                        System.out.println("(CN2)sesionVenta.getTipoPagoCargo(): "+sesionVenta.getTipoPagoCargo());
                        System.out.println("(CN2)sesionVenta.getAprobacionCargo(): "+sesionVenta.getAprobacionCargo());
                   }

                    System.out.println("Reembolso: "+String.valueOf(devuelveImporteCompleto));
                    if(!sesionVenta.getUserCon().getSysCobroBancario()){
                        if(!cancelaCobroTarjBanc(devuelveImporteCompleto)) return;
                    }
                    else{
                        if(!cancelaSistemaCobroTarjetaBancaria(devuelveImporteCompleto)) return;
                    }
                }
                if(!sesionVenta.CancelaBoletoMultiple("Otro: "+otroMotivo.getText().toUpperCase(), Aprobacion)){
                    DialogoAceptar.mostrarDialogo("¡No fue posible cancelar el boleto!","Contacte al Administrador del sistema.", Color.RED);
                    this.dispose();
                    return;
                } else{
                    //sesionVenta.cancelaLealtad();
                    String msgDevuelve="";
                    if(boletos[0][9].toString().equals("EFE")){
                        msgDevuelve = "<br><center>Devuelva <font color="+ColoresInterfaz.cHTML3+" size=+1>$ "+sesionVenta.customFormat("##,##0.00",devuelveImporte)+
                                "</font> al cliente.</center>";
                    }
                    else{
                        if(boletos[0][9].toString().equals("BBV"))
                            msgDevuelve = "<br><center>Solicitud de reembolso enviada al banco emisor.</center>";
                    }
                    
                    sesionVenta.EFECTIVO_CAJA-=devuelveImporte;
                    
                    armaAsientoTipo();
                    long corridaId = sesionVenta.getCorridaId(sesionVenta.getVariosTmsBoletosVentaTbl().get(0).getClaveCorrida());
                    System.out.println("CorridaId::: "+corridaId);
                    if(corridaId==-1){
                        this.getToolkit().beep();
                        DialogoAceptar.mostrarDialogo("¡El boleto se cancelo correctamente!","<html>Ahora marque el boleto<br><font color="+ColoresInterfaz.cHTML3+">"+jTxtFolioPreimpreso.getText()+"</font><br>como Cancelado..." +
                            msgDevuelve+"</html>", colorDialogoActivo);
                        DialogoAceptar.mostrarDialogo("TMS Venta.", "<html>No fue posible liberar asiento o<br>tipo de pasajero (corridaId).</html>",Color.RED);
                        this.dispose();
                        return;
                    }
                    sesionVenta.iTempos=1;
                    int rSP=-1;
                    while(rSP==-1){
                        rSP=sesionVenta._OcuparAsientosSP(corridaId, sesionVenta.getCadenaAsientos(), sesionVenta.getCadenaTiposPasaje(), "E");
                        if(rSP==-1){
                            sesionVenta.iTempos++;
                            if(sesionVenta.iTempos>sesionVenta.tTempos){
                                this.getToolkit().beep();
                                DialogoAceptar.mostrarDialogo("TMS Venta.", "Asiento bloqueado.",Color.RED);
                                limpia();
                                return;
                            }
                        }
                    }
                    if(rSP!=0 && rSP!=-1)
                        DialogoAceptar.mostrarDialogo("TMS Venta.", "<html>No fue posible liberar asiento<br>o tipo de pasajero.</html>",Color.RED);
                    
                    DialogoAceptar.mostrarDialogo("¡El boleto se cancelo correctamente!","<html>Ahora marque el boleto<br><font color="+ColoresInterfaz.cHTML3+">"+jTxtFolioPreimpreso.getText()+"</font><br>como Cancelado..." +
                            msgDevuelve+"</html>", colorDialogoActivo);
                    
                    if(!sesionVenta.AuditarFuncion()){
                        DialogoAceptar.mostrarDialogo("¡Error al tratar de auditar la funcion Cancelar Boleto!", "La aplicacion será cerrada.\nContacte al administrador del sistema.",Color.RED);
                        this.dispose();
                        return;
                    }
                    
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    otroMotivo.setText("Otra Razon");
                    jCboMotivos.setSelectedIndex(0);
                    jCboMotivos.setEnabled(false);
                    otroMotivo.setEnabled(false);
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                }
                break;
        }
    }//GEN-LAST:event_otroMotivoKeyPressed
    
    private void jCboMotivosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCboMotivosKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_LEFT:
                jCboMotivos.setSelectedIndex(0);
                jCboMotivos.setEnabled(false);
                otroMotivo.setText("");
                otroMotivo.setEnabled(false);
                jTxtNoAsiento.selectAll();
                jTxtNoAsiento.requestFocusInWindow();
                break;
            case KeyEvent.VK_RIGHT:
                if(jCboMotivos.getSelectedItem().equals("Otro")){
                    otroMotivo.setEnabled(true);
                    otroMotivo.setText("Otra Razon");
                    otroMotivo.selectAll();
                    otroMotivo.requestFocusInWindow();
                    return;
                } else{
                    jCboMotivos.setSelectedIndex(0);
                    jCboMotivos.setEnabled(false);
                    otroMotivo.setText("");
                    otroMotivo.setEnabled(false);
                    jCboOrigen.requestFocusInWindow();
                }
                break;
            case KeyEvent.VK_ESCAPE:
                this.dispose();
                break;
            case KeyEvent.VK_ENTER:
                if(jCboMotivos.getSelectedItem().equals("Otro")){
                    otroMotivo.setEnabled(true);
                    otroMotivo.setText("Otra Razon");
                    otroMotivo.selectAll();
                    otroMotivo.requestFocusInWindow();
                    return;
                }
                break;
            case KeyEvent.VK_F8:
                Aprobacion = "";
                if(jCboMotivos.getSelectedItem().equals("Otro")){
                    DialogoAceptar.mostrarDialogo("¡Ingrese motivo de cancelacion!","Es necesario tener motivo para cancelar.", Color.RED);
                    otroMotivo.setEnabled(true);
                    otroMotivo.setText("Otra Razon");
                    otroMotivo.selectAll();
                    otroMotivo.requestFocusInWindow();
                    return;
                }
                boolean viajado = false;
                for(int i=0; i<boletos.length; i++)
                {
                    if(boletos[i][12].toString().equals("S"))
                    {
                        viajado = true;
                        break;
                    }
                }
                if(viajado){
                    DialogoAceptar.mostrarDialogo("¡No es posible cancelar el boleto!","El pasajero ya Viajó con este boleto.", Color.RED);
                    this.dispose();
                    return;
                }
                
                if(sesionVenta.getDtFechaDespachoTarjeta()!=null){
                    Date fechaActual = new Date(this.thX.getFecha().getTime());
                    long minutosDespues = sesionVenta.getUserCon().getMinDesCan()*60000;
                    Date fechaCalculada = new Date(sesionVenta.getDtFechaDespachoTarjeta().getTime()+minutosDespues);
                    if(fechaActual.getTime()>fechaCalculada.getTime()){
                        DialogoAceptar.mostrarDialogo("¡Tiempo para cancelar agotado!","Pida autorizacion del Supervisor.", Color.RED);
                        jDlgAutorizaSupervisor dlg = new jDlgAutorizaSupervisor(sesionVenta,"5005", "Cancelar Boleto");
                        dlg.setVisible(true);
                        if(!dlg.getRespuesta()) return;
                    }
                }

                //Mostrar el cargo por cancelacion
                double devuelveImporte=0;
                double devuelveImporteCompleto=0;
                double cargo=0;
                for(int i=0; i<boletos.length; i++)
                {
                    devuelveImporteCompleto+=Double.valueOf(boletos[i][7].toString());
                    devuelveImporte+=((Double.valueOf(boletos[i][7].toString()))-Double.valueOf(boletos[i][11].toString()));
                    cargo+=Double.valueOf(boletos[i][11].toString());
                }
                System.out.println("Cargo: "+String.valueOf(cargo));
                System.out.println("Reembolso: "+String.valueOf(devuelveImporte));
                if(cargo>0)
                {
                    DialogoSiNo = new JDlgSiNo("¡Confirmacion!","<html><center><font size=+1>Se cobrara un cargo de  </font><font color="+ColoresInterfaz.cHTML3+" size=+2>$ "+sesionVenta.customFormat("##,##0.00",cargo)+"</font> <font size=+1>al cliente.   </center>Por concepto: </font><br><center><font color="+ColoresInterfaz.cHTML3+"> Cargo por Cancelación</font></center><font size=+1>¿Desa continuar con la cancelación?</font></html>",true);
                    boolean res = DialogoSiNo.getResultado();
                    if(!res)
                        return;
                }

                
                if(!sesionVenta.cancelaLealtad()){
                    DialogoAceptar.mostrarDialogo("Error de Cancelacion","<html>¡No fue posible cancelar las estrellas acumuladas!.<br> Contacte al Administrador del sistema.</html>", Color.RED);
                    this.dispose();
                    return;
                }
                
                // MOD: PARA UNA SOLA TRANSACCION BANCARIA
//                double devuelveImporte=0;
//                for(int i=0; i<boletos.length; i++)
//                    devuelveImporte+=Double.valueOf(boletos[i][7].toString());
                // CANCELACION DE TARJETA BANCARIA (NO AMEX)
                if(boletos[0][9].toString().equals("BBV")){// un boleto por boleto
                    if(!sesionVenta.getExisteImpresoraVoucher(sesionVenta.getTmsBoletosVentaTbl().getEmpresa())){
                        DialogoAceptar.mostrarDialogo("No esta disponible la impresora de vouchers.","<html>No es posible realizar la transaccion.<br>Contacte al administrador del sistema.</html>", Color.RED);
                        return;
                    }
                    if(!sesionVenta.ValidaFuncionUsuario("5016")){
                        jDlgAutorizaSupervisor dlg = new jDlgAutorizaSupervisor(sesionVenta,"5016", "Cancelar Venta Tarjeta de Credito");
                        dlg.setVisible(true);
                        if(!dlg.getRespuesta()) return;
                    }
                    System.out.println("Reembolso: "+String.valueOf(devuelveImporteCompleto));
                    if(cargo>0)
                        sesionVenta.setCobroCargo(true);
                    if (sesionVenta.isCobroCargo())
                    {
                    //      EjecutaCobro();
                        sesionVenta.setImporteVenta(cargo);
                        System.out.println("Envia el cobro de cargo por cancelacion1...");
                        JDlgCobro jDlgCobro = new JDlgCobro(boletos, sesionVenta, "", "CN","", null, this.thX);
                        if(!jDlgCobro.isCerrar())jDlgCobro.setVisible(true);
                        if(jDlgCobro.getVentaOk()!=0)
                            return;
                        System.out.println("(CN1)sesionVenta.getTipoPagoCargo(): "+sesionVenta.getTipoPagoCargo());
                        System.out.println("(CN1)sesionVenta.getAprobacionCargo(): "+sesionVenta.getAprobacionCargo());
                   }
                    if(!sesionVenta.getUserCon().getSysCobroBancario()){
                        if(!cancelaCobroTarjBanc(devuelveImporteCompleto)) return;
                    }
                    else{
                        if(!cancelaSistemaCobroTarjetaBancaria(devuelveImporteCompleto)) return;
                    }
                }
                if(!sesionVenta.CancelaBoletoMultiple(jCboMotivos.getSelectedItem().toString(),Aprobacion)){
                    DialogoAceptar.mostrarDialogo("¡No fue posible cancelar el boleto!","Contacte al Administrador del sistema.", Color.RED);
                    this.dispose();
                    return;
                } else{
                    //sesionVenta.cancelaLealtad();
                    String msgDevuelve="";
                    if(boletos[0][9].toString().equals("EFE")){
                        msgDevuelve = "<br><center>Devuelva <font color="+ColoresInterfaz.cHTML3+" size=+1>$ "+sesionVenta.customFormat("##,##0.00",devuelveImporte)+
                                "</font> al cliente.</center>";
                    }
                    else{
                        if(boletos[0][9].toString().equals("BBV"))
                            msgDevuelve = "<br><center>Solicitud de reembolso enviada al banco emisor.</center>";
                    }
                    
                    sesionVenta.EFECTIVO_CAJA-=devuelveImporte;
                    
                    armaAsientoTipo();
                    long corridaId = sesionVenta.getCorridaId(sesionVenta.getVariosTmsBoletosVentaTbl().get(0).getClaveCorrida());
                    System.out.println("CorridaId::: "+corridaId);
                    if(corridaId==-1){
                        this.getToolkit().beep();
                        DialogoAceptar.mostrarDialogo("¡El boleto se cancelo correctamente!","<html>Ahora marque el boleto<br><font color="+ColoresInterfaz.cHTML3+">"+jTxtFolioPreimpreso.getText()+"</font><br>como Cancelado..." +
                            msgDevuelve+"</html>", colorDialogoActivo);
                        DialogoAceptar.mostrarDialogo("TMS Venta.", "<html>No fue posible liberar asiento o<br>tipo de pasajero (corridaId).</html>",Color.RED);
                        this.dispose();
                        return;
                    }
                    sesionVenta.iTempos=1;
                    int rSP=-1;
                    while(rSP==-1){
                        rSP=sesionVenta._OcuparAsientosSP(corridaId, sesionVenta.getCadenaAsientos(), sesionVenta.getCadenaTiposPasaje(), "E");
                        if(rSP==-1){            
                            sesionVenta.iTempos++;
                            if(sesionVenta.iTempos>sesionVenta.tTempos){
                                this.getToolkit().beep();
                                DialogoAceptar.mostrarDialogo("TMS Venta.", "Asiento bloqueado.",Color.RED);
                                limpia();
                                return;
                            }
                        }
                    }
                    if(rSP!=0 && rSP!=-1)
                        DialogoAceptar.mostrarDialogo("TMS Venta.", "<html>No fue posible liberar asiento<br>o tipo de pasajero.</html>",Color.RED);
                    
                    DialogoAceptar.mostrarDialogo("¡El boleto se cancelo correctamente!","<html>Ahora marque el boleto<br><font color="+ColoresInterfaz.cHTML3+">"+jTxtFolioPreimpreso.getText()+"</font><br>como Cancelado..." +
                            msgDevuelve+"</html>", colorDialogoActivo);
                    
                    if(!sesionVenta.AuditarFuncion()){
                        DialogoAceptar.mostrarDialogo("¡Error al tratar de auditar la funcion Cancelar Boleto!", "La aplicacion será cerrada.\nContacte al administrador del sistema.",Color.RED);
                        this.dispose();
                        return;
                    }
                    
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    otroMotivo.setText("Otra Razon");
                    jCboMotivos.setSelectedIndex(0);
                    jCboMotivos.setEnabled(false);
                    otroMotivo.setEnabled(false);
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                }
                break;
        }
    }//GEN-LAST:event_jCboMotivosKeyPressed
    
    private void jTxtNoAsientoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNoAsientoKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE:
                this.dispose();
                break;
            case KeyEvent.VK_ENTER:
                if(!validaCampos()) return;
                if(!valMultiTx(jTxtFolioPreimpreso.getText(), jTxtNoAsiento.getText())){
                    return;
                }
                ConstruyeMultiCancelacion();
                if(jCboOrigen.getSelectedItem().toString().equals(sesionVenta.getUserCon().getTerminalNombre())) sesionVenta.setTipoTransaccion("L");
                else sesionVenta.setTipoTransaccion("R");
                boletos = sesionVenta.buscaBoletoVendidoParaCancelar(jCboOrigen.getSelectedItem().toString(),
                        conjuntoFolios, conjuntoAsientos, jCboEmpresas.getSelectedItem().toString().substring((jCboEmpresas.getSelectedItem().toString().indexOf("-")) + 1),
                        jClsSintaxis.getVectorFoliosBoletos().size());
                if(boletos==null){
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    DialogoAceptar.mostrarDialogo("Cancelación de boleto.","No es posible realizar la cancelación de este boleto.", Color.RED);
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                    return;
                }
                
                if(!sonDeLaMismaCorrida()){
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    DialogoAceptar.mostrarDialogo("Cancelación de boleto.","<html>No es posible realizar la cancelación de estos boletos.<br>No pertenecen a la misma corrida.</html>", Color.RED);
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                    return;
                }

                if(sonPromocion())
                {
                    DialogoAceptar.mostrarDialogo("Cancelación de boleto.","<html>No es posible realizar la cancelación de estos boletos.<br>Los boletos vendidos con promoción no son cancelables.</html>", Color.RED);
                    return;
                }
                                /*
                if(sonAculuacionEstrellas()){
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    DialogoAceptar.mostrarDialogo("Cancelación de boleto.","<html>No es posible realizar la cancelación de <br>Boletos con Estrellas Acumuladas.</html>", Color.RED);
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                    return;
                }
                */
                sesionVenta.setTipoTransaccionAuxiliar(sesionVenta.getTipoTransaccion());
                sesionVenta.setDBLinkAuxiliar(sesionVenta.getDBLink());
                String FHc = sesionVenta.FechaHoraCorrida();
                //System.out.println("FECHA CORRIDA "+FHc);
                if(FHc==null){
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    DialogoAceptar.mostrarDialogo("¡Corrida sin fecha asociada!","Contacte al administrador del sistema.", Color.RED);
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                    return;
                }

                try {
                    String strDtFecha=formatoFechaHora.format(formatoDateServer2.parse(FHc).getTime());
                    fechaCorridaBoleto  = formatoFechaHora.parse(strDtFecha);
                    for(int i=0; i<boletos.length; i++){
                        boletos[i][1] = strDtFecha;
                    }
                } catch (ParseException ex) {
                    fechaCorridaBoleto = null;
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    DialogoAceptar.mostrarDialogo("¡Corrida con fecha invalida!","Contacte al administrador del sistema.", Color.RED);
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                    return;
                }
                
                xTabla.setDataVector(boletos, encabezado);
                AnchoColumnas();
                jCboMotivos.setEnabled(true);
                jCboMotivos.requestFocusInWindow();
                break;
            case KeyEvent.VK_LEFT: case KeyEvent.VK_UP:
                jTxtFolioPreimpreso.selectAll();
                jTxtFolioPreimpreso.requestFocusInWindow();
                break;
            case KeyEvent.VK_RIGHT: case KeyEvent.VK_DOWN: 
                jCboEmpresas.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jTxtNoAsientoKeyPressed
    
    private void jTxtFolioPreimpresoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFolioPreimpresoKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE:
                this.dispose();
                break;
            case KeyEvent.VK_ENTER:
                if(!validaCampos()) return;
                if(!valMultiTx(jTxtFolioPreimpreso.getText(), jTxtNoAsiento.getText())){
                    return;
                }
                ConstruyeMultiCancelacion();
                if(jCboOrigen.getSelectedItem().toString().equals(sesionVenta.getUserCon().getTerminalNombre())) sesionVenta.setTipoTransaccion("L");
                else sesionVenta.setTipoTransaccion("R");
                boletos = sesionVenta.buscaBoletoVendidoParaCancelar(jCboOrigen.getSelectedItem().toString(),
                        conjuntoFolios, conjuntoAsientos, jCboEmpresas.getSelectedItem().toString().substring((jCboEmpresas.getSelectedItem().toString().indexOf("-")) + 1),jClsSintaxis.getVectorFoliosBoletos().size());
                if(boletos==null){
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    DialogoAceptar.mostrarDialogo("Cancelación de boleto.","No es posible realizar la cancelación de este boleto.", Color.RED);
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                    return;
                }
                
                if(!sonDeLaMismaCorrida()){
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    DialogoAceptar.mostrarDialogo("Cancelación de boleto.","<html>No es posible realizar la cancelación de estos boletos.<br>No pertenecen a la misma corrida.</html>", Color.RED);
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                    return;
                }

                if(sonPromocion())
                {
                    DialogoAceptar.mostrarDialogo("Cancelación de boleto.","<html>No es posible realizar la cancelación de estos boletos.<br>Los boletos vendidos con promoción no son cancelables.</html>", Color.RED);
                    return;
                }
                                /*
                if(sonAculuacionEstrellas()){
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    DialogoAceptar.mostrarDialogo("Cancelación de boleto.","<html>No es posible realizar la cancelación de <br>Boletos con Estrellas Acumuladas.</html>", Color.RED);
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                    return;
                }
                */
                
                sesionVenta.setTipoTransaccionAuxiliar(sesionVenta.getTipoTransaccion());
                sesionVenta.setDBLinkAuxiliar(sesionVenta.getDBLink());
                String FHc = sesionVenta.FechaHoraCorrida();
                //System.out.println("FECHA CORRIDA "+FHc);
                if(FHc==null){
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    DialogoAceptar.mostrarDialogo("¡Corrida sin fecha asociada!","Contacte al administrador del sistema.", Color.RED);
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                    return;
                }

                try {
                    String strDtFecha=formatoFechaHora.format(formatoDateServer2.parse(FHc).getTime());
                    fechaCorridaBoleto  = formatoFechaHora.parse(strDtFecha);
                    for(int i=0; i<boletos.length; i++){
                        boletos[i][1] = strDtFecha;
                    }
                } catch (ParseException ex) {
                    fechaCorridaBoleto = null;
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    DialogoAceptar.mostrarDialogo("¡Corrida con fecha invalida!","Contacte al administrador del sistema.", Color.RED);
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                    return;
                }
                
                xTabla.setDataVector(boletos, encabezado);
                AnchoColumnas();
                jCboMotivos.setEnabled(true);
                jCboMotivos.requestFocusInWindow();
                break;
            case KeyEvent.VK_LEFT: case KeyEvent.VK_UP:
                jCboOrigen.requestFocusInWindow();
                break;
            case KeyEvent.VK_RIGHT: case KeyEvent.VK_DOWN:
                jTxtNoAsiento.selectAll();
                jTxtNoAsiento.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jTxtFolioPreimpresoKeyPressed
    
    private void jCboOrigenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCboOrigenKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE:
                this.dispose();
                break;
            case KeyEvent.VK_ENTER:
                if(!validaCampos()) return;
                if(!valMultiTx(jTxtFolioPreimpreso.getText(), jTxtNoAsiento.getText())){
                    return;
                }
                ConstruyeMultiCancelacion();
                if(jCboOrigen.getSelectedItem().toString().equals(sesionVenta.getUserCon().getTerminalNombre())) sesionVenta.setTipoTransaccion("L");
                else sesionVenta.setTipoTransaccion("R");
                boletos = sesionVenta.buscaBoletoVendidoParaCancelar(jCboOrigen.getSelectedItem().toString(),
                        conjuntoFolios, conjuntoAsientos, jCboEmpresas.getSelectedItem().toString().substring((jCboEmpresas.getSelectedItem().toString().indexOf("-")) + 1),jClsSintaxis.getVectorFoliosBoletos().size());
                if(boletos==null){
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    DialogoAceptar.mostrarDialogo("Cancelación de boleto.","No es posible realizar la cancelación de este boleto.", Color.RED);
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                    return;
                }
                
                if(!sonDeLaMismaCorrida()){
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    DialogoAceptar.mostrarDialogo("Cancelación de boleto.","<html>No es posible realizar la cancelación de estos boletos.<br>No pertenecen a la misma corrida.</html>", Color.RED);
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                    return;
                }

                if(sonPromocion())
                {
                    DialogoAceptar.mostrarDialogo("Cancelación de boleto.","<html>No es posible realizar la cancelación de estos boletos.<br>Los boletos vendidos con promoción no son cancelables.</html>", Color.RED);
                    return;
                }
                                /*
                if(sonAculuacionEstrellas()){
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    DialogoAceptar.mostrarDialogo("Cancelación de boleto.","<html>No es posible realizar la cancelación de <br>Boletos con Estrellas Acumuladas.</html>", Color.RED);
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                    return;
                }*/
                
                sesionVenta.setTipoTransaccionAuxiliar(sesionVenta.getTipoTransaccion());
                sesionVenta.setDBLinkAuxiliar(sesionVenta.getDBLink());
                String FHc = sesionVenta.FechaHoraCorrida();
                //System.out.println("FECHA CORRIDA "+FHc);
                if(FHc==null){
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    DialogoAceptar.mostrarDialogo("¡Corrida sin fecha asociada!","Contacte al administrador del sistema.", Color.RED);
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                    return;
                }

                try {
                    String strDtFecha=formatoFechaHora.format(formatoDateServer2.parse(FHc).getTime());
                    fechaCorridaBoleto  = formatoFechaHora.parse(strDtFecha);
                    for(int i=0; i<boletos.length; i++){
                        boletos[i][1] = strDtFecha;
                    }
                } catch (ParseException ex) {
                    fechaCorridaBoleto = null;
                    xTabla.setDataVector(null, encabezado);
                    AnchoColumnas();
                    DialogoAceptar.mostrarDialogo("¡Corrida con fecha invalida!","Contacte al administrador del sistema.", Color.RED);
                    jTxtFolioPreimpreso.setText("");
                    jTxtNoAsiento.setText("");
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                    return;
                }
                
                xTabla.setDataVector(boletos, encabezado);
                AnchoColumnas();
                jCboMotivos.setEnabled(true);
                jCboMotivos.requestFocusInWindow();
                break;
            case KeyEvent.VK_LEFT: case KeyEvent.VK_UP:
                jCboEmpresas.requestFocusInWindow();
                break;
            case KeyEvent.VK_RIGHT:
                jTxtFolioPreimpreso.selectAll();
                jTxtFolioPreimpreso.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jCboOrigenKeyPressed
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
// TODO add your handling code here:
        jCboEmpresas.setSelectedIndex(0);
        jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
        jCboOrigen.requestFocusInWindow();
        AnchoColumnas();
    }//GEN-LAST:event_formComponentShown

    private void jTxtFolioPreimpresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtFolioPreimpresoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtFolioPreimpresoActionPerformed
    
    private void AnchoColumnas() {
        int anchoContenedor = jScrollPane1.getWidth();
        TableColumn column;
        for (int i = 0; i < jTblBoletoOriginal.getColumnCount(); i++) {
            column = jTblBoletoOriginal.getColumnModel().getColumn(i);
            switch (i) {
                case 0: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.12)); break;
                case 1: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.15)); break;
                case 2: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.04)); break;
                case 3: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.04)); break;
                case 4: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.30)); break;
                case 5: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.14)); break;
                case 6: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.07)); break;
                case 7: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.07)); break;
                case 8: column.setPreferredWidth(0); column.setMinWidth(0); column.setMaxWidth(0); column.setWidth(0); break;
                case 9: column.setPreferredWidth(0); column.setMinWidth(0); column.setMaxWidth(0); column.setWidth(0); break;
                case 10: column.setPreferredWidth(0); column.setMinWidth(0); column.setMaxWidth(0); column.setWidth(0); break;
                case 11: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.07)); break;
                case 12: column.setPreferredWidth(0); column.setMinWidth(0); column.setMaxWidth(0); column.setWidth(0); break;
            }
        }
    }
    
    private boolean validaCampos(){
        if(jCboOrigen.getSelectedItem()==null){
            DialogoAceptar.mostrarDialogo("¡Importante!","Seleccione un origen.", Color.RED);
            jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre()); jCboOrigen.requestFocusInWindow(); return false;
        }
        if(jTxtFolioPreimpreso.getText().equals("")){
            DialogoAceptar.mostrarDialogo("¡Importante!","Ingrese Folio Preimpreso del Boleto.", Color.RED);
            jTxtFolioPreimpreso.requestFocusInWindow(); return false;
        }
        if(jTxtNoAsiento.getText().equals("")){
            DialogoAceptar.mostrarDialogo("¡Importante!","Ingrese Numero de Asiento.", Color.RED);
            jTxtNoAsiento.requestFocusInWindow(); return false;
        }
        if(jCboEmpresas.getSelectedItem()==null){
            DialogoAceptar.mostrarDialogo("¡Importante!","Seleccione una empresa.", Color.RED);
            jCboEmpresas.setSelectedIndex(0); jCboEmpresas.requestFocusInWindow(); return false;
        }
        return true;
    }
    
    private String PeriodoVacacional(int filax){
        String tipoPasaje = sesionVenta.getVariosTmsBoletosVentaTbl().get(filax).getTipoPasajero();
        if(!tipoPasaje.equals("S") && !tipoPasaje.equals("E") &&
                !tipoPasaje.equals("P") && !tipoPasaje.equals("C") && !tipoPasaje.equals("M")) return "";
        /*if(tipoPasaje.equals("S")) return "1";
        if(tipoPasaje.equals("C")) return "1";*/
        if(tipoPasaje.equals("M")) return "(-1)";
        return "1";
    }

    private void ordenaListaEmpresas(){
        int i, j, vA, vB; String valor;
        for(i=0; i<objEmpresas.length; i++){
            for(j=0; j<objEmpresas.length-1; j++){
                valor=objEmpresas[j+1].toString();
                vA=Integer.valueOf(objEmpresas[j].toString().substring(0,1));
                vB=Integer.valueOf(objEmpresas[j+1].toString().substring(0,1));
                if(vA>vB){
                    objEmpresas[j+1] = objEmpresas[j].toString();
                    objEmpresas[j] = valor;
                }
            }
        }
    }
    
    private void interfazColor(){
        jPanel1.setBackground(ColoresInterfaz.cFondoDialogo);
        /*jLabel4.setOpaque(true);
        jLabel4.setBackground(ColoresInterfaz.cFondoPieEncabezado2);*/
        jTblBoletoOriginal.setBackground(ColoresInterfaz.cFondoDialogo);
        jLabel4.setForeground(ColoresInterfaz.cTextoAyuda1);
        
        setFont(ColoresInterfaz.fuente1);
        jLabel1.setFont(ColoresInterfaz.fuente1);
        jCboOrigen.setFont(ColoresInterfaz.fuente1);
        jLabel2.setFont(ColoresInterfaz.fuente1);
        jTxtFolioPreimpreso.setFont(ColoresInterfaz.fuente1);
        jLabel3.setFont(ColoresInterfaz.fuente1);
        jTxtNoAsiento.setFont(ColoresInterfaz.fuente1);
        jLabel5.setFont(ColoresInterfaz.fuente1);
        jCboEmpresas.setFont(ColoresInterfaz.fuente1);
        jTblBoletoOriginal.setFont(ColoresInterfaz.fuente1);
        jLabel6.setFont(ColoresInterfaz.fuente1);
        jCboMotivos.setFont(ColoresInterfaz.fuente1);
        otroMotivo.setFont(ColoresInterfaz.fuente1);
                
        jLabel4.setFont(ColoresInterfaz.fuente1);
    }

    private boolean valMultiTx(String folios, String asientos) {
        int r=jClsSintaxis.Valfolios(folios);
        if(r!=0){
            if(r==-1) DialogoAceptar.mostrarDialogo("Folios incorrectos","<html>Ingrese correctamente los folios.<br>" +
                                                    "Ejemplo, 21448001-21448005 21448009.</html>",Color.RED);
            else if(r==1) DialogoAceptar.mostrarDialogo("Folios incorrectos",
                            "<html>Algun folio tiene mas de 10 digitos.</html>",Color.RED);
            else  DialogoAceptar.mostrarDialogo("Folios incorrectos","<html>Folio inicial no puede ser<br>mayor o igual que folio final</html>",Color.RED);
            jTxtFolioPreimpreso.selectAll();
            jTxtFolioPreimpreso.requestFocusInWindow();
            return false;
        }
        if(!jClsSintaxis.ValAsientos(asientos)){
            DialogoAceptar.mostrarDialogo("Asientos incorrectos","Ingrese correctamente los numeros de asiento.",Color.RED);
            jTxtNoAsiento.selectAll();
            jTxtNoAsiento.requestFocusInWindow();
            return false;
        }
        
        if(jClsSintaxis.getVectorFoliosBoletos().size()!=jClsSintaxis.getVectorAsientos().size()){
            DialogoAceptar.mostrarDialogo("Datos incorrectos","Cantidad de asientos y folios no es el mismo.",Color.RED);
            jTxtFolioPreimpreso.setText("");
            jTxtNoAsiento.setText("");
            jTxtFolioPreimpreso.requestFocusInWindow();
            return false;
        }
        
        return true;
    }
    
    private void ConstruyeMultiCancelacion(){
        conjuntoFolios="'"+jClsSintaxis.getVectorFoliosBoletos().get(0).toString()+"'";
        conjuntoAsientos="'"+jClsSintaxis.getVectorAsientos().get(0).toString()+"'";
            for(int i=1; i<jClsSintaxis.getVectorFoliosBoletos().size(); i++){
                conjuntoFolios=conjuntoFolios+",'"+jClsSintaxis.getVectorFoliosBoletos().get(i).toString()+"'";
                conjuntoAsientos=conjuntoAsientos+",'"+jClsSintaxis.getVectorAsientos().get(i).toString()+"'";
            }
    }

    private void armaAsientoTipo() {
        Vector BoletoAVender = new Vector();
        Vector TiposAsientos = new Vector();
        int i;
        for(i=0; i<sesionVenta.getVariosTmsBoletosVentaTbl().size(); i++){
            BoletoAVender.add(sesionVenta.getVariosTmsBoletosVentaTbl().get(i).getNoAsiento());
            TiposAsientos.add(sesionVenta.getVariosTmsBoletosVentaTbl().get(i).getTipoPasajero());
        }
        
        sesionVenta.armaCadenaAsientos(BoletoAVender);
        sesionVenta.armaCadenaTiposPasaje(TiposAsientos);
    }

    private boolean sonDeLaMismaCorrida() {
        for(int i=1; i<sesionVenta.getVariosTmsBoletosVentaTbl().size(); i++)
            if(!sesionVenta.getTmsBoletosVentaTbl().getClaveCorrida().equals(sesionVenta.getVariosTmsBoletosVentaTbl().get(i).getClaveCorrida()))
                return false;
            
        return true;
    }


    private boolean sonPromocion() {
        for(int i=0; i<sesionVenta.getVariosTmsBoletosVentaTbl().size(); i++)
        {
            System.out.println("getAdicional7(): "+sesionVenta.getVariosTmsBoletosVentaTbl().get(i).getAdicional7());
            if(sesionVenta.getVariosTmsBoletosVentaTbl().get(i).getAdicional7().toString().length()>2)
                return true;
        }
        return false;
    }


    private boolean sonAculuacionEstrellas() {
        for(int i=0; i<sesionVenta.getVariosTmsBoletosVentaTbl().size(); i++)
        {
            System.out.println("Acumacion para cancelar= "+sesionVenta.getVariosTmsBoletosVentaTbl().get(i).getAdicional8());
            if(!sesionVenta.getVariosTmsBoletosVentaTbl().get(i).getAdicional8().toString().equals(""))
                return true;
        }   
        return false;
    }    
    
    private void limpia(){
        jTxtFolioPreimpreso.setText("");
        jTxtNoAsiento.setText("");
        otroMotivo.setText("Otra Razon");
        jCboMotivos.setSelectedIndex(0);
        jCboMotivos.setEnabled(false);
        otroMotivo.setEnabled(false);
        xTabla.setDataVector(null, encabezado);
        AnchoColumnas();
        jCboEmpresas.setSelectedIndex(0);
        jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
        jCboOrigen.requestFocusInWindow();
    }

    private boolean cancelaCobroTarjBanc(double devuelveImporte) {
        xTarCred = new cancelarTarjetaCredito(sesionVenta, String.valueOf(devuelveImporte));
        xTarCred.setVisible(true);
        if(!xTarCred.getExito()){
            jTxtFolioPreimpreso.setText("");
            jTxtNoAsiento.setText("");
            xTabla.setDataVector(null, encabezado);
            AnchoColumnas();
            jCboEmpresas.setSelectedIndex(0);
            jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
            jCboOrigen.requestFocusInWindow();
            return false;
        }
        this.Aprobacion = xTarCred.aprobacion;
        return true;
    }
    
    private boolean cancelaSistemaCobroTarjetaBancaria(double devuelveImporte){
        String salidaImpresion = sesionVenta.getImpresoraVoucher(sesionVenta.getTmsBoletosVentaTbl().getEmpresa());
        if(salidaImpresion==null){
            DialogoAceptar.mostrarDialogo("TMS Venta.","<html>Salida de impresion incorrecta.<br>Contacte al administrador del sistema.</html>", Color.RED);
            return false;
        }
        sesionVenta.setVoucherBlanco(sesionVenta.isImpresoraVoucherBlanco(sesionVenta.getTmsBoletosVentaTbl().getEmpresa()));
        sesionVenta.setImpresoraNombreVoucherBlanco(sesionVenta.getNombreImpresoraVoucherBlanco(sesionVenta.getTmsBoletosVentaTbl().getEmpresa()));
        boolean[] btx = new boolean[6];
        btx[0] = false; btx[1] = false; btx[2] = true; btx[3] = false; btx[4] = false; btx[5] = false;
        sesionVenta.setImporteVenta(devuelveImporte);
        JDlgSysCboStandr x = new JDlgSysCboStandr(btx, sesionVenta, "", salidaImpresion, sesionVenta.getTmsBoletosVentaTbl().getReferenciaPago(), sesionVenta.getTmsBoletosVentaTbl().getAdicional2(), true, this.thX, true,0);
        x.setVisible(true);

        if(!x.getSuccess()) return false;
        
        JClsPinPadTBResponse z = x.getResponse();
        this.Aprobacion = z.getRspAuth()+";"+z.getRspOperationNumber();
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCboEmpresas;
    private javax.swing.JComboBox jCboMotivos;
    private javax.swing.JComboBox jCboOrigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblBoletoOriginal;
    private javax.swing.JTextField jTxtFolioPreimpreso;
    private javax.swing.JTextField jTxtNoAsiento;
    private javax.swing.JTextField otroMotivo;
    // End of variables declaration//GEN-END:variables
    private Object[] encabezado = {"CORRIDA", "FECHA CORRIDA", "#", "T", "NOMBRE", "ORIGEN", "DESTINO", "COSTO","","","","CARGO",""};
    private DefaultTableModel xTabla = new DefaultTableModel(null,encabezado){
        public boolean isCellEditable(int row, int col){
            return false;
        }
    };
    private Object[][] boletos = null;
    private SesionVenta sesionVenta = null;
    private JDlgAceptar DialogoAceptar = new JDlgAceptar();
    private JDlgSiNo DialogoSiNo;
    private Color colorDialogoActivo = new Color(0,83,255);
    private SimpleDateFormat formatoFechaHora = new SimpleDateFormat("dd/MM/yyyy HH:mm");
    private SimpleDateFormat formatoDateServer2 = new SimpleDateFormat("yyyy-MM-dd HH:mm");
    private Vector pOrigenes;
    private cancelarTarjetaCredito xTarCred;
    private String Aprobacion = "";

    private Date fechaCorridaBoleto=null;
    private Object[] objEmp;
    private Object[] objEmpresas;
    private RelojVisualVta thX=null;
    private JClsColoresInterfaz ColoresInterfaz = new JClsColoresInterfaz();
    private JClsSintaxis jClsSintaxis=null;
    private String conjuntoFolios;
    private String conjuntoAsientos;
    private Color xorColorFondo = new Color(156, 179, 201);
}
