/*
 * JDialogBuscarTarjeta.java
 *
 * Created on 10 de junio de 2008, 09:31 PM
 */

package tmslecturaviaxer;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Vector;
import javax.swing.JDialog;

/**
 *
 * @author  vgonzalez
 */
public class JDialogBuscarTarjeta extends javax.swing.JDialog {
    
    /** Creates new form JDialogBuscarTarjeta */
    public JDialogBuscarTarjeta(TmsLecturaViaxerManagedBean pbusquedas) {
        this.setTitle("Buscar Tarjeta de Viaje");
        this.busquedas = pbusquedas;
        initComponents();
        this.setModal(true);
        this.setResizable(false);
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension DilaogSize = this.getSize();
        if (DilaogSize.height > screenSize.height) {
            DilaogSize.height = screenSize.height;
        }
        if (DilaogSize.width > screenSize.width) {
            DilaogSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - DilaogSize.width ) / 2, ( screenSize.height - DilaogSize.height ) / 2 );            this.setDefaultLookAndFeelDecorated(true);
        this.setAlwaysOnTop(true);
        jlbl_barraEstado.setText("<html>  <font color=FF0000>   ESCAPE</font> Cerrar | <font color=FF0000>ENTER</font> Buscar Tarjeta </html>");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jlbl_barraEstado = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtxt_folio = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jlbl_barraEstado.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlbl_barraEstado.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Folio Tarjeta:");

        jtxt_folio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxt_folioKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Introduce el Folio de la tarjeta a bsucar");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jtxt_folio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 232, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jLabel2)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jtxt_folio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 20, Short.MAX_VALUE)
                .add(jlbl_barraEstado))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_folioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_folioKeyReleased
        //jtxt_folio
        if(evt.getKeyCode() == evt.VK_ESCAPE)
        {
            this.folioTar = "nada";
            this.dispose();
        }
        
        if(evt.getKeyCode() == evt.VK_ENTER){
            String fb = jtxt_folio.getText().toUpperCase();
            Vector vft = (Vector) busquedas.variosFacadeRemote.buscaTarjetaPorFolio(fb);
            if(vft.size()==0)
            {
                new jdlg_error("¡La tarjeta con el folio "+fb+" es invalida!","Verifique el folio de la tarjeta","Tarjeta invalida").setVisible(true);
                jtxt_folio.selectAll();
                return;
            }
            else
            {
                //Vector vf = (Vector)vft.get(0);
                this.folioTar = fb;
                this.vFolioTar = vft;
                this.dispose();
            }
        }
            
    }//GEN-LAST:event_jtxt_folioKeyReleased
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new JDialogBuscarTarjeta(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlbl_barraEstado;
    private javax.swing.JTextField jtxt_folio;
    // End of variables declaration//GEN-END:variables
    private String folioTar  ="";
    private Vector vFolioTar ;
    private TmsLecturaViaxerManagedBean busquedas;
    private Vector tarPend;
    public String getFolioTar(){
        return this.folioTar;
    }
    
    public Vector getVFolioTar(){
        return this.vFolioTar;
    }
}
