/*
 * jdlg_error.java
 *
 * Created on 26 de septiembre de 2007, 07:42 PM
 */

package tmsrecaudacion;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JRootPane;
import javax.swing.JTextField;

/**
 *
 * @author  vgonzalez
 */
public class jdlg_VentaDiesel extends javax.swing.JDialog {
    
    /**
     * Creates new form jdlg_error
     */
    public jdlg_VentaDiesel(String texto1, String texto2, String titulo){
        this.setTitle(titulo);
        this.setModal(true);
        this.setDefaultLookAndFeelDecorated(true);
        this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        initComponents();
        //this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);   
        this.setResizable(false);
        jlbl_mensaje1.setText(texto1);
        jlbl_mensaje2.setText(texto2);
        jlbl_barraEstado.setText("<html>  <font color=FF0000>ENTER: </font> Comprar | <font color=FF0000>ESC: </font> No comprar</font> </html>");
        jlbl_barraEstado.setHorizontalAlignment( JTextField.CENTER );
        int nletras = 0;
        if(texto1.length()>texto2.length())
         nletras = texto1.length();
        else 
         nletras = texto2.length();   
        this.setSize((nletras * 6) + 90,170);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            Dimension DilaogSize = this.getSize();
            if (DilaogSize.height > screenSize.height) {
                DilaogSize.height = screenSize.height;
            }
            if (DilaogSize.width > screenSize.width) {
                DilaogSize.width = screenSize.width;
            }
            this.setLocation( ( screenSize.width - DilaogSize.width ) / 2, ( screenSize.height - DilaogSize.height ) / 2 );            this.setDefaultLookAndFeelDecorated(true);
            this.getRootPane().setWindowDecorationStyle(JRootPane.QUESTION_DIALOG);
            jtxt_monto.setFocusTraversalKeysEnabled(false);
            jtxt_monto.requestFocus();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jlbl_barraEstado = new javax.swing.JLabel();
        jlbl_mensaje1 = new javax.swing.JLabel();
        jlbl_mensaje1.setFocusTraversalKeysEnabled(false);
        jlbl_mensaje2 = new javax.swing.JLabel();
        jtxt_monto = new tms_TextFields.JCuantityTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\NetBeansProyects\\TMSRecaudacion\\TMSRecaudacion-app-client\\src\\java\\tmsrecaudacion\\images\\pregunta.gif"));

        jlbl_barraEstado.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlbl_barraEstado.setText(" ENTER: Si                ESC: No");
        jlbl_barraEstado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jlbl_mensaje1.setFont(new java.awt.Font("Arial", 1, 12));
        jlbl_mensaje1.setText("sdfsdsdfsdfsdfsdfsdf");
        jlbl_mensaje1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jlbl_mensaje1KeyPressed(evt);
            }
        });

        jlbl_mensaje2.setFont(new java.awt.Font("Arial", 1, 12));
        jlbl_mensaje2.setText("dasdasdasdasdasdasdasd");

        jtxt_monto.setForeground(new java.awt.Color(0, 51, 255));
        jtxt_monto.setFont(new java.awt.Font("Tahoma", 1, 12));
        jtxt_monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_montoKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Monto:  $");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Pesos");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(22, 22, 22)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jtxt_monto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jLabel3))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                        .add(jlbl_mensaje1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 702, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jlbl_mensaje2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 702, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(layout.createSequentialGroup()
                        .add(15, 15, 15)
                        .add(jlbl_mensaje1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jlbl_mensaje2)))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jtxt_monto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 50, Short.MAX_VALUE)
                .add(jlbl_barraEstado))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_montoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_montoKeyPressed
      if(evt.getKeyCode() == evt.VK_ENTER)
      {
          float monto = Float.valueOf(jtxt_monto.getText());
          if(monto<50)
          {
             this.setAlwaysOnTop(false);
             new jdlg_error("¡El monto debe ser mayor a 50 pesos! ", "Introduce una cantidad mayor","Monto menor al permitido").setVisible(true);
             this.setAlwaysOnTop(true);
             return;
          }
          if(monto>10000)
          {
             this.setAlwaysOnTop(false);
             new jdlg_error("¡El monto debe ser menor a 10000 pesos! ", "Introduce una cantidad menor","Monto mayor al permitido").setVisible(true);
             this.setAlwaysOnTop(true);
             return;
          }
          this.setComprarDiesel(true);
          this.setMontoDiesel(Float.valueOf(jtxt_monto.getText()));
           this.dispose();
      }
      if(evt.getKeyCode() == evt.VK_ESCAPE)          
      {
          this.setMontoDiesel(0);
          this.setComprarDiesel(false);
          this.dispose();
      }
    }//GEN-LAST:event_jtxt_montoKeyPressed

    private void jlbl_mensaje1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlbl_mensaje1KeyPressed

    }//GEN-LAST:event_jlbl_mensaje1KeyPressed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jlbl_barraEstado;
    private javax.swing.JLabel jlbl_mensaje1;
    private javax.swing.JLabel jlbl_mensaje2;
    private tms_TextFields.JCuantityTextField jtxt_monto;
    // End of variables declaration//GEN-END:variables
    private float montoDiesel = 0;
    private boolean comprarDiesel = false;

    public float getMontoDiesel() {
        return montoDiesel;
    }

    public void setMontoDiesel(float montoDiesel) {
        this.montoDiesel = montoDiesel;
    }

    public boolean isComprarDiesel() {
        return comprarDiesel;
    }

    public void setComprarDiesel(boolean comprarDiesel) {
        this.comprarDiesel = comprarDiesel;
    }
}
