package tmslistapasajeros;

import entidad.TmsEstadosTbl;
import java.awt.Color;
import java.awt.Component;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import solicitud.TMSSesionListaPasajerosRemote;
import javax.swing.filechooser.FileFilter;

public class JIF_ListaPasajeros extends javax.swing.JInternalFrame { //implements KeyListener{
    Context cont = null;
    TMSSesionListaPasajerosRemote cosa = null;
    String datos [][] = null;
    String encabezados [] = {"Pasajero","A","Forma Pago", "Tipo Pasajero","Fecha-Hora Venta","Clave Corrida","Fecha-Hora Corrida", "Destino","Caja", "Tipo Operacion"};
    DefaultTableModel modelo = new DefaultTableModel(datos, encabezados);
    String salida = "Pasajero\tNumero Asiento\tForma Pago\tTipo Pasajero\tFecha-Hora Venta\tClave Corrida\tFecha-Hora Corrida\tDestino\tCaja\tTipo Operacion\t\n";
    static int num = 500;
    int registros = -1;
    JFileChooser jFileChooser = new JFileChooser();
    private KeyEvent eventoTeclado;
    
    public JIF_ListaPasajeros() {
        //super("Lista de Pasajeros");
        try {
            cont = new InitialContext(System.getProperties());
            cosa = (TMSSesionListaPasajerosRemote) cont.lookup(TMSSesionListaPasajerosRemote.class.getName());
        } catch (NamingException ex) {
            ex.printStackTrace();
        }
        
        initComponents();
        this.setIconifiable(true);
        this.setTitle("Lista de Pasajeros Rev22.10.08");
        jdch_fecha.dateEditor.addKeyListener1(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
            if(evt.getKeyCode() == evt.VK_RIGHT){
                jhtxt_hora.requestFocus();
            }
            if(evt.getKeyCode() == evt.VK_LEFT){
                jcmb_origen.requestFocus();
            }
            Evento_Tecla(evt);
        }
        });
        //setVisible(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        Inicializar();
        resizeColumnasCorridas();
        jtbl_listaPasajeros.setAutoResizeMode( JTable.AUTO_RESIZE_OFF );
        //setVisible(true);
        //this.requestFocusInWindow();
        jcmb_origen.requestFocus();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_listaPasajeros = new javax.swing.JTable();
        jProgressBar1 = new javax.swing.JProgressBar();
        jlbl_origen = new javax.swing.JLabel();
        jcmb_origen = new javax.swing.JComboBox();
        jdch_fecha = new tms_calendario.JDateChooser();
        jlbl_fecha = new javax.swing.JLabel();
        jlbl_hora = new javax.swing.JLabel();
        jhtxt_hora = new tms_TextFields.JHourTextField();
        jlbl_nombre = new javax.swing.JLabel();
        jtxt_nombre = new tms_TextFields.JTextTextField();
        jlbl_numero = new javax.swing.JLabel();
        jtxt_numero = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jlbl_barraEstado = new javax.swing.JLabel();

        setIconifiable(true);
        setTitle("Lista de Pasajeros");
        setInheritsPopupMenu(true);
        setRequestFocusEnabled(false);
        setVerifyInputWhenFocusTarget(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jtbl_listaPasajeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtbl_listaPasajeros.setModel(modelo);
        jtbl_listaPasajeros.setAutoCreateColumnsFromModel(false);
        jtbl_listaPasajeros.setEnabled(false);
        String encabezados [] = {"Pasajero","A","Forma Pago", "Tipo Pasajero","Fecha-Hora Venta","Clave Corrida","Fecha-Hora Corrida", "Destino","Caja", "Tipo Operacion"};
        jtbl_listaPasajeros.setVerifyInputWhenFocusTarget(false);
        jtbl_listaPasajeros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbl_listaPasajerosKeyPressed(evt);
            }
        });

        jScrollPane1.setViewportView(jtbl_listaPasajeros);

        jlbl_origen.setFont(new java.awt.Font("Tahoma", 1, 11));
        jlbl_origen.setText("Origen");
        jlbl_origen.setOpaque(true);

        jcmb_origen.setBackground(new java.awt.Color(255, 255, 204));
        jcmb_origen.setAutoscrolls(true);
        jcmb_origen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcmb_origenKeyPressed(evt);
            }
        });

        jdch_fecha.setBackground(new java.awt.Color(255, 255, 204));

        jlbl_fecha.setFont(new java.awt.Font("Tahoma", 1, 11));
        jlbl_fecha.setText("Fecha");
        jlbl_fecha.setOpaque(true);

        jlbl_hora.setFont(new java.awt.Font("Tahoma", 1, 11));
        jlbl_hora.setText("Hora");

        jhtxt_hora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jhtxt_horaKeyPressed(evt);
            }
        });

        jlbl_nombre.setFont(new java.awt.Font("Tahoma", 1, 11));
        jlbl_nombre.setText("Nombre");

        jtxt_nombre.setBackground(new java.awt.Color(255, 255, 204));
        jtxt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_nombreKeyPressed(evt);
            }
        });

        jlbl_numero.setFont(new java.awt.Font("Tahoma", 1, 11));
        jlbl_numero.setText("Numero de Registros");

        jtxt_numero.setEditable(false);

        jlbl_barraEstado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jlbl_numero)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jtxt_numero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jProgressBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(22, 22, 22)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jlbl_origen)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jlbl_nombre))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jcmb_origen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 183, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(29, 29, 29)
                                .add(jlbl_fecha)
                                .add(23, 23, 23)
                                .add(jdch_fecha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 189, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(26, 26, 26)
                                .add(jlbl_hora)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 32, Short.MAX_VALUE)
                                .add(jhtxt_hora, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 169, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jtxt_nombre, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 711, Short.MAX_VALUE))))
                .addContainerGap())
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlbl_origen)
                    .add(jlbl_fecha)
                    .add(jcmb_origen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jdch_fecha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlbl_hora)
                    .add(jhtxt_hora, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlbl_nombre)
                    .add(jtxt_nombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 10, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 456, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtxt_numero, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlbl_numero))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jProgressBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        jcmb_origen.requestFocusInWindow();
    }//GEN-LAST:event_formComponentShown

    private void jtbl_listaPasajerosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbl_listaPasajerosKeyPressed
        Evento_Tecla(evt);
    }//GEN-LAST:event_jtbl_listaPasajerosKeyPressed

    /**
     * Implementa el manejo de eventos de teclado cuando se presiona una tecla sobre este componente
     * @param evt Atrapa las propiedades de las teclas presionadas sobre este componente
     */
    
    private void jtxt_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_nombreKeyPressed
        if(evt.getKeyCode() == evt.VK_RIGHT){
            jcmb_origen.requestFocus();
        }
        if(evt.getKeyCode() == evt.VK_LEFT){
            jhtxt_hora.requestFocus();
        }
        Evento_Tecla(evt);
    }//GEN-LAST:event_jtxt_nombreKeyPressed

    /**
     * Implementa el manejo de eventos de teclado cuando se presiona una tecla sobre este componente
     * @param evt Atrapa las propiedades de las teclas presionadas sobre este componente
     */
    private void jhtxt_horaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jhtxt_horaKeyPressed
        if(evt.getKeyCode() == evt.VK_RIGHT){
            jtxt_nombre.requestFocus();
        }
        if(evt.getKeyCode() == evt.VK_LEFT){
            jdch_fecha.dateEditor.setFoco();
        }
        Evento_Tecla(evt);
    }//GEN-LAST:event_jhtxt_horaKeyPressed

    /**
     * Implementa el manejo de eventos de teclado cuando se presiona una tecla sobre este componente
     * @param evt Atrapa las propiedades de las teclas presionadas sobre este componente
     */
    private void jcmb_origenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcmb_origenKeyPressed
        if(evt.getKeyCode() == evt.VK_RIGHT){
            jdch_fecha.dateEditor.setFoco();
        }
        if(evt.getKeyCode() == evt.VK_LEFT){
            jtxt_nombre.requestFocus();
        }
        Evento_Tecla(evt);
    }//GEN-LAST:event_jcmb_origenKeyPressed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcmb_origen;
    private tms_calendario.JDateChooser jdch_fecha;
    private tms_TextFields.JHourTextField jhtxt_hora;
    private javax.swing.JLabel jlbl_barraEstado;
    private javax.swing.JLabel jlbl_fecha;
    private javax.swing.JLabel jlbl_hora;
    private javax.swing.JLabel jlbl_nombre;
    private javax.swing.JLabel jlbl_numero;
    private javax.swing.JLabel jlbl_origen;
    private javax.swing.JTable jtbl_listaPasajeros;
    private tms_TextFields.JTextTextField jtxt_nombre;
    private javax.swing.JTextField jtxt_numero;
    // End of variables declaration//GEN-END:variables
    
    /**
     * Este metodo atrapa todos los eventos que ocurren sobre los componentes que lo implementan, en particular en JInternalFrame
     * @param e Atrapa las propiedades de las teclas presionadas sobre este componente
     */
    /*public void keyTyped(KeyEvent e) {
    }

    public void keyPressed(KeyEvent e) {
        Evento_Tecla(e);
    }*/
    
    /**
     * Atrapa todos los eventos del teclado y los procesa dependiendo de la tecla presionada
     * @param e e es de tipo KeyEvent y atrapa las propiedades disponibles de la tecla presionada
     */
    public void Evento_Tecla(KeyEvent e) {
        try {
            
            if(e.getKeyCode() == e.VK_1 && e.isControlDown()){
                setEventoTeclado(e);
                try {this.setIcon(true);} catch (PropertyVetoException ex) { ; }
                return;
            }

            if(e.getKeyCode() == e.VK_2 && e.isControlDown()){
                try {this.setIcon(true);} catch (PropertyVetoException ex) { ; }
                return;
            }

            if(e.getKeyCode() == e.VK_F4) {
            //System.out.println("Adiiiooos =)");
                int result = JOptionPane.showOptionDialog(this, "¿Desea cerrar Lista de Pasajeros?",
                            "TMS-Lista de Pasajeros", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
                if(result == JOptionPane.YES_OPTION)
                    this.dispose();
            }else if (e.getKeyCode() == e.VK_F9) {
                //Guardar Cosas!!!
            int result = jFileChooser.showSaveDialog(this);
            if (result != JFileChooser.CANCEL_OPTION) {
                File nombre = jFileChooser.getSelectedFile();
                if ( ( nombre == null ) || ( nombre.getName().equals( "" ) ) ) {
                    JOptionPane.showMessageDialog( this, "Nombre de Archivo Invalido",
                            "TMS - Lista de Pasajeros", JOptionPane.ERROR_MESSAGE );
                } else  if(nombre.exists()) {
                        JOptionPane.showMessageDialog( this, "Archivo Existente",
                            "TMS - Lista de Pasajeros", JOptionPane.ERROR_MESSAGE );
                    } else
                     Guardar(nombre);
                }
            }else if (e.getKeyCode() == e.VK_F3) {
                registros = 0;
                String fec, hor, nom, ori;

                fec = jdch_fecha.dateEditor.getTexto();
                hor = jhtxt_hora.getText();

                ori =(String) jcmb_origen.getSelectedItem();
                nom = jtxt_nombre.getText();
                
                salida = "Pasajero\tNumero Asiento\tForma Pago\tTipo Pasajero\tFecha-Hora Venta\tClave Corrida\tFecha-Hora Corrida\tDestino\tCaja\tTipo Operacion\t\n";
                if (ori.equals("")||fec.equals("")|| nom.equals("")) {
                    JOptionPane.showMessageDialog( this, "Origen, Fecha y Nombre son campos obligatorios. \nPor favor, llene estos campos e intente de nuevo","TMS-Lista de Pasajeros", 
                            JOptionPane.ERROR_MESSAGE );   
                    datos = null;
                    registros = 0;
                    numeroRegistros();
                }else if((nom.length() != 0)&&((nom.length() < 3)||(nom.length() > 50))) {
                            JOptionPane.showMessageDialog( this, "La longitud del nombre debe ser mayor de 3 pero menor de 50\nIntente de nuevo, por favor","TMS-Lista de Pasajeros", 
                                JOptionPane.ERROR_MESSAGE );
                        datos = null;
                        registros = 0;
                        numeroRegistros();
                    } else {
                        Vector lineas = null;
                        jProgressBar1.setIndeterminate(true);
                        System.out.println(ori + " " +fec+ " " + hor+ " "+ nom);
                        lineas = cosa.consultaPasajeros(ori,fec,hor,nom);
                        System.out.println("Lineas "+lineas);
                        
                        if((lineas!= null) && (lineas.size() >0)) {
                            Vector ll = (Vector) lineas.get(0);
                            if(!(ll.get(0).toString().equals("No puedo"))) {
                                int limite = Math.min(num,lineas.size());
                                datos = new String[limite][10];
                                jProgressBar1.setMaximum(limite);
                                int cont = 0;
                                Vector campos = null;
                                for (cont = 0; cont < limite; cont++) {
                                    campos = (Vector) lineas.get(cont);
                                    registros ++;
                                   for(int j = 0; j < campos.size(); j++) {
                                        if(campos.get(j) == null) {
                                            datos[cont][j] = "";
                                            salida = "" + salida + "\t";
                                        }else {
                                            datos[cont][j] = campos.get(j).toString();
                                            salida = "" + salida + datos[cont][j];
                                        }
                                        salida = "" + salida + "\t";
                                    }
                                    salida = "" +salida + "\n";
                                }
                            }else {
                                JOptionPane.showMessageDialog(this, "La búsqueda contiene demasiados registros\nPor favor, limite la busqueda e intente de nuevo ", "TMS-Lista de Pasajeros", JOptionPane.WARNING_MESSAGE);
                                datos = null;
                                registros = 0;
                                numeroRegistros();
                            }
                                
                        }else{
                            JOptionPane.showMessageDialog(this, "No existe registro alguno. \nPor favor, intente de nuevo", "TMS-Lista de Pasajeros", JOptionPane.WARNING_MESSAGE);
                            datos = null;
                            registros = 0;
                            numeroRegistros();
                        }
                    }
                
                jtxt_numero.setText(String.valueOf(registros));
                modelo.setDataVector(datos, encabezados);
                resizeColumnasCorridas();
                jProgressBar1.setIndeterminate(false);
            }
        }catch(Exception ex){
            System.out.println(ex);
        }
        
    }

    /*public void keyReleased(KeyEvent e) {
    }*/

    /**
     * Rellena con los estados pertinentes el JComboBox de origen
     * Agrega al JFileChooser las opciones de los tipos que puede ocupar para guardar
     * Coloca los comentarios del funcionamiento de las teclas pertinentes en la barra de estado
     */
    public void Inicializar() {
        //Carga Estados
        registros = 0;
        numeroRegistros();
       
        List<TmsEstadosTbl> edos = new ArrayList<TmsEstadosTbl>();
        edos = cosa.cargarEstadosTBL();
                
        TmsEstadosTbl origen = new TmsEstadosTbl();
        
        for (int i = 0; i < edos.size(); i++) {
            origen = edos.get(i);
            jcmb_origen.insertItemAt(origen.getEstadoNombre(),i);
        }
        jcmb_origen.setSelectedIndex(0);
        jFileChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        jFileChooser.addChoosableFileFilter(new FileExtensions("Txt","txt"));
        jFileChooser.addChoosableFileFilter(new FileExtensions("MS Excel","xls"));
        jFileChooser.setAcceptAllFileFilterUsed(false);       
        jdch_fecha.dateEditor.getUiComponent().setBackground(new Color(255,255,204));
        jlbl_barraEstado.setText("<html>  <font color=FF0000>   F4</font> Salir de Consulta ListajFile de Pasajeros | <font color=FF0000>F3</font> Busca Pasajeros | <font color=FF0000>F9</font> Exportar Lista de Pasajeros| <font color=FF0000> « » </font> Moverse entre Campos | <font color=FF0000>CTRL+2</font> Minimizar ventana | <font color=FF0000>CTRL+1</font> Mostrar siguiente ventana");  
    }
    
    /**
     * Guarda los datos que se obtuvieron de la consulta en el archivo especificado
     * @param nombre Es el archivo en donde se va a almacenar toda la información
     * @throws java.io.FileNotFoundException En caso de encontrar el archivo especifiacdo o no poder almacenar los datos sobre el mismo, esta excepción es lanzada
     */
    public void Guardar(File nombre) throws FileNotFoundException {
        String ext = "";
        if(jFileChooser.getFileFilter().getDescription().equals("MS Excel(*.xls)")){
            ext = ".xls";
        }else if (jFileChooser.getFileFilter().getDescription().equals("Txt(*.txt)")){
            ext = ".txt";
        }
        FileOutputStream guardo = new FileOutputStream(nombre+ext);
        PrintStream ps = new PrintStream(guardo);
        ps.print(salida);
        ps.flush();
        ps.close();
        Abrir(nombre, ext);
    }
    
    /**
     * Establece el valor máximo por columna dependiendo de la información almacenada
     */
    public void resizeColumnasCorridas(){
        TableColumnModel columnModel = jtbl_listaPasajeros.getColumnModel();

           for (int col=0; col<jtbl_listaPasajeros.getColumnCount(); col++) 
           {
                int maxwidth = 0;            
                for (int row=0; row<jtbl_listaPasajeros.getRowCount(); row++) {
                    TableCellRenderer rend  = jtbl_listaPasajeros.getCellRenderer(row, col); 
                    Object value = jtbl_listaPasajeros.getValueAt (row, col); 
                    Component comp = rend.getTableCellRendererComponent (jtbl_listaPasajeros, value, false, false, row, col);
                    maxwidth = Math.max (comp.getPreferredSize().width, maxwidth); 
                } // for row

                TableColumn column = columnModel.getColumn (col);
                TableCellRenderer headerRenderer = column.getHeaderRenderer();
                if (headerRenderer == null)
                    headerRenderer = jtbl_listaPasajeros.getTableHeader().getDefaultRenderer();

                Object headerValue = column.getHeaderValue();
                Component headerComp = headerRenderer.getTableCellRendererComponent (jtbl_listaPasajeros, headerValue, false, false, 0, col);
                maxwidth = Math.max (maxwidth, headerComp.getPreferredSize().width);
                column.setPreferredWidth (maxwidth + 15);
           }
      }

    /**
     * Coloca en la etiqueta jxt_numero la informacion que registros (la variable) contenga
     */
    public void numeroRegistros() {
        jtxt_numero.setText(String.valueOf(registros));
    }

    /**
     * Permite, una vez almacenado un archivo, su apertura con la aplicación de Windws pertinente
     * @param ext Es la extension con la que se guardo el archivo
     * @param nombre Contiene la ruta y nombre del archivo donde se guardo la información
     */
    public void Abrir(File nombre, String ext) {
        try{
            int result = JOptionPane.showOptionDialog(this, "¿Desea abrir el archivo "+nombre.getName()+"?",
                            "TMS-Lista de Pasajeros", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if (result == JOptionPane.YES_OPTION){
                
                Process p = null;
                if(ext.equals(".xls"))
                    p=Runtime.getRuntime().exec("rundll32 SHELL32.DLL,ShellExec_RunDLL "+nombre.getAbsolutePath()+".xls"); 
                else
                    p=Runtime.getRuntime().exec("rundll32 SHELL32.DLL,ShellExec_RunDLL "+nombre.getAbsolutePath()+".txt"); 
            }
                
        }catch(Exception exc) {
            System.out.println(exc);
        }
    }
    
    public KeyEvent getEventoTeclado(){ return this.eventoTeclado; }
    public void setEventoTeclado(KeyEvent evento){ this.eventoTeclado=evento; }
    
    public void setFoco(){
        jcmb_origen.requestFocus();
    }
}