/*
 * Jdlg_busqueda.java
 *
 * Created on 15 de agosto de 2008, 02:32 PM
 */

package tms_vta_productos_er;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author  vgonzalez
 */
public class Jdlg_busqueda extends javax.swing.JDialog {
    Vector datos = new Vector();
    private int renglon = -1;
    private boolean busqClave = false;
    private boolean busqProducto = false;
    private JClsColoresInterfaz ColoresInterfaz;


    /**
     * Creates new form Jdlg_busqueda
     */
    public Jdlg_busqueda(Vector pdatos, boolean pBusqClave, boolean pBusqProducto,JClsColoresInterfaz pColoresInterfaz,Dimension tableSize) {
        //super(parent, modal);
        datos = pdatos;
        busqClave = pBusqClave;
        busqProducto = pBusqProducto;
        ColoresInterfaz = pColoresInterfaz;
        initComponents();
        System.out.println("busqClave: "+busqClave);
        System.out.println("busqProducto: "+busqProducto);
        if(pBusqClave)
            jLabel1.setText("Clave: ");
        else
            jLabel1.setText("Producto: ");
        this.setModal(true);
        this.setTitle("Busqueda de Productos");
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension DilaogSize = this.getSize();
        if (DilaogSize.height > screenSize.height) {
            DilaogSize.height = screenSize.height;
        }
        if (DilaogSize.width > screenSize.width) {
            DilaogSize.width = screenSize.width;
        }
        this.setLocation(100,100 );//( tableSize.width - DilaogSize.width ) / 2, ( tableSize.height - DilaogSize.height ) / 2 );
        this.setDefaultLookAndFeelDecorated(true);
        jLblBarraEstado1.setText("<html> <font color="+ColoresInterfaz.cHTML3+">ENTER</font> Buscar Producto | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Salir </html>");
        interfazColor();
        jtxt_valor.requestFocus();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxt_valor = new tms_TextFields.JTextTextField();
        jPanel14 = new javax.swing.JPanel();
        jLblBarraEstado1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Nombre:");

        jtxt_valor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_valorKeyPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jtxt_valor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jtxt_valor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel14.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel14.setFocusable(false);

        jLblBarraEstado1.setFont(new java.awt.Font("Tahoma", 1, 13));
        jLblBarraEstado1.setForeground(new java.awt.Color(255, 255, 255));
        jLblBarraEstado1.setText("<html> ok <br> no</html>");
        jLblBarraEstado1.setFocusable(false);

        org.jdesktop.layout.GroupLayout jPanel14Layout = new org.jdesktop.layout.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLblBarraEstado1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLblBarraEstado1)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(jPanel14, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(4, 4, 4)
                .add(jPanel14, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_valorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_valorKeyPressed
       switch (evt.getKeyCode()){
            case KeyEvent.VK_ENTER:
                boolean encontrado = false;
                if(busqClave)
                {
                    for(int i =0; i<datos.size(); i++)
                    {
                        Vector renglon = (Vector)datos.get(i);
                        if(renglon.get(0)!=null)
                        {
                            String cliente = renglon.get(0).toString().toUpperCase();
                            if(cliente.indexOf(jtxt_valor.getText().toUpperCase())>=0)
                            {
                                encontrado = true;
                                setRenglon(i);
                            }
                            if(encontrado)
                                break;
                        }
                    }
                    if(encontrado)
                        this.dispose();
                    else
                    {
                        //JOptionPane.showMessageDialog(this,"¡No se encontro ningún cliente que contenga "+ jtxt_valor.getText()+" !","",JOptionPane.WARNING_MESSAGE);
                        setRenglon(-1);
                        jtxt_valor.selectAll();
                        jtxt_valor.requestFocus();
                    }
                }
                if(busqProducto)
                {
                    encontrado = false;
                    for(int i =0; i<datos.size(); i++)
                    {
                        Vector renglon = (Vector)datos.get(i);
                        if(renglon.get(1)!=null)
                        {
                            String cliente = renglon.get(1).toString().toUpperCase();
                            if(cliente.indexOf(jtxt_valor.getText().toUpperCase())>=0)
                            {
                                encontrado = true;
                                setRenglon(i);
                            }
                            if(encontrado)
                                break;
                        }
                    }
                    if(encontrado)
                        this.dispose();
                    else
                    {
                        //JOptionPane.showMessageDialog(this,"¡No se encontro ningún cliente que contenga "+ jtxt_valor.getText()+" !","",JOptionPane.WARNING_MESSAGE);
                        setRenglon(-1);
                        jtxt_valor.selectAll();
                        jtxt_valor.requestFocus();
                    }
                }
            break;
            case KeyEvent.VK_ESCAPE:    
                //setRenglon(-1);
               this.dispose();
              break;
        }
        
    }//GEN-LAST:event_jtxt_valorKeyPressed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Jdlg_busqueda(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }

    public int getRenglon() {
        return renglon;
    }

    public void setRenglon(int renglon) {
        this.renglon = renglon;
    }

    private void interfazColor(){
        setBackground(ColoresInterfaz.cFondoVentana);
        //jPanel1.setBackground(ColoresInterfaz.cFondoVentana);
        //jLabel1.setForeground(ColoresInterfaz.cTexto1);
        //jLabel1.setFont(ColoresInterfaz.fuente4);
        jtxt_valor.setFont(ColoresInterfaz.fuente4);
        jLblBarraEstado1.setFont(ColoresInterfaz.fuente3);
        jLblBarraEstado1.setForeground(ColoresInterfaz.cTextoAyuda1);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblBarraEstado;
    private javax.swing.JLabel jLblBarraEstado1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private tms_TextFields.JTextTextField jtxt_valor;
    // End of variables declaration//GEN-END:variables
    
}
