/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JdlgCambiarOperador.java
 *
 * Created on 13/03/2014, 02:00:36 PM
 */

package com.estrellaroja.confirmacionviajes.forms;

import com.estrellaroja.confirmacionviajes.entidades.TmsAutobus;
import com.estrellaroja.confirmacionviajes.entidades.TmsOperador;
import com.estrellaroja.confirmacionviajes.entidades.TmsTarjetasViaje;
import com.estrellaroja.confirmacionviajes.solicitudes.TmsAutobusFacade;
import com.estrellaroja.confirmacionviajes.solicitudes.TmsAutobusFacadeRemote;
import com.estrellaroja.confirmacionviajes.solicitudes.TmsOperadorFacadeRemote;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JRootPane;

/**
 *
 * @author EKS Victor
 */
public class JdlgCambiarOperador extends javax.swing.JDialog {

    /** Creates new form JdlgCambiarOperador */
    public JdlgCambiarOperador(TmsTarjetasViaje tarjeta) {
      this.tarjeta= tarjeta;
        setDefaultLookAndFeelDecorated(true);
        this.setUndecorated(true);
        initComponents();
        this.getRootPane().setWindowDecorationStyle(JRootPane.INFORMATION_DIALOG);
        fillComboOperadores(tarjeta.getEmpresa());
        fillComboAutobuses(tarjeta.getEmpresa());
        fillFields(tarjeta);
        pack();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblFolio = new javax.swing.JLabel();
        jtxtFolio = new javax.swing.JTextField();
        jlblCorrida = new javax.swing.JLabel();
        jtxtCorrida = new javax.swing.JTextField();
        jlblFecha = new javax.swing.JLabel();
        jtxtFecha = new javax.swing.JTextField();
        jlblHora = new javax.swing.JLabel();
        jtxtHora = new javax.swing.JTextField();
        jlblServicio = new javax.swing.JLabel();
        jtxtServicio = new javax.swing.JTextField();
        jlblOrigen = new javax.swing.JLabel();
        jtxtOrigen = new javax.swing.JTextField();
        jlblDestino = new javax.swing.JLabel();
        jtxtDestino = new javax.swing.JTextField();
        jlblAutobus = new javax.swing.JLabel();
        jcmbAutobus = new javax.swing.JComboBox();
        jblOperador = new javax.swing.JLabel();
        jcmbOperador = new javax.swing.JComboBox();
        jcmdGuardar = new javax.swing.JButton();
        jcmdCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cambiar Operador");
        setModal(true);
        setResizable(false);

        jlblFolio.setText("Folio:");

        jtxtFolio.setEditable(false);

        jlblCorrida.setText("Corrida:");

        jtxtCorrida.setEditable(false);

        jlblFecha.setText("Fecha:");

        jtxtFecha.setEditable(false);

        jlblHora.setText("Hora:");

        jtxtHora.setEditable(false);

        jlblServicio.setText("Servicio:");

        jtxtServicio.setEditable(false);

        jlblOrigen.setText("Origen:");

        jtxtOrigen.setEditable(false);

        jlblDestino.setText("Destino:");

        jtxtDestino.setEditable(false);

        jlblAutobus.setText("Autobus:");

        jcmbAutobus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jblOperador.setLabelFor(jcmbOperador);
        jblOperador.setText("Operador");

        jcmbOperador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jcmdGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/estrellaroja/confirmacionviajes/forms/images/accept.png"))); // NOI18N
        jcmdGuardar.setMnemonic('G');
        jcmdGuardar.setText("Guardar");
        jcmdGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmdGuardarActionPerformed(evt);
            }
        });

        jcmdCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/estrellaroja/confirmacionviajes/forms/images/cancel.png"))); // NOI18N
        jcmdCancelar.setMnemonic('c');
        jcmdCancelar.setText("Cancelar");
        jcmdCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmdCancelarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(29, 29, 29)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jlblServicio)
                        .add(74, 74, 74)
                        .add(jtxtServicio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                            .add(jcmdGuardar)
                            .add(18, 18, 18)
                            .add(jcmdCancelar))
                        .add(layout.createSequentialGroup()
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(jlblFolio)
                                .add(jlblCorrida)
                                .add(jlblFecha)
                                .add(jlblHora)
                                .add(jblOperador))
                            .add(69, 69, 69)
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                                .add(jcmbOperador, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(jtxtHora)
                                .add(jtxtFecha)
                                .add(jtxtCorrida)
                                .add(jtxtFolio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jlblOrigen)
                            .add(jlblDestino)
                            .add(jlblAutobus))
                        .add(71, 71, 71)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jcmbAutobus, 0, 153, Short.MAX_VALUE)
                            .add(jtxtDestino, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .add(jtxtOrigen, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))))
                .add(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(23, 23, 23)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblFolio)
                    .add(jtxtFolio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jtxtCorrida, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblCorrida))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jtxtFecha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblFecha))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jtxtHora, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblHora))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtxtServicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblServicio))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jtxtOrigen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlblOrigen))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblDestino)
                    .add(jtxtDestino, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlblAutobus)
                    .add(jcmbAutobus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(24, 24, 24)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jblOperador)
                    .add(jcmbOperador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(39, 39, 39)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jcmdCancelar)
                    .add(jcmdGuardar))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmdCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmdCancelarActionPerformed
     dispose();
    }//GEN-LAST:event_jcmdCancelarActionPerformed

    private void jcmdGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmdGuardarActionPerformed
      TmsOperador op = (TmsOperador) jcmbOperador.getSelectedItem();
      TmsAutobus bus = (TmsAutobus) jcmbAutobus.getSelectedItem();
      tarjeta.setClaveOperador(op.getClaveOperador());
      tarjeta.setNombreOperador(op.getOperadorNombreCompleto());
      tarjeta.setAutobus(bus.getNumeroEconomico());
      this.dispose();
    }//GEN-LAST:event_jcmdGuardarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jblOperador;
    private javax.swing.JComboBox jcmbAutobus;
    private javax.swing.JComboBox jcmbOperador;
    private javax.swing.JButton jcmdCancelar;
    private javax.swing.JButton jcmdGuardar;
    private javax.swing.JLabel jlblAutobus;
    private javax.swing.JLabel jlblCorrida;
    private javax.swing.JLabel jlblDestino;
    private javax.swing.JLabel jlblFecha;
    private javax.swing.JLabel jlblFolio;
    private javax.swing.JLabel jlblHora;
    private javax.swing.JLabel jlblOrigen;
    private javax.swing.JLabel jlblServicio;
    private javax.swing.JTextField jtxtCorrida;
    private javax.swing.JTextField jtxtDestino;
    private javax.swing.JTextField jtxtFecha;
    private javax.swing.JTextField jtxtFolio;
    private javax.swing.JTextField jtxtHora;
    private javax.swing.JTextField jtxtOrigen;
    private javax.swing.JTextField jtxtServicio;
    // End of variables declaration//GEN-END:variables
  private TmsTarjetasViaje tarjeta;


  private void fillFields(TmsTarjetasViaje tarjeta) {
  SimpleDateFormat format = new SimpleDateFormat("HH:mm");
    jtxtFolio.setText(tarjeta.getFolioTarjeta());
    jtxtCorrida.setText(tarjeta.getClaveCorrida());
    jtxtDestino.setText(tarjeta.getDestino());
    jtxtOrigen.setText(tarjeta.getOrigen());
    jtxtServicio.setText(tarjeta.getServicio());
    jtxtFecha.setText(DateFormat.getDateInstance(DateFormat.MEDIUM).format(tarjeta.getFechaHoraCorrida()));
    jtxtHora.setText(format.format(tarjeta.getFechaHoraCorrida()));
  }

  private void fillComboOperadores(BigInteger empresa) {
    TmsOperadorFacadeRemote operadoresFacade = lookupTmsOperadoresFacade();
    List<TmsOperador> dbs = operadoresFacade.getByEmpresa(empresa);
    jcmbOperador.setModel(new DefaultComboBoxModel(dbs.toArray()));
    jcmbOperador.setSelectedItem(new TmsOperador(BigDecimal.ZERO, tarjeta.getClaveOperador(), BigInteger.ZERO, null, null, null));
  }
  private void fillComboAutobuses(BigInteger empresa) {
    TmsAutobusFacadeRemote autobusesFacade = lookupTmsAutobisesFacade();
    List<TmsAutobus> dbs = autobusesFacade.getByEmpresa(empresa);
    jcmbAutobus.setModel(new DefaultComboBoxModel(dbs.toArray()));
    jcmbAutobus.setSelectedItem(new TmsAutobus(BigDecimal.ZERO,tarjeta.getAutobus()));
  }

  private TmsOperadorFacadeRemote lookupTmsOperadoresFacade() {
    try {
      Context c = new InitialContext();
      return (TmsOperadorFacadeRemote) c.lookup("com.estrellaroja.confirmacionviajes.solicitudes.TmsOperadorFacadeRemote");

    } catch (NamingException ne) {
      // Logger.getLogger(getClass().getName()).log(Level.SEVERE,"exception caught" ,ne);
      throw new RuntimeException(ne);
    }
  }

  private TmsAutobusFacadeRemote lookupTmsAutobisesFacade() {
    try {
      Context c = new InitialContext();
      return (TmsAutobusFacadeRemote) c.lookup("com.estrellaroja.confirmacionviajes.solicitudes.TmsAutobusFacadeRemote");

    } catch (NamingException ne) {
      // Logger.getLogger(getClass().getName()).log(Level.SEVERE,"exception caught" ,ne);
      throw new RuntimeException(ne);
    }
  }

}
