/*
 * JDLG_Cancelar.java
 *
 * Created on 29 de enero de 2009, 07:28 PM
 */

package tmspases_traslado;

import javax.swing.JOptionPane;
import solicitud.TMSPasesTrasladoFacadeRemote;

/**
 *
 * @author  asolis
 */
public class JDLG_Cancelar extends javax.swing.JDialog {
    String usuario = "";
    TMSPasesTrasladoFacadeRemote cosa = null;
    /** Creates new form JDLG_Cancelar */
    public JDLG_Cancelar(java.awt.Frame parent, boolean modal, String usuario, TMSPasesTrasladoFacadeRemote cosa) {
        super(parent, modal);
        initComponents();
        this.setTitle("Cancelar Pase de Traslado"); 
        this.usuario = usuario;
        this.cosa = cosa;
        jlbl_barraEstado.setText("<html>  <font color=FF0000> ESCAPE</font> Salir Cancelar Pases de Traslado | <font color=FF0000> ENTER </font> Cancelar Pase de Traslado");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jlbl_folio = new javax.swing.JLabel();
        jntxt_folio = new tms_TextFields.JNumberTextField();
        jlbl_barraEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jlbl_folio.setText("Folio de Pase de Traslado: ");

        jntxt_folio.setBackground(new java.awt.Color(255, 255, 204));
        jntxt_folio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jntxt_folioKeyPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jlbl_folio)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jntxt_folio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                .addContainerGap())
            .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jntxt_folio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlbl_folio))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 20, Short.MAX_VALUE)
                .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 45, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jntxt_folioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jntxt_folioKeyPressed
         
         if(evt.getKeyCode() == evt.VK_ENTER){
                String respuesta = null;
                if(jntxt_folio.getText().length() <= 0)
                    JOptionPane.showMessageDialog( this, "Escriba el folio del Pase de Traslado",
                        "TMS - Pase de Traslado", JOptionPane.WARNING_MESSAGE );
                else
                respuesta = cosa.eliminarPasesTraslado (jntxt_folio.getText(), usuario);
                if(respuesta.equals("Todo bien")){
                    JOptionPane.showMessageDialog( this, "El Pase de Traslado con folio "+jntxt_folio.getText()+ " se ha Cancelado Correctamente",
                        "TMS - Pase de Traslado", JOptionPane.INFORMATION_MESSAGE );
                    jntxt_folio.setText("");
                }else{
                    if(respuesta.equals("No existe")){
                        JOptionPane.showMessageDialog( this, "El Pase de Traslado con folio "+jntxt_folio.getText()+" no se encuentra en el sistema o ya ha sido cancelado",
                        "TMS - Pase de Traslado", JOptionPane.ERROR_MESSAGE );
                        jntxt_folio.setText("");
                    }
                    if(respuesta.equals("Algo no salio bien")) {
                        JOptionPane.showMessageDialog( this, "En este momento no se puede cancelar el Pase de Traslado. Intente mas tarde",
                        "TMS - Pase de Traslado", JOptionPane.ERROR_MESSAGE );
                        jntxt_folio.setText("");
                    }                   
                }
        }
         if(evt.getKeyCode() == evt.VK_ESCAPE) {
            int result = JOptionPane.showOptionDialog(this, "¿Desea cerrar Cancelar Pase de Traslado?",
                    "TMS - Pase de Traslado", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);
            if(result == JOptionPane.YES_OPTION)
                this.dispose();
        }
    }//GEN-LAST:event_jntxt_folioKeyPressed
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbl_barraEstado;
    private javax.swing.JLabel jlbl_folio;
    private tms_TextFields.JNumberTextField jntxt_folio;
    // End of variables declaration//GEN-END:variables
    
}
