/*
 * JIFCanJE.java
 *
 * Created on 6 de septiembre de 2007, 12:41 PM
 */

package DialogosX;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableModel;
import subProcesos.JTextTextFieldMaxCharAlfa;
import tms_venta.SesionVenta;
import java.sql.Timestamp;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumn;
import subProcesos.JClsSintaxis;
import subProcesos.JTxtFieldFolios;
import tms_venta.JClsColoresInterfaz;

/**
 *
 * @author  ocruz
 */
 public class JDlgCanjeBolRef extends javax.swing.JDialog{
    /** Creates new form JIFCanje */

 public JDlgCanjeBolRef(SesionVenta pSesionVenta, Vector pOrigenes, Object[] pCiudadesConexion, Object[] pObjEmp, long thFechaHoraSistema){
        this.Origenes=pOrigenes;
        this.sesionVenta = pSesionVenta;
        this.CiudadesConexion = pCiudadesConexion;
        this.horaSistema = thFechaHoraSistema;
        this.horaSistemaHasta = thFechaHoraSistema+604800000; // hasta 7 dias
        sesionVenta.cargarODServicios(sesionVenta.getUserCon().getTerminalNombre());
        cbmServicio = new DefaultComboBoxModel(sesionVenta.getSs());
        this.COAnt = sesionVenta.getUserCon().getTerminalNombre();
        this.objEmp = pObjEmp;
        objEmpresas = new Object[objEmp.length];
        for(int i=0; i<objEmpresas.length; i++)
            objEmpresas[i] = sesionVenta.getEmpresasId(objEmp[i].toString()) + "-" + objEmp[i].toString();
        ordenaListaEmpresas();
        initComponents();
        setTitle(" Canje boleto referenciado");
        jLabel4.setText("<html><font color="+ColoresInterfaz.cHTML3+">ARRIBA/ABAJO </font> Ingresar Criterios | <font color="+ColoresInterfaz.cHTML3+">ENTER</font> Buscar Boleto | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Salir</html>");
        interfazColor();
        this.setModal(true);
        centrarJDialog();
        jTblBoletoOriginal.setAutoResizeMode( JTable.AUTO_RESIZE_OFF );
        jlbl_folRef.setText("Referencia");
        jClsSintaxis = new JClsSintaxis();
        xTabla.setDataVector(null, encabezado);
        jTxtFolioPreimpreso.requestFocus();
        
    }
    
    private void centrarJDialog(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, ( screenSize.height - frameSize.height ) / 2 );
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jlbl_folRef = new javax.swing.JLabel();
        jTxtFolioPreimpreso = new JTxtFieldFolios();
        jTxtFolioPreimpreso.setFocusTraversalKeysEnabled(false);
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScpBoletoOriginal = new javax.swing.JScrollPane();
        jTblBoletoOriginal = new javax.swing.JTable();
        jlbl_tipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(" Canje boleto abierto");
        setName("Ventana");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jlbl_folRef.setFont(new java.awt.Font("Tahoma", 1, 10));
        jlbl_folRef.setText("Referencia");

        jTxtFolioPreimpreso.setFont(new java.awt.Font("Tahoma", 1, 10));
        jTxtFolioPreimpreso.setName("FolioPreimpreso");
        jTxtFolioPreimpreso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtFolioPreimpresoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtFolioPreimpresoFocusLost(evt);
            }
        });
        jTxtFolioPreimpreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtFolioPreimpresoKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel4.setText("<html><font color=\"+ColoresInterfaz.cHTML1+\">ARRIBA/ABAJO</font> Ingresar Criterios | <font color=\"+ColoresInterfaz.cHTML1+\">ENTER</font> Buscar Boleto | <font color=\"+ColoresInterfaz.cHTML1+\">ESC</font> Salir</html>");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel6.setText("Boletos Referenciados:");

        jScpBoletoOriginal.setFocusable(false);
        jScpBoletoOriginal.setFont(new java.awt.Font("Tahoma", 1, 10));
        jTblBoletoOriginal.setFont(new java.awt.Font("Tahoma", 1, 10));
        jTblBoletoOriginal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTblBoletoOriginal.setModel(xTabla);
        jTblBoletoOriginal.getTableHeader().setReorderingAllowed(false);
        jTblBoletoOriginal.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTblBoletoOriginal.setFocusTraversalKeysEnabled(false);
        jTblBoletoOriginal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTblBoletoOriginalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTblBoletoOriginalFocusLost(evt);
            }
        });
        jTblBoletoOriginal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTblBoletoOriginalKeyPressed(evt);
            }
        });

        jScpBoletoOriginal.setViewportView(jTblBoletoOriginal);

        jlbl_tipo.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlbl_tipo.setForeground(new java.awt.Color(0, 0, 153));
        jlbl_tipo.setText(" ");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
            .add(jPanel1Layout.createSequentialGroup()
                .add(14, 14, 14)
                .add(jlbl_folRef)
                .add(10, 10, 10)
                .add(jTxtFolioPreimpreso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 233, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 440, Short.MAX_VALUE)
                .add(jlbl_tipo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 190, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jScpBoletoOriginal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLabel6)
                        .add(727, 727, 727))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlbl_folRef)
                    .add(jTxtFolioPreimpreso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlbl_tipo))
                .add(15, 15, 15)
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScpBoletoOriginal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtFolioPreimpresoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtFolioPreimpresoFocusLost
// TODO add your handling code here:
        jTxtFolioPreimpreso.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTxtFolioPreimpresoFocusLost

    private void jTxtFolioPreimpresoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtFolioPreimpresoFocusGained
// TODO add your handling code here:
        jTxtFolioPreimpreso.setBackground(xorColorFondo);
    }//GEN-LAST:event_jTxtFolioPreimpresoFocusGained

    private void jTblBoletoOriginalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblBoletoOriginalKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE:
                if(!sesionVenta.liberarSelectBoletosRef())
                    DialogoAceptar.mostrarDialogo("¡Liberar Boletos!","<html>¡No se pudieron liberar los boletos refenciados!</html>", Color.RED);
                xTabla.setDataVector(null, encabezado);
                AnchoColumnas();
                jLabel4.setText("<html><font color="+ColoresInterfaz.cHTML3+">ARRIBA/ABAJO </font> Ingresar Criterios | <font color="+ColoresInterfaz.cHTML3+">ENTER</font> Buscar Boleto | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Salir</html>");
                jlbl_tipo.setText("");
                jTxtFolioPreimpreso.setText("");
                jTxtFolioPreimpreso.requestFocus();
                break;
            case KeyEvent.VK_F2:
                if(jTblBoletoOriginal.getValueAt(jTblBoletoOriginal.getSelectedRow(),9).toString().equals("N"))
                {
                    jTblBoletoOriginal.setValueAt("S",jTblBoletoOriginal.getSelectedRow(),9);
                    jTblBoletoOriginal.setColumnSelectionInterval(10,10);
                    jTblBoletoOriginal.editCellAt(jTblBoletoOriginal.getSelectedRow(),10);
                    JViewport jv = jScpBoletoOriginal.getViewport();
                    jv.setViewPosition(new Point(1100,jTblBoletoOriginal.getRowHeight() * jTblBoletoOriginal.getSelectedRow()));
                    jScpBoletoOriginal.setViewport(jv);
                    jScpBoletoOriginal.setViewportView(jTblBoletoOriginal);
                    jv.repaint();
                    jTblBoletoOriginal.repaint();
                    
                }
                else
                {
                    jTblBoletoOriginal.setValueAt("",jTblBoletoOriginal.getSelectedRow(),10);
                    jTblBoletoOriginal.setColumnSelectionInterval(9,9);
                    jTblBoletoOriginal.editCellAt(9,9);
                    jTblBoletoOriginal.setValueAt("N",jTblBoletoOriginal.getSelectedRow(),9);
                }
                break;
            case KeyEvent.VK_F9:
                Vector nb = new Vector();
                int ncanj = 0;
                for(int i=0; i<jTblBoletoOriginal.getRowCount();i++)
                {
                    if(jTblBoletoOriginal.getValueAt(i,9).toString().equals("S") )
                        ncanj++;
                    
                    if(jTblBoletoOriginal.getValueAt(i,9).toString().equals("S") && jTblBoletoOriginal.getValueAt(i,10).toString().length()<4)
                    {
                        DialogoAceptar.mostrarDialogo("¡Faltan datos!","<html>Debes introducir el documento de identificación <br> " +
                                "con el que canjearon el boleto </html>", Color.RED); 
                        return;
                    }
                }
                if(ncanj==0)
                {
                    DialogoAceptar.mostrarDialogo("¡Imposible realizar canje!","<html>¡Debes seleccionar almenos un boleto para canjear!</html>", Color.RED);
                    return;
                }
                String mens = "Esta seguro de realizar el Canje ";
                if(jlbl_tipo.getText().equals(""))
                {
                    if (ncanj>1) mens = mens+" de los "+ncanj+" boletos";
                    else mens = mens+" del boleto";
                }
                else
                {
                    if (ncanj>1) mens = mens+" de los "+ncanj+" boletos abiertos";
                    else mens = mens+" del boleto abierto";
                }
                DialogoSiNo = new JDlgSiNo("¡Confirme!","¿"+mens+"?",true);
                boolean res = DialogoSiNo.getResultado();
                if(res){
                
                    for(int i=0; i<jTblBoletoOriginal.getRowCount();i++)
                        sesionVenta.getVariosTmsBoletosVentaTbl().get(i).setDocumento(jTblBoletoOriginal.getValueAt(i,10).toString());
                    for(int i=0; i<jTblBoletoOriginal.getRowCount();i++)
                        if(jTblBoletoOriginal.getValueAt(i,9).toString().equals("N"))
                            nb.add(i);
                    System.out.println("Eliminar: "+nb);
                    for(int i=0; i<nb.size(); i++)
                        sesionVenta.getVariosTmsBoletosVentaTbl().remove(Integer.valueOf(nb.get(i).toString())-i);
                    this.dispose();
                }
                else
                    return;
                break;
        }
    }//GEN-LAST:event_jTblBoletoOriginalKeyPressed

    private void jTblBoletoOriginalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTblBoletoOriginalFocusLost
// TODO add your handling code here:
    }//GEN-LAST:event_jTblBoletoOriginalFocusLost

    private void jTblBoletoOriginalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTblBoletoOriginalFocusGained
// TODO add your handling code here:
        jLabel4.setText("<html><font color="+ColoresInterfaz.cHTML3+">F2</font> Seleccionar boleto para canjear | <font color="+ColoresInterfaz.cHTML3+">F9</font> Realizar Canje de Boleto | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Nueva Busqueda</html>");
    }//GEN-LAST:event_jTblBoletoOriginalFocusGained

    private void jTxtFolioPreimpresoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFolioPreimpresoKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE:
                chOk=false;
                this.dispose();
                break;
            case KeyEvent.VK_ENTER:
                    if(!validaCampos()) return;
                    if(!valRef(jTxtFolioPreimpreso.getText())) return;
                    //ConstruyeMultiBa();
                    if(vectorTerminal.get(1).toString().equals(sesionVenta.getUserCon().getTerminalNombre())) sesionVenta.setTipoTransaccion("L");
                    else sesionVenta.setTipoTransaccion("R");
                    sesionVenta.setDBLink(vectorTerminal.get(3).toString());
                    boletosRef = sesionVenta.buscaBoletosReferencia(vectorTerminal.get(1).toString(), jTxtFolioPreimpreso.getText());
                    if(boletosRef==null){
                    DialogoAceptar.mostrarDialogo("¡Imposible realizar canje!","<html>Puede ser que la referencia sea incorrecta o<br>" +
                    "el boleto(s) ya fue canjeado.</html>", Color.RED); 
                    jTxtFolioPreimpreso.setText("");
                    jTxtFolioPreimpreso.selectAll();
                    jTxtFolioPreimpreso.requestFocusInWindow();
                    return;
                    }
                    
                    sesionVenta.setTipoTransaccionAuxiliar(sesionVenta.getTipoTransaccion());
                    sesionVenta.setDBLinkAuxiliar(sesionVenta.getDBLink());
                    sesionVenta.setReferenciaCanjeBA(jTxtFolioPreimpreso.getText());
                    if(sesionVenta.getTmsBoletosVentaTbl().getTipoOperacion().equals("VA"))
                    {
                        if(sesionVenta.getVariosTmsBoletosVentaTbl().size()>1)
                            jlbl_tipo.setText("BOLETOS ABIERTOS");
                        else
                            jlbl_tipo.setText("BOLETO ABIERTO");
                        sesionVenta.getUserCon().setSnAsiento(true);
                    }
                    else
                    {
                        sesionVenta.getUserCon().setSnAsiento(false);
                        jlbl_tipo.setText("");
                    }
//                    String tipoPasajeACanjear="";
//                    for(int i=0; i<sesionVenta.getVariosTmsBoletosVentaTbl().size(); i++){
//                        tipoPasajeACanjear = sesionVenta.getVariosTmsBoletosVentaTbl().get(i).getTipoPasajero();
//                        if(tipoPasajeACanjear.equals("E") || tipoPasajeACanjear.equals("P")){
//                            if(!sesionVenta.sonVacaciones()){
//                                DialogoAceptar.mostrarDialogo("Canje de boleto abierto.","<html>Tipo de pasajero "+tipoPasajeACanjear+" solo esta habilitado<br>en periodo vacacional.</html>", Color.RED);
//                                chOk=false;
//                                this.dispose();
//                                return;
//                            }
//                        }
//                    }
                    
                    importeBolOriginalAdulto = sesionVenta.getTmsBoletosVentaTbl().getImporteBoleto();
                    EmpresaCBA = sesionVenta.getTmsBoletosVentaTbl().getEmpresa();
                    ServicioCBA = sesionVenta.getTmsBoletosVentaTbl().getServicio();
                    OrigenCBA = sesionVenta.getTmsBoletosVentaTbl().getOrigen();
                    DestinoCBA = sesionVenta.getTmsBoletosVentaTbl().getDestino();
                    CiudadCorridaCBA = vectorTerminal.get(1).toString();//(sesionVenta.ConexionRealBAX(OrigenCBA, DestinoCBA, ServicioCBA)!=null ? OrigenCBA : jCboOrigen.getSelectedItem().toString());
                    //CiudadCorridaCBA = (existeOrigenComoCiudadConexion(jCboOrigen.getSelectedItem().toString()) ? OrigenCBA : jCboOrigen.getSelectedItem().toString());
                    
                    chOk=true;

                    xTabla.setDataVector(boletosRef, encabezado);
                    AnchoColumnas();
                    jTblBoletoOriginal.setRowSelectionInterval(0,0);
                    jTblBoletoOriginal.requestFocusInWindow();
                return;
        }
    }//GEN-LAST:event_jTxtFolioPreimpresoKeyPressed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
// TODO add your handling code here:
        jTxtFolioPreimpreso.requestFocusInWindow();
    }//GEN-LAST:event_formComponentShown
    
    private boolean validaCampos(){
        if(jTxtFolioPreimpreso.getText().equals("")){
            DialogoAceptar.mostrarDialogo("¡Importante!","Ingrese la referencia del Boleto.", Color.RED);
            jTxtFolioPreimpreso.requestFocusInWindow(); return false;
        }
        return true;
    }
    
    private void ordenaListaEmpresas(){
        Object[] objs= new Object[objEmpresas.length];
        int i, j, vA, vB; String valor;
        for(i=0; i<objEmpresas.length; i++){
            for(j=0; j<objEmpresas.length-1; j++){
                valor=objEmpresas[j+1].toString();
                vA=Integer.valueOf(objEmpresas[j].toString().substring(0,1));
                vB=Integer.valueOf(objEmpresas[j+1].toString().substring(0,1));
                if(vA>vB){
                    objEmpresas[j+1] = objEmpresas[j].toString();
                    objEmpresas[j] = valor;
                }
            }
        }
    }
 
    private boolean valRef(String referencia) {
        int nter = 0;
        try {
            nter = Integer.parseInt(referencia.substring(0, 2), 16);
        } catch (NumberFormatException ex) {
            ex.printStackTrace();
        }
        Vector vter = sesionVenta.buscaTerminalRef(nter) ;
        if(vter.size()==0){
            DialogoAceptar.mostrarDialogo("¡Imposible realizar canje!","<html>Puede ser que la referencia sea incorrecta o<br>" +
                    "el boleto(s) ya fue canjeado.</html>", Color.RED);
            jTxtFolioPreimpreso.selectAll();
            jTxtFolioPreimpreso.requestFocusInWindow();
            return false;
        }
        this.vectorTerminal = (Vector) vter.get(0);
        return true;
    }
    
//    private void ConstruyeMultiBa(){
//        conjuntoFolios="'"+jClsSintaxis.getVectorFoliosBoletos().get(0).toString()+"'";
//            for(int i=1; i<jClsSintaxis.getVectorFoliosBoletos().size(); i++)
//                conjuntoFolios=conjuntoFolios+",'"+jClsSintaxis.getVectorFoliosBoletos().get(i).toString()+"'";
//    }
//    
    private void AnchoColumnas() {
        int anchoContenedor = jScpBoletoOriginal.getWidth();
        TableColumn column;
        for (int i = 0; i < jTblBoletoOriginal.getColumnCount(); i++) {
            column = jTblBoletoOriginal.getColumnModel().getColumn(i);
            switch (i) {
//                case 0: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.12)); break;
//                case 1: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.15)); break;
//                case 2: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.04)); break;
//                case 3: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.04)); break;
//                case 4: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.35)); break;
//                case 5: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.14)); break;
//                case 6: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.08)); break;
//                case 7: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.08)); break;
////                case 0: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.12)); break;
////                case 1: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.10)); break;
////                case 2: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.03)); break;
////                case 3: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.02)); break;
////                case 4: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.07)); break;
////                case 5: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.07)); break;
////                case 6: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.07)); break;
////                case 7: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.15)); break;
////                case 8: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.15)); break;
////                case 9: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.07)); break;
////                case 10: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.15)); break;
                case 0: column.setMinWidth( 120 );column.setMaxWidth( 120 );column.setPreferredWidth(120); break;
                case 1: column.setMinWidth( 110 );column.setMaxWidth( 110 );column.setPreferredWidth(110); break;
                case 2: column.setMinWidth( 20 );column.setMaxWidth(20  );column.setPreferredWidth(20); break;
                case 3: column.setMinWidth( 20 );column.setMaxWidth( 20 );column.setPreferredWidth(20); break;
                case 4: column.setMinWidth( 60 );column.setMaxWidth( 60 );column.setPreferredWidth(60); break;
                case 5: column.setMinWidth( 60 );column.setMaxWidth( 50 );column.setPreferredWidth(50); break;
                case 6: column.setMinWidth( 50 );column.setMaxWidth( 60 );column.setPreferredWidth(60); break;
                case 7: column.setMinWidth( 220 );column.setMaxWidth( 220 );column.setPreferredWidth(220); break;
                case 8: column.setMinWidth( 220 );column.setMaxWidth( 220 );column.setPreferredWidth(220); break;
                case 9: column.setMinWidth( 60 );column.setMaxWidth( 60 );column.setPreferredWidth(60); break;
                case 10: column.setMinWidth( 180 );column.setMaxWidth( 180 );column.setPreferredWidth(180); break;
                
                
            }
            column.setResizable(false);
        }
        jTblBoletoOriginal.getColumnModel().getColumn(10).setCellEditor(new DefaultCellEditor(jtxtNombre));        
    }
    

    
    private void interfazColor(){
        jPanel1.setBackground(ColoresInterfaz.cFondoDialogo);
        /*jLabel4.setOpaque(true);
        jLabel4.setBackground(ColoresInterfaz.cFondoPieEncabezado2);*/
        jLabel4.setForeground(ColoresInterfaz.cTextoAyuda1);
        
        setFont(ColoresInterfaz.fuente1);
        jlbl_folRef.setFont(ColoresInterfaz.fuente1);
        jTxtFolioPreimpreso.setFont(ColoresInterfaz.fuente1);
        jLabel6.setFont(ColoresInterfaz.fuente1);
        jLabel4.setFont(ColoresInterfaz.fuente1);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScpBoletoOriginal;
    private javax.swing.JTable jTblBoletoOriginal;
    private javax.swing.JTextField jTxtFolioPreimpreso;
    private javax.swing.JLabel jlbl_folRef;
    private javax.swing.JLabel jlbl_tipo;
    // End of variables declaration//GEN-END:variables
    public Object[][] boletosRef = null;
    public static boolean chOk;
    public double importeBolOriginalAdulto;
    public String EmpresaCBA="";
    public String ServicioCBA="";
    public String OrigenCBA="";
    public String DestinoCBA="";
    public String CiudadCorridaCBA="";
    private SesionVenta sesionVenta = null;
    private JDlgAceptar DialogoAceptar = new JDlgAceptar();
    private Vector Origenes;
    private DefaultComboBoxModel cbmServicio;
    //private Vector canjeServicios = new Vector();
    private String COAnt;
    private Object[] CiudadesConexion;
    private Object[] objEmp;
    private Object[] objEmpresas;
    private long horaSistema, horaSistemaHasta;
    private JClsColoresInterfaz ColoresInterfaz = new JClsColoresInterfaz();
    private JClsSintaxis jClsSintaxis=null;
    private String conjuntoFolios;
    private Object[] encabezado = {"CORRIDA", "FECHA CORRIDA", "#", "T", "ORIGEN", "DESTINO", "COSTO","NOMBRE PASAJERO","NOMBRE AUTORIZADO","CANJEAR","DOCUMENTO"};
    private DefaultTableModel xTabla = new DefaultTableModel(null,encabezado){
        public boolean isCellEditable(int row, int col){
            if(col == 10)
                return true;
            else
                return false;
        }
    };
    private JTextTextFieldMaxCharAlfa jtxtNombre = new JTextTextFieldMaxCharAlfa(30);
    private Vector vectorTerminal;

    private JDlgSiNo DialogoSiNo;
    private Color xorColorFondo = new Color(156, 179, 201);
}