/*
 * JDlgCupones.java
 *
 * Created on 7 de noviembre de 2007, 08:17 PM
 */

package DialogosX;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.JComponent;
import javax.swing.JDialog;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.text.JTextComponent;
import tms_venta.JClsColoresInterfaz;
import tms_venta.SesionVenta;

/**
 *
 * @author  ocruz
 */
public class JDlgCupones extends javax.swing.JDialog {
    
    /** Creates new form JDlgCupones */
    public JDlgCupones(int pNumBoletos, JDialog compo, SesionVenta pSesionVenta) {
        super(compo, true);
        this.numBoletos = pNumBoletos;
        this.sesionVenta = pSesionVenta;
        cupones = new Object[pNumBoletos][2];
        initComponents();
        //jLabel1.setText("<html><font color="+ColoresInterfaz.cHTML3+">F2</font> Seleccionar Agencia |<font color="+ColoresInterfaz.cHTML3+">F7</font> Aceptar | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Cancelar");
        jLabel1.setText("<html><font color="+ColoresInterfaz.cHTML3+">ENTER </font> Seleccionar Agencia  | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Cancelar");
        interfazColor();
        //this.setModal(true);
        centrarJDialog();
        xVtaActual.setDataVector(cupones, encVtaActual);
        jcmbxAgenciasViaje.removeAllItems();
        for(int i=0; i<this.sesionVenta.getAgenciasViaje().size();i++)
        {
            Vector v=(Vector)this.sesionVenta.getAgenciasViaje().get(i);
            jcmbxAgenciasViaje.addItem(v.get(1).toString());
        }
        this.jTblCupones.registerKeyboardAction(new ActionListener() {
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0), JComponent.WHEN_FOCUSED);
        this.MsgCupon = "";
        this.jTblCupones.setRowSelectionInterval(0,0);
        this.jTblCupones.setColumnSelectionInterval(0,0);
        this.jcmbxAgenciasViaje.requestFocusInWindow();
        //this.jTblCupones.requestFocusInWindow();
    }
    
    public void setColNoEditable(int pColNoEditable){ this.colNoEditable=pColNoEditable; }
    
    public void setFormaPago(String pFormaPago){
        this.FormaPago = pFormaPago;
    }
    
    private void centrarJDialog(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, ( screenSize.height - frameSize.height ) / 2 );
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTblCupones = new javax.swing.JTable();
        jTblCupones = new javax.swing.JTable()
        {
            public Component prepareEditor(
                TableCellEditor editor, int row, int column)
            {

                Component c = super.prepareEditor(editor, row, column);
                if (c instanceof JTextComponent)
                {
                    ((JTextField)c).selectAll();
                }
                return c;
            }
        };
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcmbxAgenciasViaje = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ingrese Cupones");
        setModal(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setFocusable(false);

        jTblCupones.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTblCupones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTblCupones.setModel(xVtaActual);
        jTblCupones.setFocusTraversalKeysEnabled(false);
        jTblCupones.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_RIGHT, 0),"none");
        jTblCupones.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_LEFT, 0),"none");
        jTblCupones.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_TAB, 0),KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0));
        jTblCupones.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTblCupones.setRowSelectionAllowed(false);
        jTblCupones.setColumnSelectionAllowed(false);
        jTblCupones.setCellSelectionEnabled(true);
        jTblCupones.getTableHeader().setReorderingAllowed(false);
        jTblCupones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTblCuponesFocusGained(evt);
            }
        });
        jTblCupones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTblCuponesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTblCuponesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTblCupones);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><font color=\"+ColoresInterfaz.cHTML1+\">F7</font> Aceptar | <font color=\"+ColoresInterfaz.cHTML1+\">ESC</font> Cancelar");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Cliente:");

        jcmbxAgenciasViaje.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmbxAgenciasViaje.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcmbxAgenciasViajeFocusGained(evt);
            }
        });
        jcmbxAgenciasViaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcmbxAgenciasViajeKeyPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jcmbxAgenciasViaje, 0, 397, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jcmbxAgenciasViaje, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                .add(11, 11, 11)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTblCuponesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblCuponesKeyReleased
// TODO add your handling code here:
        switch(evt.getKeyCode()){
           case KeyEvent.VK_F2:
            if (jTblCupones.getCellEditor() != null)
                jTblCupones.getCellEditor().stopCellEditing();
            this.jcmbxAgenciasViaje.requestFocusInWindow();
           break;
            case KeyEvent.VK_ENTER: case KeyEvent.VK_RIGHT: case KeyEvent.VK_LEFT:
                if(FormaPago.equals("AMX") && jTblCupones.getSelectedColumn()==0){
                   objDato=xVtaActual.getValueAt(jTblCupones.getSelectedRow(),1);
                   if(objDato==null || objDato.toString().equals("")) return;
                   if(objDato.toString().length()!=sesionVenta.getUserCon().getDigitosCupon()){
                       this.getToolkit().beep();
                       DialogoAceptar.mostrarDialogo("¡Boleto de avion incorrecto!", "Ingrese "+sesionVenta.getUserCon().getDigitosCupon()+" digitos.", Color.RED);
                       jTblCupones.setRowSelectionInterval(jTblCupones.getSelectedRow(), jTblCupones.getSelectedRow());
                       jTblCupones.setColumnSelectionInterval(1, 1);
                       jTblCupones.requestFocusInWindow();
                       return;
                   }
                }
                break;
        }
    }//GEN-LAST:event_jTblCuponesKeyReleased

    private void jTblCuponesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblCuponesKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
           case KeyEvent.VK_F2:
              if (jTblCupones.getCellEditor() != null) 
               jTblCupones.getCellEditor().stopCellEditing();
              this.jcmbxAgenciasViaje.requestFocusInWindow();
           break;
            case KeyEvent.VK_F7:
                int i;
                if(FormaPago.equals("AMX")){
                    for(i=0; i<numBoletos; i++){
                        if(xVtaActual.getValueAt(i,0)==null || xVtaActual.getValueAt(i,0).toString().equals("") ||
                                xVtaActual.getValueAt(i,1)==null || xVtaActual.getValueAt(i,1).toString().equals("")){
                            DialogoAceptar.mostrarDialogo("¡Falta cupones por ingresar!", "Los "+numBoletos+" cupones son requeridos.", Color.RED);
                            jTblCupones.setRowSelectionInterval(i,i);
                            jTblCupones.requestFocusInWindow();
                            return;
                        }
                        if(xVtaActual.getValueAt(i,1).toString().length()!=sesionVenta.getUserCon().getDigitosCupon()){
                            this.getToolkit().beep();
                            DialogoAceptar.mostrarDialogo("¡Boleto de avion incorrecto!", "Ingrese "+sesionVenta.getUserCon().getDigitosCupon()+" digitos.", Color.RED);
                            jTblCupones.setRowSelectionInterval(i, i);
                            jTblCupones.setColumnSelectionInterval(1, 1);
                            jTblCupones.requestFocusInWindow();
                            return;
                        }
                        cupones[i][0] = jTblCupones.getValueAt(i,0);
                        cupones[i][1] = jTblCupones.getValueAt(i,1);
                    }
                }
                else{
                    for(i=0; i<numBoletos; i++){
                        if(xVtaActual.getValueAt(i,0)==null || xVtaActual.getValueAt(i,0).toString().equals("")){
                            DialogoAceptar.mostrarDialogo("¡Falta cupones por ingresar!", "Los "+numBoletos+" cupones son requeridos.", Color.RED);
                            jTblCupones.setRowSelectionInterval(i,i);
                            jTblCupones.requestFocusInWindow();
                            return;
                        }
                        cupones[i][0] = jTblCupones.getValueAt(i,0);
                        cupones[i][1] = jTblCupones.getValueAt(i,1);
                    }
                }
                this.clienteId = Long.valueOf(((Vector)(this.sesionVenta.getAgenciasViaje().get(jcmbxAgenciasViaje.getSelectedIndex()))).get(0).toString());
                if(this.clienteId==-1)
                {
                    DialogoAceptar.mostrarDialogo("¡Falta seleccionar Agencia de Viajes!", "Debes seleccionar un Cliente.", Color.RED);
                    jcmbxAgenciasViaje.requestFocusInWindow();
                    return;
                }
                //this.MsgCupon = "Cupones ingresados";
                this.MsgCupon = "Referencias ingresadas";
                this.dispose();
                break;
            case KeyEvent.VK_ESCAPE:
                if(FormaPago.equals("AMX")){
                    for(i=0; i<numBoletos; i++){
                        if(xVtaActual.getValueAt(i,0)==null || xVtaActual.getValueAt(i,0).toString().equals("") ||
                                xVtaActual.getValueAt(i,1)==null || xVtaActual.getValueAt(i,1).toString().equals("")){
                            this.MsgCupon = "";
                            break;
                        }
                        else{
                            if(xVtaActual.getValueAt(i,1).toString().length()!=sesionVenta.getUserCon().getDigitosCupon()){
                                this.MsgCupon = "";
                                break;
                            }
                        }
                    }
                }
                else{
                    for(i=0; i<numBoletos; i++){
                        if(xVtaActual.getValueAt(i,0)==null || xVtaActual.getValueAt(i,0).toString().equals("")){
                            this.MsgCupon = "";
                            break;
                        }
                        else{
                            cupones[i][0] = jTblCupones.getValueAt(i,0);
                            cupones[i][1] = jTblCupones.getValueAt(i,1);
                        }
                    }
                }
                this.dispose();
                break;
        }
    }//GEN-LAST:event_jTblCuponesKeyPressed

    public String getMsgCupones(){ return this.MsgCupon; }
    
    public Object[][] getFoliosCupones(){ return this.cupones; }
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
// TODO add your handling code here:
        this.jTblCupones.setRowSelectionInterval(0,0);
        this.jTblCupones.setColumnSelectionInterval(0,0);
        //this.jTblCupones.requestFocusInWindow();
        this.jcmbxAgenciasViaje.requestFocusInWindow();
    }//GEN-LAST:event_formComponentShown

    private void jTblCuponesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTblCuponesFocusGained
        jLabel1.setText("<html><font color="+ColoresInterfaz.cHTML3+">F2</font> Seleccionar Agencia |<font color="+ColoresInterfaz.cHTML3+">F7</font> Aceptar | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Cancelar");
    }//GEN-LAST:event_jTblCuponesFocusGained

    private void jcmbxAgenciasViajeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcmbxAgenciasViajeFocusGained
        jLabel1.setText("<html><font color="+ColoresInterfaz.cHTML3+">ENTER </font> Seleccionar Agencia   | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Cancelar");
    }//GEN-LAST:event_jcmbxAgenciasViajeFocusGained

    private void jcmbxAgenciasViajeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcmbxAgenciasViajeKeyPressed
    switch(evt.getKeyCode()){
            case KeyEvent.VK_ENTER:
                    this.jTblCupones.requestFocusInWindow();
            break;
            case KeyEvent.VK_ESCAPE:
                int i=0;
                if(FormaPago.equals("AMX")){
                    for(i=0; i<numBoletos; i++){
                        if(xVtaActual.getValueAt(i,0)==null || xVtaActual.getValueAt(i,0).toString().equals("") ||
                                xVtaActual.getValueAt(i,1)==null || xVtaActual.getValueAt(i,1).toString().equals("")){
                            this.MsgCupon = "";
                            break;
                        }
                        else{
                            if(xVtaActual.getValueAt(i,1).toString().length()!=sesionVenta.getUserCon().getDigitosCupon()){
                                this.MsgCupon = "";
                                break;
                            }
                        }
                    }
                }
                else{
                    for(i=0; i<numBoletos; i++){
                        if(xVtaActual.getValueAt(i,0)==null || xVtaActual.getValueAt(i,0).toString().equals("")){
                            this.MsgCupon = "";
                            break;
                        }
                        else{
                            cupones[i][0] = jTblCupones.getValueAt(i,0);
                            cupones[i][1] = jTblCupones.getValueAt(i,1);
                        }
                    }
                }
                this.dispose();
                break;
        }
    }//GEN-LAST:event_jcmbxAgenciasViajeKeyPressed
    
    private void interfazColor(){
        setBackground(ColoresInterfaz.cFondoDialogo);
        jTblCupones.setBackground(ColoresInterfaz.cFondoDialogo);
        /*jLabel1.setOpaque(true);
        jLabel1.setBackground(ColoresInterfaz.cFondoPieEncabezado2);*/
        jLabel1.setForeground(ColoresInterfaz.cTextoAyuda1);
        
        jTblCupones.setFont(ColoresInterfaz.fuente1);
        jLabel1.setFont(ColoresInterfaz.fuente1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblCupones;
    private javax.swing.JComboBox jcmbxAgenciasViaje;
    // End of variables declaration//GEN-END:variables

    private Object[] encVtaActual = {"No. Referencia", "No. Boleto"};
    private DefaultTableModel xVtaActual = new DefaultTableModel(null, encVtaActual){
        public boolean isCellEditable(int row, int col) {
            if(col==colNoEditable) return false;
            return true;
        }
    };
    Object[][] cupones;
    private JDlgAceptar DialogoAceptar = new JDlgAceptar();
    int numBoletos;

    private String MsgCupon;
    private String FormaPago;
    private Object objDato;
    private JClsColoresInterfaz ColoresInterfaz = new JClsColoresInterfaz();
    private SesionVenta sesionVenta;
    private int colNoEditable;
    private long clienteId =-1;

    /**
     * @return the clienteId
     */
    public long getClienteId() {
        return clienteId;
    }

    /**
     * @param clienteId the clienteId to set
     */
    public void setClienteId(long clienteId) {
        this.clienteId = clienteId;
    }
}
