/*
 * jDlgVentaBA.java
 *
 * Created on 10 de septiembre de 2007, 12:55 PM
 */

package DialogosX;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import tms_venta.JClsColoresInterfaz;
import tms_venta.SesionVenta;

/**
 *
 * @author  ocruz
 */
public class jDlgVentaBA extends javax.swing.JDialog {
    
    /**
     * Creates new form jDlgVentaBA
     */
    public jDlgVentaBA(SesionVenta pSesionVenta, Object[] pListadoC, long pruta) {
        this.sesionVenta = pSesionVenta;
        this.listadoC=pListadoC;
        this.ruta = pruta;
        initComponents();
        jLabel2.setText("<html><font color="+ColoresInterfaz.cHTML3+">ENTER</font> Aceptar | <font color="+ColoresInterfaz.cHTML3+">ESCAPE</font> Seleccionar servicio | <font color="+ColoresInterfaz.cHTML3+">F1</font> Nueva Consulta</html>");
        interfazColor();
        //jTextField1.setTipos(sesionVenta.CastTiposPasajeBA(listadoC[1].toString()));
        continuar = sesionVenta.queTiposPasajeVendo(listadoC[3].toString());
        if(!continuar) return;
        jTextField1.setTipos(sesionVenta.getCastTiposPasaje());
        TiposAsientos= new Vector();
        centrar();
        jLabel2.setText("<html>"+getTiposPasajeVenta()+" | <font color=#"+ColoresInterfaz.cHTML3+">ENTER</font> Aceptar |<br><font color=#"+ColoresInterfaz.cHTML3+">ESCAPE</font> Seleccionar servicio | " +
                "<font color=#"+ColoresInterfaz.cHTML3+">F1</font> Nueva Consulta</html>");
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new paquete.JTxtFieldTipoPasaje();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(" Venta boleto abierto");
        setModal(true);
        setResizable(false);
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel3.setText("Ingrese cantidad y tipo pasajero");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 10));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("<html><font color=\"+ColoresInterfaz.cHTML1+\">ENTER</font> Aceptar | <font color=\"+ColoresInterfaz.cHTML1+\">ESCAPE</font> Seleccionar servicio | <font color=\"+ColoresInterfaz.cHTML1+\">F1</font> Nueva Consulta</html>");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 185, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(17, 17, 17)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE:
                this.Resultado=1;
            break;
            case KeyEvent.VK_F1:
                this.Resultado=2;
            break;
            case KeyEvent.VK_ENTER:
                if(!obtenerTipos(jTextField1.getText())){
                    jTextField1.setText("");
                    return;
                }
                this.DatosBoletoAbierto();
                this.Resultado=0;
            break;
        }
        if(this.Resultado>-1)
            this.dispose();
    }//GEN-LAST:event_jTextField1KeyPressed

    private void centrar(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, ( screenSize.height - frameSize.height ) / 2 );
    }
    
    private boolean obtenerTipos(String txtDatos) {
        if(txtDatos.equals("")) return false;
        if(txtDatos.length()<2) return false;
        //TotalBoletos=fTotalBoletos(txtDatos);
        TiposAsientos.removeAllElements();
        String aux = txtDatos;
        boolean salida = true;
        long [] iasientos;
        int iTotalast = 0, i, n;
        char[] cTipo;
        if (aux.length() != 0) {
            String[] strTipoAsiento;
            strTipoAsiento = aux.split(" ");
            iasientos = new long[strTipoAsiento.length];
            cTipo = new char[strTipoAsiento.length];
            for (i = 0; i < strTipoAsiento.length; i++) {
                cTipo[i] = strTipoAsiento[i].charAt(strTipoAsiento[i].length() - 1);
                try{
                    if(strTipoAsiento[i].substring(0, strTipoAsiento[i].length() - 1)=="") iasientos[i]=1;
                    else iasientos[i] = Long.parseLong(strTipoAsiento[i].substring(0, strTipoAsiento[i].length() - 1));
                    iTotalast += (int)iasientos[i];
                }
                catch(NumberFormatException nfe){
                    return false;
                }
            }
            /*if (iTotalast > TotalBoletos) {
                salida = false;
            } else {*/
                for (n = 0; n < iasientos.length; n++) {
                    for (int t = 0; t < iasientos[n]; t++) {
                        TiposAsientos.add(cTipo[n]);
                    }
                }
            
            if(TiposAsientos.size()<1){ jTextField1.setText(""); return false; }
            
            for(n=0; n<TiposAsientos.size(); n++)
                if(Character.isDigit(TiposAsientos.get(n).toString().charAt(0))){jTextField1.setText(""); return false; }
            //}
        }

        this.TotalBoletos = iTotalast;
        this.jTextField1.setText("");
        return salida;
    }
/************************************** BOLETO ABIERTO *********************************/
    private void DatosBoletoAbierto(){
        long tipoId, tarifaid;
        double tTarifa = 0, tDescuento = 0, TTarifa=0;
        char tipop;
        double Tarifa = sesionVenta.getUserCon().getServicioTarifaSencillo(), suma=0;
//        BoletosBA = new Object[TotalBoletos][32];
        BoletosBA = new Object[TotalBoletos][36];//VAGL 02082013[35]
        for (int i = 0; i < this.TotalBoletos; i++) {
            tipop = TiposAsientos.elementAt(i).toString().charAt(0);
            tipoId = jTextField1.getTipopasajeid(tipop,ruta);
            BoletosBA[i][0] = null;                                                   // corrida-hora
            BoletosBA[i][1] = null;                                                   // asiento
            BoletosBA[i][2] = TiposAsientos.elementAt(i).toString();                  // tipo pasajero
            BoletosBA[i][3] = "";                                                     // nombre pasajero
            BoletosBA[i][4] = listadoC[0]+"-"+listadoC[1];                            // origen-destino
            tDescuento = jTextField1.getDescuento(tipoId);
            String redondeo =jTextField1.getRedondeo(tipoId);
            if(redondeo.equals("S"))
                TTarifa =Math.ceil(Tarifa - (tDescuento * Tarifa));
            else
            {
                TTarifa =Tarifa - (tDescuento * Tarifa);
                double d = (TTarifa - (Double.valueOf(""+TTarifa).longValue()) );
                if(d > 0 && d != .50)                                
                    TTarifa =    Math.ceil(TTarifa);
            }
            suma = suma+TTarifa;
            BoletosBA[i][5] = TTarifa;                                                // importe boleto
            BoletosBA[i][6] = "S";                                                    // BOLETO NORMAL + BOLETO ABIERTO
            BoletosBA[i][7] = listadoC[2];                                            // empresa
            BoletosBA[i][8] = listadoC[3];                                            // servicio
            BoletosBA[i][9] = sesionVenta.getUserCon().getCaja();                     // caja
            BoletosBA[i][10] = sesionVenta.getUserCon().getCorteId();                 // corte id
            BoletosBA[i][11] = null;                                                  // clave corrida
            BoletosBA[i][12] = null;                                                  // cliente id
            BoletosBA[i][13] = null;                                                  // tipo pago
            BoletosBA[i][14] = null;                                                  // referencia pago
            BoletosBA[i][15] = "VA";                                                  // tipo operacion
            BoletosBA[i][16] = null;                                                  // reservacion id
            BoletosBA[i][17] = null;                                                  // boleto relacionado id
            BoletosBA[i][18] = null;                                                  // dias validez boleto abierto
            if(!sesionVenta.getUserCon().getAplicacionVenta())
                BoletosBA[i][19] = "000000";// folio preimpreso
            else
                BoletosBA[i][19] = sesionVenta.obtenerFolioActual(listadoC[2].toString());// folio preimpreso
            BoletosBA[i][20] = sesionVenta.getUserCon().getTerminalNombre();          // ciudad Venta
            BoletosBA[i][21] = listadoC[0];                                           // origen
            BoletosBA[i][22] = listadoC[1];                                           // destino
            BoletosBA[i][23] = "L";                                                   // tipo Transaccion
            BoletosBA[i][24] = sesionVenta.getUserCon().getUsuarioNum();              // cajero
            BoletosBA[i][25] = null;                                                  // corridaId
            BoletosBA[i][26] = formatoDate.format(new Date());                        // fecha
            BoletosBA[i][27] = formatoHour.format(new Date());                        // hora
            BoletosBA[i][28] = new Boolean(false);                                    // sin numero de asiento
            BoletosBA[i][29] = "N";                                                   // tipo de venta
            BoletosBA[i][30] = "";                                                   // nombre autorizado
            BoletosBA[i][31] = "S";                                                   // 
        }
        sesionVenta.setImporteVenta(suma);
    }
    
    private String getTiposPasajeVenta() {
        String cadena="";
        Vector cx = null;
        for(int i=0; i<sesionVenta.getCastTiposPasaje().size(); i++){
            cx = (Vector) sesionVenta.getCastTiposPasaje().get(i);
            if(cadena.indexOf(cx.get(1).toString())==-1)
                cadena = cadena + "<font color="+ColoresInterfaz.cHTML3+">"+cx.get(2).toString()+"</font> "+cx.get(1).toString()+" ";
        }
        return cadena;
    }
    
    public Object[][] getBoletos(){ return BoletosBA; }
     
    public int getResultado(){ return Resultado; }
    
    public boolean getContinuar(){ return this.continuar; }

    private void interfazColor(){
        jPanel1.setBackground(ColoresInterfaz.cFondoDialogo);
        /*jLabel2.setOpaque(true);
        jLabel2.setBackground(ColoresInterfaz.cFondoPieEncabezado2);*/
        jLabel2.setForeground(ColoresInterfaz.cTextoAyuda1);
        
        jLabel3.setFont(ColoresInterfaz.fuente1);
        jTextField1.setFont(ColoresInterfaz.fuente1);
        jLabel2.setFont(ColoresInterfaz.fuente_1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private paquete.JTxtFieldTipoPasaje jTextField1;
    // End of variables declaration//GEN-END:variables
    private Object[][] BoletosBA;
    private Vector TiposAsientos;
    private int TotalBoletos;
    private int Resultado=-1;
    private Object[] listadoC=null;
    private SesionVenta sesionVenta = null;
    private SimpleDateFormat formatoDate = new SimpleDateFormat("dd/MM/yyyy");
    private SimpleDateFormat formatoHour = new SimpleDateFormat("HH:mm");
    private boolean continuar=true;
    private JClsColoresInterfaz ColoresInterfaz = new JClsColoresInterfaz();

    private long ruta;
}
