/*
 * jDlgVentaBA.java
 *
 * Created on 10 de septiembre de 2007, 12:55 PM
 */

package DialogosX;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.Vector;
import subProcesos.JThdConsultaCorrida;
import tms_venta.JClsColoresInterfaz;
import tms_venta.SesionVenta;

/**
 *
 * @author  ocruz
 */
public class jDlgCtdPasTipoAsiento extends javax.swing.JDialog {
    
    /**
     * Creates new form jDlgVentaBA
     */
    public jDlgCtdPasTipoAsiento(SesionVenta pSesionVenta, String pNombreEmpresa, long pCorridaId, long pCapacidad,
                                 String aOrigen, String aDestino, long pThreadFechaHoraSistema,
                                 Object[] pUnaCorridaDeLista, JThdConsultaCorrida pjThreadConsultaCorridas, long pruta) {
        this.thFechaHoraSistema = pThreadFechaHoraSistema;
        this.jThreadConsultaCorridas = pjThreadConsultaCorridas;
        this.origen = aOrigen; this.destino = aDestino;
        this.nombreEmpresa = pNombreEmpresa;
        this.corridaId = pCorridaId;
        this.sesionVenta = pSesionVenta;
        this.Capacidad = pCapacidad;
        this.listadoCorridas = pUnaCorridaDeLista;
        this.ruta = pruta;
        
        initComponents();
        jLabel2.setText("<html><font color="+ColoresInterfaz.cHTML3+">ENTER</font> Aceptar | <font color="+ColoresInterfaz.cHTML3+">ESCAPE</font> Salir | <font color="+ColoresInterfaz.cHTML3+">F1</font> Nueva Consulta</html>");
        interfazColor();
        jTextField1.setTipos(sesionVenta.getCastTiposPasaje());
        jLabel2.setText("<html>"+getTiposPasajeVenta()+" | <font color=#"+ColoresInterfaz.cHTML3+">ENTER</font> Aceptar | <font color=#"+ColoresInterfaz.cHTML3+">ESCAPE</font> Salir | <font color=#"+ColoresInterfaz.cHTML3+">F1</font> Nueva Consulta</html>");
        TiposAsientos= new Vector();
        this.setTitle("Servicio sin numero de asiento");
        centrar();
    }
    
    private String getTiposPasajeVenta() {
        String cadena="";
        Vector cx = null;
        for(int i=0; i<sesionVenta.getCastTiposPasaje().size(); i++){
            cx = (Vector) sesionVenta.getCastTiposPasaje().get(i);
            if(cadena.indexOf(cx.get(1).toString())==-1)
                cadena = cadena + "<font color="+ColoresInterfaz.cHTML3+">"+cx.get(2).toString()+"</font> "+cx.get(1).toString()+" ";
        }
        //System.out.println("ya entro "+cadena);
        return cadena;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new paquete.JTxtFieldTipoPasaje();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setModal(true);
        setResizable(false);
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel3.setText("Ingrese cantidad y tipo pasajero");

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 10));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel2.setText("<html><font color=\"+ColoresInterfaz.cHTML1+\">ENTER</font> Aceptar | <font color=\"+ColoresInterfaz.cHTML1+\">ESCAPE</font> Salir | <font color=\"+ColoresInterfaz.cHTML1+\">F1</font> Nueva Consulta</html>");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 217, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
            .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE:
                this.Resultado=1;
            break;
            case KeyEvent.VK_F1:
                this.Resultado=2;
            break;
            case KeyEvent.VK_ENTER:
                if(!obtenerTipos(jTextField1.getText())){
                    jTextField1.setText("");
                    return;
                }
                
                if(sesionVenta.getUserCon().getAplicacionVenta()){
                    long f1=Long.valueOf(sesionVenta.obtenerFolioActual(this.nombreEmpresa)), f2=sesionVenta.obtenerFolioFinal(this.nombreEmpresa);
                    long f3=(f2-f1)+1;
                    if(this.TotalBoletos>f3){
                        this.getToolkit().beep();
                        DialogoAceptar.mostrarDialogo("Limite de folios.",
                                    "<html>No tiene boletos suficientes para vender los asientos.<br>" +
                                    f3+" folio(s) disponible(s).</html>", Color.RED);
                        jTextField1.setText("");
                        return;
                    }
                }
                
                if(OcuparAsientosAutomaticamente()==-1){
                    jTextField1.setText("");
                    this.Resultado = -1;
                    return;
                }
                this.DatosBoletoSinNumerodeAsiento();
                this.Resultado=0;
            break;
        }
        if(this.Resultado>-1)
            this.dispose();
    }//GEN-LAST:event_jTextField1KeyPressed

    private void centrar(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, ( screenSize.height - frameSize.height ) / 2 );
    }
    
    private boolean obtenerTipos(String txtDatos) {
        if(txtDatos.equals("")) return false;
        if(txtDatos.length()<2) return false;
        //TotalBoletos=fTotalBoletos(txtDatos);
        TiposAsientos.clear();
        String aux = txtDatos;
        boolean salida = true;
        long [] iasientos;
        int iTotalast = 0, i, n;
        char[] cTipo;
        if (aux.length() != 0) {
            String[] strTipoAsiento;
            strTipoAsiento = aux.split(" ");
            iasientos = new long[strTipoAsiento.length];
            cTipo = new char[strTipoAsiento.length];
            for (i = 0; i < strTipoAsiento.length; i++) {
                cTipo[i] = strTipoAsiento[i].charAt(strTipoAsiento[i].length() - 1);
                try{
                    if(strTipoAsiento[i].substring(0, strTipoAsiento[i].length() - 1)=="") iasientos[i]=1;
                    else iasientos[i] = Long.parseLong(strTipoAsiento[i].substring(0, strTipoAsiento[i].length() - 1));
                    iTotalast += (int)iasientos[i];
                }
                catch(NumberFormatException nfe){
                    return false;
                }
            }
            /*if (iTotalast > TotalBoletos) {
                salida = false;
            } else {*/
                for (n = 0; n < iasientos.length; n++) {
                    for (int t = 0; t < iasientos[n]; t++) {
                        TiposAsientos.add(cTipo[n]);
                    }
                }
            
            if(TiposAsientos.size()<1){ jTextField1.setText(""); return false; }
            
            for(n=0; n<TiposAsientos.size(); n++)
                if(Character.isDigit(TiposAsientos.get(n).toString().charAt(0))){jTextField1.setText(""); return false; }
            //}
        }

        this.TotalBoletos = iTotalast;
        return salida;
    }
    
    private boolean consultarUnaCorrida(){
        Object[] v = jThreadConsultaCorridas.getCorridaActual(true);
        if(v==null || v.length==0) return false;
        this.unaCorrida = new Object[64];
        for(int h=0; h<v.length; h++)
            this.unaCorrida[h]=v[h].toString();
        return true;
    }
    
    private int OcuparAsientosAutomaticamente(){
        if(!consultarUnaCorrida()) return -1;
        int ctlAsientos=5, i, noAsiento=0;
        for(i = 1; i < this.Capacidad+1; i++)
            if(this.unaCorrida[ctlAsientos+i].equals("D")) noAsiento++;
        
        if(noAsiento==0){
            this.Resultado = 1;
            this.getToolkit().beep();
            DialogoAceptar.mostrarDialogo("¡Cupo completo para esta corrida!","Presione Enter para regresar a corridas.", Color.RED);
            this.dispose();
            return -1;
        }
        if(noAsiento<this.TotalBoletos){
            this.Resultado = 1;
            this.getToolkit().beep();
            DialogoAceptar.mostrarDialogo("¡No hay suficientes asientos disponibles!","Esta corrida dispone de "+(noAsiento)+" asientos.", Color.RED);
            this.dispose();
            return -1;
        }
        BoletoAVender.clear();
        noAsiento=0;
        int cuantos=0;
        for(i = 1; i < this.Capacidad+1; i++){
            if(this.unaCorrida[ctlAsientos+i].equals("D")){
                BoletoAVender.addElement(i);
                noAsiento++;
            }
            if(this.TotalBoletos==noAsiento) break;
        }
        
        if(noAsiento==0 || noAsiento<this.TotalBoletos){
            this.Resultado = 1;
            this.getToolkit().beep();
            DialogoAceptar.mostrarDialogo("TMS Venta","No hay suficientes boletos disponibles.", Color.RED);
            this.dispose();
            return -1;
        }
        
        sesionVenta.armaCadenaAsientos(BoletoAVender);
        sesionVenta.armaCadenaTiposPasaje(TiposAsientos);
        // SI ESTAN DISPONIBLES, UTILIZAMOS SP PARA OCUPARLOS
        System.out.println("SP_Ocup "+this.corridaId+" - "+sesionVenta.getCadenaAsientos());
        int rSP=sesionVenta._OcuparAsientosSP(this.corridaId, sesionVenta.getCadenaAsientos(), null, "I","","","","", false);
        System.out.println("SP_Ocup "+rSP);
        if(rSP!=0){
            this.Resultado = 1;
            this.getToolkit().beep();
            if(rSP!=-1)
                DialogoAceptar.mostrarDialogo("TMS Venta","Se han ocupado asientos que usted eligio.", Color.RED);
            else
            {
                System.out.println("Registro ocupado en SP_Ocup...");
                DialogoAceptar.mostrarDialogo("TMS Venta.", "Registro ocupado",Color.RED);
            }
            return -1;
        }
        System.out.println("SP_Ocup Tipo "+sesionVenta.getCadenaTiposPasaje());
        rSP=sesionVenta._OcuparAsientosSP(this.corridaId, sesionVenta.getCadenaAsientos(), sesionVenta.getCadenaTiposPasaje(), "A","","","","", false);
        System.out.println("SP_TIPO "+rSP);
        if(rSP!=0){
            this.Resultado = 1;
            this.getToolkit().beep();
            if(rSP!=-1){
                DialogoAceptar.mostrarDialogo("TMS Venta","<html>Se han ocupado tipos de pasajero<br>que usted eligio.</html>", Color.RED);
                sesionVenta.iTempos=1;
                rSP=-1;
                while(rSP==-1){
                    rSP=sesionVenta._OcuparAsientosSP(this.corridaId, sesionVenta.getCadenaAsientos(), null, "E","","","","", false);
                    if(rSP==-1){            
                        sesionVenta.iTempos++;
                        if(sesionVenta.iTempos>sesionVenta.tTempos){
                            System.out.println("Asiento bloqueado.");
                            return -1;
                        }
                    }
                }
            }
            else
            {
                System.out.println("Registro ocupado en SP_TIPO...");
                DialogoAceptar.mostrarDialogo("TMS Venta.", "Registro ocupado",Color.RED);
//original                rSP=sesionVenta._OcuparAsientosSP(this.corridaId, sesionVenta.getCadenaAsientos(), sesionVenta.getCadenaTiposPasaje(), "P");
//primer intento                rSP=sesionVenta._OcuparAsientosSP(this.corridaId, sesionVenta.getCadenaAsientos(), null, "P");
                rSP=sesionVenta._OcuparAsientosSP(this.corridaId, sesionVenta.getCadenaAsientos(), null, "E","","","","", false);                
                   if(rSP==-1)
                      DialogoAceptar.mostrarDialogo("TMS Venta.", "<html>No fue posible liberar asiento o<br>tipo de pasajero.</html>",Color.RED);                
            }
            return -1;
        }
        //
        return 0;
    }
/************************************** BOLETO ABIERTO *********************************/
    private void DatosBoletoSinNumerodeAsiento(){
        long tipoId, tarifaid;
        double tTarifa = 0, tDescuento = 0, TTarifa=0;
        char tipop;
        double Tarifa = sesionVenta.getUserCon().getServicioTarifaSencillo(), suma=0;
        BoletosSNA = new Object[TotalBoletos][37];//[32]
        for (int i = 0; i < this.TotalBoletos; i++) {
            tipop = TiposAsientos.elementAt(i).toString().charAt(0);
            tipoId = jTextField1.getTipopasajeid(tipop,ruta);
            BoletosSNA[i][0] = this.listadoCorridas[0].toString().substring(0,10)+"-"+this.listadoCorridas[1];  // corrida-hora
            BoletosSNA[i][1] = BoletoAVender.get(i);                                   // asiento
            BoletosSNA[i][2] = TiposAsientos.elementAt(i).toString();                  // tipo pasajero
            BoletosSNA[i][3] = "";                                                     // nombre pasajero
            //BoletosSNA[i][4] = this.listadoCorridas[4]+"-"+this.listadoCorridas[5];    // origen-destino
            BoletosSNA[i][4] = origen+"-"+this.listadoCorridas[5];    // origen-destino
            tDescuento = jTextField1.getDescuento(tipoId);
            String redondeo =jTextField1.getRedondeo(tipoId);
            if(redondeo.equals("S"))
                TTarifa = Math.ceil(Tarifa - (tDescuento * Tarifa));
            else
            {
                TTarifa = Tarifa - (tDescuento * Tarifa);      
                double d = (TTarifa - (Double.valueOf(""+TTarifa).longValue()) );
                if(d > 0 && d != .50)                                
                    TTarifa =    Math.ceil(TTarifa);            
            }
            suma = suma+TTarifa;
            BoletosSNA[i][5] = TTarifa;                                                // importe boleto
            BoletosSNA[i][6] = "A";                                                    // BOLETO NORMAL + BOLETO ABIERTO
            BoletosSNA[i][7] = this.listadoCorridas[7];                                // empresa
            BoletosSNA[i][8] = this.listadoCorridas[3];                                // servicio
            BoletosSNA[i][9] = sesionVenta.getUserCon().getCaja();                     // caja
            BoletosSNA[i][10] = sesionVenta.getUserCon().getCorteId();                 // corte id
            BoletosSNA[i][11] = this.listadoCorridas[0];                               // clave corrida
            BoletosSNA[i][12] = null;                                                  // cliente id
            BoletosSNA[i][13] = null;                                                  // tipo pago
            BoletosSNA[i][14] = null;                                                  // referencia pago
            BoletosSNA[i][15] = "VT";                                                  // tipo operacion
            BoletosSNA[i][16] = null;                                                  // reservacion id
            BoletosSNA[i][17] = null;                                                  // boleto relacionado id
            BoletosSNA[i][18] = null;                                                  // dias validez boleto abierto
            if(sesionVenta.getUserCon().getAplicacionVenta())
                BoletosSNA[i][19] = sesionVenta.obtenerFolioActual(this.nombreEmpresa);    // folio preimpreso
            else
                BoletosSNA[i][19] = "000000";    // folio preimpreso
            BoletosSNA[i][20] = sesionVenta.getUserCon().getTerminalNombre();          // ciudad Venta
            BoletosSNA[i][21] = origen;                          // origen
            BoletosSNA[i][22] = (destino.equals("TODOS") ? this.listadoCorridas[5] : destino);                               // destino
            BoletosSNA[i][23] = "L";                                                   // tipo Transaccion
            BoletosSNA[i][24] = sesionVenta.getUserCon().getUsuarioNum();              // cajero
            BoletosSNA[i][25] = this.listadoCorridas[6];                               // corridaId
            BoletosSNA[i][26] = this.listadoCorridas[1];                               // fecha
            BoletosSNA[i][27] = this.listadoCorridas[2];                               // hora
            BoletosSNA[i][28] = sesionVenta.getUserCon().getSnAsiento();               // sin numero de asiento
            BoletosSNA[i][29] = "N";                                                   //Tipo de Venta (N = Normal, F = Referenciada)
            BoletosSNA[i][30] = "";                                                    //Nombre del cliente autorizado 
            BoletosSNA[i][31] = "S";                                                    //Nombre del cliente autorizado 
            
            
        }
        sesionVenta.setImporteVenta(suma);
    }
    
    public Object[][] getBoletos(){ return BoletosSNA; }
     
    public int getResultado(){ return Resultado; }
    
    public Vector getBoletoAVender() { return this.BoletoAVender; }
    
    public Vector getTiposAsientos() { return this.TiposAsientos; }

    private void interfazColor(){
        jPanel1.setBackground(ColoresInterfaz.cFondoDialogo);
        /*jLabel2.setOpaque(true);
        jLabel2.setBackground(ColoresInterfaz.cFondoPieEncabezado2);*/
        jLabel2.setForeground(ColoresInterfaz.cTextoAyuda1);
        
        jLabel3.setFont(ColoresInterfaz.fuente1);
        jTextField1.setFont(ColoresInterfaz.fuente1);
        jLabel2.setFont(ColoresInterfaz.fuente0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private paquete.JTxtFieldTipoPasaje jTextField1;
    // End of variables declaration//GEN-END:variables
    private Object[][] BoletosSNA;
    private int TotalBoletos;
    private int Resultado=-1;
    private SesionVenta sesionVenta = null;
    private long Capacidad;
    private Object[] listadoCorridas;
    private Object[] unaCorrida;
    private JDlgAceptar DialogoAceptar = new JDlgAceptar();
    private Vector BoletoAVender = new Vector();
    private Vector TiposAsientos = new Vector();
    private JDlgSiNo DialogoSiNo;
    private long corridaId;
    private String nombreEmpresa;
    private String origen, destino;
    private long thFechaHoraSistema;
    private JThdConsultaCorrida jThreadConsultaCorridas;
    private long ruta;
    private JClsColoresInterfaz ColoresInterfaz = new JClsColoresInterfaz();
}
