/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JIFReportesVenta.java
 *
 * Created on 21-sep-2011, 16:49:35
 */

package tmsreportes.gui;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRViewer;
import tmsreportes.entidad.Reporte;
import tmsreportes.reportes.GeneradorReportes;
import tmsreportes.solicitud.TmsReportesVBeanRemote;

/**
 *
 * @author jmendoza
 */
public class JIFReportesVenta extends javax.swing.JInternalFrame{

    //<editor-fold defaultstate="collapse" desc="CONSTRUCTORES">
    /**
     * Constructor por default
     */
    public JIFReportesVenta() {}

    /**
     * Constructor de la clase que inicializa la lista desplegable de los reportes
     * @param datosIniciales Vector que contiene los datos del usuario logueado
     */
    public JIFReportesVenta(Vector datosIniciales) {
        long menuId = Long.valueOf(datosIniciales.get(4).toString());
        this.trvb = lookupTmsReportesVBeanRemote();
        reportes = trvb.getReportes(menuId);
        if(reportes.isEmpty())
            mostrarMensaje("Su perfil no tiene reportes asociados, dirijase al administrador del sistema"
                + " para mayor información", "Información", JOptionPane.INFORMATION_MESSAGE);
        this.nombreTerminal = trvb.getNombreTerminal();
        initComponents();
        jCmbReportes.requestFocus();
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapse" desc="GETTERS Y SETTERS">
    /**
     * @return the reportes
     */
    public List<Reporte> getReportes() {
        return reportes;
    }

    /**
     * @param reportes the reportes to set
     */
    public void setReportes(List<Reporte> reportes) {
        this.reportes = reportes;
    }

    /**
     * @return the reporte
     */
    public String getReporte() {
        return reporte;
    }

    /**
     * @param reporte the reporte to set
     */
    public void setReporte(String reporte) {
        this.reporte = reporte;
    }

    /**
     * @return the fechas
     */
    public String[] getFechas() {
        return fechas;
    }

    /**
     * @param fechas the fechas to set
     */
    public void setFechas(String[] fechas) {
        this.fechas = fechas;
    }

    /**
     * @return the nombreReporte
     */
    public String getNombreTerminal() {
        return nombreTerminal;
    }

    /**
     * @param nombreReporte the nombreReporte to set
     */
    public void setNombreTerminal(String nombreTerminal) {
        this.nombreTerminal = nombreTerminal;
    }
    //</editor-fold>

    //<editor-fold defaultstate="collapse" desc="CÓDIGO GENERADO">
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPnlAcciones = new javax.swing.JPanel();
        jLblReportes = new javax.swing.JLabel();
        jCmbReportes = new javax.swing.JComboBox();
        jBtnGenerarReporte = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();
        jLblFechaCorte = new javax.swing.JLabel();
        jDtcFechaCorte = new tms_calendario.JDateChooser();
        jTbpReporte = new javax.swing.JTabbedPane();
        jPnlDescripcionEventos = new javax.swing.JPanel();
        jLblF10 = new javax.swing.JLabel();
        jLblGenerarReporte = new javax.swing.JLabel();
        jLblF4 = new javax.swing.JLabel();
        jLblSalir = new javax.swing.JLabel();
        jLblTeclasDireccion = new javax.swing.JLabel();
        jLblMoverse = new javax.swing.JLabel();

        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Visor de Reportes de Venta");
        setPreferredSize(new java.awt.Dimension(1080, 860));

        jPnlAcciones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLblReportes.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLblReportes.setText("Reporte:");

        org.jdesktop.beansbinding.ELProperty eLProperty = org.jdesktop.beansbinding.ELProperty.create("${reportes}");
        org.jdesktop.swingbinding.JComboBoxBinding jComboBoxBinding = org.jdesktop.swingbinding.SwingBindings.createJComboBoxBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, this, eLProperty, jCmbReportes);
        bindingGroup.addBinding(jComboBoxBinding);

        jCmbReportes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCmbReportesItemStateChanged(evt);
            }
        });
        jCmbReportes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jCmbReportesKeyReleased(evt);
            }
        });

        jBtnGenerarReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/document_edit.png"))); // NOI18N
        jBtnGenerarReporte.setMnemonic(KeyEvent.VK_G);
        jBtnGenerarReporte.setText("Generar Reporte");
        jBtnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGenerarReporteActionPerformed(evt);
            }
        });
        jBtnGenerarReporte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBtnGenerarReporteKeyReleased(evt);
            }
        });

        jBtnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/door_in.png"))); // NOI18N
        jBtnSalir.setMnemonic(KeyEvent.VK_S);
        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        jBtnSalir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jBtnSalirKeyReleased(evt);
            }
        });

        jLblFechaCorte.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLblFechaCorte.setText("Fecha de Corte:");

        jDtcFechaCorte.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDtcFechaCortePropertyChange(evt);
            }
        });
        jDtcFechaCorte.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jDtcFechaCorteKeyReleased(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPnlAccionesLayout = new org.jdesktop.layout.GroupLayout(jPnlAcciones);
        jPnlAcciones.setLayout(jPnlAccionesLayout);
        jPnlAccionesLayout.setHorizontalGroup(
            jPnlAccionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPnlAccionesLayout.createSequentialGroup()
                .add(18, 18, 18)
                .add(jPnlAccionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLblReportes)
                    .add(jLblFechaCorte))
                .add(21, 21, 21)
                .add(jPnlAccionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPnlAccionesLayout.createSequentialGroup()
                        .add(jCmbReportes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 218, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(30, 30, 30)
                        .add(jBtnGenerarReporte, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jBtnSalir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 158, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jDtcFechaCorte, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 218, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(340, Short.MAX_VALUE))
        );
        jPnlAccionesLayout.setVerticalGroup(
            jPnlAccionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPnlAccionesLayout.createSequentialGroup()
                .add(33, 33, 33)
                .add(jPnlAccionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPnlAccionesLayout.createSequentialGroup()
                        .add(5, 5, 5)
                        .add(jLblReportes))
                    .add(jPnlAccionesLayout.createSequentialGroup()
                        .add(2, 2, 2)
                        .add(jCmbReportes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jBtnGenerarReporte)
                    .add(jBtnSalir))
                .add(jPnlAccionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPnlAccionesLayout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(jLblFechaCorte))
                    .add(jPnlAccionesLayout.createSequentialGroup()
                        .add(14, 14, 14)
                        .add(jDtcFechaCorte, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        //jDtcFechaCorte.getDateEditor().addKeyListener1(new java.awt.event.KeyAdapter() {
            //    public void keyReleased(java.awt.event.KeyEvent evt) {
                //        jDtcFechaCorteKeyReleased(evt);
                //    }});

    jTbpReporte.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            jTbpReporteFocusGained(evt);
        }
    });
    jTbpReporte.addKeyListener(new java.awt.event.KeyAdapter() {
        public void keyReleased(java.awt.event.KeyEvent evt) {
            jTbpReporteKeyReleased(evt);
        }
    });

    jPnlDescripcionEventos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

    jLblF10.setFont(new java.awt.Font("Tahoma", 1, 11));
    jLblF10.setForeground(new java.awt.Color(204, 0, 51));
    jLblF10.setText("F10:");

    jLblGenerarReporte.setFont(new java.awt.Font("Tahoma", 1, 11));
    jLblGenerarReporte.setText("Generar Reporte");

    jLblF4.setFont(new java.awt.Font("Tahoma", 1, 11));
    jLblF4.setForeground(new java.awt.Color(204, 0, 51));
    jLblF4.setText("F4:");

    jLblSalir.setFont(new java.awt.Font("Tahoma", 1, 11));
    jLblSalir.setText("Salir");

    jLblTeclasDireccion.setFont(new java.awt.Font("Tahoma", 1, 11));
    jLblTeclasDireccion.setForeground(new java.awt.Color(204, 0, 51));
    jLblTeclasDireccion.setText("Teclas de dirección:");

    jLblMoverse.setFont(new java.awt.Font("Tahoma", 1, 11));
    jLblMoverse.setText("Moverse");

    org.jdesktop.layout.GroupLayout jPnlDescripcionEventosLayout = new org.jdesktop.layout.GroupLayout(jPnlDescripcionEventos);
    jPnlDescripcionEventos.setLayout(jPnlDescripcionEventosLayout);
    jPnlDescripcionEventosLayout.setHorizontalGroup(
        jPnlDescripcionEventosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(jPnlDescripcionEventosLayout.createSequentialGroup()
            .addContainerGap()
            .add(jLblF10)
            .add(18, 18, 18)
            .add(jLblGenerarReporte)
            .add(26, 26, 26)
            .add(jLblF4)
            .add(18, 18, 18)
            .add(jLblSalir)
            .add(28, 28, 28)
            .add(jLblTeclasDireccion)
            .add(18, 18, 18)
            .add(jLblMoverse)
            .addContainerGap(608, Short.MAX_VALUE))
    );
    jPnlDescripcionEventosLayout.setVerticalGroup(
        jPnlDescripcionEventosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(jPnlDescripcionEventosLayout.createSequentialGroup()
            .addContainerGap()
            .add(jPnlDescripcionEventosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLblF10)
                .add(jLblGenerarReporte)
                .add(jLblF4)
                .add(jLblSalir)
                .add(jLblTeclasDireccion)
                .add(jLblMoverse))
            .addContainerGap(29, Short.MAX_VALUE))
    );

    org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(layout.createSequentialGroup()
            .addContainerGap()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jTbpReporte, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1050, Short.MAX_VALUE)
                .add(jPnlAcciones, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPnlDescripcionEventos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addContainerGap())
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
        .add(layout.createSequentialGroup()
            .addContainerGap()
            .add(jPnlAcciones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
            .add(jTbpReporte, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 614, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jPnlDescripcionEventos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(18, Short.MAX_VALUE))
    );

    bindingGroup.bind();

    pack();
    }// </editor-fold>//GEN-END:initComponents
    //</editor-fold>

    //<editor-fold defaultstate="collapse" desc="EVENTOS">
    private void jCmbReportesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCmbReportesItemStateChanged
        Reporte r = (Reporte) jCmbReportes.getSelectedItem();
        setReporte(new GeneradorReportes().getNombreArchivoReporte(r.getReporteEjecutable()));
}//GEN-LAST:event_jCmbReportesItemStateChanged

    private void jBtnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGenerarReporteActionPerformed
        generarReporte();
}//GEN-LAST:event_jBtnGenerarReporteActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        this.dispose();
}//GEN-LAST:event_jBtnSalirActionPerformed

    private void jDtcFechaCortePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDtcFechaCortePropertyChange
        if(jDtcFechaCorte.getDate() != null){
            java.sql.Date sqlDate = new java.sql.Date(jDtcFechaCorte.getDate().getTime());
            setFechas(trvb.obtenerFechas(sqlDate));
        }
}//GEN-LAST:event_jDtcFechaCortePropertyChange

    private void jCmbReportesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCmbReportesKeyReleased
        identificarTeclaPresionada(evt.getKeyCode(), 1);
    }//GEN-LAST:event_jCmbReportesKeyReleased

    private void jBtnGenerarReporteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnGenerarReporteKeyReleased
        identificarTeclaPresionada(evt.getKeyCode(), 2);
    }//GEN-LAST:event_jBtnGenerarReporteKeyReleased

    private void jBtnSalirKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jBtnSalirKeyReleased
        identificarTeclaPresionada(evt.getKeyCode(), 3);
    }//GEN-LAST:event_jBtnSalirKeyReleased

    private void jDtcFechaCorteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDtcFechaCorteKeyReleased
        identificarTeclaPresionada(evt.getKeyCode(), 4);
    }//GEN-LAST:event_jDtcFechaCorteKeyReleased

    private void jTbpReporteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTbpReporteKeyReleased
        identificarTeclaPresionada(evt.getKeyCode(), 5);
    }//GEN-LAST:event_jTbpReporteKeyReleased

    private void jTbpReporteFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTbpReporteFocusGained
        jCmbReportes.requestFocus();
    }//GEN-LAST:event_jTbpReporteFocusGained

    
    //</editor-fold>

    //<editor-fold defaultstate="collapse" desc="OPERACIONES">
    /**
     * Método que muestra un mensaje en un JOptionPane
     * @param mensaje Mensaje a mostrar
     * @param titulo Título del mensaje
     * @param tipo Tipo de mensaje
     */
    private void mostrarMensaje(String mensaje, String titulo, int tipo) {
        JOptionPane.showMessageDialog(this, mensaje, titulo, tipo);
    }

    /**
     * Método que invoca a las clase que genera el reporte
     */
    private void generarReporte() {
        if(jCmbReportes.getSelectedIndex() == -1) {
            mostrarMensaje("Para generar un reporte debe seleccionar uno primero",
                    "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(jDtcFechaCorte.getDate() == null){
            mostrarMensaje("Seleccione una fecha para poder generar el reporte",
                    "Información", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(getFechas().length == 0) {
            mostrarMensaje("Hubo un error al generar el período de la fecha seleccionada, "
                    + "por favor, intente nuevamente",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        GeneradorReportes gr = new GeneradorReportes();
        boolean mostrar = gr.generarReporte(getReporte(), getFechas(), getNombreTerminal(),
                null);
        System.out.println("Generado reporte " + getReporte() +  ": " + mostrar + " . Páginas generadas: " + gr.getReporteJasper().getPages().size());
        if(mostrar) {
            try {
                agregarReporte(reporte, gr.getReporteJasper());
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else {
            mostrarMensaje("No hay datos que mostrar", "Información", JOptionPane.INFORMATION_MESSAGE);
            if(jTbpReporte.getTabCount() != 0)
                jTbpReporte.removeAll();
        }
    }

    /**
     * Método que agrega el reporte generado a la interfaz gráfica para mostrarlo
     * @param titulo Título del reporte
     * @param jasperP Instancia que contiene al reporte generado
     */
    public void agregarReporte(String titulo, JasperPrint jasperP) {
        jTbpReporte.removeAll();
        JRViewer v = new JRViewer(jasperP);
        v.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                identificarTeclaPresionada(evt.getKeyCode(), 7);
            }
        });
        jTbpReporte.addTab("  " + titulo.toUpperCase() + "  ", v);
        jTbpReporte.setSelectedIndex(jTbpReporte.getTabCount()-1);
    }

    /**
     * Método que obtiene el lookup del bean remoto
     * @return Una instancia del bean de sesión
     */
    private TmsReportesVBeanRemote lookupTmsReportesVBeanRemote() {
        try {
            Context c = new InitialContext();
            return (TmsReportesVBeanRemote) c.lookup("tmsreportes.solicitud.TmsReportesVBeanRemote");
        }
        catch(NamingException ne) {
            ne.printStackTrace();
            Logger.getLogger(getClass().getName()).log(Level.SEVERE,"exception caught" ,ne);
            throw new RuntimeException(ne);
        }
    }

    private void identificarTeclaPresionada(int evento, int componente) {
        //System.out.println("Evento: " + evento + " Componente: " + componente);
        if(evento == KeyEvent.VK_ENTER && (componente == 1 || componente == 4))
                jBtnGenerarReporteActionPerformed(null);
        else if(evento == KeyEvent.VK_LEFT) {
            switch(componente) {
                case 1:
                    jDtcFechaCorte.getDateEditor().setFoco();
                    break;
                case 2:
                    jCmbReportes.requestFocus();
                    break;
                case 3:
                    jBtnGenerarReporte.requestFocus();
                    break;
                case 4:
                    jBtnSalir.requestFocus();
                    break;
                case 5:
                    jCmbReportes.requestFocus();
                    break;
                default:
                    break;
            }
        } else if(evento == KeyEvent.VK_RIGHT) {
            switch(componente) {
                case 1:
                    jBtnGenerarReporte.requestFocus();
                    break;
                case 2:
                    jBtnSalir.requestFocus();
                    break;
                case 3:
                    jDtcFechaCorte.getDateEditor().setFoco();
                    break;
                case 4:
                    jCmbReportes.requestFocus();
                    break;
                case 5:
                    jCmbReportes.requestFocus();
                    break;
                default:
                    break;
            }
        } else if(evento == KeyEvent.VK_F10)
            jBtnGenerarReporteActionPerformed(null);
        else if(evento == KeyEvent.VK_F4)
            jBtnSalirActionPerformed(null);
//        else {
//            switch(componente) {
//                case 1:
//                    jBtnGenerarReporte.requestFocus();
//                    break;
//                case 2:
//                    jBtnSalir.requestFocus();
//                    break;
//                case 3:
//                    jDtcFechaCorte.getDateEditor().setFoco();
//                    break;
//                case 4:
//                    jCmbReportes.requestFocus();
//                    break;
//                case 5:
//                    jCmbReportes.requestFocus();
//                    break;
//                default:
//                    break;
//            }
//        }

    }
    //</editor-fold>

    //<editor-fold defaultstate="collapse" desc="COMPONENTES">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnGenerarReporte;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JComboBox jCmbReportes;
    private tms_calendario.JDateChooser jDtcFechaCorte;
    private javax.swing.JLabel jLblF10;
    private javax.swing.JLabel jLblF4;
    private javax.swing.JLabel jLblFechaCorte;
    private javax.swing.JLabel jLblGenerarReporte;
    private javax.swing.JLabel jLblMoverse;
    private javax.swing.JLabel jLblReportes;
    private javax.swing.JLabel jLblSalir;
    private javax.swing.JLabel jLblTeclasDireccion;
    private javax.swing.JPanel jPnlAcciones;
    private javax.swing.JPanel jPnlDescripcionEventos;
    private javax.swing.JTabbedPane jTbpReporte;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>

    //<editor-fold defaultstate="collapse" desc="VARIABLES">
    private List<Reporte> reportes;
    private String reporte;
    private String[] fechas;
    private String nombreTerminal;
    private TmsReportesVBeanRemote trvb;
    //</editor-fold>
}
