/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JFrameTextoDinamico.java
 *
 * Created on 21/09/2011, 07:01:07 PM
 */

package textomostrarcorridas;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author vgonzalez
 */
public class JFrameTextoDinamico extends javax.swing.JFrame implements ActionListener {
    private static Cliente cliente;
    Vector<String> nomUsers;
    /** Creates new form JFrameTextoDinamico */
    public JFrameTextoDinamico() throws IOException{
        initComponents();
        this.setTitle("Texto Dinamico .- Monitor de Corridas TMS");
        jtxt_Texto.addActionListener(this);
        jbtn_MostrarTexto.addActionListener(this);
        jbtn_Posisiconar.addActionListener(this);
             jtxtArea_AreaTexto.setEditable(false);
             jtxtArea_AreaTexto.setForeground(Color.BLUE);
             jtxtArea_AreaTexto.setBorder(javax.swing.BorderFactory.createMatteBorder(3,3,3,3,new Color(25,10,80)));
             setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
             cliente=new Cliente(this);
             cliente.conexion();
             nomUsers=new Vector();
             this.setSize(600,365);
             //ponerActivos(cliente.pedirUsuarios());
             jtxt_Texto.requestFocus();//pedir el focus
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtArea_AreaTexto = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jtxt_Texto = new tms_TextFields.JTextTextField();
        jbtn_MostrarTexto = new javax.swing.JButton();
        jbtn_Salir = new javax.swing.JButton();
        jbtn_Posisiconar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jtxtArea_AreaTexto.setColumns(20);
        jtxtArea_AreaTexto.setRows(5);
        jScrollPane1.setViewportView(jtxtArea_AreaTexto);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 450, 228);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Ingrese el Texto a Mostrar:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 260, 555, 15);
        getContentPane().add(jtxt_Texto);
        jtxt_Texto.setBounds(10, 290, 451, 20);

        jbtn_MostrarTexto.setFont(new java.awt.Font("Tahoma", 1, 11));
        jbtn_MostrarTexto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/textomostrarcorridas/resourse/aceptar.png"))); // NOI18N
        jbtn_MostrarTexto.setText("Enviar");
        jbtn_MostrarTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_MostrarTextoActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_MostrarTexto);
        jbtn_MostrarTexto.setBounds(470, 285, 100, 30);

        jbtn_Salir.setFont(new java.awt.Font("Tahoma", 1, 11));
        jbtn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/textomostrarcorridas/resourse/salir.png"))); // NOI18N
        jbtn_Salir.setText("Salir");
        jbtn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_Salir);
        jbtn_Salir.setBounds(470, 60, 110, 25);

        jbtn_Posisiconar.setFont(new java.awt.Font("Tahoma", 1, 11));
        jbtn_Posisiconar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/textomostrarcorridas/resourse/pos.png"))); // NOI18N
        jbtn_Posisiconar.setText("Posicion");
        jbtn_Posisiconar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_PosisiconarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtn_Posisiconar);
        jbtn_Posisiconar.setBounds(470, 30, 110, 25);

        jLabel2.setText("Rev.27.09.11");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(500, 0, 90, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_MostrarTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_MostrarTextoActionPerformed
        jtxt_Texto.setText("");
    }//GEN-LAST:event_jbtn_MostrarTextoActionPerformed

    private void jbtn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_SalirActionPerformed
            System.exit(0);
    }//GEN-LAST:event_jbtn_SalirActionPerformed

    private void jbtn_PosisiconarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_PosisiconarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_PosisiconarActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Cliente.IP_SERVER = JOptionPane.showInputDialog("Introducir DIRECCION_IP\n(donde se ejecuta la Aplicacion Monitor de Corridas)","");
                try {
                    JFrameTextoDinamico p = new JFrameTextoDinamico();
                    p.centrarDialogo();
                    p.setVisible(true);
                    if(!cliente.isExito())
                    {
                        JOptionPane.showMessageDialog(p, "¡No se encontro la aplicacion Monitor de Corridas!","Error de Conexion", JOptionPane.ERROR_MESSAGE);
                        System.exit(0);
                    }
                } catch (IOException ex) {
                    Logger.getLogger(JFrameTextoDinamico.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtn_MostrarTexto;
    private javax.swing.JButton jbtn_Posisiconar;
    private javax.swing.JButton jbtn_Salir;
    private javax.swing.JTextArea jtxtArea_AreaTexto;
    private tms_TextFields.JTextTextField jtxt_Texto;
    // End of variables declaration//GEN-END:variables

     public void setNombreUser(String user)
     {
       
     }    
     public void mostrarMsg(String msg)
     {
         if(msg.indexOf("posicionarVentana,")>=0)
         {
            String[] txt = msg.split(",");
            this.jtxtArea_AreaTexto.append("Se posicionó la pantalla en: X = "+txt[1] + " Y = "+txt[2]+"\n");
         }
        else
            this.jtxtArea_AreaTexto.append(msg+"\n");
     }
     public void agregarUser(String user)
     {
        nomUsers.add(user);
        //ponerDatosList(this.lstActivos,nomUsers);
     }    
    
    //@Override
    public void actionPerformed(ActionEvent evt) {
       String comand=(String)evt.getActionCommand();
       /*
        if(comand.compareTo("help")==0)
        {
                va=new VentanaAyuda();
                va.setVisible(true);
        }
       if(comand.compareTo("Acerca")==0)
       {
           JOptionPane.showMessageDialog(this,"XXXXX","Desarrollado por",JOptionPane.INFORMATION_MESSAGE);
       }
        *
        */
        if(evt.getSource()==this.jbtn_MostrarTexto || evt.getSource()==this.jtxt_Texto)
        {
           String mensaje = jtxt_Texto.getText();
           cliente.flujo(mensaje);
           jtxt_Texto.setText("");
        }
        if(evt.getSource()==this.jbtn_Posisiconar)
        {
            jdlgPosicionaMonitorCorridas d = new jdlgPosicionaMonitorCorridas(this,true);
            d.centrarDialogo();
            d.setVisible(true);
            if(d.isExito())
            {
               String mensaje = jtxt_Texto.getText();
               cliente.flujo("posicionarVentana,"+d.getX()+","+d.getY());
               jtxt_Texto.setText("");
            }
        }

     }

    public void centrarDialogo(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, ( screenSize.height - frameSize.height ) / 2 );
    }
}
