/*
 * JIF_PasesTraslado.java
 *
 * Created on 27 de enero de 2009, 10:01 AM
 */

package tmspases_traslado;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import solicitud.TMSPasesTrasladoFacadeRemote;

/**
 *
 * @author  asolis
 */
public class JIF_PasesTraslado extends javax.swing.JInternalFrame {
    Context cont = null;
    TMSPasesTrasladoFacadeRemote cosa = null;
    String datos [][] = null;
    String encabezados [] = {"Tramo Origen","Tramo Destino","Estado"};
    DefaultTableModel modelo = new DefaultTableModel(datos, encabezados);
    
    /** Creates new form JIF_PasesTraslado */
    public JIF_PasesTraslado() {
         try {
            cont = new InitialContext(System.getProperties());
            cosa = (TMSPasesTrasladoFacadeRemote) cont.lookup(TMSPasesTrasladoFacadeRemote.class.getName());
        } catch (NamingException ex) {
            ex.printStackTrace();
        }
        initComponents();
        jlbl_barraEstado.setText("<html>  <font color=FF0000>   F4</font> Salir de Pases de Traslado | <font color=FF0000>F3</font> Iniciar Búsqueda | <font color=FF0000> ARRIBA/ABAJO </font> Moverse entre Campos | <font color=FF0000>CTRL+2</font> Minimizar ventana | <font color=FF0000>CTRL+1</font> Mostrar siguiente ventana");  
        resizeColumnasCorridas();
        jtbl_tramos.setAutoResizeMode( JTable.AUTO_RESIZE_OFF );
        jntxt_operador.setBackground(new Color(192,190,207));
        jntxt_operador.requestFocus();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jlbl_operador = new javax.swing.JLabel();
        jlbl_autobus = new javax.swing.JLabel();
        jlbl_ruta = new javax.swing.JLabel();
        jntxt_operador = new tms_TextFields.JNumberTextField();
        jntxt_autobus = new tms_TextFields.JNumberTextField();
        jntxt_ruta = new tms_TextFields.JNumberTextField();
        jlbl_barraEstado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jlbl_diesel = new javax.swing.JLabel();
        jlbl_peaje = new javax.swing.JLabel();
        jlbl_sueldo = new javax.swing.JLabel();
        jctxt_diesel = new tms_TextFields.JCuantityTextField();
        jc_peaje = new tms_TextFields.JCuantityTextField();
        jctxt_sueldo = new tms_TextFields.JCuantityTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_tramos = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jlbl_nombreoperador = new javax.swing.JLabel();
        jtxt_nombreoperador = new tms_TextFields.JTextTextField();
        jlbl_origen = new javax.swing.JLabel();
        jtxt_origen = new javax.swing.JTextField();
        jlbl_destino = new javax.swing.JLabel();
        jlbl_servicio = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxt_destino = new javax.swing.JTextField();
        jtxt_servicio = new javax.swing.JTextField();

        setIconifiable(true);
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pases de Traslado");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jlbl_operador.setText("Clave de Operador: ");

        jlbl_autobus.setText("No. Econ\u00f3mico de Autob\u00fas: ");

        jlbl_ruta.setText("No. Ruta: ");

        jntxt_operador.setBackground(new java.awt.Color(255, 255, 204));
        jntxt_operador.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jntxt_operadorFocusLost(evt);
            }
        });
        jntxt_operador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jntxt_operadorKeyPressed(evt);
            }
        });

        jntxt_autobus.setBackground(new java.awt.Color(255, 255, 204));
        jntxt_autobus.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jntxt_autobusFocusLost(evt);
            }
        });
        jntxt_autobus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jntxt_autobusKeyPressed(evt);
            }
        });

        jntxt_ruta.setBackground(new java.awt.Color(255, 255, 204));
        jntxt_ruta.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jntxt_rutaFocusLost(evt);
            }
        });
        jntxt_ruta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jntxt_rutaKeyPressed(evt);
            }
        });

        jlbl_diesel.setFont(new java.awt.Font("Tahoma", 1, 11));
        jlbl_diesel.setText("Diesel: ");

        jlbl_peaje.setFont(new java.awt.Font("Tahoma", 1, 11));
        jlbl_peaje.setText("Peaje: ");

        jlbl_sueldo.setFont(new java.awt.Font("Tahoma", 1, 11));
        jlbl_sueldo.setText("Sueldo: ");

        jctxt_diesel.setEditable(false);

        jc_peaje.setEditable(false);

        jctxt_sueldo.setEditable(false);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jlbl_diesel)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jlbl_peaje)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jlbl_sueldo))
                .add(16, 16, 16)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jc_peaje, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .add(jctxt_diesel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                    .add(jctxt_sueldo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(22, 22, 22)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlbl_diesel)
                    .add(jctxt_diesel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlbl_peaje)
                    .add(jc_peaje, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlbl_sueldo)
                    .add(jctxt_sueldo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jtbl_tramos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtbl_tramos.setModel(modelo);
        jScrollPane1.setViewportView(jtbl_tramos);

        jlbl_nombreoperador.setText("Nombre del Operador:");

        jtxt_nombreoperador.setEditable(false);

        jlbl_origen.setText("Origen: ");

        jtxt_origen.setEditable(false);

        jlbl_destino.setText("Destino:");

        jlbl_servicio.setText("Servicio: ");

        jLabel5.setText("Tramos: ");

        jtxt_destino.setEditable(false);

        jtxt_servicio.setEditable(false);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jlbl_servicio)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel5)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jlbl_destino)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jlbl_origen)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jlbl_nombreoperador))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jtxt_origen, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .add(jtxt_nombreoperador, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .add(jtxt_destino, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                    .add(jtxt_servicio, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlbl_nombreoperador)
                    .add(jtxt_nombreoperador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlbl_origen)
                    .add(jtxt_origen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlbl_destino)
                    .add(jtxt_destino, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlbl_servicio)
                    .add(jtxt_servicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLabel5))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 372, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(498, Short.MAX_VALUE))
            .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 880, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jlbl_autobus)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jlbl_operador)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jlbl_ruta))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jntxt_ruta, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jntxt_autobus, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jntxt_operador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 175, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(556, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 471, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(269, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(30, 30, 30)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jntxt_operador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlbl_operador))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlbl_autobus)
                    .add(jntxt_autobus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlbl_ruta)
                    .add(jntxt_ruta, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(15, 15, 15)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 286, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 28, Short.MAX_VALUE)
                .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 22, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jntxt_rutaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jntxt_rutaFocusLost
        jntxt_ruta.setBackground(new Color(255,255,204));
    }//GEN-LAST:event_jntxt_rutaFocusLost

    private void jntxt_autobusFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jntxt_autobusFocusLost
        jntxt_autobus.setBackground(new Color(255,255,204));
    }//GEN-LAST:event_jntxt_autobusFocusLost

 
    private void jntxt_operadorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jntxt_operadorFocusLost
        jntxt_operador.setBackground(new Color(255,255,204));
    }//GEN-LAST:event_jntxt_operadorFocusLost

    private void jntxt_rutaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jntxt_rutaKeyPressed
        if(evt.getKeyCode() == evt.VK_DOWN){
            jntxt_operador.setBackground(new Color(192,190,207));
            jntxt_operador.requestFocus();
        }
        
        if(evt.getKeyCode() == evt.VK_UP){
            jntxt_autobus.setBackground(new Color(192,190,207));
            jntxt_autobus.requestFocus();
        }
        evento(evt);
    }//GEN-LAST:event_jntxt_rutaKeyPressed

    private void jntxt_autobusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jntxt_autobusKeyPressed
        if(evt.getKeyCode() == evt.VK_DOWN){
            jntxt_ruta.setBackground(new Color(192,190,207));
            jntxt_ruta.requestFocus();
        }
        
        if(evt.getKeyCode() == evt.VK_UP){
            jntxt_operador.setBackground(new Color(192,190,207));
            jntxt_operador.requestFocus();
        }
        evento(evt);
    }//GEN-LAST:event_jntxt_autobusKeyPressed

    private void jntxt_operadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jntxt_operadorKeyPressed
        if(evt.getKeyCode() == evt.VK_DOWN){
            jntxt_autobus.setBackground(new Color(192,190,207));
            jntxt_autobus.requestFocus();
        }
        
        if(evt.getKeyCode() == evt.VK_UP){
            jntxt_ruta.setBackground(new Color(192,190,207));
            jntxt_ruta.requestFocus();
        }
        evento(evt);
    }//GEN-LAST:event_jntxt_operadorKeyPressed
    
    public void resizeColumnasCorridas(){
        TableColumnModel columnModel = jtbl_tramos.getColumnModel();

           for (int col=0; col<jtbl_tramos.getColumnCount(); col++) 
           {
                int maxwidth = 0;            
                for (int row=0; row<jtbl_tramos.getRowCount(); row++) {
                    TableCellRenderer rend  = jtbl_tramos.getCellRenderer(row, col); 
                    Object value = jtbl_tramos.getValueAt (row, col); 
                    Component comp = rend.getTableCellRendererComponent (jtbl_tramos, value, false, false, row, col);
                    maxwidth = Math.max (comp.getPreferredSize().width, maxwidth); 
                } // for row

                TableColumn column = columnModel.getColumn (col);
                TableCellRenderer headerRenderer = column.getHeaderRenderer();
                if (headerRenderer == null)
                    headerRenderer = jtbl_tramos.getTableHeader().getDefaultRenderer();

                Object headerValue = column.getHeaderValue();
                Component headerComp = headerRenderer.getTableCellRendererComponent (jtbl_tramos, headerValue, false, false, 0, col);
                maxwidth = Math.max (maxwidth, headerComp.getPreferredSize().width);
                column.setPreferredWidth (maxwidth + 15);
           }
      }

    private void evento(KeyEvent evt) {
        if(evt.getKeyCode() == evt.VK_F3) {
            Vector muchos = new Vector();
            muchos = cosa.buscarDatosRuta(jntxt_ruta.getText());
            System.out.println("muchos "+muchos);
            if(muchos.size() > 0) {
                Vector uno = new Vector();
                System.out.println("muchos.size() "+muchos.size());
                for(int i  = 0; i < muchos.size(); i++) {
                    uno = (Vector) muchos.get(i);
                    System.out.println("UNO "+uno);
                    if(i == 0){
                        //Colocar informacion
                        Vector operador = new Vector();
                        operador = cosa.buscarOperador(jntxt_operador.getText());
                        jtxt_nombreoperador.setText(operador.get(14).toString());
                        jtxt_origen.setText(cosa.buscarNombreEstado(String.valueOf(uno.get(6))));
                        jtxt_destino.setText(cosa.buscarNombreEstado(String.valueOf(uno.get(7))));
                        jtxt_servicio.setText(cosa.buscarNombreEstado(String.valueOf(uno.get(1))));
                    }
                    //Buscar Tramos
                    
                }
            }else{
                JOptionPane.showMessageDialog( this, "No ese número de ruta",
                       "TMS - Pases de Traslado", JOptionPane.ERROR_MESSAGE );
            }
                
        }
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private tms_TextFields.JCuantityTextField jc_peaje;
    private tms_TextFields.JCuantityTextField jctxt_diesel;
    private tms_TextFields.JCuantityTextField jctxt_sueldo;
    private javax.swing.JLabel jlbl_autobus;
    private javax.swing.JLabel jlbl_barraEstado;
    private javax.swing.JLabel jlbl_destino;
    private javax.swing.JLabel jlbl_diesel;
    private javax.swing.JLabel jlbl_nombreoperador;
    private javax.swing.JLabel jlbl_operador;
    private javax.swing.JLabel jlbl_origen;
    private javax.swing.JLabel jlbl_peaje;
    private javax.swing.JLabel jlbl_ruta;
    private javax.swing.JLabel jlbl_servicio;
    private javax.swing.JLabel jlbl_sueldo;
    private tms_TextFields.JNumberTextField jntxt_autobus;
    private tms_TextFields.JNumberTextField jntxt_operador;
    private tms_TextFields.JNumberTextField jntxt_ruta;
    private javax.swing.JTable jtbl_tramos;
    private javax.swing.JTextField jtxt_destino;
    private tms_TextFields.JTextTextField jtxt_nombreoperador;
    private javax.swing.JTextField jtxt_origen;
    private javax.swing.JTextField jtxt_servicio;
    // End of variables declaration//GEN-END:variables
    
}
