/*
 * JDlgMotivoRefol.java
 *
 * Created on 17 de noviembre de 2007, 02:53 AM
 */

package AsignacionVenta;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Vector;
import tms_venta.JClsColoresInterfaz;
import tms_venta.SesionVenta;

/**
 *
 * @author  ocruz
 */
public class JDlgMotivoRefol extends javax.swing.JDialog {
    
    /** Creates new form JDlgMotivoRefol */
    public JDlgMotivoRefol(SesionVenta pSesionVenta) {
        this.setModal(true);
        this.sesionVenta = pSesionVenta;
        initComponents();
        jLabel1.setText("<html><font color="+ColoresInterfaz.cHTML3+">F12 </font>Boletos agotados</html>");
        jLabel2.setText("<html><font color="+ColoresInterfaz.cHTML3+">F11 </font>Error de impresion en la empresa: </html>");
        jLabel3.setText("<html><font color="+ColoresInterfaz.cHTML3+">ESC</font> Cancelar Refoliado</html>");
        interfazColor();
        for(int i=0; i<sesionVenta.getUserCon().getEmpresasConFolios().length; i++)
                jComboBox1.addItem(sesionVenta.getUserCon().getEmpresasConFolios()[i][1]);
        centrarDialogo();
    }
    
    public void centrarDialogo(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, ( screenSize.height - frameSize.height ) / 2 );
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Seleccione Tipo de Refoliado:");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("<html><font color=\"+ColoresInterfaz.cHTML1+\">F11 </font>Error de impresion en la empresa: </html>");
        jLabel2.setFocusable(false);

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jComboBox1.setFocusTraversalKeysEnabled(false);
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("<html><font color=\"+ColoresInterfaz.cHTML1+\">F12 </font>Boletos agotados</html>");
        jLabel1.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("<html><font color=\"+ColoresInterfaz.cHTML1+\">ESC</font> Cancelar Refoliado</html>");
        jLabel3.setFocusable(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jComboBox1, 0, 236, Short.MAX_VALUE)
                    .add(jLabel1)
                    .add(jLabel3))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
// TODO add your handling code here:
        jComboBox1.setSelectedItem(sesionVenta.getUserCon().getEmpresaPrincipal());
        jComboBox1.requestFocusInWindow();
    }//GEN-LAST:event_formComponentShown

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_F11:
                vEmpresas = new Vector();
                vEmpresas.add(jComboBox1.getSelectedItem());
                this.dispose();
                break;
            case KeyEvent.VK_F12:
                vEmpresas = new Vector();
                this.dispose();
                break;
            case KeyEvent.VK_ESCAPE:
                vEmpresas=null;
                this.dispose();
                break;
        }
    }//GEN-LAST:event_jComboBox1KeyPressed
    
    public Vector getEmpresas(){ return this.vEmpresas; }
    
    private void interfazColor(){
        setBackground(ColoresInterfaz.cFondoDialogo);
        /*jLabel1.setOpaque(true);
        jLabel1.setBackground(ColoresInterfaz.cFondoPieEncabezado2);*/
        jLabel1.setForeground(ColoresInterfaz.cTextoAyuda1);
        /*jLabel2.setOpaque(true);
        jLabel2.setBackground(ColoresInterfaz.cFondoPieEncabezado2);*/
        jLabel2.setForeground(ColoresInterfaz.cTextoAyuda1);
        /*jLabel3.setOpaque(true);
        jLabel3.setBackground(ColoresInterfaz.cFondoPieEncabezado2);*/
        jLabel3.setForeground(ColoresInterfaz.cTextoAyuda1);
        
        jLabel2.setFont(ColoresInterfaz.fuente0);
        jComboBox1.setFont(ColoresInterfaz.fuente0);
        jLabel1.setFont(ColoresInterfaz.fuente0);
        jLabel3.setFont(ColoresInterfaz.fuente0);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables

    private SesionVenta sesionVenta;
    private Vector vEmpresas;
    private JClsColoresInterfaz ColoresInterfaz = new JClsColoresInterfaz();
}
