/*
 * JDlgSysCboStandr.java
 *
 * Created on 23 de septiembre de 2008, 03:06 PM
 */

package xer_emv_dll;

import DialogosX.JDlgAceptar;
import DialogosX.JDlgSiNo;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.io.FileWriter;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import subProcesos.RelojVisualVta;
import tms_venta.JClsColoresInterfaz;
import tms_venta.SesionVenta;
import xer_emv_dll.Paneles.JPnlCN;
import xer_emv_dll.Paneles.JPnlQRY;
import xer_emv_dll.Paneles.JPnlRVou;
import xer_emv_dll.Paneles.JPnlVD;
import xer_emv_dll.Paneles.JPnlVDAMEX;
import xer_emv_dll.Paneles.JPnlVDM;

/**
 *
 * @author  ocruz
 */
public class JDlgSysCboStandr extends javax.swing.JDialog implements KeyListener{

    /** Creates new form JDlgSysCboStandr */
    public JDlgSysCboStandr(boolean[] pBtx, SesionVenta pSesionVenta, String pAMEXP, String pSalidaImpresion, String pAutorizacion, String pNumOperacion, boolean ejecutaFuncion, RelojVisualVta pThX, boolean pimprimeVoucher, double importeProductos){
        this.thX = pThX;
        this.xF = ejecutaFuncion;
        this.paramAutorizacion = pAutorizacion;
        this.paramNumOperacion = pNumOperacion;
        this.AMEXP = pAMEXP;
        this.sesionVenta = pSesionVenta;
        this.salidaImpresion = pSalidaImpresion;
        this.referencia = sesionVenta.getUserCon().getUsuarioNum()+""+new SimpleDateFormat("ddMMyyHHmmss").format(this.thX.getFecha().getTime());
        this.importe = "$"+sesionVenta.customFormat("##,##0.00",sesionVenta.getImporteVenta()+importeProductos);
        this.Amount = String.valueOf(sesionVenta.getImporteVenta()+importeProductos);
        this.imprimeVoucher = pimprimeVoucher;
        this.sesionVenta.setTipoTDC("");
        this.setModal(true);
        this.setTitle("TMS Venta.");
        initComponents();
        this.btx = pBtx;
        construyeMenu();
        interfazColor();
        centrarJDialog();
        this.enProceso = 0;
        jClsPinPadTBRequest = new JClsPinPadTBRequest();
        jClsPinPadTBResponse = new JClsPinPadTBResponse();
        if(realizaOperacion(_VD)) jPnlVD = new JPnlVD(this);
        if(realizaOperacion(_VDM)) jPnlVDM = new JPnlVDM(this);
        if(realizaOperacion(_CN)) {
            jPnlCN = new JPnlCN(this);
            if(ejecutaFuncion) paso1CN();
        }
        if(realizaOperacion(_VOU)) jPnlRVou = new JPnlRVou(this);
        if(realizaOperacion(_QRY)) jPnlQRY = new JPnlQRY(this);
        if(realizaOperacion(_VDAMEX)) jPnlVDAMEX = new JPnlVDAMEX(this);
        this.success = false;
        this.jPnlContenido.setVisible(true);
        this.jPnlContenedorCentral.requestFocusInWindow();
        if(btx[3])
        {
            ventaMoto_F5();
            //jPnlVDM.setFoco();
        }
    }
    
    private void centrarJDialog(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        //this.setSize(screenSize.width-24, screenSize.height-66);
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, (( screenSize.height - frameSize.height ) / 2)+22);
    }
    
    private void interfazColor(){
        this.setBackground(ColoresInterfaz.cFondoPieEncabezado);
        jPnlContenedorCentral.setBackground(ColoresInterfaz.cFondoPieEncabezado);
        jPnlContenido.setBackground(ColoresInterfaz.cFondoPieEncabezado);
        jLblTitulo.setBackground(ColoresInterfaz.cFondoPieEncabezado);
        jLblTitulo.setForeground(ColoresInterfaz.cTexto2);
        jLblTitulo.setFont(ColoresInterfaz.fuente4);
        jLblBarraEstado.setBackground(ColoresInterfaz.cFondoPieEncabezado);
        jLblBarraEstado.setForeground(ColoresInterfaz.cTextoAyuda1);
        jLblBarraEstado.setFont(ColoresInterfaz.fuente3);
        jLblRespuesta.setForeground(ColoresInterfaz.cTexto2);
        jLblRespuesta.setFont(ColoresInterfaz.fuente4);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblBarraEstado = new javax.swing.JLabel();
        jPnlContenedorCentral = new javax.swing.JPanel();
        jLblTitulo = new javax.swing.JLabel();
        jPnlContenido = new javax.swing.JPanel();
        jLblRespuesta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("TMS Venta.");
        setBackground(new java.awt.Color(0, 0, 153));
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLblBarraEstado.setFont(new java.awt.Font("Calibri", 1, 16));
        jLblBarraEstado.setText("<html>Linea1</html>");
        jLblBarraEstado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblBarraEstado.setMaximumSize(new java.awt.Dimension(2147483647, 32));
        jLblBarraEstado.addKeyListener(this);

        jPnlContenedorCentral.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPnlContenedorCentral.addKeyListener(this);

        jLblTitulo.setFont(new java.awt.Font("Calibri", 1, 18));
        jLblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblTitulo.setText(" ");

        jPnlContenido.addKeyListener(this);
        jPnlContenido.setLayout(null);

        jLblRespuesta.setFont(new java.awt.Font("Calibri", 1, 18));
        jLblRespuesta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblRespuesta.setText(" ");

        org.jdesktop.layout.GroupLayout jPnlContenedorCentralLayout = new org.jdesktop.layout.GroupLayout(jPnlContenedorCentral);
        jPnlContenedorCentral.setLayout(jPnlContenedorCentralLayout);
        jPnlContenedorCentralLayout.setHorizontalGroup(
            jPnlContenedorCentralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLblRespuesta, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
            .add(jPnlContenido, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
            .add(jLblTitulo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
        );
        jPnlContenedorCentralLayout.setVerticalGroup(
            jPnlContenedorCentralLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPnlContenedorCentralLayout.createSequentialGroup()
                .add(jLblTitulo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPnlContenido, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 167, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLblRespuesta))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPnlContenedorCentral, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jLblBarraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jPnlContenedorCentral, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLblBarraEstado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
// TODO add your handling code here:
       if(!btx[3])
           this.jPnlContenedorCentral.requestFocusInWindow();
    }//GEN-LAST:event_formComponentShown

    public void keyTyped(KeyEvent e) {
    }

    public void keyPressed(KeyEvent e) {
        switch(e.getKeyCode()){
            case KeyEvent.VK_F1:
                if(!activoF1)
                {
                System.out.println("Activa el F1");
                activoF1 = true;
                this.sesionVenta.setTipoTDC("SANTANDER");
                if(!realizaOperacion(_VD)) return;
                this.jLblTitulo.setText("VENTA DIRECTA "+importe);
                agregarPanel(jPnlVD);
                this.enProceso = 1;
                jLblBarraEstado.setText("<html><font color="+ColoresInterfaz.cHTML3+">Tecla <font color=ff0000>CAN</font> de PinPad</font> Cancelar Lectura</html>");
                jProgreso = new JDlgBProgreso(new JObsBProgreso(0, 1000),this);
                if(worker!=null) worker = null;
                this.setRespondio(false);
                this.sesionVenta.setTipoTDC("SANTANDER");
                worker = new SwingWorker() {
                    public Object construct() {
                        try {sesionVenta.TextOut = new FileWriter(sesionVenta.TextFile, true);} catch (IOException ex) {ex.printStackTrace();}
                        System.out.println("COBRO VENTA: "+sesionVenta.getUserCon().getCc_Type()+" - "+sesionVenta.getUserCon().getTx_MerchantP()+" - "+referencia+" - "+sesionVenta.getUserCon().getTx_OperationTypeP()+"  Company"+sesionVenta.getUserCon().getBs_Company()+"  user: "+sesionVenta.getUserCon().getBs_User()+"   Pwd: "+sesionVenta.getUserCon().getBs_Pwd());
                        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" COBRO VENTA: "+sesionVenta.getUserCon().getCc_Type()+" - "+sesionVenta.getUserCon().getTx_MerchantP()+" - "+referencia+" - "+sesionVenta.getUserCon().getTx_OperationTypeP()+"\n");} catch (IOException ex) {ex.printStackTrace();}
                        try{sesionVenta.TextOut.close();} catch (IOException ex) {ex.printStackTrace();}
                        jClsPinPadTBResponse=jClsPinPadTBRequest.getVentaDirecta(sesionVenta.getUserCon().getDbgSetUrl(),Amount,sesionVenta.getUserCon().getBs_User(),
                                                                                 sesionVenta.getUserCon().getBs_Pwd(),sesionVenta.getUserCon().getUsuarioNum(),
                                                                                 sesionVenta.getUserCon().getBs_Company(),sesionVenta.getUserCon().getBs_Branch(),
                                                                                 sesionVenta.getUserCon().getBs_Country(),sesionVenta.getUserCon().getCc_Type(),
                                                                                 sesionVenta.getUserCon().getTx_MerchantP(),referencia,sesionVenta.getUserCon().getTx_OperationTypeP(),
                                                                                 sesionVenta.getUserCon().getTx_Currency(),AMEXP);
                        System.out.println("SALI DE FUNCION NATIVA");
                        detenerProgreso();
                        setRespondio(true);
                        mostrarResultado(true);
                        limpiaProgreso();
                        System.out.println("Desactiva el F1 (Dentro del hilo)");
                        activoF1 = false;
                        return jClsPinPadTBResponse;
                    }
                };
                 //System.out.println("Desactiva el F1");
                 //activoF1 = false;
                }
                break;
            case KeyEvent.VK_F3:
                    if(!realizaOperacion(_VDAMEX)) return;
                    if(this.enProceso==0){
                        this.sesionVenta.setTipoTDC("AMEX");
                        this.jLblTitulo.setText("VENTA DIRECTA AMERICAN EXPRESS");
                        agregarPanel(jPnlVDAMEX);
                        jPnlVDAMEX.setAvisoVisible(false);
                        jPnlVDAMEX.setFoco();
                        this.enProceso = 31;
                        jLblBarraEstado.setText("<html><font color="+ColoresInterfaz.cHTML3+">F3</font> Realizar Venta Directa AMEX| <font color="+ColoresInterfaz.cHTML3+">ESC</font> Ir atras</html>");
                    }
                    else if(this.enProceso==31){
                        if(!valCamposAMEX()){
                            DialogoAceptar.mostrarDialogo("TMS Venta.", "Todos los campos son obligatorios.", Color.RED);
                            success=false;
                            return;
                        }
                        jPnlVDAMEX.setAvisoVisible(true);
                        this.enProceso = 3;
                        jLblBarraEstado.setText("<html><font color="+ColoresInterfaz.cHTML3+">Tecla <font color=ff0000>CAN</font> de PinPad</font> Cancelar Lectura</html>");
                        this.setRespondio(false);
                        jProgreso = new JDlgBProgreso(new JObsBProgreso(0, 1000),this);
                        this.sesionVenta.setTipoTDC("AMEX");
                        if(worker!=null) worker = null;
                        worker = new SwingWorker() {
                            public Object construct() {
                                System.out.println("COBRO AMEX: "+sesionVenta.getUserCon().getCc_TypeAMEX()+" - "+sesionVenta.getUserCon().getTx_MerchantAMEX()+" - "+referencia+" - "+sesionVenta.getUserCon().getTx_OperationTypeP());
                                jClsPinPadTBResponse=jClsPinPadTBRequest.getVentaDirecta(sesionVenta.getUserCon().getDbgSetUrl(),Amount,sesionVenta.getUserCon().getBs_User(),
                                                                                         sesionVenta.getUserCon().getBs_Pwd(),sesionVenta.getUserCon().getUsuarioNum(),
                                                                                         sesionVenta.getUserCon().getBs_Company(),sesionVenta.getUserCon().getBs_Branch(),
                                                                                         sesionVenta.getUserCon().getBs_Country(),
                                                                                         sesionVenta.getUserCon().getCc_TypeAMEX(),sesionVenta.getUserCon().getTx_MerchantAMEX(),
                                                                                         referencia,sesionVenta.getUserCon().getTx_OperationTypeP(),
                                                                                         sesionVenta.getUserCon().getTx_Currency(),jPnlVDAMEX.getCodigoSeguridad());
                                System.out.println("SALI DE FUNCION NATIVA");
                                detenerProgreso();
                                setRespondio(true);
                                mostrarResultado(true);
                                limpiaProgreso();
                                return jClsPinPadTBResponse;
                            }
                        };
                    }
                    break;
            case KeyEvent.VK_F4:
                if(!realizaOperacion(_CN)) return;
                if(this.enProceso==0){
                    paso1CN();
                }
                else if(this.enProceso==41){
                    if(!valCamposCN()){
                        DialogoAceptar.mostrarDialogo("TMS Venta.", "Todos los campos son obligatorios.", Color.RED);
                        success=false;
                        return;
                    }
                    this.enProceso = 4;
                    jLblBarraEstado.setText(" ");
                    this.setRespondio(false);
                    jProgreso = new JDlgBProgreso(new JObsBProgreso(0, 1000),this);
                    if(worker!=null) worker = null;
                    worker = new SwingWorker() {
                        public Object construct(){
                            jClsPinPadTBResponse=jClsPinPadTBRequest.getCancelacion(sesionVenta.getUserCon().getDbgSetUrl(),Amount,sesionVenta.getUserCon().getBs_User(),
                                                                                    sesionVenta.getUserCon().getBs_Pwd(),sesionVenta.getUserCon().getUsuarioNum(),sesionVenta.getUserCon().getBs_Company(),
                                                                                    sesionVenta.getUserCon().getBs_Branch(),sesionVenta.getUserCon().getBs_Country(),jPnlCN.getNumeroOperacion(),jPnlCN.getAutorizacion());
                            System.out.println("SALI DE FUNCION NATIVA");
                            detenerProgreso();
                            setRespondio(true);
                            mostrarResultado(true);
                            limpiaProgreso();
                            return jClsPinPadTBResponse;
                        }
                    };
                }
                break;
            case KeyEvent.VK_F5:
//                if(!realizaOperacion(_VDM)) return;
//                if(this.enProceso==0){
//                    this.jLblTitulo.setText("VENTA DIRECTA MOTO "+importe);
//                    agregarPanel(jPnlVDM);
//                    jPnlVDM.setFoco();
//                    this.enProceso = 51;
//                    jLblBarraEstado.setText("<html><font color="+ColoresInterfaz.cHTML3+">F5</font> Realizar Venta Directa MOTO | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Ir atras</html>");
//                }
//                else if(this.enProceso==51){
//                    if(!valCamposVDM()){
//                        DialogoAceptar.mostrarDialogo("TMS Venta.", "Todos los campos son obligatorios.", Color.RED);
//                        success=false;
//                        return;
//                    }
//                    this.enProceso = 5;
//                    jLblBarraEstado.setText(" ");
//                    jProgreso = new JDlgBProgreso(new JObsBProgreso(0, 1000),this);
//                    if(worker!=null) worker = null;
//                    worker = new SwingWorker() {
//                        public Object construct() {
//                            jClsPinPadTBResponse=jClsPinPadTBRequest.getVentaDirectaMOTO(sesionVenta.getUserCon().getDbgSetUrl(),Amount,sesionVenta.getUserCon().getBs_User(),
//                                                                                         sesionVenta.getUserCon().getBs_Pwd(),sesionVenta.getUserCon().getUsuarioNum(),sesionVenta.getUserCon().getBs_Company(),
//                                                                                         sesionVenta.getUserCon().getBs_Branch(),sesionVenta.getUserCon().getBs_Country(),sesionVenta.getUserCon().getCc_Type(),
//                                                                                         jPnlVDM.getNombreTH(), jPnlVDM.getNumeroTarjeta(), jPnlVDM.getMes(), jPnlVDM.getAnio(), jPnlVDM.getCodigoSeg(),
//                                                                                         sesionVenta.getUserCon().getTx_MerchantS(),referencia,sesionVenta.getUserCon().getTx_OperationTypeS(),sesionVenta.getUserCon().getTx_Currency());
//                            System.out.println("SALI DE FUNCION NATIVA");
//                            detenerProgreso();
//                            mostrarResultado(true);
//                            limpiaProgreso();
//                            return jClsPinPadTBResponse;
//                        }
//                    };
//                }
                ventaMoto_F5();
                break;
            case KeyEvent.VK_F7:
                if(!realizaOperacion(_VOU)) return;
                if(this.enProceso==0){
                    this.jLblTitulo.setText("REIMPRIMIR VOUCHER");
                    agregarPanel(jPnlRVou);
                    jPnlRVou.setFoco();
                    this.enProceso = 71;
                    jLblBarraEstado.setText("<html><font color="+ColoresInterfaz.cHTML3+">F7</font> Reimprimir Voucher | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Ir atras</html>");
                }
                else if(this.enProceso==71){
                    if(!valCamposRVou()){
                        DialogoAceptar.mostrarDialogo("TMS Venta.", "Todos los campos son obligatorios.", Color.RED);
                        success=false;
                        return;
                    }
                    this.enProceso = 7;
                    jLblBarraEstado.setText(" ");
                    this.setRespondio(false);
                    jProgreso = new JDlgBProgreso(new JObsBProgreso(0, 1000),this);
                    if(worker!=null) worker = null;
                    worker = new SwingWorker() {
                        public Object construct(){
                            jClsPinPadTBResponse=jClsPinPadTBRequest.getReimpresionVoucher(sesionVenta.getUserCon().getDbgSetUrl(),Amount,sesionVenta.getUserCon().getBs_User(),
                                                                                           sesionVenta.getUserCon().getBs_Pwd(),sesionVenta.getUserCon().getUsuarioNum(),sesionVenta.getUserCon().getBs_Company(),
                                                                                           sesionVenta.getUserCon().getBs_Branch(),sesionVenta.getUserCon().getBs_Country(),jPnlRVou.getNumeroOperacion());
                            System.out.println("SALI DE FUNCION NATIVA");
                            detenerProgreso();
                            setRespondio(true);
                            mostrarResultado(true);
                            limpiaProgreso();
                            return jClsPinPadTBResponse;
                        }
                    };
                }
                break;
            case KeyEvent.VK_F9:
                    if(!realizaOperacion(_QRY)) return;
                    if(this.enProceso==0){
                        this.jLblTitulo.setText("CONSULTA");
                        agregarPanel(jPnlQRY);
                        jPnlQRY.setFoco();
                        this.enProceso = 91;
                        jLblBarraEstado.setText("<html><font color="+ColoresInterfaz.cHTML3+">F9</font> Consultar | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Ir atras</html>");
                    }
                    else if(this.enProceso==91){
                        if(!valCamposQRY()){
                            DialogoAceptar.mostrarDialogo("TMS Venta.", "Todos los campos son obligatorios.", Color.RED);
                            success=false;
                            return;
                        }
                        this.enProceso = 9;
                        jLblBarraEstado.setText(" ");
                        this.setRespondio(false);
                        jProgreso = new JDlgBProgreso(new JObsBProgreso(0, 1000),this);
                        if(worker!=null) worker = null;
                        worker = new SwingWorker() {
                            public Object construct(){
                                jClsPinPadTBResponse=jClsPinPadTBRequest.getConsulta(sesionVenta.getUserCon().getDbgSetUrl(),Amount,sesionVenta.getUserCon().getBs_User(),
                                                                                     sesionVenta.getUserCon().getBs_Pwd(),sesionVenta.getUserCon().getBs_Company(),
                                                                                     sesionVenta.getUserCon().getBs_Branch(),jPnlQRY.getReferencia(),jPnlQRY.getFecha());
                                System.out.println("SALI DE FUNCION NATIVA");
                                detenerProgreso();
                                setRespondio(true);
                                mostrarResultado(false);
                                limpiaProgreso();
                                return jClsPinPadTBResponse;
                            }
                        };
                    }
                    break;
                case KeyEvent.VK_ESCAPE:
                    this.success = false;
                    this.sesionVenta.setTipoTDC("");
                    switch(enProceso){
                        case 0: if(worker!=null) worker = null; this.dispose(); break;
                        case 31: case 51: case 71: case 91: limpiaProgreso(); break;
                        case 41:
                            if(this.xF){
                                if(worker!=null) worker = null;
                                this.dispose();
                            }
                            break;
                    }
                    break;
        }
    }

    public void ventaMoto_F5(){
                 if(!realizaOperacion(_VDM)) return;
                if(this.enProceso==0){
                     System.out.println("Entra a venta moto");
                    this.jLblTitulo.setText("VENTA DIRECTA MOTO "+importe);
                    agregarPanel(jPnlVDM);
                    this.enProceso = 51;
                    jLblBarraEstado.setText("<html><font color="+ColoresInterfaz.cHTML3+">F5</font> Realizar Venta Directa MOTO | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Ir atras</html>");
                    jPnlVDM.setFoco();
                }
                else if(this.enProceso==51){
                    if(!valCamposVDM()){
                        success=false;
                        return;
                    }
                    this.enProceso = 5;
                    jLblBarraEstado.setText(" ");
                    this.setRespondio(false);
                    jProgreso = new JDlgBProgreso(new JObsBProgreso(0, 1000),this);
                    if(worker!=null) worker = null;
                    System.out.println("getBs_Branch= "+sesionVenta.getUserCon().getBs_Branch());
                    System.out.println("getTx_OperationTypeS= "+sesionVenta.getUserCon().getTx_OperationTypeS());
                    System.out.println("getCc_Type= "+sesionVenta.getUserCon().getCc_Type());
                    if(!american)
                    {
                        this.sesionVenta.setTipoTDC("SANTANDER");
                        worker = new SwingWorker() {
                            public Object construct() {
                                jClsPinPadTBResponse=jClsPinPadTBRequest.getVentaDirectaMOTO(sesionVenta.getUserCon().getDbgSetUrl(),Amount,sesionVenta.getUserCon().getBs_User(),
                                                                                             sesionVenta.getUserCon().getBs_Pwd(),sesionVenta.getUserCon().getUsuarioNum(),sesionVenta.getUserCon().getBs_Company(),
                                                                                             sesionVenta.getUserCon().getBs_Branch(),sesionVenta.getUserCon().getBs_Country(),sesionVenta.getUserCon().getCc_Type(),
                                                                                             jPnlVDM.getNombreTH(), jPnlVDM.getNumeroTarjeta(), jPnlVDM.getMes(), jPnlVDM.getAnio(), jPnlVDM.getCodigoSeg(),
                                                                                             sesionVenta.getUserCon().getTx_MerchantS(),referencia,sesionVenta.getUserCon().getTx_OperationTypeS(),sesionVenta.getUserCon().getTx_Currency());
                                System.out.println("SALI DE FUNCION NATIVA");
                                detenerProgreso();
                                setRespondio(true);
                                mostrarResultado(true);
                                limpiaProgreso();
                                return jClsPinPadTBResponse;
                            }   
                        };
                    }
                    else
                    {
                        this.sesionVenta.setTipoTDC("AMEX");
                        worker = new SwingWorker() {
                            public Object construct() {
                                jClsPinPadTBResponse=jClsPinPadTBRequest.getVentaDirectaMOTO(sesionVenta.getUserCon().getDbgSetUrl(),Amount,sesionVenta.getUserCon().getBs_User(),
                                                                                             sesionVenta.getUserCon().getBs_Pwd(),sesionVenta.getUserCon().getUsuarioNum(),sesionVenta.getUserCon().getBs_Company(),
                                                                                             sesionVenta.getUserCon().getBs_Branch(),sesionVenta.getUserCon().getBs_Country(),sesionVenta.getUserCon().getCc_TypeAMEX(),
                                                                                             jPnlVDM.getNombreTH(), jPnlVDM.getNumeroTarjeta(), jPnlVDM.getMes(), jPnlVDM.getAnio(), jPnlVDM.getCodigoSeg(),
                                                                                             sesionVenta.getUserCon().getTx_MerchantAMEXMOTO(),referencia,sesionVenta.getUserCon().getTx_OperationTypeS(),sesionVenta.getUserCon().getTx_Currency());
                                System.out.println("SALI DE FUNCION NATIVA");
                                detenerProgreso();
                                mostrarResultado(true);
                                limpiaProgreso();
                                return jClsPinPadTBResponse;
                            }   
                        };
                    }
                        
                }
    }
    
    public void keyReleased(KeyEvent e) {
        
    }
  
    private void construyeMenu(){
        cadenaMenu = "<html>";
        if(realizaOperacion(_VD))
            cadenaMenu += "<font color="+ColoresInterfaz.cHTML3+">F1</font> Venta Directa | ";
        if(realizaOperacion(_VDAMEX))
            cadenaMenu += "<font color="+ColoresInterfaz.cHTML3+">F3</font> Venta Directa AMEX | ";
        if(realizaOperacion(_CN))
            cadenaMenu += "<font color="+ColoresInterfaz.cHTML3+">F4</font> Cancelacion | ";
        if(realizaOperacion(_VDM))
            cadenaMenu += "<font color="+ColoresInterfaz.cHTML3+">F5</font> Venta Directa MOTO | ";
        if(realizaOperacion(_VOU))
            cadenaMenu += "<font color="+ColoresInterfaz.cHTML3+">F7</font> Reimpresion de Voucher | ";
        if(realizaOperacion(_QRY))
            cadenaMenu += "<font color="+ColoresInterfaz.cHTML3+">F9</font> Consulta | ";
        cadenaMenu += "<font color="+ColoresInterfaz.cHTML3+">ESC</font> Salir</html>";
        jLblBarraEstado.setText(cadenaMenu);
    }
    
    boolean realizaOperacion(int i){ return this.btx[i]; }

    private void agregarPanel(javax.swing.JPanel pane1) {
        this.jPnlContenido.setLayout(null);
        pane1.setBounds(0,0,this.jPnlContenido.getWidth(),this.jPnlContenido.getHeight());
        this.jPnlContenido.add(pane1);
        this.getContentPane().repaint();
    }
    
    private void detenerProgreso(){
        if(jProgreso!=null){
            jProgreso.finaliza();
            jProgreso = null;
        }
    }
    
    public void limpiaProgreso() {
        limpiaCampos();
        jPnlContenido.removeAll();
        this.jPnlContenido.setLayout(null);
        this.getContentPane().repaint();
        enProceso=0;
        jLblTitulo.setText("");
        jLblRespuesta.setText("");
        jLblBarraEstado.setText(cadenaMenu);
        this.jPnlContenedorCentral.requestFocusInWindow();
    }
    
    private void limpiaCampos(){
        if(jPnlVDM != null){
            jPnlVDM.setNombreTH("");
            jPnlVDM.setNumeroTarjeta("");
            jPnlVDM.setMes("");
            jPnlVDM.setAnio("");
            jPnlVDM.setCodigoSeg("");
        }
        if(jPnlCN != null){
            jPnlCN.setNumeroOperacion("");
            jPnlCN.setAutorizacion("");
        }
        if(jPnlRVou != null) jPnlRVou.setNumeroOperacion("");
    }
    
    private void imprimirCamposResultado(){
        try {sesionVenta.TextOut = new FileWriter(sesionVenta.TextFile, true);} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getCc_ExpMonth(): "+jClsPinPadTBResponse.getCc_ExpMonth());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getCc_ExpMonth(): "+jClsPinPadTBResponse.getCc_ExpMonth()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getCc_ExpYear(): "+jClsPinPadTBResponse.getCc_ExpYear());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getCc_ExpYear(): "+jClsPinPadTBResponse.getCc_ExpYear()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getCc_Name(): "+jClsPinPadTBResponse.getCc_Name());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getCc_Name(): "+jClsPinPadTBResponse.getCc_Name()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getCc_Number(): "+jClsPinPadTBResponse.getCc_Number());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getCc_Number(): "+jClsPinPadTBResponse.getCc_Number()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getCc_Type(): "+jClsPinPadTBResponse.getCc_Type());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getCc_Type(): "+jClsPinPadTBResponse.getCc_Type()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getRspAuth(): "+jClsPinPadTBResponse.getRspAuth());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getRspAuth(): "+jClsPinPadTBResponse.getRspAuth()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getRspCdError(): "+jClsPinPadTBResponse.getRspCdError());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getRspCdError(): "+jClsPinPadTBResponse.getRspCdError()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getRspCdResponse(): "+jClsPinPadTBResponse.getRspCdResponse());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getRspCdResponse(): "+jClsPinPadTBResponse.getRspCdResponse()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getRspDate(): "+jClsPinPadTBResponse.getRspDate());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getRspDate(): "+jClsPinPadTBResponse.getRspDate()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getRspDsAdress(): "+jClsPinPadTBResponse.getRspDsAdress());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getRspDsAdress(): "+jClsPinPadTBResponse.getRspDsAdress()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getRspDsCompany(): "+jClsPinPadTBResponse.getRspDsCompany());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getRspDsCompany(): "+jClsPinPadTBResponse.getRspDsCompany()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getRspDsError(): "+jClsPinPadTBResponse.getRspDsError());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getRspDsError(): "+jClsPinPadTBResponse.getRspDsError()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getRspDsMerchant(): "+jClsPinPadTBResponse.getRspDsMerchant());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getRspDsMerchant(): "+jClsPinPadTBResponse.getRspDsMerchant()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getRspDsOperationType(): "+jClsPinPadTBResponse.getRspDsOperationType());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getRspDsOperationType(): "+jClsPinPadTBResponse.getRspDsOperationType()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getRspDsResponse(): "+jClsPinPadTBResponse.getRspDsResponse());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getRspDsResponse(): "+jClsPinPadTBResponse.getRspDsResponse()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getRspOperationNumber(): "+jClsPinPadTBResponse.getRspOperationNumber());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getRspOperationNumber(): "+jClsPinPadTBResponse.getRspOperationNumber()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getRspTime(): "+jClsPinPadTBResponse.getRspTime());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getRspTime(): "+jClsPinPadTBResponse.getRspTime()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getRspVoucher(): "+jClsPinPadTBResponse.getRspVoucher());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getRspVoucher(): "+jClsPinPadTBResponse.getRspVoucher()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getRspXML(): "+jClsPinPadTBResponse.getRspXML());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getRspXML(): "+jClsPinPadTBResponse.getRspXML()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getTx_Amount(): "+jClsPinPadTBResponse.getTx_Amount());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getTx_Amount(): "+jClsPinPadTBResponse.getTx_Amount()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getTx_Reference(): "+jClsPinPadTBResponse.getTx_Reference());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getTx_Reference(): "+jClsPinPadTBResponse.getTx_Reference()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getRspQryRePrint(): "+jClsPinPadTBResponse.getRspQryRePrint());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getRspQryRePrint(): "+jClsPinPadTBResponse.getRspQryRePrint()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getRspVoucherCliente(): "+jClsPinPadTBResponse.getRspVoucherCliente());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getRspQryRePrint(): "+jClsPinPadTBResponse.getRspQryRePrint()+"\n");} catch (IOException ex) {ex.printStackTrace();}
        System.out.println("jClsPinPadTBResponse.getRspVoucherComercio(): "+jClsPinPadTBResponse.getRspVoucherComercio());
        try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" jClsPinPadTBResponse.getRspQryRePrint(): "+jClsPinPadTBResponse.getRspQryRePrint()+"\n");} catch (IOException ex) {ex.printStackTrace();}
         try{sesionVenta.TextOut.close();} catch (IOException ex) {ex.printStackTrace();}
    }
    
    private void mostrarResultado(boolean imprimible){
        imprimirCamposResultado();
        JClsReadStringXML x = null;
        String stTxXML = null;
        String stTx = jClsPinPadTBResponse.getRspDsResponse();
            try {sesionVenta.TextOut = new FileWriter(sesionVenta.TextFile, true);} catch (IOException ex) {ex.printStackTrace();}
            try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" imprimible: "+imprimible+"\n");} catch (IOException ex) {ex.printStackTrace();}
            try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" stTx: "+stTx+"\n");} catch (IOException ex) {ex.printStackTrace();}
            try{sesionVenta.TextOut.close();} catch (IOException ex) {ex.printStackTrace();}
        if(!imprimible){
            x = new JClsReadStringXML();
            stTxXML = jClsPinPadTBResponse.getRspQryRePrint().replace("<transaccionesCautM></transaccionesCautM>","");
            stTxXML = stTxXML.replaceAll("&","");
            String valor = x.getValorNodo(stTxXML,"nb_response","");
            System.out.println(valor);
            try {sesionVenta.TextOut = new FileWriter(sesionVenta.TextFile, true);} catch (IOException ex) {ex.printStackTrace();}
            try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" "+valor+"\n");} catch (IOException ex) {ex.printStackTrace();}
            try{sesionVenta.TextOut.close();} catch (IOException ex) {ex.printStackTrace();}
            if(stTxXML!=null) stTx = valor;
        }
            try {sesionVenta.TextOut = new FileWriter(sesionVenta.TextFile, true);} catch (IOException ex) {ex.printStackTrace();}
            try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" stTx(2): "+stTx+"\n");} catch (IOException ex) {ex.printStackTrace();}
            try{sesionVenta.TextOut.close();} catch (IOException ex) {ex.printStackTrace();}

        String msg = "<html>";
        if(stTx.equals("approved")){
            if(!imprimible){
                System.out.println("XML "+jClsPinPadTBResponse.getRspXML());
                System.out.println("XML "+jClsPinPadTBResponse.getRspQryRePrint());
                msg += "Transaccion APROBADA.<br>";
                msg += x.getValorNodo(stTxXML,"cc_nombre","");
                msg += "</html>";
                DialogoAceptar.mostrarDialogo("TMS Venta.", msg, Color.RED);
                success=true;
                if(worker!=null) worker = null;
                this.dispose();
                return;
            }
            JClsImprimeVoucher jClsImprimeVoucher = new JClsImprimeVoucher();
            if (imprimeVoucher)
            {
                String vou = "";
                if(sesionVenta.isActivoEMVFull())
                {
                    try{
                        if(sesionVenta.isImpVouComercio())
                            vou = jClsPinPadTBResponse.getRspVoucherComercio()+"\n@br  \n@br  "+jClsPinPadTBResponse.getRspVoucherCliente();
                        else
                            vou = jClsPinPadTBResponse.getRspVoucherCliente()+"\n@br  \n@br  ";
                    } catch (Exception e)
                    {e.printStackTrace(); DialogoAceptar.mostrarDialogo("¡Configuracion EMV Full!", "¡La DLL del EVM Full no esta configurada!\n Contacte al Administrador del Sistema", Color.RED);}
                }
                else
                    vou = jClsPinPadTBResponse.getRspVoucher();
                jClsImprimeVoucher.ImprimeDatos(vou, salidaImpresion, 0,"","",sesionVenta.getImpresoraNombreVoucherBlanco(), sesionVenta.isVoucherBlanco());
                //VAGL 14092011 Se manda a llamar dos metodos en lugar de unos solo para imprimir el voucher
                //jClsImprimeVoucher.ImprimeDatos(jClsPinPadTBResponse.getRspVoucher(), salidaImpresion, 0,"","");
            try {sesionVenta.TextOut = new FileWriter(sesionVenta.TextFile, true);} catch (IOException ex) {ex.printStackTrace();}
            try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" Transaccion Aprobada... \n");} catch (IOException ex) {ex.printStackTrace();}
            try{sesionVenta.TextOut.close();} catch (IOException ex) {ex.printStackTrace();}

            }
            msg += "Transaccion APROBADA.<br>Numero de autorizacion: "+jClsPinPadTBResponse.getRspAuth();
            msg += "</html>";
            DialogoAceptar.mostrarDialogo("TMS Venta.", msg, Color.RED);
            //09102008 ReimprimirVoucher(jClsPinPadTBResponse.getRspVoucher());
            success=true;
            if(worker!=null) worker = null;
            this.dispose();
            return;
        }
        else if(jClsPinPadTBResponse.getRspDsResponse().equals("denied")){
            System.out.println("Denied---> "+jClsPinPadTBResponse.getRspCdResponse());
            if(this.enProceso==4) msg += "Transacción declinada ("+jClsPinPadTBResponse.getRspCdResponse()+").";
            //VAGL 06092011 se cambiaron los mensajes por los mensaje sugeridos por MIT
            //else msg += "Transacción declinada ("+jClsPinPadTBResponse.getRspCdResponse()+").<br>Solicite otra forma de pago";
            else msg += "La operación fue declinada por el banco emisor. ("+jClsPinPadTBResponse.getRspCdResponse()+"). <br> No se realizó ningún cargo a su tarjeta. <br>Solicite otra forma de pago";
            success=false;
            try {sesionVenta.TextOut = new FileWriter(sesionVenta.TextFile, true);} catch (IOException ex) {ex.printStackTrace();}
            try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" Transaccion Denegada... \n");} catch (IOException ex) {ex.printStackTrace();}
            try{sesionVenta.TextOut.close();} catch (IOException ex) {ex.printStackTrace();}

        }
        else if(jClsPinPadTBResponse.getRspDsResponse().equals("error")){
            System.out.println("Error---> "+jClsPinPadTBResponse.getRspCdError()+" - "+jClsPinPadTBResponse.getRspDsError());
            if(this.enProceso==4) msg += "Error en transacción ("+jClsPinPadTBResponse.getRspCdError()+").";
            else{
                if(jClsPinPadTBResponse.getRspCdError().equals("PPE11"))
                    msg += "No se ha realizado ningún cargo a su tarjeta. <br> Ha excedido el tiempo de respuesta.<br>Intentar nuevamente";
                else
                    msg += "No se ha realizado ningún cargo a su tarjeta. <br> Error en transacción: "+jClsPinPadTBResponse.getRspDsError()+"<br>Vuelva a realizar el cobro o intente mas tarde";
            }
            success=false;
            try {sesionVenta.TextOut = new FileWriter(sesionVenta.TextFile, true);} catch (IOException ex) {ex.printStackTrace();}
            try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" Error en la Transaccion... \n");} catch (IOException ex) {ex.printStackTrace();}
            try{sesionVenta.TextOut.write(sesionVenta.formatoFechaHoraBD.format(new Date())+" Error---> "+jClsPinPadTBResponse.getRspCdError()+" - "+jClsPinPadTBResponse.getRspDsError()+" \n");} catch (IOException ex) {ex.printStackTrace();}
            try{sesionVenta.TextOut.close();} catch (IOException ex) {ex.printStackTrace();}

        }
        this.referencia = sesionVenta.getUserCon().getUsuarioNum()+""+new SimpleDateFormat("ddMMyyHHmmss").format(this.thX.getFecha().getTime());
        msg += "</html>";
        DialogoAceptar.mostrarDialogo("TMS Venta.", msg, Color.RED);
    }
    
    public JClsPinPadTBResponse getResponse(){ return jClsPinPadTBResponse; }
    
    public boolean getSuccess(){ return success; }

    private boolean valCamposVDM() {
        if(jPnlVDM.getNombreTH().equals("") || jPnlVDM.getNumeroTarjeta().equals("") || jPnlVDM.getMes().equals("") || jPnlVDM.getAnio().equals("") || jPnlVDM.getCodigoSeg().equals("")) 
        {
            DialogoAceptar.mostrarDialogo("TMS Venta.", "Todos los campos son obligatorios.", Color.RED);
            return false;
        }
        if(jPnlVDM.getNumeroTarjeta().length()==16)
        {
            if(jPnlVDM.getCodigoSeg().length()==3)
             american = false;
            else
            {
                DialogoAceptar.mostrarDialogo("TMS Venta.", "Código de seguridad incorrecto.", Color.RED);
                return false;
            }
            
        }

        if(jPnlVDM.getNumeroTarjeta().length()==15)
        {
            if(jPnlVDM.getCodigoSeg().length()==4)
             american = true;
            else
            {
                DialogoAceptar.mostrarDialogo("TMS Venta.", "Código de seguridad incorrecto.", Color.RED);
                return false;
            }
            
        } 
        if(jPnlVDM.getNumeroTarjeta().length()<15)
        {
            {
                DialogoAceptar.mostrarDialogo("TMS Venta.", "Número de Tarjeta inválido.", Color.RED);
                return false;
            }
        }

        if(sesionVenta.getTmsVtaFacade().validaTarjetaNoPermitida(sesionVenta.getEnc().encriptar(jPnlVDM.getNumeroTarjeta())))
        {
            DialogoAceptar.mostrarDialogo("TMS Venta.", "<html>La operación fue declinada(999). <br> No se realizó ningún cargo a su tarjeta. <br>Solicite otra forma de pago</html>", Color.RED);
            return false;
        }
        return true;
    }
    
    private boolean valCamposCN() {
        if(jPnlCN.getNumeroOperacion().equals("") || jPnlCN.getAutorizacion().equals("")) return false;
        return true;
    }
    
    private boolean valCamposRVou() {
        if(jPnlRVou.getNumeroOperacion().equals("")) return false;
        return true;
    }
    
    private boolean valCamposQRY() {
        if(jPnlQRY.getReferencia().equals("") || jPnlQRY.getFecha().equals("")) return false;
        return true;
    }
    
    private boolean valCamposAMEX() {
        if(jPnlVDAMEX.getCodigoSeguridad().equals("")) return false;
        return true;
    }

    private void paso1CN() {
        this.jLblTitulo.setText("CANCELACIÓN "+importe);
        agregarPanel(jPnlCN);
        jPnlCN.setFoco();
        if(!this.paramAutorizacion.equals(""))
            jPnlCN.setInhabilitarCampos(this.paramNumOperacion, this.paramAutorizacion);
        this.enProceso = 41;
        jLblBarraEstado.setText("<html><font color="+ColoresInterfaz.cHTML3+">F4</font> Realizar cancelacion | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Ir atras</html>");
    }
    
    public String getReference(){ return this.referencia; }

   /* private void ReimprimirVoucher(String strVoucher) {
        int i=1;
        do{
            DialogoSiNo = new JDlgSiNo("TMS Venta.", "<html>Voucher enviado a la impresora<br>¿Desea reimprimirlo?</html>", true);
            if(!DialogoSiNo.getResultado()) return;
            new JClsImprimeVoucher().ImprimeDatos(strVoucher, salidaImpresion, i,"","");
            i++;
        }while(true);
    }
    *
    */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLblBarraEstado;
    private javax.swing.JLabel jLblRespuesta;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JPanel jPnlContenedorCentral;
    private javax.swing.JPanel jPnlContenido;
    // End of variables declaration//GEN-END:variables
    private static final int _VD  = 0;
    private static final int _VDAMEX  = 1;
    private static final int _CN  = 2;
    private static final int _VDM = 3;
    private static final int _VOU = 4;
    private static final int _QRY = 5;
    private int enProceso;
    private boolean activoF1 = false;
    
    private JClsColoresInterfaz ColoresInterfaz = new JClsColoresInterfaz();
    
    private JClsPinPadTBRequest jClsPinPadTBRequest;
    private JClsPinPadTBResponse jClsPinPadTBResponse;

    private SwingWorker worker = null;
    private JDlgBProgreso jProgreso = null;
    private boolean[] btx;
    private String cadenaMenu;
    
    private JPnlVD jPnlVD = null;
    private JPnlVDM jPnlVDM = null;
    private JPnlCN jPnlCN = null;
    private JPnlRVou jPnlRVou = null;
    private JPnlQRY jPnlQRY = null;
    private JPnlVDAMEX jPnlVDAMEX = null;
    private JDlgAceptar DialogoAceptar = new JDlgAceptar();
    private JDlgSiNo DialogoSiNo = null;
    private boolean success;
    private String Amount;
    private String importe;
    private String referencia;
    private String paramAutorizacion;
    private String paramNumOperacion;
    
    private SesionVenta sesionVenta = null;
    private String AMEXP;

    private String salidaImpresion;
    private boolean xF;
    
    private RelojVisualVta thX=null;

    private boolean american = false;
    private boolean respondio = false;
    private final boolean imprimeVoucher;
    private boolean estaListaNegra = false;

    public boolean isRespondio() {
        return respondio;
    }

    public void setRespondio(boolean respondio) {
        this.respondio = respondio;
    }
}
