/*
 * JDlgCupones.java
 *
 * Created on 7 de noviembre de 2007, 08:17 PM
 */

package DialogosX;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JDialog;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.text.JTextComponent;
import tms_venta.JClsColoresInterfaz;
import tms_venta.SesionVenta;

/**
 *
 * @author  ocruz
 */
public class JDlgCupones extends javax.swing.JDialog {
    
    /** Creates new form JDlgCupones */
    public JDlgCupones(int pNumBoletos, JDialog compo, SesionVenta pSesionVenta) {
        super(compo, true);
        this.numBoletos = pNumBoletos;
        this.sesionVenta = pSesionVenta;
        cupones = new Object[numBoletos][2];
        initComponents();
        jLabel1.setText("<html><font color="+ColoresInterfaz.cHTML3+">F7</font> Aceptar | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Cancelar");
        interfazColor();
        //this.setModal(true);
        centrarJDialog();
        xVtaActual.setDataVector(cupones, encVtaActual);
        this.MsgCupon = "";
        this.jTblCupones.setRowSelectionInterval(0,0);
        this.jTblCupones.setColumnSelectionInterval(0,0);
        this.jTblCupones.requestFocusInWindow();
    }
    
    public void setColNoEditable(int pColNoEditable){ this.colNoEditable=pColNoEditable; }
    
    public void setFormaPago(String pFormaPago){
        this.FormaPago = pFormaPago;
    }
    
    private void centrarJDialog(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, ( screenSize.height - frameSize.height ) / 2 );
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblCupones = new javax.swing.JTable();
        jTblCupones = new javax.swing.JTable()
        {
            public Component prepareEditor(
                TableCellEditor editor, int row, int column)
            {

                Component c = super.prepareEditor(editor, row, column);
                if (c instanceof JTextComponent)
                {
                    ((JTextField)c).selectAll();
                }
                return c;
            }
        };
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ingrese Cupones");
        setModal(true);
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane1.setFocusable(false);
        jTblCupones.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTblCupones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTblCupones.setModel(xVtaActual);
        jTblCupones.setFocusTraversalKeysEnabled(false);
        jTblCupones.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_RIGHT, 0),"none");
        jTblCupones.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_LEFT, 0),"none");
        jTblCupones.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_TAB, 0),KeyStroke.getKeyStroke(KeyEvent.VK_ENTER, 0));
        jTblCupones.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTblCupones.setRowSelectionAllowed(false);
        jTblCupones.setColumnSelectionAllowed(false);
        jTblCupones.setCellSelectionEnabled(true);
        jTblCupones.getTableHeader().setReorderingAllowed(false);
        jTblCupones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTblCuponesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTblCuponesKeyReleased(evt);
            }
        });

        jScrollPane1.setViewportView(jTblCupones);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("<html><font color=\"+ColoresInterfaz.cHTML1+\">F7</font> Aceptar | <font color=\"+ColoresInterfaz.cHTML1+\">ESC</font> Cancelar");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 357, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTblCuponesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblCuponesKeyReleased
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ENTER: case KeyEvent.VK_RIGHT: case KeyEvent.VK_LEFT:
                if(FormaPago.equals("AMX") && jTblCupones.getSelectedColumn()==0){
                   objDato=xVtaActual.getValueAt(jTblCupones.getSelectedRow(),1);
                   if(objDato==null || objDato.toString().equals("")) return;
                   if(objDato.toString().length()!=sesionVenta.getUserCon().getDigitosCupon()){
                       this.getToolkit().beep();
                       DialogoAceptar.mostrarDialogo("¡Boleto de avion incorrecto!", "Ingrese "+sesionVenta.getUserCon().getDigitosCupon()+" digitos.", Color.RED);
                       jTblCupones.setRowSelectionInterval(jTblCupones.getSelectedRow(), jTblCupones.getSelectedRow());
                       jTblCupones.setColumnSelectionInterval(1, 1);
                       jTblCupones.requestFocusInWindow();
                       return;
                   }
                }
                break;
        }
    }//GEN-LAST:event_jTblCuponesKeyReleased

    private void jTblCuponesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblCuponesKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_F7:
                int i;
                if(FormaPago.equals("AMX")){
                    for(i=0; i<numBoletos; i++){
                        if(xVtaActual.getValueAt(i,0)==null || xVtaActual.getValueAt(i,0).toString().equals("") ||
                                xVtaActual.getValueAt(i,1)==null || xVtaActual.getValueAt(i,1).toString().equals("")){
                            DialogoAceptar.mostrarDialogo("¡Falta cupones por ingresar!", "Los "+numBoletos+" cupones son requeridos.", Color.RED);
                            jTblCupones.setRowSelectionInterval(i,i);
                            jTblCupones.requestFocusInWindow();
                            return;
                        }
                        if(xVtaActual.getValueAt(i,1).toString().length()!=sesionVenta.getUserCon().getDigitosCupon()){
                            this.getToolkit().beep();
                            DialogoAceptar.mostrarDialogo("¡Boleto de avion incorrecto!", "Ingrese "+sesionVenta.getUserCon().getDigitosCupon()+" digitos.", Color.RED);
                            jTblCupones.setRowSelectionInterval(i, i);
                            jTblCupones.setColumnSelectionInterval(1, 1);
                            jTblCupones.requestFocusInWindow();
                            return;
                        }
                        cupones[i][0] = jTblCupones.getValueAt(i,0);
                        cupones[i][1] = jTblCupones.getValueAt(i,1);
                    }
                }
                else{
                    for(i=0; i<numBoletos; i++){
                        if(xVtaActual.getValueAt(i,0)==null || xVtaActual.getValueAt(i,0).toString().equals("")){
                            DialogoAceptar.mostrarDialogo("¡Falta cupones por ingresar!", "Los "+numBoletos+" cupones son requeridos.", Color.RED);
                            jTblCupones.setRowSelectionInterval(i,i);
                            jTblCupones.requestFocusInWindow();
                            return;
                        }
                        cupones[i][0] = jTblCupones.getValueAt(i,0);
                        cupones[i][1] = jTblCupones.getValueAt(i,1);
                    }
                }
                this.MsgCupon = "Cupones ingresados";
                this.dispose();
                break;
            case KeyEvent.VK_ESCAPE:
                if(FormaPago.equals("AMX")){
                    for(i=0; i<numBoletos; i++){
                        if(xVtaActual.getValueAt(i,0)==null || xVtaActual.getValueAt(i,0).toString().equals("") ||
                                xVtaActual.getValueAt(i,1)==null || xVtaActual.getValueAt(i,1).toString().equals("")){
                            this.MsgCupon = "";
                            break;
                        }
                        else{
                            if(xVtaActual.getValueAt(i,1).toString().length()!=sesionVenta.getUserCon().getDigitosCupon()){
                                this.MsgCupon = "";
                                break;
                            }
                        }
                    }
                }
                else{
                    for(i=0; i<numBoletos; i++){
                        if(xVtaActual.getValueAt(i,0)==null || xVtaActual.getValueAt(i,0).toString().equals("")){
                            this.MsgCupon = "";
                            break;
                        }
                        else{
                            cupones[i][0] = jTblCupones.getValueAt(i,0);
                            cupones[i][1] = jTblCupones.getValueAt(i,1);
                        }
                    }
                }
                this.dispose();
                break;
        }
    }//GEN-LAST:event_jTblCuponesKeyPressed

    public String getMsgCupones(){ return this.MsgCupon; }
    
    public Object[][] getFoliosCupones(){ return this.cupones; }
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
// TODO add your handling code here:
        this.jTblCupones.setRowSelectionInterval(0,0);
        this.jTblCupones.setColumnSelectionInterval(0,0);
        this.jTblCupones.requestFocusInWindow();
    }//GEN-LAST:event_formComponentShown
    
    private void interfazColor(){
        setBackground(ColoresInterfaz.cFondoDialogo);
        jTblCupones.setBackground(ColoresInterfaz.cFondoDialogo);
        /*jLabel1.setOpaque(true);
        jLabel1.setBackground(ColoresInterfaz.cFondoPieEncabezado2);*/
        jLabel1.setForeground(ColoresInterfaz.cTextoAyuda1);
        
        jTblCupones.setFont(ColoresInterfaz.fuente1);
        jLabel1.setFont(ColoresInterfaz.fuente1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblCupones;
    // End of variables declaration//GEN-END:variables

    private Object[] encVtaActual = {"No. Cupon", "No. Boleto"};
    private DefaultTableModel xVtaActual = new DefaultTableModel(null, encVtaActual){
        public boolean isCellEditable(int row, int col) {
            if(col==colNoEditable) return false;
            return true;
        }
    };
    Object[][] cupones;
    private JDlgAceptar DialogoAceptar = new JDlgAceptar();
    int numBoletos;

    private String MsgCupon;
    private String FormaPago;
    private Object objDato;
    private JClsColoresInterfaz ColoresInterfaz = new JClsColoresInterfaz();
    private SesionVenta sesionVenta;
    private int colNoEditable;
}
