/*
 * JDlgACHorarios.java
 *
 * Created on 23 de octubre de 2007, 02:32 PM
 */

package tms_corridaextra;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Timestamp;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Vector;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import tms_TextFields.JHourTextField;
import tms_TextFields.JNumberTextField;
import tms_psd.*;
import tms_psd.util.BarraMensajes;
import tms_psd.util.JDlgAceptar;
import tms_psd.util.JDlgSiNo;
import tms_psd.util.TmsCorridasVentaV;

/**
 *
 * @author  ocruz
 */
public class JDlgACHorarios extends javax.swing.JDialog {
    
    /**
     * Creates new form JDlgACHorarios
     */
    public JDlgACHorarios(SesionVenta pSesionVenta) {
        this.sesionVenta = pSesionVenta;
        initComponents();
        this.setModal(true);
        this.setTitle("Abrir/Cerrar Horarios - "+hoyEs);
        centrarJDialog();
        inhabilitarF10();
    }
    
    //"Clave", "T", "E", "Servicio", "Empresa", "Origen", "Destino", "Horario"}
    private void AnchoColumnas1(){
        TableColumn column = null;
        int anchoContenedor = jScrollPane1.getWidth();
        for (int i = 0; i < 8; i++) {
            column = jTblCorridas.getColumnModel().getColumn(i);
            switch(i){
                case 0:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.17)); break;
                case 1:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.05)); break;
                case 2:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.05)); break;
                case 3:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.17)); break;
                case 4:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.22)); break;
                case 5:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.13)); break;
                case 6:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.13)); break;
                case 7:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.08)); break;
            }
            column.setResizable(false);
        }
    }
    
    private void inhabilitarF10() {
        this.jComboBox1.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
        this.jTxtHoraInicial.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
        this.jTxtHoraFinal.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
        this.jTxtFrecuencia.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
        this.jTblCalculo.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
        this.jTblCorridas.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
    }
    
    //"Clave", "T", "E", "Horario"}
    private void AnchoColumnas2(){
        TableColumn column = null;
        int anchoContenedor = jScrollPane2.getWidth();
        for (int i = 0; i < 4; i++) {
            column = jTblCalculo.getColumnModel().getColumn(i);
            switch(i){
                case 0:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.50)); break;
                case 1:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.10)); break;
                case 2:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.10)); break;
                case 3:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.30)); break;
            }
            column.setResizable(false);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtHoraInicial = new JHourTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtHoraFinal = new JHourTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtFrecuencia = new JNumberTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox(sesionVenta.getVectorServicios());
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblCorridas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblCalculo = new javax.swing.JTable();
        jLblResultados = new javax.swing.JLabel();
        jLblMensajes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Abrir/Cerrar Horarios - 23/10/2007");
        setModal(true);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Criterios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), java.awt.Color.black));
        jPanel1.setFocusTraversalKeysEnabled(false);
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Hora Inicial:");

        jTxtHoraInicial.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTxtHoraInicial.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtHoraInicial.setFocusTraversalKeysEnabled(false);
        jTxtHoraInicial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtHoraInicialKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Hora Final:");

        jTxtHoraFinal.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTxtHoraFinal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtHoraFinal.setFocusTraversalKeysEnabled(false);
        jTxtHoraFinal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtHoraFinalKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Frecuencia:");

        jLabel4.setText("minutos");

        jTxtFrecuencia.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTxtFrecuencia.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtFrecuencia.setFocusTraversalKeysEnabled(false);
        jTxtFrecuencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtFrecuenciaKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("Servicio:");

        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTxtHoraInicial, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(13, 13, 13)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTxtHoraFinal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 50, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(13, 13, 13)
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTxtFrecuencia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(jComboBox1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(jLabel4)
                    .add(jTxtHoraInicial, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTxtHoraFinal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTxtFrecuencia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Corridas a procesar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), java.awt.Color.black));
        jTblCorridas.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTblCorridas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTblCorridas.setModel(xListado1);
        jTblCorridas.setFocusTraversalKeysEnabled(false);
        jTblCorridas.getTableHeader().setReorderingAllowed(false);
        jTblCorridas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTblCorridasKeyPressed(evt);
            }
        });

        jScrollPane1.setViewportView(jTblCorridas);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo horario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), java.awt.Color.black), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), java.awt.Color.black));
        jTblCalculo.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTblCalculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTblCalculo.setModel(xListado2);
        jTblCalculo.setFocusTraversalKeysEnabled(false);
        jTblCalculo.getTableHeader().setReorderingAllowed(false);
        jTblCalculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTblCalculoKeyPressed(evt);
            }
        });

        jScrollPane2.setViewportView(jTblCalculo);

        jLblResultados.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLblResultados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 233, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(jLblResultados, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLblResultados, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLblMensajes.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLblMensajes.setText("hola");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLblMensajes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 790, Short.MAX_VALUE)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLblMensajes))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE: 
                DialogoSiNo = new JDlgSiNo("¡Confirme!", "¿Desea cancelar el proceso?");
                if(!DialogoSiNo.getResultado()) return;
                liberarCorridas();
                this.dispose(); break;
            case KeyEvent.VK_RIGHT: jTxtHoraInicial.selectAll(); jTxtHoraInicial.requestFocusInWindow(); break;
            case KeyEvent.VK_LEFT: jTxtFrecuencia.selectAll(); jTxtFrecuencia.requestFocusInWindow(); break;
            case KeyEvent.VK_ENTER:
                if(!ValidaHoras()) return;
                if(!ValidarHoraFrecuencia()) return;
                ejecutoCalculo(); break;
        }
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jTblCalculoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblCalculoKeyPressed
// TODO add your handling code here:
        int indice;
        switch(evt.getKeyCode()){
            case KeyEvent.VK_F2: jLblMensajes.setText(barraMensajes.getMsgRolCadena(2)); jTblCorridas.setColumnSelectionInterval(0,0); jTblCorridas.setRowSelectionInterval(0,0); jTblCorridas.requestFocusInWindow(); break;
            case KeyEvent.VK_F1: jTxtHoraInicial.setEnabled(true); jTxtHoraFinal.setEnabled(true); jComboBox1.setEnabled(true);
                liberarCorridas();
                xListado1.setDataVector(null, encabezado1);
                AnchoColumnas1();
                xListado2.setDataVector(null, encabezado2);
                AnchoColumnas2();
                jLblMensajes.setText(barraMensajes.getMsgRolCadena(0));
                jLblResultados.setText("");
                jTxtHoraInicial.selectAll();
                jTxtHoraInicial.requestFocusInWindow(); break;
            case KeyEvent.VK_F9: 
                xListado2.setDataVector(null, encabezado2);
                AnchoColumnas2();
                jLblMensajes.setText(barraMensajes.getMsgRolCadena(1));
                jTxtFrecuencia.requestFocusInWindow(); break;
            case KeyEvent.VK_ENTER:
                if(casoRolCadena==1){
                    if(!xListado2.getValueAt(jTblCalculo.getSelectedRow(), 0).toString().contains("EXTRA")) return;
                    
                    indice = recorte-(jTblCalculo.getRowCount()-(jTblCalculo.getSelectedRow()+1));
                    
                    if(xListado2.getValueAt(jTblCalculo.getSelectedRow(), 0).toString().equals("EXTRA+")){
                        System.out.println("QUE PASO::: indice "+(indice)+" indice-1 "+(indice-1)+" c.s "+corridasExtra.size());
                        JDlgCEx jDlgCEx = new JDlgCEx(sesionVenta, corridasExtra.get(indice-1),
                                indice, 2, xListado2.getValueAt(jTblCalculo.getSelectedRow(),3).toString());
                        jDlgCEx.setVisible(true);
                        if(jDlgCEx.getCapturaCE()==1){
                            TmsCorridasVentaV corridaExtra = new TmsCorridasVentaV();
                            corridaExtra = jDlgCEx.getCorridaExtra();
                            corridasExtra.set((indice-1), corridaExtra);
                            xListado2.setValueAt(jDlgCEx.getLetraEstado(),jTblCalculo.getSelectedRow(), 2);
                        }
                        return;
                    }
                    
                    if(xListado2.getValueAt(jTblCalculo.getSelectedRow(), 0).toString().substring(0,5).equals("EXTRA")){
                        if((indice == 1 && corridasExtra.size()==0) || xListado2.getValueAt(jTblCalculo.getSelectedRow()-1, 0).toString().equals("EXTRA+")){
                            System.out.println("QUE PASO::: indice "+(indice)+" indice-1 "+(indice-1)+" c.s "+corridasExtra.size());
                            JDlgCEx jDlgCEx = new JDlgCEx(sesionVenta, null, indice, 1, xListado2.getValueAt(jTblCalculo.getSelectedRow(),3).toString());
                            jDlgCEx.setVisible(true);
                            if(jDlgCEx.getCapturaCE()==1){
                                TmsCorridasVentaV corridaExtra = new TmsCorridasVentaV();
                                corridaExtra = jDlgCEx.getCorridaExtra();
                                corridasExtra.add(corridaExtra);
                                filaEspecial = jTblCalculo.getSelectedRow();
                                xListado2.setValueAt(jDlgCEx.getLetraEstado(),jTblCalculo.getSelectedRow(), 2);
                                xListado2.setValueAt("EXTRA+",jTblCalculo.getSelectedRow(), 0);
                                filaEspecial = -1;
                            }
                            return;
                        }
                        else
                            DialogoAceptar = new JDlgAceptar("¡Aun no ha creado la anterior corrida!", "Debe crear las corridas secuencialmente.", Color.RED);
                    }
                }
                break;
            case KeyEvent.VK_F12:
                if(jTblCalculo.getSelectedRow()==jTblCalculo.getRowCount()-1){
                    DialogoAceptar = new JDlgAceptar("¡Ultima corrida seleccionada!", "Para ejecutar esta funcion no debe seleccionar la ultima corrida.", Color.RED);
                    return;
                }
                
                if(!xListado2.getValueAt(jTblCalculo.getSelectedRow(), 0).toString().equals("EXTRA+")){
                    DialogoAceptar = new JDlgAceptar("¡Esta corrida extra no ha sido creada!", "Seleccione corrida con clave EXTRA+.", Color.RED);
                    return;
                }
                
                indice = recorte-(jTblCalculo.getRowCount()-(jTblCalculo.getSelectedRow()+1));
                //System.out.println("QUE PASO::: indice "+(indice)+" indice-1 "+(indice-1)+" c.s "+corridasExtra.size());
                JDlgCEx jDlgCEx = new JDlgCEx(sesionVenta, corridasExtra.get(indice-1),
                                indice, 0, xListado2.getValueAt(jTblCalculo.getSelectedRow(),3).toString());
                jDlgCEx.setVisible(true);
                if(jDlgCEx.getCapturaCE()==1){
                    clonarCE(jTblCalculo.getSelectedRow(), indice);
                    DialogoAceptar = new JDlgAceptar("¡Corridas extras creadas correctamente!", "", colorDialogoActivo);
                }
                break;
            case KeyEvent.VK_F10:
                if(casoRolCadena==1 && (corridasExtra==null || corridasExtra.size()==0 || recorte>corridasExtra.size())){
                    DialogoAceptar = new JDlgAceptar("¡Corridas extras incompletas!", "No ha creado todas las corridas extras.", Color.RED);
                    return;
                }
                Timestamp fechaHora = null;
                boolean todoBien = true;
                jLblMensajes.setText("Guardando cambios, espere...");
                switch(casoRolCadena){
                    case 0:
                        for(int i=0; i<listado1.length; i++){
                            try {
                                fechaHora = new Timestamp(formatoFechaHora.parse(hoyEs+" "+listado2[i][3].toString()).getTime());
                            } catch (ParseException ex) {
                                ex.printStackTrace();
                                todoBien = false;
                                break;
                            }
                            if(!sesionVenta.abreCorridaNuevoHorario(Long.valueOf(listado2[i][4].toString()), fechaHora, listado2[i][3].toString())){
                                todoBien = false;
                                break;
                            }
                        }
                        break;
                    case 1:
                        for(int i=0; i<listado1.length; i++){
                            try {
                                fechaHora = new Timestamp(formatoFechaHora.parse(hoyEs+" "+listado2[i][3].toString()).getTime());
                            } catch (ParseException ex) {
                                todoBien = false;
                                break;
                            }
                            if(!sesionVenta.abreCorridaNuevoHorario(Long.valueOf(listado2[i][4].toString()), fechaHora, listado2[i][3].toString())){
                                todoBien = false;
                                break;
                            }
                        }
                        if(todoBien) res=sesionVenta.guardarCorridaExtra(corridasExtra);
                        break;
                    case 2:
                        for(int i=0; i<listado1.length; i++){
                            if(i<listado2.length){
                                try {
                                    fechaHora = new Timestamp(formatoFechaHora.parse(hoyEs+" "+listado2[i][3].toString()).getTime());
                                } catch (ParseException ex) {
                                    todoBien = false;
                                    break;
                                }
                                if(!sesionVenta.abreCorridaNuevoHorario(Long.valueOf(listado2[i][4].toString()), fechaHora, listado2[i][3].toString())){
                                    todoBien = false;
                                    break;
                                }
                            }
                            else if(!sesionVenta.cancelaCorrida(Long.valueOf(listado1[i][8].toString()))){
                                    todoBien = false;
                                    break;
                                }
                        }
                        break;
                }
                if(!todoBien){
                    DialogoAceptar = new JDlgAceptar("¡No existe conexion a la base de datos!", "<html>Es posible que el estado de algunas corridas este en proceso.<br>Contacte al administrador del sistema.", Color.RED);
                    this.dispose();
                }
                jTxtHoraInicial.setEnabled(true); jTxtHoraFinal.setEnabled(true);  jComboBox1.setEnabled(true);
                xListado1.setDataVector(null, encabezado1);
                AnchoColumnas1();
                xListado2.setDataVector(null, encabezado2);
                AnchoColumnas2();
                jLblMensajes.setText(barraMensajes.getMsgRolCadena(0));
                jLblResultados.setText("");
                jTxtHoraInicial.setText("");
                jTxtHoraFinal.setText("");
                jTxtFrecuencia.setText("");
                DialogoAceptar = new JDlgAceptar("¡Cambios realizados correctamente!", "Si lo desea puede consultarlos en el monitor de corridas.", colorDialogoActivo);
                jTxtHoraInicial.requestFocusInWindow();break;
        }
    }//GEN-LAST:event_jTblCalculoKeyPressed

    private void clonarCE(int filaSel, int indiceCE){
        TmsCorridasVentaV x = corridasExtra.get(indiceCE-1);
        TmsCorridasVentaV y;
        String HoraX;
        String FechaX;
        for(int i=filaSel+1; i<listado2.length; i++){
            HoraX=xListado2.getValueAt(i,3).toString();
            filaEspecial = i;
            if(xListado2.getValueAt(i, 0).toString().equals("EXTRA+")){ // CORRIDA CREADA
                y = new TmsCorridasVentaV();
                try {
                    y.setHoraCorrida(new Timestamp(formatoHora.parse(HoraX).getTime()));
                } catch (ParseException ex) {
                    ;
                }
                FechaX = hoyEs+" "+HoraX;
                try {
                    y.setFechaHoraCorrida(new Timestamp(formatoFechaHora.parse(FechaX).getTime()));
                } catch (ParseException ex) {
                    ;
                }
                y.setAutobus(x.getAutobus());
                y.setAutobusId(x.getAutobusId());
                y.setAutobusOriginal(x.getAutobusOriginal());
                y.setAutobusOriginalId(x.getAutobusOriginalId());
                y.setClaveCorrida(x.getClaveCorrida());
                y.setCorridaId(x.getCorridaId());
                y.setCorridaRelacionadaId(x.getCorridaRelacionadaId());
                y.setCortesiasCorrida(x.getCortesiasCorrida());
                y.setCreadoPor(x.getCreadoPor());
                y.setDestino(x.getDestino());
                y.setDestinoId(x.getDestinoId());
                y.setEmpresa(x.getEmpresa());
                y.setEmpresaId(x.getEmpresaId());
                y.setEstadoCorrida(x.getEstadoCorrida());
                y.setEstadoCorridaId(x.getEstadoCorridaId());
                y.setEstudiantesCorrida(x.getEstudiantesCorrida());
                y.setFechaCreacion(x.getFechaCreacion());
                y.setMenoresCorrida(x.getMenoresCorrida());
                y.setMontoAnticipos(x.getMontoAnticipos());
                y.setNumeroContrato(x.getNumeroContrato());
                y.setNumeroOrden(x.getNumeroOrden());
                y.setOperador(x.getOperador());
                y.setOperadorAdicional(x.getOperadorAdicional());
                y.setOperadorId(x.getOperadorId());
                y.setOperadorOriginal(x.getOperadorOriginal());
                y.setOperadorOriginalId(x.getOperadorOriginalId());
                y.setOrigen(x.getOrigen());
                y.setOrigenId(x.getOrigenId());
                y.setPlantillaId(x.getPlantillaId());
                y.setProfesoresCorrida(x.getProfesoresCorrida());
                y.setRutaId(x.getRutaId());
                y.setRutaNombre(x.getRutaNombre());
                y.setRutaNumero(x.getRutaNumero());
                y.setTipoCorrida(x.getTipoCorrida());
                y.setUltimaActualizacionPor(x.getUltimaActualizacionPor());
                y.setUltimaFechaActualizacion(x.getUltimaFechaActualizacion());
                corridasExtra.set(indiceCE, y);
                xListado2.setValueAt(x.getEstadoCorrida(),i,2);
                indiceCE++;
            }
            else{ // CORRIDA EXTRA NUEVA
                y = new TmsCorridasVentaV();
                try {
                    y.setHoraCorrida(new Timestamp(formatoHora.parse(HoraX).getTime()));
                } catch (ParseException ex) {
                    ;
                }
                FechaX = hoyEs+" "+HoraX;
                try {
                    y.setFechaHoraCorrida(new Timestamp(formatoFechaHora.parse(FechaX).getTime()));
                } catch (ParseException ex) {
                    ;
                }
                y.setAutobus(x.getAutobus());
                y.setAutobusId(x.getAutobusId());
                y.setAutobusOriginal(x.getAutobusOriginal());
                y.setAutobusOriginalId(x.getAutobusOriginalId());
                y.setClaveCorrida(x.getClaveCorrida());
                y.setCorridaId(x.getCorridaId());
                y.setCorridaRelacionadaId(x.getCorridaRelacionadaId());
                y.setCortesiasCorrida(x.getCortesiasCorrida());
                y.setCreadoPor(x.getCreadoPor());
                y.setDestino(x.getDestino());
                y.setDestinoId(x.getDestinoId());
                y.setEmpresa(x.getEmpresa());
                y.setEmpresaId(x.getEmpresaId());
                y.setEstadoCorrida(x.getEstadoCorrida());
                y.setEstadoCorridaId(x.getEstadoCorridaId());
                y.setEstudiantesCorrida(x.getEstudiantesCorrida());
                y.setFechaCreacion(x.getFechaCreacion());
                y.setMenoresCorrida(x.getMenoresCorrida());
                y.setMontoAnticipos(x.getMontoAnticipos());
                y.setNumeroContrato(x.getNumeroContrato());
                y.setNumeroOrden(x.getNumeroOrden());
                y.setOperador(x.getOperador());
                y.setOperadorAdicional(x.getOperadorAdicional());
                y.setOperadorId(x.getOperadorId());
                y.setOperadorOriginal(x.getOperadorOriginal());
                y.setOperadorOriginalId(x.getOperadorOriginalId());
                y.setOrigen(x.getOrigen());
                y.setOrigenId(x.getOrigenId());
                y.setPlantillaId(x.getPlantillaId());
                y.setProfesoresCorrida(x.getProfesoresCorrida());
                y.setRutaId(x.getRutaId());
                y.setRutaNombre(x.getRutaNombre());
                y.setRutaNumero(x.getRutaNumero());
                y.setSenectudCorrida(x.getSenectudCorrida());
                y.setServicio(x.getServicio());
                y.setServicioId(x.getServicioId());
                y.setTipoCorrida(x.getTipoCorrida());
                y.setUltimaActualizacionPor(x.getUltimaActualizacionPor());
                y.setUltimaFechaActualizacion(x.getUltimaFechaActualizacion());
                corridasExtra.add(y);
                xListado2.setValueAt("EXTRA+",i, 0);
                xListado2.setValueAt(x.getEstadoCorrida(),i,2);
            }
            filaEspecial = -1;
        }
    }
    
    private void jTblCorridasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblCorridasKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_F3: jLblMensajes.setText(barraMensajes.getMsgRolCadena(3)); jTblCalculo.setColumnSelectionInterval(0,0); jTblCalculo.setRowSelectionInterval(0,0); jTblCalculo.requestFocusInWindow(); break;
            case KeyEvent.VK_F1: jTxtHoraInicial.setEnabled(true); jTxtHoraFinal.setEnabled(true);  jComboBox1.setEnabled(true);
                liberarCorridas();
                xListado1.setDataVector(null, encabezado1);
                AnchoColumnas1();
                xListado2.setDataVector(null, encabezado2);
                AnchoColumnas2();
                jLblMensajes.setText(barraMensajes.getMsgRolCadena(0));
                jLblResultados.setText("");
                jTxtHoraInicial.selectAll();
                jTxtHoraInicial.requestFocusInWindow(); break;
            case KeyEvent.VK_F9: 
                xListado2.setDataVector(null, encabezado2);
                AnchoColumnas2();
                jLblMensajes.setText(barraMensajes.getMsgRolCadena(1));
                jTxtFrecuencia.requestFocusInWindow(); break;
        }
    }//GEN-LAST:event_jTblCorridasKeyPressed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
// TODO add your handling code here:
        xListado1.setDataVector(null, encabezado1);
        AnchoColumnas1();
        xListado2.setDataVector(null, encabezado2);
        AnchoColumnas2();
        jLblMensajes.setText(barraMensajes.getMsgRolCadena(0));
        jLblResultados.setText("");
        jTxtHoraInicial.selectAll();
        jTxtHoraInicial.requestFocusInWindow();
    }//GEN-LAST:event_formComponentShown

    private void jTxtFrecuenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFrecuenciaKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE: 
                DialogoSiNo = new JDlgSiNo("¡Confirme!", "¿Desea cancelar el proceso?");
                if(!DialogoSiNo.getResultado()) return;
                liberarCorridas();
                this.dispose(); break;
            case KeyEvent.VK_RIGHT: if(!jTxtHoraInicial.isEnabled()) return;
                jComboBox1.requestFocusInWindow(); break;
            case KeyEvent.VK_LEFT: if(!jTxtHoraInicial.isEnabled()) return;
                jTxtHoraFinal.selectAll(); jTxtHoraFinal.requestFocusInWindow(); break;
            case KeyEvent.VK_ENTER: if(!jTxtHoraInicial.isEnabled()) return; if(!ValidaHoras()) return; 
            if(!ValidarHoraFrecuencia()) return;
            ejecutoCalculo(); break;
            case KeyEvent.VK_F2: if(jTblCorridas.getRowCount()==0) return; jLblMensajes.setText(barraMensajes.getMsgRolCadena(2)); jTblCorridas.setColumnSelectionInterval(0,0); jTblCorridas.setRowSelectionInterval(0,0); jTblCorridas.requestFocusInWindow(); break;
            case KeyEvent.VK_F3: if(jTblCalculo.getRowCount()==0) return; jLblMensajes.setText(barraMensajes.getMsgRolCadena(3)); jTblCalculo.setColumnSelectionInterval(0,0); jTblCalculo.setRowSelectionInterval(0,0); jTblCalculo.requestFocusInWindow(); break;
            case KeyEvent.VK_F1: jTxtHoraInicial.setEnabled(true); jTxtHoraFinal.setEnabled(true);  jComboBox1.setEnabled(true);
                liberarCorridas();
                xListado1.setDataVector(null, encabezado1);
                AnchoColumnas1();
                xListado2.setDataVector(null, encabezado2);
                AnchoColumnas2();
                jLblMensajes.setText(barraMensajes.getMsgRolCadena(0));
                jLblResultados.setText("");
                jTxtHoraInicial.selectAll();
                jTxtHoraInicial.requestFocusInWindow(); break;
            case KeyEvent.VK_F9: if(!ValidarFrecuencia()) return; CalculoRolCadena(); jTxtFrecuencia.requestFocusInWindow(); break;
            case KeyEvent.VK_F10:
                if(jTblCalculo.getRowCount()==0) return;
                if(casoRolCadena==1 && (corridasExtra==null || corridasExtra.size()==0 || recorte>corridasExtra.size())){
                    DialogoAceptar = new JDlgAceptar("¡Corridas extras incompletas!", "No ha creado todas las corridas extras.", Color.RED);
                    return;
                }
                Timestamp fechaHora = null;
                boolean todoBien = true;
                jLblMensajes.setText("Guardando cambios, espere...");
                switch(casoRolCadena){
                    case 0:
                        for(int i=0; i<listado1.length; i++){
                            try {
                                fechaHora = new Timestamp(formatoFechaHora.parse(hoyEs+" "+listado2[i][3].toString()).getTime());
                            } catch (ParseException ex) {
                                ex.printStackTrace();
                                todoBien = false;
                                break;
                            }
                            if(!sesionVenta.abreCorridaNuevoHorario(Long.valueOf(listado2[i][4].toString()), fechaHora, listado2[i][3].toString())){
                                todoBien = false;
                                break;
                            }
                        }
                        break;
                    case 1:
                        for(int i=0; i<listado1.length; i++){
                            try {
                                fechaHora = new Timestamp(formatoFechaHora.parse(hoyEs+" "+listado2[i][3].toString()).getTime());
                            } catch (ParseException ex) {
                                todoBien = false;
                                break;
                            }
                            if(!sesionVenta.abreCorridaNuevoHorario(Long.valueOf(listado2[i][4].toString()), fechaHora, listado2[i][3].toString())){
                                todoBien = false;
                                break;
                            }
                        }
                        if(todoBien) res=sesionVenta.guardarCorridaExtra(corridasExtra);
                        break;
                    case 2:
                        for(int i=0; i<listado1.length; i++){
                            if(i<listado2.length){
                                try {
                                    fechaHora = new Timestamp(formatoFechaHora.parse(hoyEs+" "+listado2[i][3].toString()).getTime());
                                } catch (ParseException ex) {
                                    todoBien = false;
                                    break;
                                }
                                if(!sesionVenta.abreCorridaNuevoHorario(Long.valueOf(listado2[i][4].toString()), fechaHora, listado2[i][3].toString())){
                                    todoBien = false;
                                    break;
                                }
                            }
                            else if(!sesionVenta.cancelaCorrida(Long.valueOf(listado1[i][8].toString()))){
                                    todoBien = false;
                                    break;
                                }
                        }
                        break;
                }
                if(!todoBien){
                    int r = Integer.valueOf(res[0]);
                    if(r!=1){
                        switch(r){
                            case 0: DialogoAceptar = new JDlgAceptar("¡No existe conexion a la base de datos!","<html>Es posible que el estado de algunas corridas este en proceso.<br>Contacte al administrador del sistema.</html>", Color.RED); break;
                            case -1: DialogoAceptar = new JDlgAceptar("Corrida extra "+res[1]+" no creada.","<html>Corrida creada solo en TMS_CORRIDAS_TBL.<br>Contacte al administrador del sistema.</html>", Color.RED); break;
                            case -2: DialogoAceptar = new JDlgAceptar("¡No existe conexion a la base de datos!","<html>Fecha hora del servidor incorrecta.<br>Contacte al administrador del sistema.</html>", Color.RED); break;
                        }
                    }
                    this.dispose();
                }
                jTxtHoraInicial.setEnabled(true); jTxtHoraFinal.setEnabled(true);  jComboBox1.setEnabled(true);
                xListado1.setDataVector(null, encabezado1);
                AnchoColumnas1();
                xListado2.setDataVector(null, encabezado2);
                AnchoColumnas2();
                jLblMensajes.setText(barraMensajes.getMsgRolCadena(0));
                jLblResultados.setText("");
                jTxtHoraInicial.setText("");
                jTxtHoraFinal.setText("");
                jTxtFrecuencia.setText("");
                DialogoAceptar = new JDlgAceptar("¡Cambios realizados correctamente!", "Si lo desea puede consultarlos en el monitor de corridas.", colorDialogoActivo);
                jTxtHoraInicial.requestFocusInWindow();break;
        }
    }//GEN-LAST:event_jTxtFrecuenciaKeyPressed

    private void jTxtHoraFinalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtHoraFinalKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE: 
                DialogoSiNo = new JDlgSiNo("¡Confirme!", "¿Desea cancelar el proceso?");
                if(!DialogoSiNo.getResultado()) return;
                liberarCorridas();
                this.dispose(); break;
            case KeyEvent.VK_RIGHT: jTxtFrecuencia.selectAll(); jTxtFrecuencia.requestFocusInWindow(); break;
            case KeyEvent.VK_LEFT: jTxtHoraInicial.selectAll(); jTxtHoraInicial.requestFocusInWindow(); break;
            case KeyEvent.VK_ENTER:
                if(!ValidaHoras()) return;
                if(!ValidarHoraFrecuencia()) return;
                ejecutoCalculo(); break;
        }
    }//GEN-LAST:event_jTxtHoraFinalKeyPressed

    private void jTxtHoraInicialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtHoraInicialKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE: 
                DialogoSiNo = new JDlgSiNo("¡Confirme!", "¿Desea cancelar?");
                if(!DialogoSiNo.getResultado()) return;
                liberarCorridas();
                this.dispose(); break;
            case KeyEvent.VK_RIGHT: jTxtHoraFinal.selectAll(); jTxtHoraFinal.requestFocusInWindow(); break;
            case KeyEvent.VK_LEFT: jComboBox1.requestFocusInWindow(); break;
            case KeyEvent.VK_ENTER:
                if(!ValidaHoras()) return;
                if(!ValidarHoraFrecuencia()) return;
                ejecutoCalculo(); break;
        }
    }//GEN-LAST:event_jTxtHoraInicialKeyPressed

    private void ejecutoCalculo(){
        strFecha1 = hoyEs + " " + jTxtHoraInicial.getText();
        String strFecha2 = hoyEs + " " + jTxtHoraFinal.getText();
        int resultado = sesionVenta.corridasAProcesarVenta(jComboBox1.getSelectedItem().toString(), strFecha1, strFecha2);
        switch(resultado){
            case -1: DialogoAceptar = new JDlgAceptar("¡Error al tratar de recuperar informacion de la base de datos!", "Contacte al administrador del sistema.", Color.RED); break;
            case 0: DialogoAceptar = new JDlgAceptar("Resultados de busqueda", "No existen corridas en este periodo de tiempo.", Color.RED); return;
            case 1: 
                int resultado2 = sesionVenta.corridasAProcesarNormal();
                switch(resultado){
                    case -1: DialogoAceptar = new JDlgAceptar("¡Error al tratar de recuperar informacion de la base de datos!", "<html>Es posible que el estado de las corridas de venta este en proceso.<br>Contacte al administrador del sistema.</html>", Color.RED); break;
                    case 0: DialogoAceptar = new JDlgAceptar("¡Error al tratar de recuperar informacion de la base de datos!", "<html>ID's de corridas_venta y corrida no coinciden.<br>Contacte al administrador del sistema.</html>", Color.RED); break;
                    case 1: listado1 = sesionVenta.corridasAProcesar();
                        if(listado1==null)
                            DialogoAceptar = new JDlgAceptar("¡Error al tratar de recuperar informacion de la base de datos!", "<html>Es posible que el estado de las corridas de venta este en proceso.<br>Contacte al administrador del sistema.</html>", Color.RED);
                        else{
                            xListado1.setDataVector(listado1,encabezado1);
                            AnchoColumnas1();
                            jTxtHoraInicial.setEnabled(false);
                            jTxtHoraFinal.setEnabled(false);
                             jComboBox1.setEnabled(false);
                            jLblMensajes.setText(barraMensajes.getMsgRolCadena(1));
                            this.CalculoRolCadena();
                            jTxtFrecuencia.requestFocusInWindow();
                            return;
                        }
                }
                break;
        }
        this.dispose();
        return;
    }
    
    public int liberarCorridas(){
        if(jTblCorridas.getRowCount()==0) return -1;
        int resultado = sesionVenta.liberarCorridas();
        switch(resultado){
            case -1: case 0: DialogoAceptar = new JDlgAceptar("¡Error al tratar de recuperar informacion de la base de datos!", "<html>El estado de las corridas actuales quedo en proceso<br>Contacte al administrador del sistema.</html>", Color.RED); break;
            case 1: 
                int resultado2 = sesionVenta.liberarCorridasVenta();
                switch(resultado){
                    case -1: case 0: DialogoAceptar = new JDlgAceptar("¡Error al tratar de recuperar informacion de la base de datos!", "<html>Es posible que el estado de las corridas de venta este en proceso.<br>Contacte al administrador del sistema.</html>", Color.RED); break;
                    case 1: return 0;
                }
                break;
        }
        return 1;
    }
    
    private boolean ValidaHoras(){
        if(jComboBox1.getSelectedItem()==null) return false;
        if(jTxtHoraInicial.getText().equals("") || jTxtHoraInicial.getText().length()!=5){
            DialogoAceptar = new JDlgAceptar("¡Hora invalida!", "Escriba una hora inicial correcta.", Color.RED);
            jTxtHoraInicial.selectAll();
            jTxtHoraInicial.requestFocusInWindow();
            return false;
        }
        
        try {
            horaInicial= new Timestamp(formatoFechaHora.parse(hoyEs+" "+jTxtHoraInicial.getText()).getTime());
        } catch (ParseException ex) {
            DialogoAceptar = new JDlgAceptar("¡Importante!","¡El valor del campo hora es incorrecto!", Color.RED);
            jTxtHoraInicial.selectAll();
            jTxtHoraInicial.requestFocusInWindow();
            return false;
        }
        Timestamp tmActual=new Timestamp(new Date().getTime()-59000);
        
        if(tmActual.getTime()>horaInicial.getTime()){
            DialogoAceptar = new JDlgAceptar("¡Hora inicial pasada!","Ingrese un valor actual o posterior.", Color.RED);
            jTxtHoraInicial.selectAll();
            jTxtHoraInicial.requestFocusInWindow();
            return false;
        }
        
        if(jTxtHoraFinal.getText().equals("") || jTxtHoraFinal.getText().length()!=5){
            DialogoAceptar = new JDlgAceptar("¡Hora invalida!", "Escriba una hora final correcta.", Color.RED);
            jTxtHoraFinal.selectAll();
            jTxtHoraFinal.requestFocusInWindow();
            return false;
        }
        
        if(jTxtFrecuencia.getText().equals("")){
            DialogoAceptar = new JDlgAceptar("¡Frecuencia invalida!", "Escriba una frecuencia correcta.", Color.RED);
            jTxtFrecuencia.requestFocusInWindow();
            return false;
        }
        
        return true;
    }
        
    private void centrarJDialog(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, ( screenSize.height - frameSize.height ) / 2 );
    }
    
    private boolean ValidarHoraFrecuencia(){
        Frecuencia = Integer.valueOf(jTxtFrecuencia.getText());
        if(Frecuencia>1440){
            DialogoAceptar = new JDlgAceptar("¡Frecuencia fuera de rango!","<html>Valor maximo 1440 minutos.<br>Presione ENTER para continuar...</html>", Color.RED);
            jTxtFrecuencia.selectAll();
            jTxtFrecuencia.requestFocusInWindow();
            return false;
        }
        
        if(Frecuencia==0){
            DialogoAceptar = new JDlgAceptar("¡Frecuencia incorrecta!","<html>La <font color=ff0000>frecuencia</font> no debe ser 0.</html>", Color.RED);
            jTxtFrecuencia.selectAll();
            jTxtFrecuencia.requestFocusInWindow();
            return false;
        }
        
        try {
            horaInicial= new Timestamp(formatoHora.parse(jTxtHoraInicial.getText()).getTime());
        } catch (ParseException ex) {
            DialogoAceptar = new JDlgAceptar("¡Importante!","¡El valor del campo hora es incorrecto!", Color.RED);
            jTxtHoraInicial.selectAll();
            jTxtHoraInicial.requestFocusInWindow();
            return false;
        }
        
        try {
            horaFinal= new Timestamp(formatoHora.parse(jTxtHoraFinal.getText()).getTime());
        } catch (ParseException ex) {
            DialogoAceptar = new JDlgAceptar("¡Importante!","¡El valor del campo hora es incorrecto!", Color.RED);
            jTxtHoraFinal.selectAll();
            jTxtHoraFinal.requestFocusInWindow();
            return false;
        }
        
        if(this.horaInicial.getTime()>horaFinal.getTime()){
            DialogoAceptar = new JDlgAceptar("¡Hora final incorrecta!","<html><font color=ff0000>Hora final</font> debe ser mayor que <font color=ff0000>hora inicial</font>.</html>", Color.RED);
            jTxtHoraFinal.setText("");
            jTxtHoraFinal.selectAll();
            jTxtHoraFinal.requestFocusInWindow();
            return false;
        }
        
        minutos = (horaFinal.getTime()-this.horaInicial.getTime())/60000;
        if(minutos<Frecuencia){
            DialogoAceptar = new JDlgAceptar("¡Frecuencia incorrecta!","<html>La <font color=ff0000>frecuencia</font> debe ser menor o igual <br>que la diferencia entre hora inicial y final.</html>", Color.RED);
            jTxtFrecuencia.selectAll();
            jTxtFrecuencia.requestFocusInWindow();
            return false;
        }
        return true;
    }
    
    public float roundNum(float num, int ndec){
        float valor = 0;
        valor = num;
        valor = valor*ndec;
        valor = Math.round(valor);
        valor = valor/ndec;
        return valor;
    }
    
    private void CalculoRolCadena(){
        salidasCalculadas = (int)(minutos / Frecuencia)+1;
        String msgCalculo="";
        recorte=Math.abs(salidasCalculadas-listado1.length);
        String mensaje="";
        casoRolCadena = 0;
        if(salidasCalculadas>listado1.length){
            corridasExtra = new ArrayList<TmsCorridasVentaV>();
            casoRolCadena = 1;
            mensaje = (recorte == 1 ? " corrida extra creada" : " corridas extras creadas");
            msgCalculo = "<br><font color=ff0000>"+recorte+mensaje+"</font>.";
        }
        if(salidasCalculadas<listado1.length){
            casoRolCadena = 2;
            mensaje = (recorte == 1 ? " corrida cancelada" : " corridas canceladas");
            msgCalculo = "<br><font color=ff0000>"+recorte+mensaje+"</font>.";
        }
        // INFORME
        if(minutos<60)
            jLblResultados.setText("<html><font color=ff0000>"+listado1.length+"</font> corridas disponibles.<br><font color=ff0000>"+salidasCalculadas+"</font> salidas calculadas para un tiempo de <font color=ff0000>"+
                minutos+"</font> "+(minutos==1 ? "minuto" : "minutos")+"."+msgCalculo+"</html>");
        else{
            float hora = minutos/60;
            jLblResultados.setText("<html><font color=ff0000>"+listado1.length+"</font> corridas disponibles.<br><font color=ff0000>"+salidasCalculadas+"</font> salidas calculadas para un tiempo de <font color=ff0000>"+
                roundNum(hora,2)+"</font> "+(hora==1 ? "hora" : "horas")+"."+msgCalculo+"</html>");
        }
        // datos tabla horario
        MinutosFrecuencia=Frecuencia*60000;
        listado2 = new Object[salidasCalculadas][5];
        Timestamp calculoHorario = null;
        Vector z;
        for(int i=0; i<salidasCalculadas; i++){
            if(i<listado1.length){
                listado2[i][0] = listado1[i][0];
                listado2[i][1] = listado1[i][1];
                listado2[i][2] = listado1[i][2];
                z=new Vector();
                z = (Vector) sesionVenta.getConjuntoCorridas().get(i);
                listado2[i][4] = z.get(0);
            }
            else{
                listado2[i][0] = "EXTRA";
                listado2[i][1] = "E";
                listado2[i][2] = "A";
                listado2[i][4] = null;
            }
           
            try {
                calculoHorario = new Timestamp(formatoFechaHora.parse(strFecha1).getTime()+(i*MinutosFrecuencia));
            } catch (ParseException ex) {
                ex.printStackTrace();
            }
            
            listado2[i][3] = formatoHora.format(calculoHorario);
        }
        xListado2.setDataVector(listado2, encabezado2);
        AnchoColumnas2();
    }

    private boolean ValidarFrecuencia() {
        if(jTxtFrecuencia.getText().equals("")){
            DialogoAceptar = new JDlgAceptar("¡Frecuencia invalida!", "Escriba una frecuencia correcta.", Color.RED);
            jTxtFrecuencia.requestFocusInWindow();
            return false;
        }
        
        Frecuencia = Integer.valueOf(jTxtFrecuencia.getText());
        if(Frecuencia>1440){
            DialogoAceptar = new JDlgAceptar("¡Frecuencia fuera de rango!","<html>Valor maximo 1440 minutos (1 dia).<br>Presione ENTER para continuar...</html>", Color.RED);
            jTxtFrecuencia.selectAll();
            jTxtFrecuencia.requestFocusInWindow();
            return false;
        }
        
        if(Frecuencia==0){
            DialogoAceptar = new JDlgAceptar("¡Frecuencia incorrecta!","<html>La <font color=ff0000>frecuencia</font> no debe ser 0.</html>", Color.RED);
            jTxtFrecuencia.selectAll();
            jTxtFrecuencia.requestFocusInWindow();
            return false;
        }
        
        if(minutos<Frecuencia){
            DialogoAceptar = new JDlgAceptar("¡Frecuencia incorrecta!","<html>La <font color=ff0000>frecuencia</font> debe ser menor o igual <br>que la diferencia entre hora inicial y final.</html>", Color.RED);
            jTxtFrecuencia.selectAll();
            jTxtFrecuencia.requestFocusInWindow();
            return false;
        }
        return true;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLblMensajes;
    private javax.swing.JLabel jLblResultados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTblCalculo;
    private javax.swing.JTable jTblCorridas;
    private javax.swing.JTextField jTxtFrecuencia;
    private javax.swing.JTextField jTxtHoraFinal;
    private javax.swing.JTextField jTxtHoraInicial;
    // End of variables declaration//GEN-END:variables
    private SesionVenta sesionVenta = null;
    private JDlgAceptar DialogoAceptar;
    private JDlgSiNo DialogoSiNo;
    private Object[] encabezado1 = {"Clave", "T", "E", "Servicio", "Empresa", "Origen", "Destino", "Horario"};
    private DefaultTableModel xListado1 = new DefaultTableModel(null, encabezado1){
            public boolean isCellEditable(int row, int col) {
                return false;
            }   
    };
    private Object[][] listado1;
    private Object[] encabezado2 = {"Clave", "T", "E", "Horario"};
    private DefaultTableModel xListado2 = new DefaultTableModel(null, encabezado2){
            public boolean isCellEditable(int row, int col) {
                if(col==0 && row == filaEspecial) return true;
                return false;
            }   
    };
    private Object[][] listado2;
    private SimpleDateFormat formatoFechaHora= new SimpleDateFormat("dd/MM/yyyy HH:mm");
    private SimpleDateFormat formatoHora= new SimpleDateFormat("HH:mm");
    private SimpleDateFormat formatoFecha= new SimpleDateFormat("dd/MM/yyyy");
    private int fila=-1;
    private String hoyEs = formatoFecha.format(new Date());
    private BarraMensajes barraMensajes = new BarraMensajes();
    private int Frecuencia;
    private long MinutosFrecuencia;
    private Timestamp horaInicial;
    private Timestamp horaFinal;
    private float minutos;
    private int salidasCalculadas=-1;
    private String strFecha1;

    private int casoRolCadena;
    int recorte;
    private List<TmsCorridasVentaV> corridasExtra = null;
    private Color colorDialogoActivo = new Color(0,83,255);
    private int filaEspecial = -1;
    
    private String[] res;
}