/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JPanelExcepciones.java
 *
 * Created on 10/06/2014, 05:40:13 PM
 */
package tms_incidencias;

import DialogosIncidencias.JDlgSiNo;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Timestamp;
import java.util.Date;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import tms_incidencias.entidad.TmsActAdicionalesTbl;
import tms_incidencias.entidad.TmsExcepcionIncidenciaTbl;
import tms_incidencias.gui.modelos.DefaultComboBoxModel;
import tms_incidencias.interfaces.ComboBoxModelList;
import tms_incidencias.modelo.ActividadAdicional;
import tms_incidencias.util.SwingUtilities;
import tms_incidencias.works.CargarExcepcionesIncidencia;
import tms_incidencias.works.EliminarExcepcionIncidencia;
import tms_incidencias.works.GuardarExcepcionIncidencia;

/**
 *
 * @author Osvaldo Sanchez
 */
public class JPanelExcepciones extends javax.swing.JPanel {

    /** Creates new form JPanelExcepciones */
    public JPanelExcepciones(SesionVenta pSesionVenta,Long idUsuario1) {
        idUsuario=idUsuario1;
        sesionVenta = pSesionVenta;
        initComponents();
        initTabla();
        llenarCombosIncidencias();
        cargarExcepciones();
        anchoColumnas();
        //Se obtiene el jframe padre para mostrar el dialogo de espera
        java.awt.Container c = this.getParent();
        while (!(c instanceof javax.swing.JFrame) && (c != null)) {
            c = c.getParent();
        }
        parentFrame = (JFrame) c;
        this.setFocusable(true);
        //Se asignan los eventos del teclado al panel
        this.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0), "F5");
        this.getActionMap().put(F5, f5);
        this.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "ESCAPE");
        this.getActionMap().put(ESCAPE, escape);
        this.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), "F10");
        this.getActionMap().put(F10, f10);
        //Se asignan los eventos del teclado a los combos
        jComboIncidencia1.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0), "F5");
        jComboIncidencia1.getActionMap().put(F5, f5);
        jComboIncidencia1.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), "F10");
        jComboIncidencia1.getActionMap().put(F10, f10);
        jComboIncidencia2.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0), "F5");
        jComboIncidencia2.getActionMap().put(F5, f5);
        jComboIncidencia2.getInputMap().put(KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), "F10");
        jComboIncidencia2.getActionMap().put(F10, f10);
        jComboIncidencia1.requestFocus();

    }
 
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelAgregarExcepcion = new javax.swing.JPanel();
        jLabelIncidencia1 = new javax.swing.JLabel();
        jLabelExcepcion2 = new javax.swing.JLabel();
        jComboIncidencia1 = new javax.swing.JComboBox();
        jComboIncidencia2 = new javax.swing.JComboBox();
        jPanelExcepciones = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableExcepciones = new javax.swing.JTable();
        jPanelEstatus = new javax.swing.JPanel();
        jLblBarraEstado = new javax.swing.JLabel();

        jPanelAgregarExcepcion.setBorder(javax.swing.BorderFactory.createTitledBorder("Agregar Excepcion"));

        jLabelIncidencia1.setText("Incidencia 1:");

        jLabelExcepcion2.setText("Incidencia 2:");

        jComboIncidencia1.setModel(new DefaultComboBoxModel());
        jComboIncidencia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboIncidencia1ActionPerformed(evt);
            }
        });
        jComboIncidencia1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboIncidencia1FocusGained(evt);
            }
        });
        jComboIncidencia1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboIncidencia1KeyPressed(evt);
            }
        });

        jComboIncidencia2.setModel(new DefaultComboBoxModel());
        jComboIncidencia2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboIncidencia2ActionPerformed(evt);
            }
        });
        jComboIncidencia2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboIncidencia2FocusGained(evt);
            }
        });
        jComboIncidencia2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboIncidencia2KeyPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanelAgregarExcepcionLayout = new org.jdesktop.layout.GroupLayout(jPanelAgregarExcepcion);
        jPanelAgregarExcepcion.setLayout(jPanelAgregarExcepcionLayout);
        jPanelAgregarExcepcionLayout.setHorizontalGroup(
            jPanelAgregarExcepcionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelAgregarExcepcionLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelAgregarExcepcionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jPanelAgregarExcepcionLayout.createSequentialGroup()
                        .add(jLabelIncidencia1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jComboIncidencia1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 228, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanelAgregarExcepcionLayout.createSequentialGroup()
                        .add(jLabelExcepcion2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jComboIncidencia2, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(461, Short.MAX_VALUE))
        );
        jPanelAgregarExcepcionLayout.setVerticalGroup(
            jPanelAgregarExcepcionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelAgregarExcepcionLayout.createSequentialGroup()
                .addContainerGap()
                .add(jPanelAgregarExcepcionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelIncidencia1)
                    .add(jComboIncidencia1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanelAgregarExcepcionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabelExcepcion2)
                    .add(jComboIncidencia2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanelExcepciones.setBorder(javax.swing.BorderFactory.createTitledBorder("Excepciones"));

        jTableExcepciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableExcepciones.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTableExcepcionesFocusLost(evt);
            }
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTableExcepcionesFocusGained(evt);
            }
        });
        jTableExcepciones.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableExcepcionesKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableExcepciones);

        org.jdesktop.layout.GroupLayout jPanelExcepcionesLayout = new org.jdesktop.layout.GroupLayout(jPanelExcepciones);
        jPanelExcepciones.setLayout(jPanelExcepcionesLayout);
        jPanelExcepcionesLayout.setHorizontalGroup(
            jPanelExcepcionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        jPanelExcepcionesLayout.setVerticalGroup(
            jPanelExcepcionesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 167, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        jPanelEstatus.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLblBarraEstado.setText("<html><font color=ff0000>ARR/ABA </font>Seleccione Incidencia| <font color=ff0000>F5</font> Buscar </html>");

        org.jdesktop.layout.GroupLayout jPanelEstatusLayout = new org.jdesktop.layout.GroupLayout(jPanelEstatus);
        jPanelEstatus.setLayout(jPanelEstatusLayout);
        jPanelEstatusLayout.setHorizontalGroup(
            jPanelEstatusLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanelEstatusLayout.createSequentialGroup()
                .add(jLblBarraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 768, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelEstatusLayout.setVerticalGroup(
            jPanelEstatusLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelEstatusLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .add(jLblBarraEstado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanelAgregarExcepcion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanelExcepciones, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanelEstatus, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanelAgregarExcepcion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelExcepciones, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanelEstatus, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableExcepcionesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableExcepcionesKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableExcepcionesKeyPressed

    private void jComboIncidencia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboIncidencia1ActionPerformed
        // TODO add your handling code here:
        actualizaBarraEstado();
    }//GEN-LAST:event_jComboIncidencia1ActionPerformed

    private void jComboIncidencia2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboIncidencia2ActionPerformed
        // TODO add your handling code here:
        actualizaBarraEstado();
    }//GEN-LAST:event_jComboIncidencia2ActionPerformed

    private void jTableExcepcionesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableExcepcionesFocusGained
        // TODO add your handling code here:
        if(!sePuedeGuardar)
            jLblBarraEstado.setText("<html><font color=ff0000>ARR/ABA</font>Seleccione Excepcion| <font color=ff0000>Supr</font> Eliminar </html>");
        else
            jLblBarraEstado.setText("<html><font color=ff0000>ARR/ABA</font>Seleccione Excepcion| <font color=ff0000>Supr</font> Eliminar| <font color=ff0000>F10</font> Guardar </html>");
    }//GEN-LAST:event_jTableExcepcionesFocusGained

    private void jTableExcepcionesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTableExcepcionesFocusLost
        // TODO add your handling code here:
        actualizaBarraEstado();
    }//GEN-LAST:event_jTableExcepcionesFocusLost

    private void jComboIncidencia1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboIncidencia1FocusGained
        // TODO add your handling code here:
        actualizaBarraEstado();
    }//GEN-LAST:event_jComboIncidencia1FocusGained

    private void jComboIncidencia2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboIncidencia2FocusGained
        // TODO add your handling code here:
        actualizaBarraEstado();
    }//GEN-LAST:event_jComboIncidencia2FocusGained

    private void jComboIncidencia1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboIncidencia1KeyPressed
        // TODO add your handling code here:
        switch(evt.getKeyCode()){
             case KeyEvent.VK_DOWN:
                jComboIncidencia1.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jComboIncidencia1KeyPressed

    private void jComboIncidencia2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboIncidencia2KeyPressed
        // TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_UP:
                jComboIncidencia1.requestFocusInWindow();
                break;
             case KeyEvent.VK_DOWN:
                jTableExcepciones.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jComboIncidencia2KeyPressed

    /**
     * Accion cuando se presiona la tecla F5
     */
    private Action f5 = new AbstractAction(F5) {

        //////@Override
        public void actionPerformed(ActionEvent e) {
             cargarExcepciones();
        }
    };

     /**
     * Accion cuando se presiona la tecla ESCAPE
     */
    private Action escape = new AbstractAction(ESCAPE) {
        //////@Override
        public void actionPerformed(ActionEvent e) {
             jComboIncidencia1.requestFocus();
        }
    };

     /**
     * Accion cuando se presiona la tecla F10
     */
    private Action f10 = new AbstractAction(ESCAPE) {
        //////@Override
        public void actionPerformed(ActionEvent e) {
              if (sePuedeGuardar) {
                    guardarExcepcion();
                }
        }
    };
/**
 * Actualiza la barra de estado
 * para activar el guardado dependiendo
 * si tiene valores ambos combos de incidencias
 */
    private void actualizaBarraEstado() {
        if (jComboIncidencia1.getSelectedIndex() == -1 || jComboIncidencia2.getSelectedIndex() == -1) {
            jLblBarraEstado.setText("<html><font color=ff0000>ARR/ABA</font>Seleccione Incidencia| <font color=ff0000>F5</font> Buscar </html>");
            sePuedeGuardar = false;
        } else {
            jLblBarraEstado.setText("<html><font color=ff0000>F10</font>Guardar| <font color=ff0000>F5</font> Buscar </html>");
            sePuedeGuardar = true;
        }
    }

    /**
     * Metodo que llena ambos combos de incidencias
     */
    private void llenarCombosIncidencias() {
        List<ActividadAdicional> incidencias = (List<ActividadAdicional>) sesionVenta.getActividadesAdicionalesIncidencias();
       if(incidencias!=null && incidencias.size()>0)
        ((ComboBoxModelList<ActividadAdicional>) jComboIncidencia1.getModel()).add(incidencias);
        ((ComboBoxModelList<ActividadAdicional>) jComboIncidencia2.getModel()).add(incidencias);
    }

    private void cargarExcepciones() {
        //Se muestra dialogo en espera en pantalla
        JDialog dialogoEspera = SwingUtilities.getDialogoEspera(parentFrame);
        dialogoEspera.setVisible(true);
        CargarExcepcionesIncidencia c = new CargarExcepcionesIncidencia((DefaultTableModel) jTableExcepciones.getModel(), dialogoEspera, sesionVenta);
        c.execute();
        jComboIncidencia1.requestFocus();
    }

    /**
     * Inicializa la configuracion
     * de la tabla de excepciones
     */
    private void initTabla() {

    jTableExcepciones.setRowSelectionInterval(0,0);
        modelo = new DefaultTableModel(null, encabezado) {

            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        // ListSelectionModel cellSelectionModel = jTableExcepciones.getSelectionModel();
        // cellSelectionModel.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        jTableExcepciones.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        modelo.setDataVector(null, encabezado);
        jTableExcepciones.setModel(modelo);

        //Se agregan los eventos del teclado a la tabla
        InputMap inputMap = jTableExcepciones.getInputMap(WHEN_FOCUSED);
        ActionMap actionMap = jTableExcepciones.getActionMap();
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0), "F5");
        actionMap.put(F5, f5);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), "F10");
        actionMap.put(F10, f10);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), "ESCAPE");
        actionMap.put(ESCAPE, escape);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_DELETE, 0), "delete");
        actionMap.put("delete", new AbstractAction() {
            public void actionPerformed(ActionEvent evt) {
                if(jTableExcepciones.getSelectedRow()>=0)
                eliminarExcepcion((Short) jTableExcepciones.getModel().getValueAt(jTableExcepciones.getSelectedRow(), 0));

            }
        });

    }

    /**
     * Establece el ancho de las columnas
     * de la tabla de excepciones
     * dependiendo el ancho del panel
     */
    private void anchoColumnas() {
        jTableExcepciones.getColumnModel().getColumn(0).setMaxWidth(0);
        jTableExcepciones.getColumnModel().getColumn(0).setMinWidth(0);
        jTableExcepciones.getColumnModel().getColumn(0).setPreferredWidth(0);
        int anchoContenedor = this.getWidth();
        TableColumn column;
        for (int i = 0; i < jTableExcepciones.getColumnCount(); i++) {
            column = jTableExcepciones.getColumnModel().getColumn(i);
            switch (i) {
                case 0:
                    column.setPreferredWidth(0);
                    break;
                case 1:
                    column.setPreferredWidth(Math.round(anchoContenedor * (float) 0.10));
                    break;
                case 2:
                    column.setPreferredWidth(Math.round(anchoContenedor * (float) 0.15));
                    break;
                case 3:
                    column.setPreferredWidth(Math.round(anchoContenedor * (float) 0.15));
                    break;
                case 4:
                    column.setPreferredWidth(Math.round(anchoContenedor * (float) 0.10));
                    break;
            }
        }
    }

    /**
     * Asigna valores a la excepcion
     * y se invoca el Worker correspondiente
     * para guardar
     */
    private void guardarExcepcion() {
        //Se asignan valores al nuevo objeto
        TmsExcepcionIncidenciaTbl excepcion = new TmsExcepcionIncidenciaTbl();
        excepcion.setCreadoPor(idUsuario);
        excepcion.setFechaCreacion(new Timestamp(new Date().getTime()));
        excepcion.setTipoActividadAdicional1(new TmsActAdicionalesTbl(((ActividadAdicional) jComboIncidencia1.getModel().getSelectedItem()).getId()));
        excepcion.setTipoActividadAdicional2(new TmsActAdicionalesTbl(((ActividadAdicional) jComboIncidencia2.getModel().getSelectedItem()).getId()));
        restablecer();
        //Se muestra dialogo en espera en pantalla
        JDialog dialogoEspera = SwingUtilities.getDialogoEspera(parentFrame);
        dialogoEspera.setVisible(true);
        GuardarExcepcionIncidencia guardar = new GuardarExcepcionIncidencia(excepcion, sesionVenta, dialogoEspera, jTableExcepciones);
        guardar.execute();
    }

    /**
     * Restablece valores de inicio
     */
    public void restablecer(){
        jComboIncidencia1.setSelectedIndex(-1);
        jComboIncidencia2.setSelectedIndex(-1);
        sePuedeGuardar=false;
        jComboIncidencia1.requestFocusInWindow();
    }

    /**
     * Elimina una excepcion seleccionada
     * @param id
     */
    private void eliminarExcepcion(Short id) {
        JDlgSiNo dialogoSiNo = new JDlgSiNo("¡Confirme!", "¿Desea eliminar la excepcion seleccionada?");
        boolean r = dialogoSiNo.getResultado();
        if (r) {
            JDialog dialogoEspera = SwingUtilities.getDialogoEspera(parentFrame);
            dialogoEspera.setVisible(true);
            EliminarExcepcionIncidencia eliminar = new EliminarExcepcionIncidencia(id, sesionVenta, dialogoEspera,jTableExcepciones);
            eliminar.execute();
        }
    }



    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboIncidencia1;
    private javax.swing.JComboBox jComboIncidencia2;
    private javax.swing.JLabel jLabelExcepcion2;
    private javax.swing.JLabel jLabelIncidencia1;
    private javax.swing.JLabel jLblBarraEstado;
    private javax.swing.JPanel jPanelAgregarExcepcion;
    private javax.swing.JPanel jPanelEstatus;
    private javax.swing.JPanel jPanelExcepciones;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableExcepciones;
    // End of variables declaration//GEN-END:variables
    private SesionVenta sesionVenta = null;
    private Object[] encabezado = {"ID", "INCIDENCIA 1", "INCIDENCIA 2", "CREADA POR", "FECHA DE CREACION"};
    private DefaultTableModel modelo;
    private JFrame parentFrame;
    private boolean sePuedeGuardar;
    private static final String F5 = "F5";
    private static final String ESCAPE = "ESCAPE";
    private static final String F10 = "F10";
    private Long idUsuario;
}
