/*
 * JIFCorteRecaudacion.java
 *
 * Created on 15 de agosto de 2007, 12:05 PM
 */

package corterecaudacion;

import corterecaudacion.util.jdlg_pregunta_detallado;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.io.IOException;
import java.io.InputStream;
import java.math.BigDecimal;
import java.net.Socket;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import xertmsCorteReca.entidad.TmsCortesTbl;
import xertmsCorteReca.entidad.TmsUsuariosTbl;

/**
 *
 * @author  vgonzalez
 */
public class JIFCorteRecaudacion extends javax.swing.JInternalFrame {
    private KeyEvent eventoTeclado;
    
    /** Creates new form JIFCorteRecaudacion */
    public JIFCorteRecaudacion(Vector pDatosIniciales) {
        this.datosIniciales = pDatosIniciales;
        this.usuario = Long.valueOf(datosIniciales.get(0).toString());
        this.ipAS = datosIniciales.get(5).toString();
        this.portAS = Integer.valueOf(datosIniciales.get(6).toString());
        initComponents();
        JDialog d = new JDialog();
        d.setDefaultLookAndFeelDecorated(true);
        d.dispose();
        d = null;
        busquedas = new TMSCorteRecManagedBean();
        jtbl_cortes.setModel(modeloCortes);
        resizeColumnas();
        this.setTitle("TMSRecauda Rev16.07.08");
        //((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy");
        jtxt_fecha.setFocusTraversalKeysEnabled(false);
        jlbl_barraEstado.setText("<html>  <font color=FF0000>F4 </font> Salir | <font color=FF0000> Enter </font> Buscar Cortes |  <font color=FF0000> F2 </font> Seleccionar/Deseleccionar solo pendientes  |  <font color=FF0000> F3 </font> Seleccionar/Deseleccionar Todos los cortes pendientes  | <font color=FF0000>CTRL+2</font> Minimizar ventana | <font color=FF0000>CTRL+1</font> Mostrar siguiente ventana</html>");
        jtxt_fecha.setText(ff.format(new Date()));
        jtxt_fecha.selectAll();
        this.addComponentListener(new ComponentAdapter() {public void componentShown(ComponentEvent ce) {jtxt_fecha.requestFocus();}});
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        grupo_botones = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jchbx_pendientes = new javax.swing.JCheckBox();
        jchbx_pendientes.setSelected(true);
        jtxt_fecha = new tms_TextFields.JDateTextField();
        jchbx_todosPendientes = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbl_cortes = new javax.swing.JTable();
        jtbl_cortes = new JTable(modeloCortes);
        jtbl_cortes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jlbl_barraEstado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Busqueda de Cortes"));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Fecha:");
        jLabel1.setFocusable(false);

        jchbx_pendientes.setFont(new java.awt.Font("Tahoma", 1, 11));
        jchbx_pendientes.setText("Solo Pedientes");
        jchbx_pendientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jchbx_pendientes.setFocusable(false);
        jchbx_pendientes.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jtxt_fecha.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_fechaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxt_fechaFocusLost(evt);
            }
        });
        jtxt_fecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_fechaKeyPressed(evt);
            }
        });

        jchbx_todosPendientes.setFont(new java.awt.Font("Tahoma", 1, 11));
        jchbx_todosPendientes.setText("Todos los Pendientes");
        jchbx_todosPendientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jchbx_todosPendientes.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jtxt_fecha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 149, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(17, 17, 17)
                .add(jchbx_pendientes)
                .add(20, 20, 20)
                .add(jchbx_todosPendientes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jchbx_todosPendientes)
                    .add(jtxt_fecha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jchbx_pendientes))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Cortes de Usuario"));
        jtbl_cortes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtbl_cortes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtbl_cortesFocusGained(evt);
            }
        });
        jtbl_cortes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbl_cortesKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtbl_cortesKeyReleased(evt);
            }
        });

        jScrollPane1.setViewportView(jtbl_cortes);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );

        jlbl_barraEstado.setFont(new java.awt.Font("Tahoma", 1, 11));
        jlbl_barraEstado.setText("jLabel2");
        jlbl_barraEstado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Rev05.10.10");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(759, Short.MAX_VALUE)
                .add(jLabel2)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(168, 168, 168)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(163, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jlbl_barraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 839, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel2)
                .add(17, 17, 17)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(24, 24, 24)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 70, Short.MAX_VALUE)
                .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxt_fechaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_fechaFocusLost
         jtxt_fecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
    }//GEN-LAST:event_jtxt_fechaFocusLost

    private void jtxt_fechaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_fechaFocusGained
      jlbl_barraEstado.setText("<html>  <font color=FF0000>F4 </font> Salir | <font color=FF0000> Enter </font> Buscar Cortes |  <font color=FF0000> F2 </font> Seleccionar/Deseleccionar solo pendientes  |  <font color=FF0000> F3 </font> Seleccionar/Deseleccionar Todos los cortes pendientes  | <font color=FF0000>CTRL+2</font> Minimizar ventana | <font color=FF0000>CTRL+1</font> Mostrar siguiente ventana</html>");
      jtxt_fecha.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 88, 236)));
        
    }//GEN-LAST:event_jtxt_fechaFocusGained

    private void jtxt_fechaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_fechaKeyPressed
        if(evt.getKeyCode() == evt.VK_1 && evt.isControlDown()){
            setEventoTeclado(evt);
            try {this.setIcon(true);} catch (PropertyVetoException ex) { ; }
            return;
        }
        
        if(evt.getKeyCode() == evt.VK_2 && evt.isControlDown()){
            try {this.setIcon(true);} catch (PropertyVetoException ex) { ; }
            return;
        }

        if(evt.getKeyCode() == evt.VK_ENTER)
       {
             String campoFecha = jtxt_fecha.getText();
              if(campoFecha.length()==10 || jchbx_todosPendientes.isSelected())
                  buscarCortes();
               else
                {
                     JOptionPane.showMessageDialog(this,"         ¡La fecha es invalida!\n Favor de introducir una fecha valida","Fecha Invalida",JOptionPane.ERROR_MESSAGE);
                     jlbl_barraEstado.setText("<html>  <font color=FF0000>F4 </font> Salir | <font color=FF0000> Enter </font> Buscar Cortes |  <font color=FF0000> F2 </font> Seleccionar/Deseleccionar solo pendientes  |  <font color=FF0000> F3 </font> Seleccionar/Deseleccionar Todos los cortes pendientes</html>");
                     jtxt_fecha.setText("");
                     jtxt_fecha.requestFocus();
                }
            
       }    
        if(evt.getKeyCode() == evt.VK_F2)
        {
            if(jchbx_pendientes.isSelected())
                jchbx_pendientes.setSelected(false);
            else
            {
                jchbx_pendientes.setSelected(true);
                jchbx_todosPendientes.setSelected(false);
            }
        }
        
        if(evt.getKeyCode() == evt.VK_F3)
        {
            if(jchbx_todosPendientes.isSelected())
                jchbx_todosPendientes.setSelected(false);
            else
            {
                jchbx_todosPendientes.setSelected(true);
                jchbx_pendientes.setSelected(false);
                jtxt_fecha.setText("");
            }
        }      
       
       if(evt.getKeyCode() == evt.VK_F4)
           salir();
    
    }//GEN-LAST:event_jtxt_fechaKeyPressed

    private void jtbl_cortesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtbl_cortesFocusGained
        jlbl_barraEstado.setText("<html>  <font color=FF0000>ESC </font> Regresar a busquedas | <font color=FF0000> F5 </font> Detallar del Corte |  <font color=FF0000> F6 </font> Imprimir Corte</html>");    
    }//GEN-LAST:event_jtbl_cortesFocusGained

    
    private void jtbl_cortesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbl_cortesKeyReleased
        if(evt.getKeyCode() == evt.VK_F5)
           detalleCorte();
        if(evt.getKeyCode() == evt.VK_F6)
        {
            jdlg_pregunta_detallado di = new jdlg_pregunta_detallado();
            di.setVisible(true);
            System.out.println("Tipo de Corte: "+di.getTipo());
            if(di.getTipo().equals("normal"))
                imprimirCorteNormal();
            if(di.getTipo().equals("detallado"))
                imprimirCorteDetallado();
                
            //imprimirCorte();
        }
    }//GEN-LAST:event_jtbl_cortesKeyReleased

    private void jrbtn_superrapidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbtn_superrapidosKeyPressed
    }//GEN-LAST:event_jrbtn_superrapidosKeyPressed

    private void jrbtn_ampersaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbtn_ampersaKeyPressed
    }//GEN-LAST:event_jrbtn_ampersaKeyPressed

    private void jtbl_cortesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbl_cortesKeyPressed
        if(evt.getKeyCode() == evt.VK_ESCAPE)
        {
             modeloCortes.setDataVector(null,encabezadoCortes);
             jlbl_barraEstado.setText("<html>  <font color=FF0000>F4 </font> Salir | <font color=FF0000> Enter </font> Buscar Cortes |  <font color=FF0000> F2 </font> Seleccionar/Deseleccionar solo pendientes  |  <font color=FF0000> F3 </font> Seleccionar/Deseleccionar Todos los cortes pendientes</html>");
             resizeColumnas();
             jtxt_fecha.setText("");
             jtxt_fecha.requestFocus();
        }  
    }//GEN-LAST:event_jtbl_cortesKeyPressed

    private void jbtn_buscarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbtn_buscarKeyPressed
    }//GEN-LAST:event_jbtn_buscarKeyPressed

   private void salir(){
//      Jdlg_Pregunta salida = new Jdlg_Pregunta("Confirmacion de salida"," ¿Seguro que desea salir de la Aplicacion?");
//      salida.setVisible(true);
//      if(salida.getRespuesta())
      jdlg_pregunta_SN psn =  new jdlg_pregunta_SN("Confirmacion de salida", "¿Seguro que desea salir de la Aplicacion?");
      psn.setVisible(true);
      if(respuestaSN)
          this.dispose();
}
    private void jlbl_salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbl_salirMouseClicked
    }//GEN-LAST:event_jlbl_salirMouseClicked

    private void jbtn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_buscarActionPerformed
    }//GEN-LAST:event_jbtn_buscarActionPerformed
    
    private void jtxt_fecha_keyPressed(KeyEvent e) {
        if(e.getKeyCode() == e.VK_TAB)
            //jtxt_fecha.requestFocus();

       if(e.getKeyCode() == e.VK_ENTER)
       {
             String campoFecha = jtxt_fecha.getText();
              if(campoFecha.length()==10)
                  buscarCortes();
               else
                {
                     JOptionPane.showMessageDialog(this,"         ¡La fecha es invalida!\n Favor de introducir una fecha valida","Fecha Invalida",JOptionPane.ERROR_MESSAGE);
                     jlbl_barraEstado.setText("<html>  <font color=FF0000>F4 </font> Salir | <font color=FF0000> Enter </font> Buscar Cortes |  <font color=FF0000> F2 </font> Seleccionar/Deseleccionar solo pendientes  |  <font color=FF0000> F3 </font> Seleccionar/Deseleccionar Todos los cortes pendientes</html>");
                     jtxt_fecha.setText("");
                     jtxt_fecha.requestFocus();
                }
            
       }    
        if(e.getKeyCode() == e.VK_F2)
        {
            if(jchbx_pendientes.isSelected())
                jchbx_pendientes.setSelected(false);
            else
                jchbx_pendientes.setSelected(true);
        }
        
       if(e.getKeyCode() == e.VK_F4)
           salir();
        
    }
    
    

  private void buscarCortes()   {
      if(!abreSocketAS()){
       new  jdlg_error_conexionBD_NET("En este momento no es posible realizar la operación.","Intentelo mas tarde.","¡No existe una conexión con la Base de Datos!").setVisible(true);
       return;
    }

     String campoFecha = jtxt_fecha.getText();
     boolean reporte = false;
     boolean entra = true;
     if(jchbx_todosPendientes.isSelected())
         entra = true;
     if(campoFecha.length()<10 && !jchbx_todosPendientes.isSelected())
       entra = false;
     if(entra)// campoFecha.length()==10)
      {
         String ts ="cor.NOMBRE_SESION =  'R_AMPERSA'";//"cor.NOMBRE_SESION in ('R_AMPERSA','R_TURISMOER') ";
           //if(jrbtn_ampersa.isSelected())
           //    ts = "cor.NOMBRE_SESION in ('R_AMPERSA','R_TURISMOER') ";
           //else
           //    ts = "cor.NOMBRE_SESION =  'R_SUPERRAPIDOS'";
         if(jchbx_todosPendientes.isSelected())
             listacortes = busquedas.cortesTblFacadeRemote.buscarTodosCortes();
         else
            listacortes = busquedas.cortesTblFacadeRemote.buscarCortes(jtxt_fecha.getText(),jchbx_pendientes.isSelected(),ts);
         
         if(listacortes.size()>0)
         {
             Object[][] datos = new Object[listacortes.size()][6];
             for(int i=0; i<listacortes.size(); i++)
             {
                 Vector vcorte = (Vector)listacortes.get(i); 
                 TmsUsuariosTbl usuario =  busquedas.usuariosTblFacadeRemote.find(BigDecimal.valueOf(Long.valueOf(vcorte.get(1).toString())));
                 datos[i][0] = vcorte.get(0).toString();
                 datos[i][1] = usuario.getUsuarioNumero();
                 datos[i][2] = usuario.getUsuarioNombre();
                 StringTokenizer tokz=new StringTokenizer(vcorte.get(4).toString(),"_");
                 datos[i][3] = tokz.nextToken();
                 datos[i][3] = tokz.nextToken();
                 Timestamp fechaAct = null;
                 fechaAct = fechaAct.valueOf(vcorte.get(2).toString());
                 SimpleDateFormat ff = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
                 Timestamp fechaCor = null;
                 fechaCor = fechaCor.valueOf(vcorte.get(3).toString());
                 datos[i][4] = ff.format(fechaAct);
                 if(vcorte.get(5).toString().equals("R"))
                 {
                     datos[i][5] =  ff.format(fechaCor);
                     reporte = true;
                 }
                 else
                   datos[i][5] =  "";
             }
             modeloCortes.setDataVector(datos,encabezadoCortes);
             resizeColumnas();
             jtbl_cortes.setRowSelectionInterval(0,0);
             jtbl_cortes.setColumnSelectionInterval(0,0);
             jtbl_cortes.requestFocus();
         }//listaCorte > 0
         else
         {
                 new jdlg_advertencia("¡La busqueda no produjo resultados!","","No hay resultados").setVisible(true);
                 modeloCortes.setDataVector(null,encabezadoCortes);
                 resizeColumnas();
                 {
                     jlbl_barraEstado.setText("<html>  <font color=FF0000>F4 </font> Salir | <font color=FF0000> Enter </font> Buscar Cortes |  <font color=FF0000> F2 </font> Seleccionar/Deseleccionar solo pendientes  |  <font color=FF0000> F3 </font> Seleccionar/Deseleccionar Todos los cortes pendientes</html>");
                     jtxt_fecha.selectAll();
                     jtxt_fecha.requestFocus();
                 }
         }
//         if(reporte)
//             jbtn_imprimir.setEnabled(true);
//         else
//             jbtn_imprimir.setEnabled(false);
     }//valida fecha
    else
    {
         JOptionPane.showMessageDialog(this,"         ¡La fecha es invalida!\n Favor de introducir una fecha valida","Fecha Invalida",JOptionPane.ERROR_MESSAGE);
         jlbl_barraEstado.setText("<html>  <font color=FF0000>F4 </font> Salir | <font color=FF0000> Enter </font> Buscar Cortes |  <font color=FF0000> F2 </font> Seleccionar/Deseleccionar solo pendientes  |  <font color=FF0000> F3 </font> Seleccionar/Deseleccionar Todos los cortes pendientes</html>");
         jtxt_fecha.setText("");
         jtxt_fecha.requestFocus();
    }     
 }
 
  private void detalleCorte(){
     if(jtbl_cortes.getRowCount()>0)
     {
        if(jtbl_cortes.getSelectedRow()>=0)
        {
         TmsCortesTbl corte =  busquedas.cortesTblFacadeRemote.find(BigDecimal.valueOf(Long.valueOf(jtbl_cortes.getValueAt(jtbl_cortes.getSelectedRow(),0).toString())));
         if(corte.getEstadoCorte().equals("P") || corte.getEstadoCorte().equals("E"))
         {
         jdlDetalleCorte jddc = new jdlDetalleCorte("TMS - Corte de "+jtbl_cortes.getValueAt(jtbl_cortes.getSelectedRow(),1)+" "+jtbl_cortes.getValueAt(jtbl_cortes.getSelectedRow(),2), usuario, busquedas, BigDecimal.valueOf(Long.valueOf(jtbl_cortes.getValueAt(jtbl_cortes.getSelectedRow(),0).toString())),jtbl_cortes.getValueAt(jtbl_cortes.getSelectedRow(),1).toString(),this );
         jddc.setVisible(true);
//         if(jddc.getAccionCompleta())
//         {
//            Vector vcorte = (Vector)listacortes.get(jtbl_cortes.getSelectedRow()); 
//            vcorte.set(5,"R");
//             imprimirCorte();
//             modeloCortes.removeRow(jtbl_cortes.getSelectedRow());
//             if(jtbl_cortes.getRowCount()>0)
//             {
//                 jtbl_cortes.setRowSelectionInterval(0,0);
//                 jtbl_cortes.setColumnSelectionInterval(0,0);
//                 jtbl_cortes.requestFocus();
//             }
//             else
//             {
//                 jlbl_barraEstado.setText("<html>  <font color=FF0000>F4 </font> Salir | <font color=FF0000> Enter </font> Buscar Cortes |  <font color=FF0000> F2 </font> Seleccionar/Deseleccionar solo pendientes  |  <font color=FF0000> F3 </font> Seleccionar/Deseleccionar Todos los cortes pendientes</html>");
//                 jtxt_fecha.setText("");
//                 jtxt_fecha.requestFocus();
//             }
//          }
         }//if(esta_pendiente)
        else
        {
         //JOptionPane.showMessageDialog(this,"¡El corte ya fue realizado!","Corte Realizado",JOptionPane.WARNING_MESSAGE);
            new jdlg_advertencia("¡El corte ya fue realizado!","","Corte Realizado").setVisible(true);
          jtbl_cortes.setRowSelectionInterval(0,0);
          jtbl_cortes.setColumnSelectionInterval(0,0);
          jtbl_cortes.requestFocus();
        }
       }//if(selectedRow<0)
      else
      {
            JOptionPane.showConfirmDialog(this,"¡Debes seleccionar un corte!","No hay cortes seleccionado",JOptionPane.ERROR_MESSAGE);
            jtbl_cortes.setRowSelectionInterval(0,0);
            jtbl_cortes.setColumnSelectionInterval(0,0);
            jtbl_cortes.requestFocus();
      }
     }//if(RowCount >0)
     else
         return;
  }
  
  
  public void mandaImprimirCorte(){
           Vector vcorte = (Vector)listacortes.get(jtbl_cortes.getSelectedRow()); 
            vcorte.set(5,"R");
             imprimirCorte();
             modeloCortes.removeRow(jtbl_cortes.getSelectedRow());
             if(jtbl_cortes.getRowCount()>0)
             {
                 jtbl_cortes.setRowSelectionInterval(0,0);
                 jtbl_cortes.setColumnSelectionInterval(0,0);
                 jtbl_cortes.requestFocus();
             }
             else
             {
                 jlbl_barraEstado.setText("<html>  <font color=FF0000>F4 </font> Salir | <font color=FF0000> Enter </font> Buscar Cortes |  <font color=FF0000> F2 </font> Seleccionar/Deseleccionar solo pendientes  |  <font color=FF0000> F3 </font> Seleccionar/Deseleccionar Todos los cortes pendientes</html>");
                 jtxt_fecha.setText("");
                 jtxt_fecha.requestFocus();
             }
  }
  
  private void imprimirCorte(){
      //Jdlg_Pregunta salida = new Jdlg_Pregunta("Confirmacion de Reimpresion de Corte"," ¿Seguro que desea imprimir el corte?");
      //salida.setVisible(true);
      //if(salida.getRespuesta())
     Vector vcorte = (Vector)listacortes.get(jtbl_cortes.getSelectedRow()); 
     if(vcorte.get(5).toString().equals("R"))
     {
      jdlg_pregunta_SN psn =  new jdlg_pregunta_SN("Confirmacion de Reimpresion de Corte", "¿Seguro que desea imprimir el corte?");
      psn.setVisible(true);
      if(respuestaSN)
      {
        
        try {
            Map param = new HashMap();
            InputStream imagen = getClass().getClassLoader().getResourceAsStream("Reportes/logito.JPG");
            param.put("CORTE_ID",BigDecimal.valueOf(Long.valueOf(jtbl_cortes.getValueAt(jtbl_cortes.getSelectedRow(),0).toString())));
            param.put("IMAGENLOGO",imagen);
            InputStream input = getClass().getClassLoader().getResourceAsStream("Reportes/CorteFinTurnoReca.jasper");
            JasperPrint print = null; 
            print=JasperFillManager.fillReport(input,param,conection());
            System.out.println("print : "+ print);
            System.out.println("reporte : "+ input);
            System.out.println("imagen : "+ imagen);
            JRViewer er = new JRViewer(print);
            Dimension FrameSize = this.getSize();
            //er.setBounds(0,0,FrameSize.width - 10,FrameSize.height - 150);//
            er.setBounds(0,0,735,463);
            JasperViewer.viewReport(print,false);
            } catch(Exception e) {
                e.printStackTrace();
            }        

          
       /*
        Vector datosServerCortes = busquedas.cortesTblFacadeRemote.buscaDatosServidorReportes();
        System.out.println("Datos Servidor de Reportes: "+datosServerCortes);
        Vector vv1 = (Vector)datosServerCortes.get(0);
        Vector vv2 = (Vector)datosServerCortes.get(1);
        Vector vv3 = (Vector)datosServerCortes.get(2);
        if(vv1.size()==0 || vv2.size()==0 || vv3.size()==0)
        {
            new jdlg_error("¡Los parametros del servidor de cortes estan mal configurados!","","Erro de Configuración").setVisible(true);
            return;
        }
        Vector v1 = (Vector)vv1.get(0);
        Vector v2 = (Vector)vv2.get(0);
        Vector v3 = (Vector)vv3.get(0);
        
        String reporte = "";
        String ts= jtbl_cortes.getValueAt(jtbl_cortes.getSelectedRow(),3).toString();
        //if(jrbtn_superrapidos.isSelected())
        // reporte = "TMSRPCRS.rdf";
        //else   rep_tmsPuebla   "xertms/xertms@CENTRALDB"   "http://tmspuebla.estrellaroja.com.mx:7778/reports/rwservlet/getjobid"
          reporte = "TMSRPCRE.rdf";  
//        String[] argumentos = {v1.get(0).toString(),null,
//            reporte,"file","output.pdf","pdf",v2.get(0).toString(),
//            v3.get(0).toString(),"paramform=no P_FECHA_CORTE="+jtxt_fecha.getText()};
//            v3.get(0).toString(),"paramform=no P_CORTE_ID="+Long.valueOf(jtbl_cortes.getValueAt(jtbl_cortes.getSelectedRow(),0).toString())};//jtxt_fecha.getText()};

//        String[] argumentos = {v1.get(0).toString(),null,
//            reporte,"file","output.pdf","pdf",v2.get(0).toString(),
//            v3.get(0).toString(),"paramform=no P_FECHA_CORTE="+jtxt_fecha.dateEditor.getTexto()};
//       TmsRWWebService webService = null;
         System.out.println("va a imprimir el reporte => "+reporte);
 //       System.out.println("con los datos del servidor de Reportes => "+argumentos[0]+","+argumentos[1]+","+argumentos[2]+","+argumentos[3]+","+argumentos[4]+","+argumentos[5]+","+argumentos[6]+","+argumentos[7]+","+argumentos[8]);

         Vector vvURL = (Vector)busquedas.cortesTblFacadeRemote.buscaURL();
        if(vvURL.size()==0)
        {
            new jdlg_error("¡Los parametros del servidor de cortes estan mal configurados!","","Error de Configuración").setVisible(true);
            return;
        }
        Vector  vURL = (Vector)vvURL.get(0);
          BrowserControl bc = new BrowserControl();
          String urlRep = vURL.get(0).toString();//http://sumas3.estrellaroja.com.mx:7779/reports/rwsevlet? Tomado de parametro: P_VLRREPURL
          String nargumentos = "cmdkey="+v2.get(0).toString()+"&TMSRPCRE.rdf&P_CORTE_ID="+Long.valueOf(jtbl_cortes.getValueAt(jtbl_cortes.getSelectedRow(),0).toString());
                                    //centralReports
        try {
            //webService = new TmsRWWebService(argumentos);
            System.out.println("EL url del Reporte: "+urlRep+nargumentos);
          bc.displayURL(urlRep+nargumentos);
            
        } catch (Exception ex) {
            System.out.println("ERROR:"+ex.getMessage());
            JOptionPane.showMessageDialog(this,"¡No fue posible imprimir el reporte!\n      Favor de intentar de nuevo","Fallo de reimpresion de reporte",JOptionPane.ERROR_MESSAGE);                    
            return;
        }
       // System.out.println("webService:"+webService.getMsgTerminacion());
        JOptionPane.showMessageDialog(this,"¡El reporte fue enviado a su Explorador de Internet predeterminado!","Reimpresion del corte",JOptionPane.INFORMATION_MESSAGE);
      */
      }
    }//if
     else
       new jdlg_error("¡El corte esta pendiente!. No puedes imprimirlo hasta que este realizado","","El corte esta pendiente").setVisible(true);
  }
  
  
    private void imprimirCorteNormal(){
     Vector vcorte = (Vector)listacortes.get(jtbl_cortes.getSelectedRow()); 
     if(vcorte.get(5).toString().equals("R"))
     {
        try {
            Map param = new HashMap();
            InputStream imagen = getClass().getClassLoader().getResourceAsStream("Reportes/logito.JPG");
            param.put("CORTE_ID",BigDecimal.valueOf(Long.valueOf(jtbl_cortes.getValueAt(jtbl_cortes.getSelectedRow(),0).toString())));
            param.put("IMAGENLOGO",imagen);
            InputStream input = getClass().getClassLoader().getResourceAsStream("Reportes/CorteFinTurnoReca.jasper");
            JasperPrint print = null; 
            print=JasperFillManager.fillReport(input,param,conection());
            System.out.println("print : "+ print);
            System.out.println("reporte : "+ input);
            System.out.println("imagen : "+ imagen);
            JRViewer er = new JRViewer(print);
            Dimension FrameSize = this.getSize();
            //er.setBounds(0,0,FrameSize.width - 10,FrameSize.height - 150);//
            er.setBounds(0,0,735,463);
            JasperViewer.viewReport(print,false);
            } catch(Exception e) {
                e.printStackTrace();
            }       
    }//if
     else
       new jdlg_error("¡El corte esta pendiente!. No puedes imprimirlo hasta que este realizado","","El corte esta pendiente").setVisible(true);
  }  
  
 
    private void imprimirCorteDetallado(){
     Vector vcorte = (Vector)listacortes.get(jtbl_cortes.getSelectedRow()); 
     if(vcorte.get(5).toString().equals("R"))
     {
        try {
            Map param = new HashMap();
            InputStream imagen = getClass().getClassLoader().getResourceAsStream("Reportes/logito.JPG");
            param.put("CORTE_ID",BigDecimal.valueOf(Long.valueOf(jtbl_cortes.getValueAt(jtbl_cortes.getSelectedRow(),0).toString())));
            param.put("CORTE_FOLIO",jtbl_cortes.getValueAt(jtbl_cortes.getSelectedRow(),1).toString());
            param.put("CORTE_INICIO",jtbl_cortes.getValueAt(jtbl_cortes.getSelectedRow(),4).toString());
            param.put("CORTE_FIN",jtbl_cortes.getValueAt(jtbl_cortes.getSelectedRow(),5).toString());
            param.put("IMAGENLOGO",imagen);
            InputStream input = getClass().getClassLoader().getResourceAsStream("Reportes/ReporteCorteFinTurnoDetallado.jasper");
            JasperPrint print = null; 
            print=JasperFillManager.fillReport(input,param,conection());
            System.out.println("print : "+ print);
            System.out.println("reporte : "+ input);
            System.out.println("imagen : "+ imagen);
            JRViewer er = new JRViewer(print);
            Dimension FrameSize = this.getSize();
            //er.setBounds(0,0,FrameSize.width - 10,FrameSize.height - 150);//
            er.setBounds(0,0,735,463);
            JasperViewer.viewReport(print,false);
            } catch(Exception e) {
                e.printStackTrace();
            }       
      
    }//if
     else
       new jdlg_error("¡El corte esta pendiente!. No puedes imprimirlo hasta que este realizado","","El corte esta pendiente").setVisible(true);
  }   
  
  
  
  
          private Connection conection() throws ClassNotFoundException, SQLException, NamingException{
            Connection conn = null;
            try {
                Context initContext = new InitialContext();
                DataSource ds = (DataSource)initContext.lookup("TMS_CENTRAL_DB");        
                conn = ds.getConnection();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            return conn;
        }

  
  private void resizeColumnas(){
        TableColumn columinv = jtbl_cortes.getColumnModel().getColumn(0);
        columinv.setMinWidth( 75 );
        columinv.setMaxWidth( 75 );
        columinv.setPreferredWidth(75);
        columinv = jtbl_cortes.getColumnModel().getColumn(1);
        columinv.setMinWidth( 85 );
        columinv.setMaxWidth( 85 );
        columinv.setPreferredWidth(85);        
        columinv = jtbl_cortes.getColumnModel().getColumn(3);
        columinv.setMinWidth( 100);
        columinv.setMaxWidth( 100 );
        columinv.setPreferredWidth(100);        
        columinv = jtbl_cortes.getColumnModel().getColumn(4);
        columinv.setMinWidth( 123);
        columinv.setMaxWidth( 123 );
        columinv.setPreferredWidth(123);        
        columinv = jtbl_cortes.getColumnModel().getColumn(5);
        columinv.setMinWidth( 120);
        columinv.setMaxWidth( 120 );
        columinv.setPreferredWidth(120);        
  }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupo_botones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jchbx_pendientes;
    private javax.swing.JCheckBox jchbx_todosPendientes;
    private javax.swing.JLabel jlbl_barraEstado;
    private javax.swing.JTable jtbl_cortes;
    private tms_TextFields.JDateTextField jtxt_fecha;
    // End of variables declaration//GEN-END:variables
    private long usuario= -1;
    private Timestamp fecha_servidor;
    private TMSCorteRecManagedBean busquedas;
    private String[] encabezadoCortes = {"Corte","Numero","Nombre","","Fecha Inicio Actividad","Fecha Corte"};
    private DefaultTableModel modeloCortes= new DefaultTableModel(null,encabezadoCortes){
    public boolean isCellEditable (int row, int column){if (column == 10)return true;return false;}};
    private boolean respuestaSN;
    private List listacortes;
    private Vector datosIniciales;

    private JasperPrint print;

    private String ipAS;
    private int portAS;

class jdlg_pregunta_SN extends javax.swing.JDialog {
    
    /**
     * Creates new form jdlg_pregunta_SN
     */
    public jdlg_pregunta_SN(String titulo, String pregunta){
        this.setTitle(titulo);
        this.setModal(true);
        this.setDefaultLookAndFeelDecorated(true);
        this.setUndecorated(true);
        this.getRootPane().setWindowDecorationStyle(JRootPane.QUESTION_DIALOG);
        this.setAlwaysOnTop(true);
        initComponents();
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);        
        this.setResizable(false);
        jlbl_mensaje.setText(pregunta);
        jlbl_barraEstado.setText("<html>  <font color=FF0000>ENTER: </font> Si                 <font color=FF0000>             ESC: </font> No  </html>");
        jlbl_barraEstado.setHorizontalAlignment( JTextField.CENTER );
        int nletras = pregunta.length();
        this.setSize((nletras * 6) + 80,150);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            Dimension DilaogSize = this.getSize();
            if (DilaogSize.height > screenSize.height) {
                DilaogSize.height = screenSize.height;
            }
            if (DilaogSize.width > screenSize.width) {
                DilaogSize.width = screenSize.width;
            }
            this.setLocation( ( screenSize.width - DilaogSize.width ) / 2, ( screenSize.height - DilaogSize.height ) / 2 );            this.setDefaultLookAndFeelDecorated(true);
            //this.setUndecorated(true);
            this.getRootPane().setWindowDecorationStyle(JRootPane.QUESTION_DIALOG);
            jlbl_mensaje.requestFocus();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jlbl_barraEstado = new javax.swing.JLabel();
        jlbl_mensaje = new javax.swing.JLabel();
        jlbl_mensaje.setFocusTraversalKeysEnabled(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\NetBeansProyects\\TMSRecaudacion\\TMSRecaudacion-app-client\\src\\java\\tmsrecaudacion\\images\\pregunta.gif"));

        jlbl_barraEstado.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlbl_barraEstado.setForeground(new java.awt.Color(153, 153, 153));
        jlbl_barraEstado.setText(" ENTER: Si                ESC: No");
        jlbl_barraEstado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jlbl_mensaje.setFont(new java.awt.Font("Arial", 1, 12));
        jlbl_mensaje.setText("sdfsdsdfsdfsdfsdfsdf");
        jlbl_mensaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jlbl_mensajekeyReleased(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .add(14, 14, 14)
                .add(jlbl_mensaje, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .add(424, 424, 424))
            .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(21, 21, 21)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jlbl_mensaje))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 59, Short.MAX_VALUE)
                .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>                           

    private void jlbl_mensajekeyReleased(java.awt.event.KeyEvent evt) {                                        
      if(evt.getKeyCode() == evt.VK_ESCAPE)
      {
          respuestaSN = false;
          this.dispose();
      }
      if(evt.getKeyCode() == evt.VK_ENTER)
      {
          respuestaSN = true;
          this.dispose();
      }
      
    }                                       
    
    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jlbl_barraEstado;
    private javax.swing.JLabel jlbl_mensaje;
    // End of variables declaration                   
    
}   

////// verifica si hay conexion con la BD ///////
public boolean abreSocketAS(){
        Socket s = null;
        try {
            s = new Socket(this.ipAS, this.portAS);
            return true;
        }catch( IOException e ) {
            return false;
        }catch(Exception err){
            return false;
   }
}
    public void setFoco(){
            jtxt_fecha.requestFocus();
    }
    

    public KeyEvent getEventoTeclado(){ return this.eventoTeclado; }
    
    public void setEventoTeclado(KeyEvent evento){ this.eventoTeclado=evento; }

}
