/*
 * jdlgPreguntaExportVista.java
 *
 * Created on 11 de agosto de 2008, 06:00 PM
 */

package reportesrecaudajasper;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JRootPane;

/**
 *
 * @author  vgonzalez
 */
public class jdlgPreguntaExportVista extends javax.swing.JDialog{
    
    /** Creates new form jdlgPreguntaExportVista */
    public jdlgPreguntaExportVista() {
        initComponents();
        this.setModal(true);
        this.setDefaultLookAndFeelDecorated(true);
        this.getRootPane().setWindowDecorationStyle(JRootPane.QUESTION_DIALOG);
        this.setAlwaysOnTop(true);
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            Dimension DilaogSize = this.getSize();
            if (DilaogSize.height > screenSize.height) {
                DilaogSize.height = screenSize.height;
            }
            if (DilaogSize.width > screenSize.width) {
                DilaogSize.width = screenSize.width;
            }
            this.setLocation( ( screenSize.width - DilaogSize.width ) / 2, ( screenSize.height - DilaogSize.height ) / 2 );            this.setDefaultLookAndFeelDecorated(true);
        
        jrbtngpo.add(jrbtn_vistaPrevia);
        jrbtngpo.add(jrbtn_exportaExcel);
        jlbl_barraEstado.setText("<html>  <font color=FF0000>ENTER </font> Aceptar </html>");
        jrbtn_vistaPrevia.setSelected(true);
        jrbtn_vistaPrevia.requestFocus();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jrbtngpo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlbl_barraEstado = new javax.swing.JLabel();
        jrbtn_vistaPrevia = new javax.swing.JRadioButton();
        jrbtn_exportaExcel = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\NetBeansProyects\\TMSRecaudacion\\TMSRecaudacion-app-client\\src\\java\\tmsrecaudacion\\images\\pregunta.gif"));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("\u00bf Que tipo de salida del reporte prefiere?");

        jlbl_barraEstado.setFont(new java.awt.Font("Tahoma", 1, 11));
        jlbl_barraEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbl_barraEstado.setText("jLabel3");
        jlbl_barraEstado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jrbtn_vistaPrevia.setFont(new java.awt.Font("Tahoma", 1, 12));
        jrbtn_vistaPrevia.setText("Vista Previa");
        jrbtn_vistaPrevia.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrbtn_vistaPrevia.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jrbtn_vistaPrevia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jrbtn_vistaPreviaKeyReleased(evt);
            }
        });

        jrbtn_exportaExcel.setFont(new java.awt.Font("Tahoma", 1, 12));
        jrbtn_exportaExcel.setText("Exportar a Excel");
        jrbtn_exportaExcel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jrbtn_exportaExcel.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jrbtn_exportaExcel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jrbtn_exportaExcelKeyReleased(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(jLabel1)
                .add(22, 22, 22)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(jrbtn_vistaPrevia, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 102, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(21, 21, 21)
                        .add(jrbtn_exportaExcel))
                    .add(jLabel2))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 29, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel2))
                .add(24, 24, 24)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jrbtn_vistaPrevia)
                    .add(jrbtn_exportaExcel))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 28, Short.MAX_VALUE)
                .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        jrbtn_vistaPrevia.requestFocusInWindow();
    }//GEN-LAST:event_formComponentShown

    private void jrbtn_exportaExcelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbtn_exportaExcelKeyReleased
       if(evt.getKeyCode()== evt.VK_ENTER)
       {
            if(jrbtn_vistaPrevia.isSelected())
                this.setTipo("Vista");
            if(jrbtn_exportaExcel.isSelected())
                this.setTipo("Excel");
            this.dispose();
       }

    }//GEN-LAST:event_jrbtn_exportaExcelKeyReleased

    private void jrbtn_vistaPreviaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jrbtn_vistaPreviaKeyReleased
       if(evt.getKeyCode()== evt.VK_ENTER)
       {
            if(jrbtn_vistaPrevia.isSelected())
                this.setTipo("Vista");
            if(jrbtn_exportaExcel.isSelected())
                this.setTipo("Excel");
            this.dispose();
       }
    }//GEN-LAST:event_jrbtn_vistaPreviaKeyReleased
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jdlgPreguntaExportVista().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlbl_barraEstado;
    private javax.swing.JRadioButton jrbtn_exportaExcel;
    private javax.swing.JRadioButton jrbtn_vistaPrevia;
    private javax.swing.ButtonGroup jrbtngpo;
    // End of variables declaration//GEN-END:variables
    private String tipo = "";

    public String getTipo() {
        return tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
}
