/*
 * JPanelDetalle.java
 *
 * Created on 21 de agosto de 2009, 11:24 AM
 */

package tms_incidencias;

import DialogosIncidencias.JDlgAceptar;
import DialogosIncidencias.JDlgOperador;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.Rectangle;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import oracle.sql.DATE;
import java.awt.Color;

/**
 *
 * @author  brojas
 */
public class JPanelDetalle extends javax.swing.JPanel {
private SesionVenta sesionVenta= null;
public final static Cursor busyCursor = Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR);
public final static Cursor defaultCursor = Cursor.getDefaultCursor();
private String hoy="";

// datos para cellrender de la tabla
private Color colorDialogoActivo = new Color(96,192,255);
private Color colorhoybackg = new Color(70,100,250);
private Color colorhoyFont = new Color(250,70,70);
private Font font_table = new java.awt.Font("Arial",  Font.BOLD, 15);
private javax.swing.border.LineBorder lb = new javax.swing.border.LineBorder(colorDialogoActivo, 1, false);
private  SimpleDateFormat formatoDelTexto = new SimpleDateFormat("dd/MM/yyyy");
   

    /** Creates 0ew form JPanelDetalle */
    public JPanelDetalle(SesionVenta pSesionVenta)   throws Exception {
        initComponents();
        sesionVenta = pSesionVenta;
         jbInit();
         
    } 
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanelvacio1 = new javax.swing.JPanel();
        jPanelvacio2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jCboAnho = new javax.swing.JComboBox();
        jCboMes = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTxtNombreOperador = new tms_TextFields.JTextTextField();
        jTxtNumeroOperador = new tms_TextFields.JCuantityTextField();
        jLabel7 = new javax.swing.JLabel();
        jCheckCorridas = new javax.swing.JCheckBox();
        jPanelTabla = new javax.swing.JPanel();
        jPanelTable = new javax.swing.JPanel();
        jscpDias = new javax.swing.JScrollPane();
        jtblDias = new javax.swing.JTable();
        jPanelDetalle = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDetalle = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLblBarraEstado = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanelvacio1.setOpaque(false);
        jPanelvacio1.setPreferredSize(new java.awt.Dimension(50, 0));
        org.jdesktop.layout.GroupLayout jPanelvacio1Layout = new org.jdesktop.layout.GroupLayout(jPanelvacio1);
        jPanelvacio1.setLayout(jPanelvacio1Layout);
        jPanelvacio1Layout.setHorizontalGroup(
            jPanelvacio1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 50, Short.MAX_VALUE)
        );
        jPanelvacio1Layout.setVerticalGroup(
            jPanelvacio1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 469, Short.MAX_VALUE)
        );
        add(jPanelvacio1, java.awt.BorderLayout.EAST);

        jPanelvacio2.setOpaque(false);
        jPanelvacio2.setPreferredSize(new java.awt.Dimension(50, 0));
        jPanelvacio2.setRequestFocusEnabled(false);
        org.jdesktop.layout.GroupLayout jPanelvacio2Layout = new org.jdesktop.layout.GroupLayout(jPanelvacio2);
        jPanelvacio2.setLayout(jPanelvacio2Layout);
        jPanelvacio2Layout.setHorizontalGroup(
            jPanelvacio2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 50, Short.MAX_VALUE)
        );
        jPanelvacio2Layout.setVerticalGroup(
            jPanelvacio2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 469, Short.MAX_VALUE)
        );
        add(jPanelvacio2, java.awt.BorderLayout.WEST);

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 165));
        jCboAnho.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCboAnho.setToolTipText("A\u00f1o");
        jCboAnho.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCboAnhoItemStateChanged(evt);
            }
        });
        jCboAnho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCboAnhoKeyPressed(evt);
            }
        });

        jCboMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jCboMes.setToolTipText("Mes ");
        jCboMes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCboMesItemStateChanged(evt);
            }
        });
        jCboMes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCboMesKeyPressed(evt);
            }
        });

        jLabel1.setText("Mes:");

        jLabel2.setText("A\u00f1o:");

        jLabel3.setText("Clave Operador:");

        jLabel4.setText("Nombre Operador:");

        jTxtNombreOperador.setColumns(50);
        jTxtNombreOperador.setEditable(false);
        jTxtNombreOperador.setToolTipText("Nombre del Operador");
        jTxtNombreOperador.setEnabled(false);
        jTxtNombreOperador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtNombreOperadorKeyPressed(evt);
            }
        });

        jTxtNumeroOperador.setColumns(10);
        jTxtNumeroOperador.setToolTipText("Clave del Operador");
        jTxtNumeroOperador.setName("jTxtNumeroOperador");
        jTxtNumeroOperador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtNumeroOperadorKeyPressed(evt);
            }
        });

        jLabel7.setText("Corridas:");

        jCheckCorridas.setToolTipText("Seleccionar si se requiere ver las corridas");
        jCheckCorridas.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckCorridas.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(53, 53, 53)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel7)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(jPanel1Layout.createSequentialGroup()
                            .add(59, 59, 59)
                            .add(jLabel1))
                        .add(jLabel3)))
                .add(13, 13, 13)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jCboMes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 116, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jTxtNumeroOperador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 103, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(27, 27, 27)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel4)
                            .add(jLabel2))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jTxtNombreOperador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 299, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jCboAnho, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jCheckCorridas))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(42, 42, 42)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jLabel4)
                    .add(jTxtNombreOperador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jTxtNumeroOperador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(12, 12, 12)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jCboMes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jCboAnho)
                    .add(jLabel2))
                .add(22, 22, 22)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel7)
                    .add(jCheckCorridas))
                .add(34, 34, 34))
        );
        add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanelTabla.setLayout(new java.awt.BorderLayout());

        jPanelTable.setLayout(new java.awt.BorderLayout());

        jPanelTable.setPreferredSize(new java.awt.Dimension(100, 200));
        jscpDias.setPreferredSize(new java.awt.Dimension(452, 230));
        jtblDias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtblDias.setPreferredSize(new java.awt.Dimension(300, 220));
        jscpDias.setViewportView(jtblDias);

        jPanelTable.add(jscpDias, java.awt.BorderLayout.NORTH);

        jPanelDetalle.setLayout(new java.awt.BorderLayout());

        jPanelDetalle.setPreferredSize(new java.awt.Dimension(100, 300));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(162, 210));
        jTextAreaDetalle.setColumns(20);
        jTextAreaDetalle.setEditable(false);
        jTextAreaDetalle.setRows(5);
        jTextAreaDetalle.setToolTipText("Incidencias del dia");
        jTextAreaDetalle.setWrapStyleWord(true);
        jTextAreaDetalle.setPreferredSize(new java.awt.Dimension(160, 150));
        jScrollPane1.setViewportView(jTextAreaDetalle);

        jPanelDetalle.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(100, 50));

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel6)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel6)
        );
        jPanelDetalle.add(jPanel3, java.awt.BorderLayout.NORTH);

        jPanelTable.add(jPanelDetalle, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 100));

        jLblBarraEstado.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLblBarraEstado.setText("<html><font color=ff0000>IZQ/DER</font> Ingrese Criterio de Busqueda | <font color=ff0000>ENTER</font> Buscar <font color=ff0000>F5</font> Buscar Operador | Clic en el d\u00eda para ver detalle.</html>");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLblBarraEstado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 835, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLblBarraEstado)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanelTable.add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanelTabla.add(jPanelTable, java.awt.BorderLayout.CENTER);

        add(jPanelTabla, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

    private void jCboAnhoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCboAnhoItemStateChanged
       UpdateCalendar();
    }//GEN-LAST:event_jCboAnhoItemStateChanged

    private void jCboMesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCboMesItemStateChanged
       UpdateCalendar();
    }//GEN-LAST:event_jCboMesItemStateChanged

    private void jTxtNombreOperadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNombreOperadorKeyPressed
       seleccionarOperador(); 
    }//GEN-LAST:event_jTxtNombreOperadorKeyPressed

    private void jTxtNumeroOperadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNumeroOperadorKeyPressed
// TODO add your handling code here:
       switch(evt.getKeyCode()){
            case KeyEvent.VK_RIGHT:
                jCboMes.requestFocusInWindow();
                break;
            case KeyEvent.VK_LEFT:
                jCboAnho.requestFocusInWindow();
                break;
            case KeyEvent.VK_ENTER: seleccionarOperador(); 
                break;
            case KeyEvent.VK_F5: seleccionarOperador(); 
                break;
       }
     
    }//GEN-LAST:event_jTxtNumeroOperadorKeyPressed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
   
    }//GEN-LAST:event_formKeyPressed

    private void jCboAnhoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCboAnhoKeyPressed
    jCboAnho_keyPressed(evt);
    }//GEN-LAST:event_jCboAnhoKeyPressed

    private void jCboMesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCboMesKeyPressed
// TODO add your handling code here:
     jCboMes_keyPressed(evt);
    }//GEN-LAST:event_jCboMesKeyPressed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCboAnho;
    private javax.swing.JComboBox jCboMes;
    private javax.swing.JCheckBox jCheckCorridas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLblBarraEstado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelDetalle;
    private javax.swing.JPanel jPanelTabla;
    private javax.swing.JPanel jPanelTable;
    private javax.swing.JPanel jPanelvacio1;
    private javax.swing.JPanel jPanelvacio2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDetalle;
    private tms_TextFields.JTextTextField jTxtNombreOperador;
    private tms_TextFields.JCuantityTextField jTxtNumeroOperador;
    private javax.swing.JScrollPane jscpDias;
    private javax.swing.JTable jtblDias;
    // End of variables declaration//GEN-END:variables
    
    
    private Object[] meses = {"Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto",
                              "Septiembre", "Octubre", "Noviembre", "Diciembre"};
    private Object[] anhos = new Object[5];
    private Object[] dias = {"Dom", "Lun", "Mar", "Mie", "Jue", "Vie", "Sab"};
    private Object[][] datos = new Object[6][7];
    private int[] diasPorMes = {
                                31, 28, 31, 30, 31, 30,
                                31, 31, 30, 31, 30, 31
                            };
    private int xM, xA;
    private String today="";
    private DefaultTableModel xTabla = new DefaultTableModel(null,dias){
            public boolean isCellEditable(int row, int col){
                return false;
            }
        };
    
    

    private void jbInit() throws Exception {
        jtblDias = new JTable(xTabla);
        today=sesionVenta.getToDate();
      
        hoy= today.substring(0,2);
        xM = Integer.valueOf(today.substring(3,5));    
        xA = Integer.valueOf(today.substring(6,10));
     
        for(int i=-1; i<4; i++)
            anhos[i+1] = xA+i;
        jCboMes.removeAllItems();
        DefaultComboBoxModel defaultModel =new DefaultComboBoxModel(meses);
        jCboMes.setModel(defaultModel);
        
        jCboAnho.removeAllItems();
        defaultModel =new DefaultComboBoxModel(anhos);
        jCboAnho.setModel(defaultModel);
        
        jCboMes.setSelectedIndex(xM-1);
        jCboAnho.setSelectedItem(xA);
        Calendario(xM-1, xA);
        jCboAnho.setBounds(new Rectangle(110, 5, 95, 22));
        jCboAnho.setFont(new Font("Dialog", 1, 11));
        jscpDias.setBounds(new Rectangle(5, 35, 480, 250));   // BRA 5, 35, 280, 130));
        jscpDias.setFocusable(false);  
        jtblDias.setFocusable(false);
        jtblDias.setRowSelectionAllowed(false);
        jtblDias.setColumnSelectionAllowed(false);
        jtblDias.getTableHeader().setReorderingAllowed(false);
        jtblDias.getTableHeader().setResizingAllowed(false);
        jtblDias.setFont(new Font("Dialog", 1, 11));
        jscpDias.getViewport().add(jtblDias, null);
        jtblDias.setDefaultRenderer(Object.class, new colorOperadoresRenderer1());
        jtblDias.addMouseListener(new java.awt.event.MouseAdapter() { 
            public void mouseClicked(java.awt.event.MouseEvent e) { 
                if(jtblDias.getModel().getRowCount() >0 && jtblDias.getValueAt(jtblDias.getSelectedRow(),jtblDias.getSelectedColumn()) != null )
                {
                     showIncidicnciaByDay(); 
                  }    
               
                //dispose();   
            } 
        });   // 
      }
       
    
     private void jCboMes_keyPressed(KeyEvent e) {
      jTextAreaDetalle.setText("");
        switch(e.getKeyCode()){
            case KeyEvent.VK_RIGHT:
                UpdateCalendar();
                jCboAnho.requestFocusInWindow();
                 
                break;
            case KeyEvent.VK_LEFT:
                 jTxtNumeroOperador.requestFocusInWindow();
                 UpdateCalendar();
                break;
            case KeyEvent.VK_ENTER:
                 UpdateCalendar();
                 break;
           case KeyEvent.VK_F5: seleccionarOperador(); break;             
            //  BRA case KeyEvent.VK_ESCAPE: this.dispose();
        }
      
    }
        
    private void jCboAnho_keyPressed(KeyEvent e) {
      jTextAreaDetalle.setText("");
              switch(e.getKeyCode()){
            case KeyEvent.VK_RIGHT:
                 jTxtNumeroOperador.requestFocusInWindow();
                 UpdateCalendar();
                break;
            case KeyEvent.VK_LEFT:
                 jCboMes.requestFocusInWindow();
                 UpdateCalendar();
                break;
            case KeyEvent.VK_ENTER:
                 UpdateCalendar();
            break;
             case KeyEvent.VK_F5: seleccionarOperador(); break;    
           // BRA  case KeyEvent.VK_ESCAPE: this.dispose();
        }
          
    }

    private void jtbl_keyPressed(KeyEvent e)
    {
      seleccionarOperador();  
    }
    
    private void AnchoColumnas(JTable jtblTabla, int ancho) {
        int anchoContenedor = ancho;
        TableColumn column;
        jtblTabla.setRowHeight(35);
        for (int i = 0; i < jtblTabla.getColumnCount(); i++) {
            column = jtblTabla.getColumnModel().getColumn(i);
            switch (i) {
                case 0: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.145)); break;
                case 1: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.1425)); break;
                case 2: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.1425)); break;
                case 3: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.14)); break;
                case 4: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.1425)); break;
                case 5: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.1425)); break;
                case 6: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.145)); break;
            }
        }
    }  // 

/******************************* CALENDARIO ***********************************/
    private void Calendario(int pMes, int pAnho){
    datos = new Object[6][7];
    int diasDeMes = 0;
    int celVacias = 0;
    GregorianCalendar actCal = (GregorianCalendar) Calendar.getInstance();
    GregorianCalendar Cal = new GregorianCalendar(pAnho, pMes, 1);
    //System.out.println("Calculando calendario "+pMes+"  "+pAnho);
     if ( pMes >=0)
       {
        diasDeMes = diasPorMes[pMes];
        today=sesionVenta.getToDate();
        if(pMes == Calendar.FEBRUARY && Cal.isLeapYear(pAnho)) diasDeMes++;  // Checa si el año es bisiesto
        celVacias = Cal.get(Calendar.DAY_OF_WEEK)-1;
        int fila = 0;
        int i=1,j;
        while(i <= diasDeMes){
            for(j=celVacias; j<7; j++){
                 datos[fila][j]=i;
                i++;
                if(i > diasDeMes) break;
            } 
            fila++;  
            celVacias=0;  
        }

        xTabla.setDataVector(datos,dias);
        AnchoColumnas(jtblDias,680); // 280
      }
    }  

    
    private void seleccionarOperador() {
        jTxtNumeroOperador.setText("");
        jTxtNombreOperador.setText("");  
        jTextAreaDetalle.setText("");
        JDlgOperador jDlgOperador = new JDlgOperador(sesionVenta);
        jDlgOperador.setVisible(true);
        if(!jDlgOperador.getEvento()) return;
        jTxtNumeroOperador.setText(sesionVenta.getTmsEstadoOperadoresV().get(sesionVenta.getFilaOperadorSeleccionado()).getClaveOperador());
        jTxtNombreOperador.setText(sesionVenta.getTmsEstadoOperadoresV().get(sesionVenta.getFilaOperadorSeleccionado()).getOperadorNombreCompleto());
    }
    
    
public void showIncidicnciaByDay()
{
  String day=jtblDias.getValueAt(jtblDias.getSelectedRow(),jtblDias.getSelectedColumn())+"";    
  String  cve_operador= jTxtNumeroOperador.getText();
  if (cve_operador.length() > 0 )
  {
   this.setCursor(busyCursor);
    String agno=jCboAnho.getSelectedItem()+"";
    String mes=jCboMes.getSelectedItem()+"";
    for (int i = 0; i < meses.length; i++) {
        if(meses[i].toString().equalsIgnoreCase(mes))
        { mes=(i+1)+""; break; }
    }
    if(day.length()==1)
        day="0"+day;
    if(mes.length()==1)
        mes="0"+mes;
    String date = day+"/"+mes+"/"+agno;
    Vector Vincidencias = sesionVenta.getIncideciasOperadorByDay(cve_operador,date);
    String strIncidencias="";
    if(Vincidencias != null && Vincidencias.size() > 0){
        strIncidencias="          I N C I D E N C I A S \n\n"; 
        strIncidencias+="    Incidencia                            Fecha Inicial                  Fecha Final                       Status               OBS\n"; // 
        Vector vincidencia =null;
        try {
            String obs = "";
            if(Vincidencias != null && Vincidencias.size() >0 )
              for (int i = 0; i < Vincidencias.size(); i++) {
                vincidencia= (Vector)Vincidencias.elementAt(i);
                obs = vincidencia.elementAt(3)!= null  ? vincidencia.elementAt(3).toString():"";
                strIncidencias+=fiilcade(vincidencia.elementAt(0).toString(),25)+"       "+
                                   vincidencia.elementAt(1).toString()+"          "+
                                   vincidencia.elementAt(2).toString()+"             "+
                                   vincidencia.elementAt(4).toString()+"         "+
                                   obs+"\n";
                }  //or
          } catch (Exception e) {
             e.printStackTrace();   
             System.out.println("Error showIncidicnciaByDay() en fechas"+e.getMessage());
             setCursor(defaultCursor);
        }
        }// if
      
    if(strIncidencias.length() > 0)
       jTextAreaDetalle.setText(strIncidencias+"\n\n"+getCorridasbyDay(cve_operador,date));
      else
        jTextAreaDetalle.setText(getCorridasbyDay(cve_operador,date));
   this.setCursor(defaultCursor);         
  }
  else
      new JDlgAceptar("¡Verifique criterios de busqueda!", "<html>Debe de proporcinar la clave del operador.</html>", Color.RED);
  }


private String fiilcade(String cade, int lengt)
{
   int l=cade.length();
   if (cade.length() < lengt)
   {
       for (int i=l; i < lengt; i++) 
           cade+=" ";
       
   }
   return cade;
}
   

public String getCorridasbyDay(String cve_operadorr, String fecha)
{
    String strCorridas ="";
    if (jCheckCorridas.isSelected())
    {
      Vector  Vcorridas=sesionVenta.getCorridasOperadorByDay(cve_operadorr,fecha);
      if(Vcorridas != null && Vcorridas.size() > 0){
          Vector vcorrida=null;
          strCorridas="C O R R I D A S \n \n";
          strCorridas+="     FECHA - HORA                                SERVICIO                              ORIGEN             DESTINO          AUTOBUS\n";
          try {
               if(Vcorridas != null && Vcorridas.size() >0 )
                for (int i = 0; i < Vcorridas.size(); i++) {
                      vcorrida=(Vector)Vcorridas.elementAt(i);
                      strCorridas+= fiilcade(vcorrida.elementAt(0).toString(),25)+"         ";
                      strCorridas+=fiilcade(vcorrida.elementAt(1).toString(),25)+"             ";
                      strCorridas+=vcorrida.elementAt(2).toString()+"                ";
                      strCorridas+=vcorrida.elementAt(3).toString()+"                       ";
                      strCorridas+=vcorrida.elementAt(4).toString()+"\n";
                  }  // fr
          } catch (Exception e) {
           e.printStackTrace();   
           System.out.println("Error getCorridasbyDay() en fechas"+e.getMessage());
           setCursor(defaultCursor);
          }
          }  // if
          
    }
    return strCorridas; 
}


public Component prepareRenderer(TableCellRenderer renderer, int rowIndex, int colIndex) {
      Component component = jtblDias.prepareRenderer(renderer, rowIndex, colIndex);    
      component.setBackground(Color.ORANGE);
    return component;
}


 public void getTableCellRendererComponent (JTable table, boolean hasFocus, int rowIndex, int colIndex) {
      
      boolean isSelected = table.isCellSelected(rowIndex, colIndex);
      DefaultTableCellRenderer defRender = (DefaultTableCellRenderer)table.getCellRenderer(rowIndex, colIndex);
      Component cellRenderer =defRender.getTableCellRendererComponent(table, "xx", isSelected, false,rowIndex, colIndex);
      cellRenderer.setBackground(Color.lightGray);
   }
  

 private class colorOperadoresRenderer1 extends DefaultTableCellRenderer{
 
 public Component getTableCellRendererComponent(JTable table, Object value, boolean selected,
    boolean focused, int row, int column){
    super.getTableCellRendererComponent(table, value, selected, focused, row, column);
    today=sesionVenta.getToDate();
    Object strDataTable=jtblDias.getValueAt(row,column);
     
    int dia=Integer.parseInt( today.substring(0,2));
    int mes = Integer.valueOf(today.substring(3,5));    
    String ano= today.substring(6,10);
    
    setFont(font_table);
    if(row==jtblDias.getSelectedRow() && column ==jtblDias.getSelectedColumn()){
         setBackground(colorDialogoActivo);
         setForeground(Color.WHITE);
            }
    else if(strDataTable != null &&    // fecha actual
                    jCboAnho.getSelectedItem().toString().equalsIgnoreCase(ano) &&
                    jCboMes.getSelectedIndex() ==  mes-1   &&
                    strDataTable.toString().equalsIgnoreCase(dia+""))
                {   setBackground(colorhoybackg);
                    setForeground(colorhoyFont);    
               }
    else{
        setForeground(Color.BLACK);
        setBackground(Color.WHITE);
       // if(row==jtblDias.getSelectedRow()) setBorder(lb);
    }
    return this;
    }   // End Component
    
 }   // End colorOperadoresRenderer1
 

 
    public void keyPressed(KeyEvent e) {
    int compo = (e.getComponent()==null || e.getComponent().getName()==null ? -3 : Integer.valueOf(e.getComponent().getName()));
        switch(e.getKeyCode()){
           case KeyEvent.VK_RIGHT:
                switch(compo){
                    case 0:
                        if(jTxtNumeroOperador.isFocusOwner())
                           jCboMes.requestFocusInWindow();
                         else if(jCboMes.isFocusOwner())
                                 {  jCboAnho.requestFocusInWindow();  
                                    UpdateCalendar();
                                 }
                        else if(jCboAnho.isFocusOwner())  
                                 {jTxtNumeroOperador.requestFocusInWindow();
                                  UpdateCalendar();
                                 }
                        break;
                }
            break;

            case KeyEvent.VK_LEFT:
                switch(compo){
                    case 0:
                          if(jCboAnho.isFocusOwner())
                           {  jCboMes.requestFocusInWindow();
                              UpdateCalendar();
                          }
                        else if(jCboMes.isFocusOwner())
                          jTxtNumeroOperador.requestFocusInWindow();
                        
                        else if(jTxtNumeroOperador.isFocusOwner())
                        { jCboAnho.requestFocusInWindow();
                          UpdateCalendar();
                        }
                                                
                }
            break;
        
        }
    }
    
    
    public void UpdateCalendar()
    {
        if(jCboMes.getItemCount() >0 && jCboAnho.getItemCount() >0)
          {
            //System.out.println(" MES "+jCboMes.getSelectedIndex()+ "   Año "+ jCboAnho.getSelectedItem() );
           jTextAreaDetalle.setText("");
            Calendario(jCboMes.getSelectedIndex(),Integer.valueOf(jCboAnho.getSelectedItem().toString()));
          }
    }

} 


