/*
 * JDlgCH.java
 *
 * Created on 18 de febrero de 2009, 01:27 PM
 */

package tms_cambiarHorarios;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.ComboBoxModel;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import tms_psd.SesionVenta;
import tms_psd.util.JDlgAceptar;
import tms_psd.util.JDlgSiNo;
import xertms.entidad.TmsCorridasTbl;
import xertms.entidad.TmsCorridasVentaTbl;

/**
 *
 * @author  vgonzalez
 */
public class JDlgCH extends javax.swing.JDialog {
    
    /** Creates new form JDlgCH */
    public JDlgCH(ComboBoxModel mservicio, ComboBoxModel mempresa, ComboBoxModel morigen, ComboBoxModel mdestino, SesionVenta psesionVenta) {
        //super(parent, modal);
        initComponents();
        this.setModal(true);
        this.setTitle("Sustitucion de horarios");
        centrarJDialog();
        inhabilitarF10();
        this.sesionVenta = psesionVenta;
        jtxt_fecha.dateEditor.addKeyListener1(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtx_fechaKeyPressed(evt);
            }
        });
        jtxt_fechaSustitucion.dateEditor.addKeyListener1(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtx_fechaSustitucionKeyPressed(evt);
            }
        });
        jcmb_Servicio.setModel(mservicio);
        jcmb_empresa.setModel(mempresa);
        jcmb_Origen.setModel(morigen);
        jcmb_Destino.setModel(mdestino);
        jTblCorridas.setModel(modeloCorridas);
        AnchoColumnas();
        jLblMensajes.setText("<html><font color=ff0000>&#171; &#187;</font> Ingresar datos | <font color=ff0000>ENTER</font> Buscar corridas | <font color=ff0000>ESC</font> Cancelar</html>");
        jcmb_Servicio.requestFocusInWindow();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jLblMensajes = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcmb_Servicio = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jcmb_empresa = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jcmb_Origen = new javax.swing.JComboBox();
        jcmb_Destino = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxt_fecha = new tms_calendario.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jtxt_horaI = new tms_TextFields.JHourTextField();
        jLabel8 = new javax.swing.JLabel();
        jtxt_horaF = new tms_TextFields.JHourTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblCorridas = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jtxt_fechaSustitucion = new tms_calendario.JDateChooser();
        jProgressBar1 = new javax.swing.JProgressBar();

        jMenu1.setText("Menu");
        jMenuBar1.add(jMenu1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLblMensajes.setText("Barra Estado");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Busqueda de corridas", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11)));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Servicio:");

        jcmb_Servicio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmb_Servicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcmb_ServicioKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Empresa:");

        jcmb_empresa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmb_empresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcmb_empresaKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Origen:");

        jcmb_Origen.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmb_Origen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcmb_OrigenKeyPressed(evt);
            }
        });

        jcmb_Destino.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jcmb_Destino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcmb_DestinoKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel5.setText("Destno:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel6.setText("Fecha:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel7.setText("Hora Desde:");

        jtxt_horaI.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_horaIKeyPressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel8.setText("Hora Hasta:");

        jtxt_horaF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_horaFKeyPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 39, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jtxt_fecha, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 109, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(22, 22, 22)
                        .add(jLabel7)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jtxt_horaI, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(13, 13, 13)
                        .add(jLabel8)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jtxt_horaF, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 49, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jcmb_Servicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 164, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(13, 13, 13)
                        .add(jLabel3)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jcmb_empresa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 193, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jcmb_Origen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 86, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 24, Short.MAX_VALUE)
                .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jcmb_Destino, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 89, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel2)
                        .add(jcmb_Servicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel3)
                        .add(jcmb_empresa, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel4)
                        .add(jcmb_Origen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel5)
                        .add(jcmb_Destino, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(15, 15, 15)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(jLabel6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jtxt_fecha, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jtxt_horaI, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 18, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(jtxt_horaF, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Corridas a sustituir", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12)));
        jTblCorridas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTblCorridas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTblCorridasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTblCorridasFocusLost(evt);
            }
        });
        jTblCorridas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTblCorridasKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTblCorridasKeyReleased(evt);
            }
        });

        jScrollPane1.setViewportView(jTblCorridas);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 290, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel9.setText("Fecha a Sustituir:");

        jtxt_fechaSustitucion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_fechaSustitucionFocusGained(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLblMensajes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel9)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jtxt_fechaSustitucion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 108, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(591, Short.MAX_VALUE))
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jProgressBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 13, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel9)
                    .add(jtxt_fechaSustitucion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jProgressBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLblMensajes))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTblCorridasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblCorridasKeyReleased
        if(evt.getKeyCode() == evt.VK_LEFT || evt.getKeyCode() == evt.VK_RIGHT )
            jTblCorridas.setColumnSelectionInterval(6,6);   
    }//GEN-LAST:event_jTblCorridasKeyReleased

    private void jtxt_fechaSustitucionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_fechaSustitucionFocusGained
        jLblMensajes.setText("<html><font color=ff0000>ESC</font> Regresar a las corridas | <font color=ff0000>ENTER</font> Sustituir Horarios</html>");            
        jtxt_fechaSustitucion.dateEditor.setFoco();
    }//GEN-LAST:event_jtxt_fechaSustitucionFocusGained

    private void jTblCorridasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTblCorridasFocusLost
        jLblMensajes.setText("<html><font color=ff0000>&#171; &#187;</font> Ingresar datos | <font color=ff0000>ENTER</font> Buscar corridas | <font color=ff0000>ESC</font> Cancelar</html>");
    }//GEN-LAST:event_jTblCorridasFocusLost

    private void jTblCorridasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTblCorridasFocusGained
        jLblMensajes.setText("<html><font color=ff0000>F3</font> Ingresar Fecha para sustituir | <font color=ff0000>ESC</font> Nueva busqueda de corridas | <font color=ff0000>ESPACIO</font> Seleccionar/Deseleccionar horarios | <font color=ff0000>ENTER</font> Sustituir Horarios</html>");    
    }//GEN-LAST:event_jTblCorridasFocusGained

    private void inhabilitarF10() {
        this.jcmb_Destino.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
        this.jcmb_Origen.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
        this.jcmb_Servicio.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
        this.jcmb_empresa.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
        this.jtxt_fecha.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
        this.jtxt_fechaSustitucion.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
        this.jtxt_horaF.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
        this.jtxt_horaI.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
        this.jTblCorridas.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
       }    
    
    public void deshabilitarCampos(){
        this.jcmb_Destino.setEnabled(false);
        this.jcmb_Origen.setEnabled(false);
        this.jcmb_Servicio.setEnabled(false);
        this.jcmb_empresa.setEnabled(false);
        this.jtxt_fecha.setEnabled(false);
        //this.jtxt_fechaSustitucion.setEnabled(false);
        this.jtxt_horaF.setEnabled(false);
        this.jtxt_horaI.setEnabled(false);
       // this.jTblCorridas.setEnabled(false);
    }

    public void habilitarCampos(){
        this.jcmb_Destino.setEnabled(true);
        this.jcmb_Origen.setEnabled(true);
        this.jcmb_Servicio.setEnabled(true);
        this.jcmb_empresa.setEnabled(true);
        this.jtxt_fecha.setEnabled(true);
        this.jtxt_fechaSustitucion.setEnabled(true);
        this.jtxt_horaF.setEnabled(true);
        this.jtxt_horaI.setEnabled(true);
        this.jTblCorridas.setEnabled(true);
        jcmb_Servicio.requestFocus();
    }
        
    private void centrarJDialog(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, ( screenSize.height - frameSize.height ) / 2 );
    }    
    
    private void jTblCorridasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblCorridasKeyPressed
        if(evt.getKeyCode() == evt.VK_LEFT || evt.getKeyCode() == evt.VK_RIGHT )
            jTblCorridas.setColumnSelectionInterval(6,6);   

        if(evt.getKeyCode() == evt.VK_F3)
            jtxt_fechaSustitucion.dateEditor.setFoco();
        
        if(evt.getKeyCode() == evt.VK_ENTER)
            sustituirCorridas();
        
        if(evt.getKeyCode() == evt.VK_ESCAPE)
        {
            modeloCorridas.setDataVector(null,encabezadoCorridas);
            habilitarCampos();
        }

    }//GEN-LAST:event_jTblCorridasKeyPressed

    private void jtx_fechaKeyPressed(java.awt.event.KeyEvent evt) {
        if(evt.getKeyCode() == evt.VK_LEFT)
            jcmb_Destino.requestFocus();

        if(evt.getKeyCode() == evt.VK_RIGHT)
            jtxt_horaI.requestFocus();
        
        if(evt.getKeyCode() == evt.VK_ESCAPE)
            this.dispose();

        if(evt.getKeyCode() == evt.VK_ENTER)
            buscarCorridas();
    }
    
     private void   jtx_fechaSustitucionKeyPressed(java.awt.event.KeyEvent evt) {
        if(evt.getKeyCode() == evt.VK_ESCAPE)
            jTblCorridas.requestFocus();

        if(evt.getKeyCode() == evt.VK_ENTER)
            sustituirCorridas();
    }
    
    private void jtxt_horaFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_horaFKeyPressed
        if(evt.getKeyCode() == evt.VK_LEFT)
            jtxt_horaI.requestFocus();

        if(evt.getKeyCode() == evt.VK_RIGHT)
            jcmb_Servicio.requestFocus();
        
        if(evt.getKeyCode() == evt.VK_ESCAPE)
            this.dispose();

        if(evt.getKeyCode() == evt.VK_ENTER)
            buscarCorridas();
    }//GEN-LAST:event_jtxt_horaFKeyPressed

    private void jtxt_horaIKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_horaIKeyPressed
        if(evt.getKeyCode() == evt.VK_LEFT)
            jtxt_fecha.dateEditor.setFoco();

        if(evt.getKeyCode() == evt.VK_RIGHT)
            jtxt_horaF.requestFocus();
        
        if(evt.getKeyCode() == evt.VK_ESCAPE)
            this.dispose();

        if(evt.getKeyCode() == evt.VK_ENTER)
            buscarCorridas();
    }//GEN-LAST:event_jtxt_horaIKeyPressed

    private void jcmb_DestinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcmb_DestinoKeyPressed
        if(evt.getKeyCode() == evt.VK_LEFT)
            jcmb_Origen.requestFocus();

        if(evt.getKeyCode() == evt.VK_RIGHT)
            jtxt_fecha.dateEditor.setFoco();
        
        if(evt.getKeyCode() == evt.VK_ESCAPE)
            this.dispose();

        if(evt.getKeyCode() == evt.VK_ENTER)
            buscarCorridas();
    }//GEN-LAST:event_jcmb_DestinoKeyPressed

    private void jcmb_OrigenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcmb_OrigenKeyPressed
        if(evt.getKeyCode() == evt.VK_LEFT)
            jcmb_empresa.requestFocus();

        if(evt.getKeyCode() == evt.VK_RIGHT)
            jcmb_Destino.requestFocus();
        
        if(evt.getKeyCode() == evt.VK_ESCAPE)
            this.dispose();

        if(evt.getKeyCode() == evt.VK_ENTER)
            buscarCorridas();
    }//GEN-LAST:event_jcmb_OrigenKeyPressed

    private void jcmb_empresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcmb_empresaKeyPressed
        if(evt.getKeyCode() == evt.VK_LEFT)
            jcmb_Servicio.requestFocus();

        if(evt.getKeyCode() == evt.VK_RIGHT)
            jcmb_Origen.requestFocus();
        
        if(evt.getKeyCode() == evt.VK_ESCAPE)
            this.dispose();

        if(evt.getKeyCode() == evt.VK_ENTER)
            buscarCorridas();
    }//GEN-LAST:event_jcmb_empresaKeyPressed

    private void jcmb_ServicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcmb_ServicioKeyPressed
        if(evt.getKeyCode() == evt.VK_LEFT)
            jtxt_horaF.requestFocus();

        if(evt.getKeyCode() == evt.VK_RIGHT)
            jcmb_empresa.requestFocus();
        
        if(evt.getKeyCode() == evt.VK_ESCAPE)
            this.dispose();

        if(evt.getKeyCode() == evt.VK_ENTER)
            buscarCorridas();
        
    }//GEN-LAST:event_jcmb_ServicioKeyPressed
    
    private boolean validaFechas() {
        if(jtxt_horaI.getText().length()!=0 && jtxt_horaI.getText().length()!=5){
            DialogoAceptar = new JDlgAceptar("¡Valor de hora incorrecta!", "Ingrese un valor como 15:30 o deje vacio el campo.", Color.RED);
            jtxt_horaI.selectAll();
            jtxt_horaI.requestFocusInWindow();
            return false;
        }
        
        if(jtxt_fecha.dateEditor.getTexto().length()==0 || jtxt_fecha.dateEditor.getTexto().length()==1 || jtxt_fecha.dateEditor.getTexto().length()==4 || (jtxt_fecha.dateEditor.getTexto().length()>6 &&  jtxt_fecha.dateEditor.getTexto().length()<10)){
            DialogoAceptar = new JDlgAceptar("¡Valor de fecha incorrecta!", "Ingrese un valor como 15/09/2009.", Color.RED);
            jtxt_fecha.dateEditor.setTexto("");
            jtxt_fecha.dateEditor.setFoco();
            return false;
        }

        if(jtxt_fecha.dateEditor.getTexto().length()==2 || jtxt_fecha.dateEditor.getTexto().length()==3){
            String dtStrFecha = formatoFecha.format(new Date()).substring(3);
            if(jtxt_fecha.dateEditor.getTexto().length()==2) jtxt_fecha.dateEditor.setTexto(jtxt_fecha.dateEditor.getTexto() +"/"+dtStrFecha);
            else jtxt_fecha.dateEditor.setTexto(jtxt_fecha.dateEditor.getTexto()+dtStrFecha);
        }

        if(jtxt_fecha.dateEditor.getTexto().length()==5 || jtxt_fecha.dateEditor.getTexto().length()==6){
            String dtStrFecha = formatoFecha.format(new Date()).substring(6);
            if(jtxt_fecha.dateEditor.getTexto().length()==5) jtxt_fecha.dateEditor.setTexto(jtxt_fecha.dateEditor.getTexto() +"/"+dtStrFecha);
            else jtxt_fecha.dateEditor.setTexto(jtxt_fecha.dateEditor.getTexto()+dtStrFecha);
        }
        
        if(jtxt_horaF.getText().length()!=0 && jtxt_horaF.getText().length()!=5){
            DialogoAceptar = new JDlgAceptar("¡Valor de hora incorrecta!", "Ingrese un valor como 15:30 o deje vacio el campo.", Color.RED);
            jtxt_horaF.selectAll();
            jtxt_horaF.requestFocusInWindow();
            return false;
        }

        return true;
    }   
        
    private void AnchoColumnas(){
        TableColumn column = null;
        int anchoContenedor = jScrollPane1.getWidth(); //(int)(jScpDetalle.getWidth()*0.80);
        for (int i = 0; i < 7; i++) {
            column = jTblCorridas.getColumnModel().getColumn(i);
            switch(i){
                case 0:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.28)); break;
                case 1:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.28)); break;
                case 2:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.13)); break;
                case 3:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.12)); break;
                case 4:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.12)); break;
                case 5:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.06)); break;
                case 6:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.09)); break;
            }
            column.setResizable(false);
        }
        /*jVwpMaestro.setView(jTblMaestro);
        jVwpMaestro.setPreferredSize(jTblMaestro.getPreferredSize());
        jScpDetalle.setRowHeaderView(jVwpMaestro);
        jScpDetalle.setCorner(JScrollPane.UPPER_LEFT_CORNER, jTblMaestro.getTableHeader());*/
    }
    
    public void buscarCorridas(){
       sesionVenta.getDBLinkClaveOrigen(jcmb_Origen.getSelectedItem().toString());
        if(jcmb_Origen.getSelectedItem().toString().equals(sesionVenta.getTerminalNombre())){
            //transaccionRemota = false;
            //limProc=500;
        }
        else{
            //transaccionRemota = true;
            //limProc=300;
        }
        
        if(!validaFechas()) return;
        
        if(jcmb_Origen.getSelectedItem().toString().equals(jcmb_Destino.getSelectedItem().toString())){
            DialogoAceptar = new JDlgAceptar("PSD.", "Origen es igual a destino.", Color.RED);
            return;
        }
        
        int edoConsulta=sesionVenta.busquedaSustitucion(jcmb_Servicio.getSelectedItem().toString(), jcmb_empresa.getSelectedItem().toString(),
                "", "", false,
                jtxt_fecha.dateEditor.getTexto(), jtxt_horaI.getText(), jtxt_fechaSustitucion.dateEditor.getTexto(), jtxt_horaF.getText(),
                jcmb_Destino.getSelectedItem().toString());
        
        if(edoConsulta!=1){
            if(edoConsulta==-21){
                this.getToolkit().beep();
                DialogoAceptar = new JDlgAceptar("En este momento no es posible realizar la operacion.","<html>Por favor intentelo mas tarde o<br>contacte al administrador del sistema.</html>", Color.RED);
                return;
            }
            AnchoColumnas();
            //AnchoColumnasDetalle();
            DialogoAceptar = new JDlgAceptar("¡No existen corridas con estos criterios!", "Presione ENTER para continuar...", Color.RED);
            return;
        }            
        infoCorridas = sesionVenta.getVectorCorridasSust();
        if(infoCorridas==null)
        {
            DialogoAceptar = new JDlgAceptar("¡No existen corridas con estos criterios!", "Presione ENTER para continuar...", Color.RED);
            return;
        }
        deshabilitarCampos();
        Object[][] datosInfo = new Object[infoCorridas.size()][7];
            for(int i=0; i<infoCorridas.size();i++)
            {
                Vector unaInfo= (Vector)infoCorridas.get(i);
                datosInfo[i][0] = unaInfo.get(0).toString();
                datosInfo[i][1] = unaInfo.get(1).toString();
                datosInfo[i][2] = unaInfo.get(2).toString();
                datosInfo[i][3] = unaInfo.get(3).toString();
                datosInfo[i][4] = unaInfo.get(4).toString();
                datosInfo[i][5] = unaInfo.get(5).toString();
                datosInfo[i][6] = (boolean)true;
            }
            modeloCorridas.setDataVector(datosInfo,encabezadoCorridas);
            AnchoColumnas();
            System.out.println("Encabezado corridas: "+encabezadoCorridas);
            System.out.println("Info corridas: "+infoCorridas);
        jtxt_fechaSustitucion.dateEditor.setTexto("");
        jTblCorridas.setRowSelectionInterval(0,0);
        jTblCorridas.setColumnSelectionInterval(6,6);
        jTblCorridas.requestFocus();
    }
    
    public void sustituirCorridas(){
        if(jtxt_fechaSustitucion.dateEditor.getTexto().length()==0 || jtxt_fechaSustitucion.dateEditor.getTexto().length()==1 || jtxt_fechaSustitucion.dateEditor.getTexto().length()==4 || (jtxt_fechaSustitucion.dateEditor.getTexto().length()>6 &&  jtxt_fechaSustitucion.dateEditor.getTexto().length()<10)){
            DialogoAceptar = new JDlgAceptar("¡Valor de fecha incorrecta!", "Ingrese un valor como 15/09/2009.", Color.RED);
            jtxt_fechaSustitucion.dateEditor.setTexto("");
            jtxt_fechaSustitucion.dateEditor.setFoco();
            return;
        }
        
        if(jtxt_fechaSustitucion.dateEditor.getTexto().length()==2 || jtxt_fechaSustitucion.dateEditor.getTexto().length()==3){
            String dtStrFecha = formatoFecha.format(new Date()).substring(3);
            if(jtxt_fechaSustitucion.dateEditor.getTexto().length()==2) jtxt_fechaSustitucion.dateEditor.setTexto(jtxt_fechaSustitucion.dateEditor.getTexto() +"/"+dtStrFecha);
            else jtxt_fechaSustitucion.dateEditor.setTexto(jtxt_fechaSustitucion.dateEditor.getTexto()+dtStrFecha);
        }

        if(jtxt_fechaSustitucion.dateEditor.getTexto().length()==5 || jtxt_fechaSustitucion.dateEditor.getTexto().length()==6){
            String dtStrFecha = formatoFecha.format(new Date()).substring(6);
            if(jtxt_fechaSustitucion.dateEditor.getTexto().length()==5) jtxt_fechaSustitucion.dateEditor.setTexto(jtxt_fechaSustitucion.dateEditor.getTexto() +"/"+dtStrFecha);
            else jtxt_fechaSustitucion.dateEditor.setTexto(jtxt_fechaSustitucion.dateEditor.getTexto()+dtStrFecha);
        }
        
        DialogoSiNo = new JDlgSiNo("¡Confirme!", "<html>¿Seguro que desea sustitur los horarios del dia "+jtxt_fecha.dateEditor.getTexto()+"<br> al dia "+jtxt_fechaSustitucion.dateEditor.getTexto()+"? <br>      Esta operacion puede tardar varios minutos.</html>");
        if(!DialogoSiNo.getResultado()) return;
        //jLblMensajes.setText("<html><font color=ff0000>Borrando corridas del dia "+jtxt_fechaSustitucion.dateEditor.getTexto()+" de las "+(jtxt_horaI.getText().equals("") ?"00:00" : jtxt_horaI.getText())+" hasta las "+(jtxt_horaF.getText().equals("") ?"23:59" : jtxt_horaF.getText())+"</font></html>");            
        int edoConsulta=sesionVenta.busquedaSustitucion2(jcmb_Servicio.getSelectedItem().toString(), jcmb_empresa.getSelectedItem().toString(),
                "", "", false,
                jtxt_fechaSustitucion.dateEditor.getTexto(), jtxt_horaI.getText(), jtxt_fechaSustitucion.dateEditor.getTexto(), jtxt_horaF.getText(),
                jcmb_Destino.getSelectedItem().toString());

        Vector infoCorridas2 = sesionVenta.getVectorCorridasSust();
        Vector corOcup = new Vector();
        if(infoCorridas2!=null)
        {
            jProgressBar1.setValue(0);
            jProgressBar1.setValue( 0 );
            jProgressBar1.setMinimum( 0 );
            jProgressBar1.setMaximum(infoCorridas2.size() -1);
            Vector unaCorrida;
            System.out.println("DBLink = "+sesionVenta.getDBLink());
            for(int i=0; i<infoCorridas2.size(); i++)
            {
                unaCorrida = (Vector)infoCorridas2.get(i);
                int ocp = sesionVenta.getSesionPSDFacate().ocupacionCorrida(Long.valueOf(unaCorrida.get(6).toString()), sesionVenta.getDBLink());
                System.out.println("Ocupacion de la corrida "+unaCorrida.get(0).toString()+" es: "+ocp);
                if(ocp==0)
                    sesionVenta.borraCorrida(Long.valueOf(unaCorrida.get(6).toString()));
                else
                    corOcup.add(unaCorrida.get(1).toString()+"-"+unaCorrida.get(2).toString()+"-"+unaCorrida.get(3).toString()+"-"+unaCorrida.get(4).toString()+"-"+unaCorrida.get(5).toString());
                    //servicio-empresa-origen-destino-hora
              jProgressBar1.setValue(i);
              //System.out.println("aumenta la barra de estado a: "+i);
              jProgressBar1.setStringPainted(true);
              jProgressBar1.paint(jProgressBar1.getGraphics());   
            }
            
        }
            System.out.println("Vector de corridas con Ocupacion es: "+corOcup);
            jProgressBar1.setValue(0);
            jProgressBar1.setValue( 0 );
            jProgressBar1.setMinimum( 0 );
            Vector vcorridasNuevas  = modeloCorridas.getDataVector();
            jProgressBar1.setMaximum(vcorridasNuevas.size() -1);
            TmsCorridasTbl corrida = null;
            TmsCorridasVentaTbl corridaVenta = null;
            String[] s;
            for (int i=0; i<vcorridasNuevas.size(); i++)
            {
              Vector corridaNueva = (Vector)vcorridasNuevas.get(i);
              Boolean agregar = (Boolean)corridaNueva.get(6);  
              //System.out.println("("+i+") Boolean: "+agregar);
              if(agregar)  
              {                 //servicio-empresa-origen-destino-hora
                  String cadena = corridaNueva.get(1).toString()+"-"+corridaNueva.get(2).toString()+"-"+corridaNueva.get(3).toString()+"-"+corridaNueva.get(4).toString()+"-"+corridaNueva.get(5).toString();
                  if(corOcup.indexOf(cadena)==-1)
                  {
                     corrida = null;
                     corridaVenta = null;
                     Vector vi = (Vector)infoCorridas.get(i);
                     corrida = sesionVenta.getSesionPSDFacate().buscaCororida(Long.valueOf(vi.get(6).toString()),sesionVenta.getDBLink());
                     corridaVenta = sesionVenta.getSesionPSDFacate().buscaCororidaVenta(Long.valueOf(vi.get(6).toString()),sesionVenta.getDBLink());
                    //System.out.println("Empresa de la corrida("+corrida.getClaveCorrida()+"): "+corrida.getEmpresaId()+"-"+corridaVenta.getEmpresa());
                    long corridaId;
                    String claveCorrida;
                    Timestamp fecha = null;
                    //System.out.println("fecha obtenida: "+jtxt_fechaSustitucion.getDate());
                    String fc = fcc.format(jtxt_fechaSustitucion.getDate())+" "+corridaNueva.get(5).toString()+":00";
                    fecha=fecha.valueOf(fc);
                        corrida.setFechaHoraCorrida(fecha);
                        corrida.setTipoCorrida("N");
                        corrida.setNumeroContrato("");
                        corrida.setNumeroOrden("");
                        corrida.setCorridaRelacionadaId(null);
                        corrida.setCreadoPor(sesionVenta.getUsuarioId());
                        corrida.setAdicional4("PSD");     
                        s =  sesionVenta.getSesionPSDFacate().registrarCorridaNormal(sesionVenta.getPrefijoTerminalId(), corrida, 
                        (sesionVenta.getUbicacionTerminal().toString().length()>3 ? sesionVenta.getUbicacionTerminal().toString().substring(0,4) : sesionVenta.getUbicacionTerminal().toString().substring(0,3)+"_"),
                        sesionVenta.getServicioLetra(corridaNueva.get(1).toString()), 
                        (corridaNueva.get(5).toString()).replaceAll(":",""), sesionVenta.getEsquemaPropio(),
                        claveOrigenCorrida(corridaNueva.get(3).toString()), sesionVenta.getDBLink());      
                        if(s==null){
                            DialogoAceptar = new JDlgAceptar("¡Error al generar la corrida!", "Hubo un error al generar la corrida. Contacte al administrador", Color.RED);
                            return ;
                        }
                        
                        if(s[0].equals("-1")){
                            DialogoAceptar = new JDlgAceptar("¡Error al generar la corrida!", "Hubo un error al generar la corrida. Contacte al administrador", Color.RED);
                            return ;
                        }
                        corridaId = Long.valueOf(s[0]);
                        claveCorrida = s[1];
                        corridaVenta.setCorridaId(corridaId);
                        corridaVenta.setClaveCorrida(claveCorrida);
                        corridaVenta.setEstadoCorrida("A");
                        corridaVenta.setOperador("");
                        corridaVenta.setOperadorAdicional("");
                        corridaVenta.setOperadorOriginal("");
                        corridaVenta.setAutobus("");
                        corridaVenta.setAutobusOriginal("");
                        corridaVenta.setFechaHoraCorrida(fecha);
                        corridaVenta.setAsiento1("D"); corridaVenta.setAsiento2("D"); corridaVenta.setAsiento3("D"); corridaVenta.setAsiento4("D"); corridaVenta.setAsiento5("D");
                        corridaVenta.setAsiento6("D"); corridaVenta.setAsiento7("D"); corridaVenta.setAsiento8("D"); corridaVenta.setAsiento9("D"); corridaVenta.setAsiento10("D");
                        corridaVenta.setAsiento11("D"); corridaVenta.setAsiento12("D"); corridaVenta.setAsiento13("D"); corridaVenta.setAsiento14("D"); corridaVenta.setAsiento15("D");
                        corridaVenta.setAsiento16("D"); corridaVenta.setAsiento17("D"); corridaVenta.setAsiento18("D"); corridaVenta.setAsiento19("D"); corridaVenta.setAsiento20("D");
                        corridaVenta.setAsiento21("D"); corridaVenta.setAsiento22("D"); corridaVenta.setAsiento23("D"); corridaVenta.setAsiento24("D"); corridaVenta.setAsiento25("D");
                        corridaVenta.setAsiento26("D"); corridaVenta.setAsiento27("D"); corridaVenta.setAsiento28("D"); corridaVenta.setAsiento29("D"); corridaVenta.setAsiento30("D");
                        corridaVenta.setAsiento31("D"); corridaVenta.setAsiento32("D"); corridaVenta.setAsiento33("D"); corridaVenta.setAsiento34("D"); corridaVenta.setAsiento35("D");
                        corridaVenta.setAsiento36("D"); corridaVenta.setAsiento37("D"); corridaVenta.setAsiento38("D"); corridaVenta.setAsiento39("D"); corridaVenta.setAsiento40("D");
                        corridaVenta.setAsiento41("D"); corridaVenta.setAsiento42("D"); corridaVenta.setAsiento43("D"); corridaVenta.setAsiento44("D"); corridaVenta.setAsiento45("D");
                        corridaVenta.setAsiento46("D"); corridaVenta.setAsiento47("D"); corridaVenta.setAsiento48("D"); corridaVenta.setAsiento49("D"); corridaVenta.setAsiento50("D");
                        corridaVenta.setAsiento51("D"); corridaVenta.setAsiento52("D"); corridaVenta.setAsiento53("D"); corridaVenta.setAsiento54("D"); corridaVenta.setAsiento55("D");
                        corridaVenta.setAsiento56("D"); corridaVenta.setAsiento57("D"); corridaVenta.setAsiento58("D"); corridaVenta.setAsiento59("D"); corridaVenta.setAsiento60("D");
                        corridaVenta.setAsiento61("D"); corridaVenta.setAsiento62("D"); corridaVenta.setAsiento63("D"); corridaVenta.setAsiento64("D"); corridaVenta.setAsiento65("D");
                        corridaVenta.setAsiento66("D"); corridaVenta.setAsiento67("D"); corridaVenta.setAsiento68("D"); corridaVenta.setAsiento69("D"); corridaVenta.setAsiento70("D");
                        corridaVenta.setAsiento71("D"); corridaVenta.setAsiento72("D"); corridaVenta.setAsiento73("D"); corridaVenta.setAsiento74("D"); corridaVenta.setAsiento75("D");
                        corridaVenta.setAsiento76("D"); corridaVenta.setAsiento77("D"); corridaVenta.setAsiento78("D"); corridaVenta.setAsiento79("D"); corridaVenta.setAsiento80("D");
                        corridaVenta.setAsiento81("D"); corridaVenta.setAsiento82("D"); corridaVenta.setAsiento83("D"); corridaVenta.setAsiento84("D"); corridaVenta.setAsiento85("D");
                        corridaVenta.setAdicional4("PSD");
                        // guardar corrida extra
                        if(!sesionVenta.getSesionPSDFacate().registrarCorridaExtraVenta(corridaVenta, sesionVenta.getEsquemaPropio(), sesionVenta.getDBLink()))
                        {
                            DialogoAceptar = new JDlgAceptar("¡Error al generar la corrida venta!", "Hubo un error al generar la corrida venta. Contacte al administrador", Color.RED);
                            return ;
                        }
                 }
              }
              jProgressBar1.setValue(i);
              jProgressBar1.setStringPainted(true);
              jProgressBar1.paint(jProgressBar1.getGraphics());   
            }
            jProgressBar1.setValue(0);
            jProgressBar1.setValue( 0 );
            jProgressBar1.setMinimum( 0 );
            jProgressBar1.setMaximum(0);
            jProgressBar1.setStringPainted(true);
            jProgressBar1.paint(jProgressBar1.getGraphics());   
            DialogoAceptar = new JDlgAceptar("¡Corridas generadas!", "Las corridas fueron sustituidas correctamente", Color.RED);
            this.jtxt_fecha.dateEditor.setTexto("");
            this.jtxt_fechaSustitucion.dateEditor.setTexto("");
            this.jtxt_horaF.setText("");
            this.jtxt_horaI.setText("");
            modeloCorridas.setDataVector(null,encabezadoCorridas);
            habilitarCampos();
    } 
    
    public String claveOrigenCorrida(String origen){
        if(origen.length()>4) return origen.substring(0,4);
        if(origen.length()==4) return origen;
        if(origen.length()==3) return origen+"_";
        if(origen.length()==2) return origen+"__";
        if(origen.length()==1) return origen+"___";
        return origen;
    }    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblMensajes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblCorridas;
    private javax.swing.JComboBox jcmb_Destino;
    private javax.swing.JComboBox jcmb_Origen;
    private javax.swing.JComboBox jcmb_Servicio;
    private javax.swing.JComboBox jcmb_empresa;
    private tms_calendario.JDateChooser jtxt_fecha;
    private tms_calendario.JDateChooser jtxt_fechaSustitucion;
    private tms_TextFields.JHourTextField jtxt_horaF;
    private tms_TextFields.JHourTextField jtxt_horaI;
    // End of variables declaration//GEN-END:variables
    private Object[] encabezadoCorridas = {"Corrida","Servicio","Empresa","Origen","Destino","Hora","Sustituir"};
    private DefaultTableModel modeloCorridas = new DefaultTableModel(null,encabezadoCorridas){
            public boolean isCellEditable(int row, int column) {
            if (column == 6  )
               return true;
            return false;
            }
            public Class getColumnClass(int c) { 
               return getValueAt(0, c).getClass(); }
        };
    private SesionVenta sesionVenta;
    private JDlgAceptar DialogoAceptar;
    private SimpleDateFormat formatoFecha= new SimpleDateFormat("dd/MM/yyyy");
    private Vector infoCorridas;
    private JDlgSiNo DialogoSiNo;
    private SimpleDateFormat fcc= new SimpleDateFormat("yyyy-MM-dd");
    
}
