/*
 * JDlgSustitucion.java
 *
 * Created on 9 de octubre de 2007, 06:15 PM
 */

package tms_asigsust;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import tms_psd.*;
import tms_psd.util.BarraMensajes;
import tms_psd.util.JDlgAceptar;
import tms_psd.util.JDlgSiNo;
import xertms.entidad.TmsOperadoresTbl;

/**
 *
 * @author  ocruz
 */
public class JDlgAsignacionOperador extends javax.swing.JDialog{
    /**
     * Creates new form JDlgSustitucion
     */
    public JDlgAsignacionOperador(SesionVenta pSesionVenta, int pFilaCorrida,String pfecha) {
        this.filaCorrida = pFilaCorrida;
        this.sesionVenta = pSesionVenta;
         this.fecha = pfecha;
        initComponents();
        this.setModal(true);
        centrarJDialog();
        this.jTxtNumOper.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
        this.jTblOper.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        grupo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLblBarraEstado = new javax.swing.JLabel();
        jScpOper = new javax.swing.JScrollPane();
        jTblOper = new javax.swing.JTable();
        jTblOper.setFocusTraversalKeysEnabled(false);
        jLabel1 = new javax.swing.JLabel();
        jTxtNumOper = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Asignacion de Operador");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLblBarraEstado.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLblBarraEstado.setText("<html><font color=ff0000>ENTER</font> BuscarOperadores | <font color=ff0000>ESC</font> Cancelar</html>");

        jScpOper.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), java.awt.Color.black));
        jTblOper.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTblOper.setModel(xOper);
        jTblOper.setName("3");
        jTblOper.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTblOperKeyPressed(evt);
            }
        });

        jScpOper.setViewportView(jTblOper);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Numero Operador:");

        jTxtNumOper.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTxtNumOper.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtNumOper.setText("%");
        jTxtNumOper.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtNumOperKeyPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLblBarraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jTxtNumOper, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 63, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(564, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScpOper, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTxtNumOper, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScpOper, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 219, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLblBarraEstado))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTblOperKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblOperKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE:
                xOper.setDataVector(null, oper);
                AnchoColumnasDetalle();
                this.operacionRealizada = false;
                jLblBarraEstado.setText("<html><font color=ff0000>ENTER</font> Buscar Operadores | <font color=ff0000>ESC</font> Cancelar</html>");
                jTxtNumOper.setText("%");
                jTxtNumOper.requestFocusInWindow();
            break;
            case KeyEvent.VK_F11:
                String resp = sesionVenta.getSesionPSDFacate().getValidaIncicenciaOper(listaOper.get(jTblOper.getSelectedRow()).getClaveOperador(),this.fecha);
                if(!resp.equals(""))
                {
                    DialogoAceptar = new JDlgAceptar("PSD.", resp, Color.RED);
                    this.operacionRealizada = false;
                    return;
                }
                DialogoSiNo = new JDlgSiNo("¡Confirme...!", "<html>¿Realmente desea asignar el operador <font color=ff0000>"+jTblOper.getValueAt(jTblOper.getSelectedRow(),0).toString()+"</font><br>" +
                        "a la corrida <font color=ff0000>"+sesionVenta.getTmsMonitorCorridaV().get(filaCorrida).getClaveCorrida()+"</font>?</html>");
                if(!DialogoSiNo.getResultado()) return;
                if(!sesionVenta.asignaOperador(sesionVenta.getTmsMonitorCorridaV().get(filaCorrida).getCorridaId(),
                        listaOper.get(jTblOper.getSelectedRow()).getOperadorId(), listaOper.get(jTblOper.getSelectedRow()).getClaveOperador())){
                    DialogoAceptar = new JDlgAceptar("¡Asignacion incorrecta!","Contacte al administrador del sistema.", Color.RED);
                    xOper.setDataVector(null, oper);
                    AnchoColumnasDetalle();
                    this.operacionRealizada = false;
                    jTxtNumOper.setText("%");
                    jTxtNumOper.requestFocusInWindow();
                    return;
                }
                else{
                    if(!sesionVenta.registraEnRolOperadorSust(listaOper.get(jTblOper.getSelectedRow()).getOperadorId())){
                            DialogoAceptar = new JDlgAceptar("¡No fue posible cambiar el estado del operador asignado!", "Contacte al administrador del sistema.", Color.RED);
                            xOper.setDataVector(null, oper);
                        AnchoColumnasDetalle();
                        this.operacionRealizada = false;
                        jTxtNumOper.setText("%");
                        jTxtNumOper.requestFocusInWindow();
                        return;
                    }
                    this.NumeroAsig = listaOper.get(jTblOper.getSelectedRow()).getClaveOperador();
                    this.AsigId =  listaOper.get(jTblOper.getSelectedRow()).getOperadorId();
                    this.NombreAsig = listaOper.get(jTblOper.getSelectedRow()).getOperadorNombreCompleto();
                    this.operacionRealizada = true;
                    this.dispose();
                }
            break;
        }
    }//GEN-LAST:event_jTblOperKeyPressed

    private void jTxtNumOperKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtNumOperKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ENTER:
                if(jTxtNumOper.getText().equals("")){
                    DialogoAceptar = new JDlgAceptar("¡Criterio invalido!","Ingrese un criterio de busqueda (% para buscar todo).", Color.RED);
                    return;
                }
                listaOper = sesionVenta.queryOperadoresByClave(jTxtNumOper.getText());
                if(listaOper==null || listaOper.size()==0){
                    jTxtNumOper.selectAll();
                    DialogoAceptar = new JDlgAceptar("¡La consulta no genero resultados!","Ingrese un criterio de busqueda (% para buscar todo).", Color.RED);
                    return;
                }
                datos = new Object[listaOper.size()][3];
                for(int i=0; i<listaOper.size(); i++){
                    datos[i][0] = listaOper.get(i).getClaveOperador();
                    datos[i][1] = listaOper.get(i).getOperadorNombreCompleto();
                    datos[i][2] = "Estado: "+sesionVenta.getAccion(listaOper.get(i).getAccion1Id())+
                                  " - Ubicacion: "+sesionVenta.getAccion(listaOper.get(i).getAccion2Id())+
                                  " - Actividad: "+sesionVenta.getAccion(listaOper.get(i).getAccion3Id());
                }
                xOper.setDataVector(datos, oper);
                AnchoColumnasDetalle();
                jLblBarraEstado.setText("<html><font color=ff0000>F11</font> Asignar Operador | <font color=ff0000>ESC</font> Nueva Busqueda</html>");
                jTblOper.setColumnSelectionInterval(0,0);
                jTblOper.setRowSelectionInterval(0,0);
                jTblOper.requestFocusInWindow();
            break;
            case KeyEvent.VK_ESCAPE:
                this.dispose();
            break;
        }
    }//GEN-LAST:event_jTxtNumOperKeyPressed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
// TODO add your handling code here:
        jTxtNumOper.requestFocusInWindow();
    }//GEN-LAST:event_formComponentShown

    private void centrarJDialog(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, ( screenSize.height - frameSize.height ) / 2 );
    }
    
    private void AnchoColumnasDetalle(){
        TableColumn column = null;
        int anchoContenedor = jScpOper.getWidth();
        for (int i = 0; i < jTblOper.getColumnCount(); i++) {
            column = jTblOper.getColumnModel().getColumn(i);
            switch(i){
                case 0:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.10)); break;
                case 1:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.35)); break;
                case 2:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.55)); break;
            }
            column.setResizable(false);
        }
    }
    
    public boolean getResultado(){ return this.operacionRealizada; }
    
    public String getNumeroOperadorAsig(){ return this.NumeroAsig; }
    
    public long getNumeroOperadorAsigId(){ return this.AsigId; }
    
    public String getNombreOperadorAsig(){ return this.NombreAsig; }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLblBarraEstado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScpOper;
    private javax.swing.JTable jTblOper;
    private javax.swing.JTextField jTxtNumOper;
    // End of variables declaration//GEN-END:variables
    private SimpleDateFormat formatoHora= new SimpleDateFormat("HH:mm");
    private JDlgAceptar DialogoAceptar;
    private Object[] oper = {"Numero", "Nombre", "Estado"};
    private DefaultTableModel xOper = new DefaultTableModel(null, oper){
            public boolean isCellEditable(int row, int col) {
                return false;
            }   
    };
    private boolean operacionRealizada = false;
    private SesionVenta sesionVenta = null;
    private int filaCorrida;
    private BarraMensajes barraMensajes = new BarraMensajes();
    private Color colorDialogoActivo = new Color(0,83,255);
    private String NumeroAsig="";
    private String NombreAsig="";
    private long AsigId;
    private List<TmsOperadoresTbl> listaOper=null;
    private Object[][] datos = null;
    private JDlgSiNo DialogoSiNo;
    private String fecha;
}