/*
 * JDLG_BusquedaNombre.java
 *
 * Created on 28 de mayo de 2009, 04:27 PM
 */

package tmscodigobarras;

import java.awt.Color;
import java.awt.Component;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRootPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumnModel;
import solicitud.TMSSesionCodBarRemote;
import tms_TextFields.JDateTextField;
import tms_TextFields.JHourTextField;
import tms_TextFields.JTextTextField;
import tms_calendario.JDateChooser;
import tmscodigobarras.clases.SwingWorker;

/**
 *
 * @author  asolis
 */
public class JDLG_BusquedaNombre extends javax.swing.JDialog {
    Color focusado;
    Color noFocusado;    
    private TMSSesionCodBarRemote facade;
    private Vector buscadosHeader;
    private Vector buscadosData;
    private DefaultTableModel buscadosTable;
    private DefaultComboBoxModel origenModel;
    private DefaultComboBoxModel destinoModel;
    private DefaultComboBoxModel servicioModel;
    private String estaTerminal;
    private int indiceTerminal;
    private Vector origenDestino;
    private boolean tabla = false;
    public String folioPreimpreso = "";
    JIF_ValidarCodigoBarras codigoBarras;
    public String fecha="";
            
    /** Creates new form JDLG_BusquedaNombre */
    public JDLG_BusquedaNombre(java.awt.Frame parent, boolean modal, TMSSesionCodBarRemote facade,JIF_ValidarCodigoBarras codigoBarras ){
        super(parent, modal);
        this.setTitle("Busqueda por Nombre");
        this.facade = facade;
        origenDestino = facade.buscarOrigenesDestinos();
        cargarOrigenes();        
        cargarDestinos(true);
        cargarServicios();
        fecha = facade.fecha();        
        this.codigoBarras = codigoBarras;
        buscadosHeader = new Vector();
        buscadosData= new Vector();
        buscadosHeader.add("Referencia");
        buscadosHeader.add("Folio"); 
        buscadosHeader.add("Nombre Pasajero");
        buscadosHeader.add("No. Asiento");
        buscadosHeader.add("Forma Pago");
        buscadosHeader.add("Tipo Pasajero");
        buscadosHeader.add("Fecha-Hora Venta");
        buscadosHeader.add("Clave Corrida");
        buscadosHeader.add("Fecha-Hora Corrida");
        buscadosHeader.add("Origen");
        buscadosHeader.add("Destino");
        buscadosHeader.add("Caja");
        buscadosHeader.add("Tipo Operacion");        
        
        buscadosTable = new DefaultTableModel(null, buscadosHeader){
            public boolean isCellEditable(int row, int col) {
                return false;
            }
        };
        
        initComponents();  
        jdt_fechaCompra.setText(fecha);
        jdt_fechaCorrida.setText(fecha);
        jcb_origen.setBackground(Color.WHITE);
        jcb_destino.setBackground(Color.WHITE);
        jcb_servicio.setBackground(Color.WHITE);
        
        jcb_origen.setSelectedIndex(indiceTerminal);
        jcb_destino.setSelectedIndex(0);
        jcb_servicio.setSelectedIndex(0);
        focusado = new Color(192,190,207);
        noFocusado = Color.WHITE;
        jlbl_barraEstado.setText("<html>  <font color=FF0000>   ESC</font> Regresar | <font color=FF0000>   ENTER</font> Buscar de Boleto");
               
        jtbl_buscados.setAutoResizeMode( JTable.AUTO_RESIZE_OFF );
        resizeColumnasCorridas(jtbl_buscados);

etiqueta.setVisible(false);
progressBar.setVisible(false);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jpnl_nombre = new javax.swing.JPanel();
        jlbl_nombre = new javax.swing.JLabel();
        jlbl_apellidos = new javax.swing.JLabel();
        jtxt_apellidos = new tms_TextFields.JTextTextField();
        jtxt_nombre = new tms_TextFields.JTextTextField();
        jpnl_fechahoracorrida = new javax.swing.JPanel();
        jlbl_fecha = new javax.swing.JLabel();
        jlbl_hora = new javax.swing.JLabel();
        jdt_fechaCorrida = new tms_calendario.JDateTextField();
        jdt_fechaCompra = new tms_calendario.JDateTextField();
        jpnl_datosCorrida = new javax.swing.JPanel();
        jlbl_origen = new javax.swing.JLabel();
        jlbl_destino = new javax.swing.JLabel();
        jlbl_servicio = new javax.swing.JLabel();
        jcb_origen = new javax.swing.JComboBox();
        jcb_destino = new javax.swing.JComboBox();
        jcb_servicio = new javax.swing.JComboBox();
        jlbl_barraEstado = new javax.swing.JLabel();
        jscp_buscados = new javax.swing.JScrollPane();
        jtbl_buscados = new javax.swing.JTable();
        progressBar = new javax.swing.JProgressBar();
        etiqueta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jpnl_nombre.setBorder(javax.swing.BorderFactory.createTitledBorder("Nombre Pasajero"));
        jlbl_nombre.setText("Nombre:");

        jlbl_apellidos.setText("Apellidos:");

        jtxt_apellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_apellidosKeyPressed(evt);
            }
        });

        jtxt_nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxt_nombreFocusGained(evt);
            }
        });
        jtxt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxt_nombreKeyPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpnl_nombreLayout = new org.jdesktop.layout.GroupLayout(jpnl_nombre);
        jpnl_nombre.setLayout(jpnl_nombreLayout);
        jpnl_nombreLayout.setHorizontalGroup(
            jpnl_nombreLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpnl_nombreLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpnl_nombreLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlbl_nombre)
                    .add(jlbl_apellidos))
                .add(9, 9, 9)
                .add(jpnl_nombreLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jtxt_nombre, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 456, Short.MAX_VALUE)
                    .add(jtxt_apellidos, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnl_nombreLayout.setVerticalGroup(
            jpnl_nombreLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnl_nombreLayout.createSequentialGroup()
                .add(jpnl_nombreLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpnl_nombreLayout.createSequentialGroup()
                        .add(36, 36, 36)
                        .add(jpnl_nombreLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jlbl_apellidos)
                            .add(jtxt_apellidos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jlbl_nombre)
                    .add(jtxt_nombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnl_fechahoracorrida.setBorder(javax.swing.BorderFactory.createTitledBorder("Fecha y Hora Corrida"));
        jlbl_fecha.setText("Fecha Corrida:");

        jlbl_hora.setText("Fecha Compra:");

        jdt_fechaCorrida.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdt_fechaCorridaKeyPressed(evt);
            }
        });

        jdt_fechaCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jdt_fechaCompraKeyPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpnl_fechahoracorridaLayout = new org.jdesktop.layout.GroupLayout(jpnl_fechahoracorrida);
        jpnl_fechahoracorrida.setLayout(jpnl_fechahoracorridaLayout);
        jpnl_fechahoracorridaLayout.setHorizontalGroup(
            jpnl_fechahoracorridaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpnl_fechahoracorridaLayout.createSequentialGroup()
                .add(jpnl_fechahoracorridaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jpnl_fechahoracorridaLayout.createSequentialGroup()
                        .add(jlbl_fecha)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED))
                    .add(jpnl_fechahoracorridaLayout.createSequentialGroup()
                        .add(jlbl_hora, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                        .add(1, 1, 1)))
                .add(jpnl_fechahoracorridaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jdt_fechaCorrida, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .add(jdt_fechaCompra, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnl_fechahoracorridaLayout.setVerticalGroup(
            jpnl_fechahoracorridaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnl_fechahoracorridaLayout.createSequentialGroup()
                .add(16, 16, 16)
                .add(jpnl_fechahoracorridaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlbl_fecha)
                    .add(jdt_fechaCorrida, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(16, 16, 16)
                .add(jpnl_fechahoracorridaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlbl_hora)
                    .add(jdt_fechaCompra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jpnl_datosCorrida.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Corrida"));
        jlbl_origen.setText("Origen:");

        jlbl_destino.setText("Destino:");

        jlbl_servicio.setText("Servicio:");

        jcb_origen.setModel(origenModel);
        jcb_origen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcb_origenKeyPressed(evt);
            }
        });

        jcb_destino.setModel(destinoModel);
        jcb_destino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcb_destinoKeyPressed(evt);
            }
        });

        jcb_servicio.setModel(servicioModel);
        jcb_servicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcb_servicioKeyPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jpnl_datosCorridaLayout = new org.jdesktop.layout.GroupLayout(jpnl_datosCorrida);
        jpnl_datosCorrida.setLayout(jpnl_datosCorridaLayout);
        jpnl_datosCorridaLayout.setHorizontalGroup(
            jpnl_datosCorridaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnl_datosCorridaLayout.createSequentialGroup()
                .addContainerGap()
                .add(jpnl_datosCorridaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlbl_servicio)
                    .add(jpnl_datosCorridaLayout.createSequentialGroup()
                        .add(jpnl_datosCorridaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jlbl_origen)
                            .add(jlbl_destino))
                        .add(14, 14, 14)
                        .add(jpnl_datosCorridaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jcb_origen, 0, 212, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jcb_servicio, 0, 212, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jcb_destino, 0, 212, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jpnl_datosCorridaLayout.setVerticalGroup(
            jpnl_datosCorridaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jpnl_datosCorridaLayout.createSequentialGroup()
                .add(jpnl_datosCorridaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlbl_origen)
                    .add(jcb_origen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jpnl_datosCorridaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlbl_destino)
                    .add(jcb_destino, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jpnl_datosCorridaLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jlbl_servicio)
                    .add(jcb_servicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jlbl_barraEstado.setText("jLabel1");

        jtbl_buscados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtbl_buscados.setModel(buscadosTable);
        jtbl_buscados.getTableHeader().setReorderingAllowed(false);
        jtbl_buscados.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jtbl_buscados.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtbl_buscadosKeyPressed(evt);
            }
        });

        jscp_buscados.setViewportView(jtbl_buscados);

        progressBar.setIndeterminate(true);

        etiqueta.setText("Procesando:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jscp_buscados, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                            .add(layout.createSequentialGroup()
                                .add(jpnl_fechahoracorrida, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jpnl_datosCorrida, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jpnl_nombre, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 350, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 23, Short.MAX_VALUE)
                        .add(etiqueta)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(progressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jpnl_nombre, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jpnl_datosCorrida, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jpnl_fechahoracorrida, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jscp_buscados, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 344, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                        .add(etiqueta))
                    .add(layout.createSequentialGroup()
                        .add(progressBar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void eventoKey(java.awt.event.KeyEvent evt){
if(enproceso) return;
        if(evt.getKeyCode() == evt.VK_ESCAPE){
            if(!tabla)
                funcionEscape();
            else
                limpiarCajitas(this.getComponents());
        }

        if(evt.getKeyCode() == evt.VK_ENTER){
           if(!tabla)
                buscarB();
            else{
            //codigoBarras.setReferencia(jtbl_buscados.getValueAt(jtbl_buscados.getSelectedRow(), 0).toString());
            codigoBarras.setFolioP(jtbl_buscados.getValueAt(jtbl_buscados.getSelectedRow(), 1).toString());
            codigoBarras.buscarB();
            this.dispose();                  
            }    
        }
    }
    
    private void jtbl_buscadosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtbl_buscadosKeyPressed
        if(evt.getKeyCode() == evt.VK_ESCAPE){
                limpiarCajitas(this.getComponents());
            }        
            if(evt.getKeyCode() == evt.VK_ENTER){
                //codigoBarras.setReferencia(jtbl_buscados.getValueAt(jtbl_buscados.getSelectedRow(), 0).toString());
                codigoBarras.setFolioP(jtbl_buscados.getValueAt(jtbl_buscados.getSelectedRow(), 1).toString());
                codigoBarras.buscarB();
                this.dispose();
            }
    }//GEN-LAST:event_jtbl_buscadosKeyPressed

    private void jdt_fechaCompraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdt_fechaCompraKeyPressed
        if(evt.getKeyCode() == evt.VK_UP){            
                ganarFoco(jdt_fechaCorrida,focusado);
                ganarFoco(jdt_fechaCompra,noFocusado);
                jdt_fechaCorrida.requestFocus();
            }
            if(evt.getKeyCode() == evt.VK_DOWN){            
                ganarFoco(jcb_origen,focusado);
                ganarFoco(jdt_fechaCompra,noFocusado);
                jcb_origen.requestFocus();
            }
        eventoKey(evt);
    }//GEN-LAST:event_jdt_fechaCompraKeyPressed

    private void jdt_fechaCorridaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jdt_fechaCorridaKeyPressed
        if(evt.getKeyCode() == evt.VK_DOWN){            
                ganarFoco(jdt_fechaCompra,focusado);
                ganarFoco(jdt_fechaCorrida,noFocusado);
                jdt_fechaCompra.requestFocus();
            }
            if(evt.getKeyCode() == evt.VK_UP){            
                ganarFoco(jtxt_apellidos,focusado);
                ganarFoco(jdt_fechaCorrida,noFocusado);               
                jtxt_apellidos.requestFocus();
            }
        eventoKey(evt);
    }//GEN-LAST:event_jdt_fechaCorridaKeyPressed

    private void jtxt_nombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxt_nombreFocusGained
        ganarFoco(jtxt_nombre,focusado);
    }//GEN-LAST:event_jtxt_nombreFocusGained

    private void jcb_servicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcb_servicioKeyPressed
        if(evt.getKeyCode() == evt.VK_RIGHT){
            ganarFoco(jtxt_nombre,focusado);
            ganarFoco(jcb_servicio,noFocusado);
            jtxt_nombre.requestFocus();
        }
        if(evt.getKeyCode() == evt.VK_LEFT){
            ganarFoco(jcb_destino,focusado);
            ganarFoco(jcb_servicio,noFocusado);
            jcb_destino.requestFocus();
        }        
        eventoKey(evt);
    }//GEN-LAST:event_jcb_servicioKeyPressed

    private void jcb_destinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcb_destinoKeyPressed
        if(evt.getKeyCode() == evt.VK_RIGHT){            
            ganarFoco(jcb_servicio,focusado);
            ganarFoco(jcb_destino,noFocusado);
            jcb_servicio.requestFocus();
        }
        if(evt.getKeyCode() == evt.VK_LEFT){            
            ganarFoco(jcb_origen,focusado);
            ganarFoco(jcb_destino,noFocusado);
            jcb_origen.requestFocus();
        }
        eventoKey(evt);
    }//GEN-LAST:event_jcb_destinoKeyPressed

    private void jcb_origenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcb_origenKeyPressed
        if(evt.getKeyCode() == evt.VK_RIGHT){            
            ganarFoco(jcb_destino,focusado);
            ganarFoco(jcb_origen,noFocusado);
            jcb_destino.requestFocus();
        }
        if(evt.getKeyCode() == evt.VK_LEFT){            
            //ganarFoco(jdt_fechaCompra,focusado);
            ganarFoco(jcb_origen,noFocusado);
            jdt_fechaCompra.requestFocus();
        }
    eventoKey(evt);
    }//GEN-LAST:event_jcb_origenKeyPressed

    private void jtxt_apellidosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_apellidosKeyPressed
        if(evt.getKeyCode() == evt.VK_DOWN){            
            ganarFoco(jdt_fechaCorrida,focusado);            
            ganarFoco(jtxt_apellidos,noFocusado);
            jdt_fechaCorrida.requestFocus();
        }
        if(evt.getKeyCode() == evt.VK_UP){            
            ganarFoco(jtxt_nombre,focusado);
            ganarFoco(jtxt_apellidos,noFocusado);
            jtxt_nombre.requestFocus();
        }
    eventoKey(evt);
    }//GEN-LAST:event_jtxt_apellidosKeyPressed

    private void jtxt_nombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_nombreKeyPressed
        if(evt.getKeyCode() == evt.VK_DOWN){            
            ganarFoco(jtxt_apellidos,focusado);
            ganarFoco(jtxt_nombre,noFocusado);
            jtxt_apellidos.requestFocus();
        }
        if(evt.getKeyCode() == evt.VK_UP){
            ganarFoco(jcb_servicio,focusado);
            ganarFoco(jtxt_nombre,noFocusado);
            jcb_servicio.requestFocus();
        }
        eventoKey(evt);      
    }//GEN-LAST:event_jtxt_nombreKeyPressed
    
    public void ganarFoco(Component component, Color color){
        Object obj = (Object)component;           
        if (obj instanceof JTextTextField)         
            ((JTextField)obj).setBackground(color);        
        if (obj instanceof JTextField)
            ((JTextField)obj).setBackground(color);
        if ( obj instanceof JComboBox)
            ((JComboBox)obj).setBackground(color);
        if ( obj instanceof JDateChooser)        
            ((JDateChooser)obj).setBackground(color);
    }

    private void funcionEscape() {
        if(jtxt_nombre.getText().length() == 0 && 
           jtxt_apellidos.getText().length() == 0 && 
           jdt_fechaCorrida.getText().length() == 0 && 
           jdt_fechaCompra.getText().length() == 0 &&
           jcb_origen.getSelectedIndex() == 0 &&
           jcb_destino.getSelectedIndex() == 0 &&
           jcb_servicio.getSelectedIndex() == 0)
            this.dispose();
        else{
            System.out.println("limpiarComponentes");
            limpiarCajitas(this.getContentPane().getComponents());            
        }            
    }

    /*private void limpiarComponentes(Component[] component) {        
        Object obj;
        for(int k = 0; k< component.length; k++) {
            obj = (Object)component[k];
            if (obj instanceof JTextTextField)
                ((JTextField)obj).setText("");
            if (obj instanceof JTextField)
                ((JTextField)obj).setText("");
            if ( obj instanceof JComboBox)
                ((JComboBox)obj).setSelectedIndex(0);
            if ( obj instanceof JDateChooser) 
                ((JDateChooser)obj).dateEditor.setTexto(new Date().toString());
            if ( obj instanceof JHourTextField)
                ((JHourTextField)obj).setText("");
            if ( obj instanceof JTable) {
                //((JHourTextField)obj).setText("");
                buscadosTable.setDataVector(null, buscadosHeader);
            }
            if(obj instanceof JPanel)
                limpiarComponentes(((JPanel)obj).getComponents());
        }
    }*/

    private void buscarBoleto() {
        if(jtxt_nombre.getText().length() == 0 && 
           jtxt_apellidos.getText().length() == 0 && 
           jdt_fechaCorrida.getText().length() == 0 && 
           jdt_fechaCompra.getText().length() == 0 &&
           jcb_origen.getSelectedIndex() == 0 &&
           jcb_destino.getSelectedIndex() == 0 &&
           jcb_servicio.getSelectedIndex() == 0){            
              JOptionPane.showMessageDialog( this, "¡Error! No ha seleccionado ningun parametro de búsqueda",
                                        "TMS - Facturar Boleto", JOptionPane.ERROR_MESSAGE );
              return;
        }
        
        etiqueta.setVisible(true);
        progressBar.setVisible(true);        
        
        String nombre = jtxt_nombre.getText().replaceAll(" ", "");
        String apellidos = jtxt_apellidos.getText().replaceAll(" ","");
        String nombreCompleto = ""+nombre.toUpperCase() + apellidos.toUpperCase();
        String origen = ""+jcb_origen.getSelectedItem().toString();
        String destino = ""+jcb_destino.getSelectedItem().toString();
        String servicio = ""+jcb_servicio.getSelectedItem().toString();
        String fechaCorrida = "'"+jdt_fechaCorrida.getText()+"'";
        String fechaVenta = "'"+jdt_fechaCompra.getText()+"'";
        if(jdt_fechaCorrida.getText().length() == 0)
            fechaCorrida = "NULL";
        if(jdt_fechaCompra.getText().length() == 0)
            fechaVenta = "NULL";
        if(jcb_origen.getSelectedIndex() == 0)
            origen = "";
        if(jcb_destino.getSelectedIndex() == 0)
            destino = "";
        if(jcb_servicio.getSelectedIndex() == 0)
            servicio = "";
        buscadosData =  facade.buscarBoletoNombre(nombreCompleto, fechaCorrida, origen, destino, servicio,fechaVenta);        
        if(buscadosData == null){
            JOptionPane.showMessageDialog( this, "<html>¡Error! No se ha encontrado información con los parámetros seleccionados.<br>Intente nuevamente con una selección de parámetros de búsqueda diferentes.</html>",
                                        "TMS - Facturar Boleto", JOptionPane.ERROR_MESSAGE );
            tabla = false;
            limpiarCajitas(this.getComponents());
              return;
        }
        if(buscadosData.size() == 0){
            JOptionPane.showMessageDialog( this, "<html>¡Error! No se ha encontrado información con los parámetros seleccionados.<br>Intente nuevamente con una selección de parámetros de búsqueda diferentes.</html>",
                                        "TMS - Facturar Boleto", JOptionPane.ERROR_MESSAGE );
              tabla = false;
              limpiarCajitas(this.getComponents());
              return;
        }
        System.out.println("buscadosData buscarBoletoNombre "+buscadosData);
        buscadosTable.setDataVector(buscadosData, buscadosHeader);       
        resizeColumnasCorridas(jtbl_buscados);
        //folioPreimpreso = jtbl_buscados.getValueAt(0,0).toString();
        jtbl_buscados.setRowSelectionInterval(0,0);
        tabla = true;
        jtbl_buscados.requestFocus();
        jlbl_barraEstado.setText("<html>  <font color=FF0000>   ESC</font> Nueva Búsqueda | <font color=FF0000>   ENTER</font> Seleccionar Boleto");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiqueta;
    private javax.swing.JComboBox jcb_destino;
    private javax.swing.JComboBox jcb_origen;
    private javax.swing.JComboBox jcb_servicio;
    private tms_calendario.JDateTextField jdt_fechaCompra;
    private tms_calendario.JDateTextField jdt_fechaCorrida;
    private javax.swing.JLabel jlbl_apellidos;
    private javax.swing.JLabel jlbl_barraEstado;
    private javax.swing.JLabel jlbl_destino;
    private javax.swing.JLabel jlbl_fecha;
    private javax.swing.JLabel jlbl_hora;
    private javax.swing.JLabel jlbl_nombre;
    private javax.swing.JLabel jlbl_origen;
    private javax.swing.JLabel jlbl_servicio;
    private javax.swing.JPanel jpnl_datosCorrida;
    private javax.swing.JPanel jpnl_fechahoracorrida;
    private javax.swing.JPanel jpnl_nombre;
    private javax.swing.JScrollPane jscp_buscados;
    private javax.swing.JTable jtbl_buscados;
    private tms_TextFields.JTextTextField jtxt_apellidos;
    private tms_TextFields.JTextTextField jtxt_nombre;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
    
    public void resizeColumnasCorridas(JTable jtable){
        TableColumnModel columnModel = jtable.getColumnModel();

           for (int col=0; col<jtable.getColumnCount(); col++) 
           {
                int maxwidth = 0;            
                for (int row=0; row<jtable.getRowCount(); row++) {
                    TableCellRenderer rend  = jtable.getCellRenderer(row, col); 
                    Object value = jtable.getValueAt (row, col); 
                    Component comp = rend.getTableCellRendererComponent (jtable, value, false, false, row, col);
                    maxwidth = Math.max (comp.getPreferredSize().width, maxwidth); 
                } // for row

                TableColumn column = columnModel.getColumn (col);
                TableCellRenderer headerRenderer = column.getHeaderRenderer();
                if (headerRenderer == null)
                    headerRenderer = jtable.getTableHeader().getDefaultRenderer();

                Object headerValue = column.getHeaderValue();
                Component headerComp = headerRenderer.getTableCellRendererComponent (jtable, headerValue, false, false, 0, col);
                maxwidth = Math.max (maxwidth, headerComp.getPreferredSize().width);
                column.setPreferredWidth (maxwidth + 15);
           }
        jtbl_buscados.setModel(buscadosTable);
      }

    private void cargarOrigenes() {
        System.out.println("origenDestino "+origenDestino);
        origenModel = new DefaultComboBoxModel(origenDestino);
        estaTerminal = facade.buscarTerminal().get(0).toString();
        indiceTerminal = indiceTerminal(origenModel, estaTerminal);
    }
   
    private void cargarDestinos(boolean estado) {
        Vector vec = new Vector();
        if(estado) {
            for(int j = 0; j < origenDestino.size(); j++)
                vec.add(origenDestino.get(j).toString());
            destinoModel = new DefaultComboBoxModel(vec);
        }
        destinoModel.removeElementAt(indiceTerminal);
    }
    
    private void cargarServicios() {
        Vector vec = facade.buscarServicios();
        servicioModel = new DefaultComboBoxModel(vec);
    }
    
   private int indiceTerminal(DefaultComboBoxModel model, String terminal){
        System.out.println("terminal "+terminal);
        for(int k = 0; k < model.getSize(); k++) {
            //System.out.println("model.getElementAt(k).toString() "+model.getElementAt(k).toString());
            if(model.getElementAt(k).toString().equals(terminal)){
                return k;
            }
        }
        return 0;
    }

    private void limpiarCajitas(Component[] component) {
       Object obj;        
        buscadosTable.setDataVector(null, buscadosHeader);
        jtbl_buscados.setModel(buscadosTable);
        for(int i = 0; i < component.length; i++){
            obj = (Object)component[i];
            //System.out.println("obj "+obj.getClass().toString());
            if (obj instanceof JComboBox ){
                ((JComboBox)obj).setSelectedIndex(0);               
            }
            if (obj instanceof JTextField) {
                ((JTextField)obj).setText("");                
            }
            if (obj instanceof JDateTextField) {
                ((JDateChooser)obj).dateEditor.setTexto("");                
            }            
            if(obj instanceof JPanel)
                limpiarCajitas(((JPanel)obj).getComponents());
            if(obj instanceof JRootPane)
                limpiarCajitas(((JRootPane)obj).getComponents());
            if(obj instanceof JLayeredPane)
                limpiarCajitas(((JLayeredPane)obj).getComponents());
            ganarFoco(component[i], noFocusado );
        }
        jtxt_nombre.requestFocus();
        tabla = false;
    }
    
private boolean enproceso=false;
    public void buscarB(){
            SwingWorker worker = new SwingWorker(){
                public Object construct() {
                    return doWork();
                }

                public void finished() {
                    System.out.println("Finished!!");
                    etiqueta.setVisible(false);
                    progressBar.setVisible(false);
                    enproceso=false;                        
                }
            };
            
            if(enproceso) return;
            enproceso=true;
            worker.start();    
    }
    
    Object doWork() {
        try {

        buscarBoleto();    
        
        if(Thread.interrupted()){
            throw new InterruptedException();
        }
        
        }catch(InterruptedException e){
            return "Interrupted";
        }catch(Exception ex){
            ex.printStackTrace();
            return "Interrupted";            
        }
        return "All Done";
    }    
    
}


