/*
 * JDlgBProgreso.java
 *
 * Created on 25 de septiembre de 2008, 10:23 AM
 */

package xer_emv_dll;

import DialogosX.JDlgAceptar;
import DialogosX.JDlgAcumulaEstrellasHO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Observer;
import javax.swing.SwingUtilities;
import tms_venta.JClsColoresInterfaz;

/**
 *
 * @author  ocruz
 */
public class JDlgBProgresoLealtadHO extends javax.swing.JDialog {
    
    /** Creates new form JDlgBProgreso */
    public JDlgBProgresoLealtadHO(JObsBProgreso pModelo, final JDlgAcumulaEstrellasHO met) {
        this.setModal(false);
        initComponents();
        interfazColor();
        centrarJDialog();
        this.setVisible(true);
        modelo = pModelo;
        jlbl_mensaje.setFocusTraversalKeysEnabled(false);
        //this.setUndecorated(true);
        modelo.addObserver (new Observer (){
             public void update(java.util.Observable o, Object arg){
                 final int numero = Integer.valueOf(arg.toString());
                 SwingUtilities.invokeLater(new Runnable(){
                     public void run(){
                         //if(numero>190){
                         //if(numero>600){
                         if(met.isRespondio())
                         {
                             //met.limpiaProgreso();
                             finaliza();
                             //new JDlgAceptar().mostrarDialogo("TMS Venta.", "Operación cancelada.",Color.RED);
                             new JDlgAceptar().mostrarDialogo("TMS Lealtad.", "Tiempo de espera agotado.",Color.RED);
                         }
                             jPsbBarra.setString(numero+" s");
                     }
                 });
             }
         });
    }   
    
    private void centrarJDialog(){
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, (( screenSize.height - frameSize.height ) / 2)+22);
    }
    
    private void interfazColor(){
        jPsbBarra.setForeground(ColoresInterfaz.cFondoPieEncabezado);
        jPsbBarra.setFont(ColoresInterfaz.fuente3);
        jlbl_mensaje.setForeground(ColoresInterfaz.cFondoPieEncabezado);
        jPsbBarra.setFont(ColoresInterfaz.fuente2);
        
    }
    
    public void finaliza(){
        if(modelo!=null){
            modelo.detenerTimer();
            modelo.deleteObservers();
            modelo = null;
            System.out.println("hilo barra de progreso finalizado.");
            this.dispose();
            return;
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPsbBarra = new javax.swing.JProgressBar();
        jlbl_mensaje = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Por favor espere...");
        setAlwaysOnTop(true);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPsbBarra.setFocusable(false);
        jPsbBarra.setIndeterminate(true);
        jPsbBarra.setString("0 s");
        jPsbBarra.setStringPainted(true);

        jlbl_mensaje.setText("Leyendo tarjeta, favor de no presionar ninguna tecla.");
        jlbl_mensaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jlbl_mensajeKeyPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPsbBarra, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jlbl_mensaje, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPsbBarra, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jlbl_mensaje)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbl_mensajeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jlbl_mensajeKeyPressed
        if(evt.getKeyCode() == evt.VK_C && evt.isControlDown())
            finaliza();
    }//GEN-LAST:event_jlbl_mensajeKeyPressed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        jlbl_mensaje.requestFocusInWindow();
        
    }//GEN-LAST:event_formWindowGainedFocus

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jPsbBarra;
    private javax.swing.JLabel jlbl_mensaje;
    // End of variables declaration//GEN-END:variables
    private JClsColoresInterfaz ColoresInterfaz = new JClsColoresInterfaz();
    private JObsBProgreso modelo;
}
