/*
 * JIFAccUbic.java
 *
 * Created on 15 de agosto de 2007, 12:16 PM
 */

package tms_accesoubicaciones;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.beans.PropertyVetoException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Vector;
import javax.swing.JComponent;
import javax.swing.JInternalFrame;
import javax.swing.KeyStroke;
import tms_accesoubicaciones.util.BarraMensajes;
import tms_accesoubicaciones.util.JDlgAceptar;
import tms_accesoubicaciones.util.JDlgSiNo;

/**
 *
 * @author  ocruz
 */
public class JIFAccUbic extends JInternalFrame{
    
    /**
     * Creates new form JIFAccUbic
     */
    public JIFAccUbic(Vector datosIniciales) {
        this.datosIniciales = datosIniciales;
        this.USUARIO_ID = Long.valueOf(datosIniciales.get(0).toString());
        this.USUARIO_NUMERO = datosIniciales.get(1).toString();
        this.USUARIO_NOMBRE = datosIniciales.get(2).toString();
        this.SESION_ID = Long.valueOf(datosIniciales.get(3).toString());
        this.MENU_ID = Long.valueOf(datosIniciales.get(4).toString());
        System.out.println("SISTEMA INICIADO");
        sesionVenta = new SesionVenta(this.USUARIO_ID, this.MENU_ID);
        int inicio = sesionVenta.procesoInicial();
        switch(inicio){
            case -1: DialogoAceptar = new JDlgAceptar("¡No existe conexion con la base de datos!", "Contacte al administrador del sistema.", Color.RED); break;
            case 1: DialogoAceptar = new JDlgAceptar("¡Configuracion de terminal local incorrecta!", "Contacte al administrador del sistema.", Color.RED); break;
            case 2: DialogoAceptar = new JDlgAceptar("¡Configuracion de estados de autobus incorrecta!", "Contacte al administrador del sistema.", Color.RED); break;
        }
        if(inicio!=0) {
            this.inicioGral=false;
            return;
        }
        this.inicioGral=true;
        initComponents();
        //((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        this.setTitle("Autobus - Acceso a Ubicaciones - "+formatoFecha.format(new Date())+"                 v1.22");
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        centrarJIF();
        inhabilitarF10();
    }
    
    private void inhabilitarF10() {
        this.jCboUbi.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
        this.jCboAct.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
    }

    private void centrarJIF(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, ( screenSize.height - frameSize.height ) / 2 );
    }
    
    private void CerrarIFrame(){
        DialogoSiNo = new JDlgSiNo("!Confirme¡", "¿Realmente desea salir del programa?");
        if(!DialogoSiNo.getResultado()) return;
        this.dispose();
        return;
    }
    
    public boolean getInicioGral(){ return this.inicioGral; }
    
    public void setMensaje(String msg){
        jLblBarraEstado.setText(msg);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLblBarraEstado = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxtEco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtDesc = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jCboUbi = new javax.swing.JComboBox(sesionVenta.getUbicaciones());
        jLabel4 = new javax.swing.JLabel();
        jCboAct = new javax.swing.JComboBox(sesionVenta.getCausas());

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconifiable(true);
        setTitle("Autobus - Acceso a Ubicaciones");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLblBarraEstado.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLblBarraEstado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLblBarraEstado.setText("<html><font color=ff0000>F1</font> Seleccionar autobus | <font color=ff0000>&#171; &#187;</font> Ingresar datos | <font color=ff0000>F9</font> Guardar cambios | <font color=ff0000>F4</font> Cerrar aplicacion</html>");
        jLblBarraEstado.setFocusable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registrar Ubicacion de Autobus", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), java.awt.Color.black));
        jPanel1.setFocusable(false);
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("Numero Economico:");

        jTxtEco.setEditable(false);
        jTxtEco.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTxtEco.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtEco.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Descripcion:");

        jTxtDesc.setEditable(false);
        jTxtDesc.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTxtDesc.setFocusable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("Ubicacion:");

        jCboUbi.setFont(new java.awt.Font("Tahoma", 1, 11));
        jCboUbi.setFocusTraversalKeysEnabled(false);
        jCboUbi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCboUbiKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel4.setText("Actividad:");

        jCboAct.setFont(new java.awt.Font("Tahoma", 1, 11));
        jCboAct.setFocusTraversalKeysEnabled(false);
        jCboAct.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCboActKeyPressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jLabel1)
                    .add(jLabel2)
                    .add(jLabel3)
                    .add(jLabel4))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jTxtEco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 97, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jCboAct, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jCboUbi, 0, 188, Short.MAX_VALUE))
                    .add(jTxtDesc, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jTxtEco, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jTxtDesc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jCboUbi, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(jCboAct, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(10, 10, 10)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
                .add(10, 10, 10))
            .add(jLblBarraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLblBarraEstado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCboActKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCboActKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_RIGHT: case KeyEvent.VK_LEFT: jCboUbi.requestFocusInWindow(); break;
            case KeyEvent.VK_1: if(evt.isControlDown()){
                                    this.eventoTeclado=evt;
                                    try {this.setIcon(true);} catch (PropertyVetoException ex) { ; }
                                  }
                                  break;
            case KeyEvent.VK_2: if(evt.isControlDown()) 
                                try {this.setIcon(true);
                                } catch (PropertyVetoException ex) { ; } break;
            case KeyEvent.VK_F4: CerrarIFrame(); break;
            
            case KeyEvent.VK_F1: SeleccionarAutobus(); break;
            case KeyEvent.VK_F9: GuardarInfo(); break;
        }
    }//GEN-LAST:event_jCboActKeyPressed

    private void jCboUbiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCboUbiKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_RIGHT: case KeyEvent.VK_LEFT: jCboAct.requestFocusInWindow(); break;
            case KeyEvent.VK_1: if(evt.isControlDown()){
                                    this.eventoTeclado=evt;
                                    try {this.setIcon(true);} catch (PropertyVetoException ex) { ; }
                                  }
                                  break;
            case KeyEvent.VK_2: if(evt.isControlDown()) 
                                try {this.setIcon(true);
                                } catch (PropertyVetoException ex) { ; } break;
            case KeyEvent.VK_F4: CerrarIFrame(); break;
            
            case KeyEvent.VK_F1: SeleccionarAutobus(); break;
            case KeyEvent.VK_F9: GuardarInfo(); break;
        }
    }//GEN-LAST:event_jCboUbiKeyPressed
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
// TODO add your handling code here:
        jLblBarraEstado.setText(barraMensajes.getMsgComun(0));
        setFoco();
    }//GEN-LAST:event_formComponentShown

    public void setFoco(){
        jCboUbi.requestFocusInWindow();
    }
    
    private void SeleccionarAutobus() {
        JDlgSelAutobus jDlgSelAutobus = new JDlgSelAutobus(sesionVenta);
        jDlgSelAutobus.setVisible(true);
        this.Fila=jDlgSelAutobus.getFilaAutobusSeleccionado();
        if(this.Fila==-1) return;
        jTxtEco.setText(sesionVenta.getAutobuses(this.Fila).getNumeroEconomico());
        jTxtDesc.setText("Estado: "+sesionVenta.getAutobuses(this.Fila).getEstadoNombre()+" - Ubicacion: "+
                sesionVenta.getAutobuses(this.Fila).getUbicacionNombre()+" - Actividad: "+
                sesionVenta.getAutobuses(this.Fila).getActividadNombre());
    }

    private void GuardarInfo() {
        if(jTxtEco.getText().equals("")){
            DialogoAceptar = new JDlgAceptar("¡Imposible registrar el acceso!", "No ha seleccionado un autobus.", Color.RED);
            return;
        }
        
        /*if(jCboUbi.getSelectedItem().toString().equals(sesionVenta.getAutobuses(this.Fila).getUbicacionNombre())){
            DialogoAceptar = new JDlgAceptar("¡La ubicacion es la misma!", "Seleccione la ubicacion real del autobus.", Color.RED);
            jCboUbi.requestFocusInWindow();
            return;
        }*/
        
        /*if(jCboAct.getSelectedItem().toString().equals(sesionVenta.getAutobuses(this.Fila).getActividadNombre())){
            DialogoAceptar = new JDlgAceptar("¡La actividad es la misma!", "Seleccione la actividad nueva del autobus.", Color.RED);
            jCboAct.requestFocusInWindow();
            return;
        }*/
        
        if(!sesionVenta.registraAccesoUbicacion(this.Fila, jCboUbi.getSelectedItem().toString(), jCboAct.getSelectedItem().toString())){
            DialogoAceptar = new JDlgAceptar("¡No se pudo actualizar el estado del autobus!", "Intentelo mas tarde.", Color.RED);
            this.dispose();
            return;
        }
        DialogoAceptar = new JDlgAceptar("¡Estado del autobus actualizado correctamente!", "<html>Autobus "+jTxtEco.getText()+" "+sesionVenta.getNuevoEstado()+"."+sesionVenta.getMsgActEdoOper()+"<html>", Color.RED);
        jTxtEco.setText("");
        jTxtDesc.setText("");
        jCboUbi.setSelectedIndex(0);
        jCboAct.setSelectedIndex(0);
        jCboUbi.requestFocusInWindow();
    }
        
    public KeyEvent getEventoTeclado(){ return this.eventoTeclado; }
    
    public void setEventoTeclado(KeyEvent evento){ this.eventoTeclado=evento; }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCboAct;
    private javax.swing.JComboBox jCboUbi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLblBarraEstado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtDesc;
    private javax.swing.JTextField jTxtEco;
    // End of variables declaration//GEN-END:variables
    private Vector datosIniciales = new Vector();
    private long MENU_ID=282;
    private long USUARIO_ID=282;
    private String USUARIO_NUMERO;
    private String USUARIO_NOMBRE;
    private long SESION_ID=282;
    
    private SesionVenta sesionVenta=null;
    private JDlgAceptar DialogoAceptar;
    private JDlgSiNo DialogoSiNo;
    private BarraMensajes barraMensajes = new BarraMensajes();
    private boolean inicioGral;
    private int Fila=-1;
    private SimpleDateFormat formatoFecha= new SimpleDateFormat("dd/MM/yyyy");
    private KeyEvent eventoTeclado;
}