/*
 * JIFCanJE.java
 *
 * Created on 6 de septiembre de 2007, 12:41 PM
 */

package DialogosX;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JViewport;
import javax.swing.table.DefaultTableModel;
import tms_venta.SesionVenta;
import java.sql.Timestamp;
import javax.swing.DefaultCellEditor;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableColumn;
import subProcesos.JClsSintaxis;
import subProcesos.JTextTextFieldMaxCharAlfa;
import subProcesos.JTxtFieldFolios;
import tms_venta.JClsColoresInterfaz;

/**
 *
 * @author  ocruz
 */
public class JDlgCanjeBAMultiBoleto extends javax.swing.JDialog{
    /** Creates new form JIFCanje */
    public JDlgCanjeBAMultiBoleto(SesionVenta pSesionVenta, Vector pOrigenes, Object[] pCiudadesConexion, Object[] pObjEmp, long thFechaHoraSistema){
        this.Origenes=pOrigenes;
        this.sesionVenta = pSesionVenta;
        this.CiudadesConexion = pCiudadesConexion;
        this.horaSistema = thFechaHoraSistema;
        this.horaSistemaHasta = thFechaHoraSistema+604800000; // hasta 7 dias
        sesionVenta.cargarODServicios(sesionVenta.getUserCon().getTerminalNombre());
        cbmServicio = new DefaultComboBoxModel(sesionVenta.getSs());
        this.COAnt = sesionVenta.getUserCon().getTerminalNombre();
        this.objEmp = pObjEmp;
        objEmpresas = new Object[objEmp.length];
        for(int i=0; i<objEmpresas.length; i++)
            objEmpresas[i] = sesionVenta.getEmpresasId(objEmp[i].toString()) + "-" + objEmp[i].toString();
        ordenaListaEmpresas();
        initComponents();
        jTblBoletoOriginal.setAutoResizeMode( JTable.AUTO_RESIZE_OFF );
        jLabel4.setText("<html><font color="+ColoresInterfaz.cHTML3+">ARRIBA/ABAJO </font> Ingresar Criterios | <font color="+ColoresInterfaz.cHTML3+">ENTER</font> Buscar Boleto | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Salir</html>");
        interfazColor();
        jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
        jlblestino.setVisible(false);
        jCboDestino.setVisible(false);
        jLabel3.setVisible(true);
        jCboServicio.setVisible(true);
        jLabel6.setVisible(true);
        jCboEmpresas.setVisible(true);        
        this.setModal(true);
        centrarJDialog();
        
        jlbl_folRef.setText("Folio");
        jClsSintaxis = new JClsSintaxis();
        xTabla.setDataVector(null, encabezado);
        AnchoColumnas();
        jCboServicio.setSelectedIndex(0);
    }
    
    private void centrarJDialog(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, ( screenSize.height - frameSize.height ) / 2 );
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCboOrigen = new javax.swing.JComboBox();
        jCboOrigen = new JComboBox(Origenes);
        jCboOrigen.setFocusTraversalKeysEnabled(false);
        jlbl_folRef = new javax.swing.JLabel();
        jTxtFolioPreimpreso = new JTxtFieldFolios();
        jTxtFolioPreimpreso.setFocusTraversalKeysEnabled(false);
        jLabel3 = new javax.swing.JLabel();
        jCboServicio = new javax.swing.JComboBox();
        jCboServicio = new JComboBox(cbmServicio);
        jCboServicio.setFocusTraversalKeysEnabled(false);
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCboEmpresas = new javax.swing.JComboBox();
        jCboEmpresas = new JComboBox(objEmpresas);
        jScpBoletoOriginal = new javax.swing.JScrollPane();
        jTblBoletoOriginal = new javax.swing.JTable();
        jchbx_bolRef = new javax.swing.JCheckBox();
        jchbx_bolConv = new javax.swing.JCheckBox();
        jCboDestino = new javax.swing.JComboBox();
        jCboDestino = new JComboBox(Origenes);
        jCboDestino.setFocusTraversalKeysEnabled(false);
        jlblestino = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(" Canje boleto abierto");
        setName("Ventana"); // NOI18N
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel1.setText("Origen");

        jCboOrigen.setFont(new java.awt.Font("Tahoma", 1, 10));
        jCboOrigen.setName("Origen"); // NOI18N
        jCboOrigen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCboOrigenKeyPressed(evt);
            }
        });

        jlbl_folRef.setFont(new java.awt.Font("Tahoma", 1, 10));
        jlbl_folRef.setText("Referencia");

        jTxtFolioPreimpreso.setFont(new java.awt.Font("Tahoma", 1, 10));
        jTxtFolioPreimpreso.setName("FolioPreimpreso"); // NOI18N
        jTxtFolioPreimpreso.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTxtFolioPreimpresoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTxtFolioPreimpresoFocusLost(evt);
            }
        });
        jTxtFolioPreimpreso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtFolioPreimpresoKeyPressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel3.setText("Servicio");

        jCboServicio.setFont(new java.awt.Font("Tahoma", 1, 10));
        jCboServicio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCboServicioKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel4.setText("<html><font color=\"+ColoresInterfaz.cHTML1+\">ARRIBA/ABAJO</font> Ingresar Criterios | <font color=\"+ColoresInterfaz.cHTML1+\">ENTER</font> Buscar Boleto | <font color=\"+ColoresInterfaz.cHTML1+\">ESC</font> Salir</html>");
        jLabel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 10));
        jLabel6.setText("Empresa");

        jCboEmpresas.setFont(new java.awt.Font("Tahoma", 1, 10));
        jCboEmpresas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCboEmpresasKeyPressed(evt);
            }
        });

        jScpBoletoOriginal.setFocusable(false);
        jScpBoletoOriginal.setFont(new java.awt.Font("Tahoma", 1, 10));

        jTblBoletoOriginal.setFont(new java.awt.Font("Tahoma", 1, 10));
        jTblBoletoOriginal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTblBoletoOriginal.setModel(xTabla);
        jTblBoletoOriginal.getTableHeader().setReorderingAllowed(false);
        jTblBoletoOriginal.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        jTblBoletoOriginal.setFocusTraversalKeysEnabled(false);
        jTblBoletoOriginal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTblBoletoOriginalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTblBoletoOriginalFocusLost(evt);
            }
        });
        jTblBoletoOriginal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTblBoletoOriginalKeyPressed(evt);
            }
        });
        jScpBoletoOriginal.setViewportView(jTblBoletoOriginal);

        jchbx_bolRef.setFont(new java.awt.Font("Tahoma", 1, 10));
        jchbx_bolRef.setText("Boleto Referenciado");
        jchbx_bolRef.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jchbx_bolRef.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jchbx_bolRef.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jchbx_bolRefFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jchbx_bolRefFocusLost(evt);
            }
        });
        jchbx_bolRef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jchbx_bolRefKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jchbx_bolRefKeyReleased(evt);
            }
        });
        jchbx_bolRef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jchbx_bolRefMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jchbx_bolRefMouseReleased(evt);
            }
        });

        jchbx_bolConv.setFont(new java.awt.Font("Tahoma", 1, 10));
        jchbx_bolConv.setText("Boleto Convenio");
        jchbx_bolConv.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jchbx_bolConv.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jchbx_bolConv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jchbx_bolConvMouseClicked(evt);
            }
        });
        jchbx_bolConv.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jchbx_bolConvFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jchbx_bolConvFocusLost(evt);
            }
        });
        jchbx_bolConv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jchbx_bolConvKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jchbx_bolConvKeyReleased(evt);
            }
        });

        jCboDestino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCboDestinoKeyPressed(evt);
            }
        });

        jlblestino.setFont(new java.awt.Font("Tahoma", 1, 10));
        jlblestino.setText("Destino");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(14, 14, 14)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jLabel1)
                            .add(jlbl_folRef)
                            .add(jLabel3)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel6)))
                .add(10, 10, 10)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jTxtFolioPreimpreso, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 693, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, jCboServicio, 0, 269, Short.MAX_VALUE)
                            .add(jCboEmpresas, 0, 269, Short.MAX_VALUE))
                        .add(434, 434, 434))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jCboOrigen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 143, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(29, 29, 29)
                        .add(jchbx_bolRef)
                        .add(14, 14, 14)
                        .add(jchbx_bolConv)
                        .add(16, 16, 16)
                        .add(jlblestino)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCboDestino, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 126, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScpBoletoOriginal, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jCboOrigen, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jchbx_bolRef)
                    .add(jchbx_bolConv)
                    .add(jlblestino)
                    .add(jCboDestino, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(7, 7, 7)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jlbl_folRef)
                    .add(jTxtFolioPreimpreso, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel3)
                    .add(jCboServicio, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCboEmpresas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScpBoletoOriginal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 238, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 12, Short.MAX_VALUE)
                .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 21, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCboDestinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCboDestinoKeyPressed
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE:
                chOk=false;
                this.dispose();
                break;
            case KeyEvent.VK_ENTER:
                break;
                
            case KeyEvent.VK_LEFT:
                jchbx_bolConv.requestFocusInWindow();
                break;
            case KeyEvent.VK_RIGHT:
                jTxtFolioPreimpreso.selectAll();
                jTxtFolioPreimpreso.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jCboDestinoKeyPressed

    private void jchbx_bolConvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jchbx_bolConvMouseClicked
       jchbx_bolConv.setSelected(!jchbx_bolConv.isSelected());
        /*
        if(jchbx_bolConv.isSelected()) {
            jchbx_bolConv.setSelected(false);
            jCboDestino.setVisible(false);
            jlblestino.setVisible(false);
        } else {
            jchbx_bolConv.setSelected(true);
            jCboDestino.setVisible(true);
            jCboDestino.setSelectedIndex(0);
            jlblestino.setVisible(true);
        }
         * 
         */
    }//GEN-LAST:event_jchbx_bolConvMouseClicked

    private void jchbx_bolConvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jchbx_bolConvKeyReleased
        if(evt.getKeyCode() == evt.VK_SPACE) {
            jchbx_bolConv.setSelected(!jchbx_bolConv.isSelected());
            /*
            if(jchbx_bolConv.isSelected()) {
                jchbx_bolConv.setSelected(false);
                jCboDestino.setVisible(false);
                jlblestino.setVisible(false);
            } else {
                jchbx_bolConv.setSelected(true);
                jCboDestino.setVisible(true);
                jCboDestino.setSelectedIndex(0);
                jlblestino.setVisible(true);
            }
             * 
             */
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jchbx_bolConvKeyReleased

    private void jchbx_bolConvKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jchbx_bolConvKeyPressed
        if(evt.getKeyCode() == evt.VK_SPACE)
            return;
        
        if(evt.getKeyCode() == evt.VK_LEFT)
            jchbx_bolRef.requestFocus();
        
        if(evt.getKeyCode() == evt.VK_RIGHT) {
            if(jCboDestino.isVisible())
                jCboDestino.requestFocusInWindow();
            else {
                jTxtFolioPreimpreso.selectAll();
                jTxtFolioPreimpreso.requestFocusInWindow();
            }
        }
        
        if(evt.getKeyCode() == evt.VK_F2) {
            if(jchbx_bolConv.isSelected()) {
                jchbx_bolConv.setSelected(false);
                jCboDestino.setVisible(false);
                jlblestino.setVisible(false);
                jLabel3.setVisible(true);
                jCboServicio.setVisible(true);
                jLabel6.setVisible(true);
                jCboEmpresas.setVisible(true);        
                
            } else {
                jchbx_bolConv.setSelected(true);
                jCboDestino.setVisible(true);
                jCboDestino.setSelectedIndex(0);
                jlblestino.setVisible(true);
                jLabel3.setVisible(false);
                jCboServicio.setVisible(false);
                jLabel6.setVisible(false);
                jCboEmpresas.setVisible(false);        
                
            }
        }
        
        if(evt.getKeyCode() == evt.VK_ESCAPE) {
            chOk=false;
            this.dispose();
        }
        
        
        if(evt.getKeyCode() == evt.VK_ENTER) {
            }
            
 
        
    }//GEN-LAST:event_jchbx_bolConvKeyPressed

    private void jchbx_bolConvFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jchbx_bolConvFocusLost
        jchbx_bolConv.setFont(new java.awt.Font("Calibri", 1, 15));
        jLabel4.setText("<html><font color="+ColoresInterfaz.cHTML3+">IZQ DER </font> Ingresar Criterios | <font color="+ColoresInterfaz.cHTML3+">ENTER</font> Buscar Boleto | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Salir</html>");
    }//GEN-LAST:event_jchbx_bolConvFocusLost

    private void jchbx_bolConvFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jchbx_bolConvFocusGained
        jchbx_bolConv.setFont(new java.awt.Font("Calibri", 3, 15));
        jLabel4.setText("<html><font color="+ColoresInterfaz.cHTML3+">IZQ DER </font> Ingresar Criterios | <font color="+ColoresInterfaz.cHTML3+">F2</font> Seleccionar/Deseleccionar | <font color="+ColoresInterfaz.cHTML3+">ENTER</font> Buscar Boleto | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Salir</html>");
    }//GEN-LAST:event_jchbx_bolConvFocusGained

    private void jchbx_bolRefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jchbx_bolRefMouseClicked
          if(jchbx_bolRef.isSelected())
              jchbx_bolRef.setSelected(false);
          else
             jchbx_bolRef.setSelected(true);  
    }//GEN-LAST:event_jchbx_bolRefMouseClicked

    private void jchbx_bolRefKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jchbx_bolRefKeyReleased
      if(evt.getKeyCode() == evt.VK_SPACE)
      {
          if(jchbx_bolRef.isSelected())
              jchbx_bolRef.setSelected(false);
          else
             jchbx_bolRef.setSelected(true);     
      }

    }//GEN-LAST:event_jchbx_bolRefKeyReleased

    private void jchbx_bolRefMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jchbx_bolRefMouseReleased
   
      
    }//GEN-LAST:event_jchbx_bolRefMouseReleased

    private void jchbx_bolRefFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jchbx_bolRefFocusLost
        jchbx_bolRef.setFont(new java.awt.Font("Calibri", 1, 15));
        jLabel4.setText("<html><font color="+ColoresInterfaz.cHTML3+">ARRIBA/ABAJO </font> Ingresar Criterios | <font color="+ColoresInterfaz.cHTML3+">ENTER</font> Buscar Boleto | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Salir</html>");
    }//GEN-LAST:event_jchbx_bolRefFocusLost

    private void jchbx_bolRefFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jchbx_bolRefFocusGained
        jchbx_bolRef.setFont(new java.awt.Font("Calibri", 3, 15));
        jLabel4.setText("<html><font color="+ColoresInterfaz.cHTML3+">ARRIBA/ABAJO </font> Ingresar Criterios | <font color="+ColoresInterfaz.cHTML3+">F2</font> Seleccionar/Deseleccionar | <font color="+ColoresInterfaz.cHTML3+">ENTER</font> Buscar Boleto | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Salir</html>");
    }//GEN-LAST:event_jchbx_bolRefFocusGained

    private void jchbx_bolRefKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jchbx_bolRefKeyPressed
     if(evt.getKeyCode() == evt.VK_SPACE)
         return;

     if(evt.getKeyCode() == evt.VK_LEFT)
      if(jCboOrigen.isEnabled())
          jCboOrigen.requestFocus();
         
     if(evt.getKeyCode() == evt.VK_RIGHT)    
     {
         //jTxtFolioPreimpreso.selectAll();
         //jTxtFolioPreimpreso.requestFocusInWindow();
         jchbx_bolConv.requestFocus();
     }
     
     if(evt.getKeyCode() == evt.VK_F2)
     {
         if(jchbx_bolRef.isSelected())
         {
             jchbx_bolRef.setSelected(false);
             jlbl_folRef.setText("Folio");
             jCboOrigen.setEnabled(true);
             jCboServicio.setEnabled(true);
             jCboEmpresas.setEnabled(true);
         }
         else
         {
             jchbx_bolRef.setSelected(true);
             jlbl_folRef.setText("Referencia");
             jCboOrigen.setEnabled(false);
             jCboServicio.setEnabled(false);
             jCboEmpresas.setEnabled(false);
         }
     }
     
            if(evt.getKeyCode() == evt.VK_ESCAPE)
            {
                chOk=false;
                this.dispose();
            }
            
          if(evt.getKeyCode() == evt.VK_ENTER)
          {
                    if(!this.COAnt.equals(jCboOrigen.getSelectedItem().toString())){
                        sesionVenta.getDBLinkClaveOrigen(jCboOrigen.getSelectedItem().toString());
                        sesionVenta.cargarODServicios(jCboOrigen.getSelectedItem().toString());
                        cbmServicio = new DefaultComboBoxModel(sesionVenta.getSs());
                        jCboServicio.setModel(cbmServicio);
                        this.COAnt=jCboOrigen.getSelectedItem().toString();
                    }
                    if(!validaCampos()) return;
                    if(!valMultiTx(jTxtFolioPreimpreso.getText())) return;
                    ConstruyeMultiBa();
                    if(jCboOrigen.getSelectedItem().toString().equals(sesionVenta.getUserCon().getTerminalNombre())) sesionVenta.setTipoTransaccion("L");
                    else sesionVenta.setTipoTransaccion("R");
                    if(jchbx_bolConv.isSelected())
                         boletos = sesionVenta.validaBoletoACConvenio(jCboOrigen.getSelectedItem().toString(), jCboDestino.getSelectedItem().toString(),  conjuntoFolios);
                    else
                        boletos = sesionVenta.buscaBoletoAbiertoMult(jCboOrigen.getSelectedItem().toString(), conjuntoFolios, 
                            sesionVenta.getVectorServiciosReal(jCboServicio.getSelectedItem().toString()), jCboEmpresas.getSelectedItem().toString().substring(2),
                            jClsSintaxis.getVectorFoliosBoletos().size());
                    if(boletos==null){
                        DialogoAceptar.mostrarDialogo("¡Imposible realizar canje!","<html>Puede ser que los criterios de busqueda son incorrectos o<br>" +
                                "el boleto no es abierto o ya fue canjeado o<br>la vigencia de canje ya caduco.</html>", Color.RED);
                        jTxtFolioPreimpreso.setText("");
                        jCboEmpresas.setSelectedIndex(0);
                        jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                        if(!this.COAnt.equals(jCboOrigen.getSelectedItem().toString())){
                            sesionVenta.getDBLinkClaveOrigen(jCboOrigen.getSelectedItem().toString());
                            sesionVenta.cargarODServicios(jCboOrigen.getSelectedItem().toString());
                            cbmServicio = new DefaultComboBoxModel(sesionVenta.getSs());
                            jCboServicio.setModel(cbmServicio);
                            this.COAnt=jCboOrigen.getSelectedItem().toString();
                        }
                        if(jchbx_bolRef.isSelected())
                            jTxtFolioPreimpreso.requestFocusInWindow();
                        else    
                            jCboOrigen.requestFocusInWindow();
                        return;
                    }
                    
                    if(!sonBoletosIgualCorrida()){
                        DialogoAceptar.mostrarDialogo("Canje de boleto abierto.","<html>Todos los boletos deben ser del mismo<br>origen, destino y servicio.</html>", Color.RED);
                        jTxtFolioPreimpreso.setText("");
                        jCboServicio.setSelectedIndex(0);
                        jCboEmpresas.setSelectedIndex(0);
                        jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                        if(jchbx_bolRef.isSelected())
                            jTxtFolioPreimpreso.requestFocusInWindow();
                        else    
                            jCboOrigen.requestFocusInWindow();
                        return;
                    }
                    
                    sesionVenta.setReferenciaCanjeBA(jTxtFolioPreimpreso.getText());
                    sesionVenta.setTipoTransaccionAuxiliar(sesionVenta.getTipoTransaccion());
                    sesionVenta.setDBLinkAuxiliar(sesionVenta.getDBLink());
                    
                    String tipoPasajeACanjear="";
                    for(int i=0; i<sesionVenta.getVariosTmsBoletosVentaTbl().size(); i++){
                        tipoPasajeACanjear = sesionVenta.getVariosTmsBoletosVentaTbl().get(i).getTipoPasajero();
                        if(tipoPasajeACanjear.equals("E") || tipoPasajeACanjear.equals("P")){
                            if(!sesionVenta.sonVacaciones()){
                                DialogoAceptar.mostrarDialogo("Canje de boleto abierto.","<html>Tipo de pasajero "+tipoPasajeACanjear+" solo esta habilitado<br>en periodo vacacional.</html>", Color.RED);
                                chOk=false;
                                this.dispose();
                                return;
                            }
                        }
                    }
                    
                    importeBolOriginalAdulto = sesionVenta.getTmsBoletosVentaTbl().getImporteBoleto();
                    tipoPasajero = sesionVenta.getTmsBoletosVentaTbl().getTipoPasajero();
                    EmpresaCBA = sesionVenta.getTmsBoletosVentaTbl().getEmpresa();
                    ServicioCBA = sesionVenta.getTmsBoletosVentaTbl().getServicio();
                    OrigenCBA = sesionVenta.getTmsBoletosVentaTbl().getOrigen();
                    DestinoCBA = sesionVenta.getTmsBoletosVentaTbl().getDestino();
                    CiudadCorridaCBA = (sesionVenta.ConexionRealBAX(OrigenCBA, DestinoCBA, ServicioCBA)!=null ? OrigenCBA : jCboOrigen.getSelectedItem().toString());
                    //CiudadCorridaCBA = (existeOrigenComoCiudadConexion(jCboOrigen.getSelectedItem().toString()) ? OrigenCBA : jCboOrigen.getSelectedItem().toString());
                    
                    if(!existenCorridasDeEmpresaParaCanjear()){
                        chOk=false;
                        this.dispose();
                        return;
                    }
                    
                    chOk=true;

                    xTabla.setDataVector(boletos, encabezado);
                    AnchoColumnas();
                    jTblBoletoOriginal.setRowSelectionInterval(0,0);
                    jTblBoletoOriginal.requestFocusInWindow();     
          }
     
    }//GEN-LAST:event_jchbx_bolRefKeyPressed

    private void jTxtFolioPreimpresoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtFolioPreimpresoFocusLost
// TODO add your handling code here:
        jTxtFolioPreimpreso.setBackground(Color.WHITE);
    }//GEN-LAST:event_jTxtFolioPreimpresoFocusLost

    private void jTxtFolioPreimpresoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtFolioPreimpresoFocusGained
// TODO add your handling code here:
        jTxtFolioPreimpreso.setBackground(xorColorFondo);
    }//GEN-LAST:event_jTxtFolioPreimpresoFocusGained

    private void jTblBoletoOriginalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblBoletoOriginalKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE:
                xTabla.setDataVector(null, encabezado);
                AnchoColumnas();
                if(jchbx_bolRef.isSelected())
                {
                 jTxtFolioPreimpreso.selectAll();
                 jTxtFolioPreimpreso.requestFocusInWindow();
                }
                else
                {
                    jTxtFolioPreimpreso.setText("");
                    jCboServicio.setSelectedIndex(0);
                    jCboEmpresas.setSelectedIndex(0);
                    jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                    jCboOrigen.requestFocusInWindow();
                }
                break;
            case KeyEvent.VK_F2:
                   if(jchbx_bolRef.isSelected())
                    {
                        if(jTblBoletoOriginal.getValueAt(jTblBoletoOriginal.getSelectedRow(),9).toString().equals("N"))
                        {
                            jTblBoletoOriginal.setValueAt("S",jTblBoletoOriginal.getSelectedRow(),9);
                            jTblBoletoOriginal.setColumnSelectionInterval(10,10);
                            jTblBoletoOriginal.editCellAt(jTblBoletoOriginal.getSelectedRow(),10);
                            JViewport jv = jScpBoletoOriginal.getViewport();
                            jv.setViewPosition(new Point(1100,jTblBoletoOriginal.getRowHeight() * jTblBoletoOriginal.getSelectedRow()));
                            jScpBoletoOriginal.setViewport(jv);
                            jScpBoletoOriginal.setViewportView(jTblBoletoOriginal);
                            jv.repaint();
                            jTblBoletoOriginal.repaint();

                        }
                        else
                        {
                            jTblBoletoOriginal.setValueAt("",jTblBoletoOriginal.getSelectedRow(),10);
                            jTblBoletoOriginal.setValueAt("N",jTblBoletoOriginal.getSelectedRow(),9);
                        }
                    }
                break;
            case KeyEvent.VK_F7:
                if(jchbx_bolRef.isSelected())
                {
                    Vector nb = new Vector();
                    int ncanj = 0;
                    for(int i=0; i<jTblBoletoOriginal.getRowCount();i++)
                    {
                        if(jTblBoletoOriginal.getValueAt(i,9).toString().equals("S") )
                            ncanj++;

                        if(jTblBoletoOriginal.getValueAt(i,9).toString().equals("S") && jTblBoletoOriginal.getValueAt(i,10).toString().length()<4)
                        {
                            DialogoAceptar.mostrarDialogo("¡Faltan datos!","<html>Debes introducir el documento de identificación <br> " +
                                    "con el que canjearon el boleto ", Color.RED); 
                            return;
                        }
                    }
                    if(ncanj==0)
                    {
                        DialogoAceptar.mostrarDialogo("¡Imposible realizar canje!","<html>¡Debes seleccionar almenos un boleto para canjear!</html>", Color.RED);
                        return;
                    }
                    for(int i=0; i<jTblBoletoOriginal.getRowCount();i++)
                        sesionVenta.getVariosTmsBoletosVentaTbl().get(i).setDocumento(jTblBoletoOriginal.getValueAt(i,10).toString());
                    for(int i=0; i<jTblBoletoOriginal.getRowCount();i++)
                        if(jTblBoletoOriginal.getValueAt(i,9).toString().equals("N"))
                            nb.add(i);
                    System.out.println("Eliminar: "+nb);
                    for(int i=0; i<nb.size(); i++)
                        sesionVenta.getVariosTmsBoletosVentaTbl().remove(Integer.valueOf(nb.get(i).toString())-i);
             }
                this.dispose();
                break;
        }
    }//GEN-LAST:event_jTblBoletoOriginalKeyPressed

    private void jTblBoletoOriginalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTblBoletoOriginalFocusLost
// TODO add your handling code here:
        jLabel4.setText("<html><font color="+ColoresInterfaz.cHTML3+">ARRIBA/ABAJO </font> Ingresar Criterios | <font color="+ColoresInterfaz.cHTML3+">ENTER</font> Buscar Boleto | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Salir</html>");
    }//GEN-LAST:event_jTblBoletoOriginalFocusLost

    private void jTblBoletoOriginalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTblBoletoOriginalFocusGained
// TODO add your handling code here:
        if(jchbx_bolRef.isSelected())
            jLabel4.setText("<html><font color="+ColoresInterfaz.cHTML3+">F2</font> Seleccionar boleto para canjear | <font color="+ColoresInterfaz.cHTML3+">F7</font> Realizar Canje | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Nueva Busqueda</html>");
        else
            jLabel4.setText("<html><font color="+ColoresInterfaz.cHTML3+">F7</font> Realizar Canje | <font color="+ColoresInterfaz.cHTML3+">ESC</font> Nueva Busqueda</html>");
    }//GEN-LAST:event_jTblBoletoOriginalFocusGained

    private void jCboEmpresasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCboEmpresasKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE:
                chOk=false;
                this.dispose();
                break;
            case KeyEvent.VK_ENTER:
                    if(!validaCampos()) return;
                    if(!valMultiTx(jTxtFolioPreimpreso.getText())) return;
                    ConstruyeMultiBa();
                    if(jCboOrigen.getSelectedItem().toString().equals(sesionVenta.getUserCon().getTerminalNombre())) sesionVenta.setTipoTransaccion("L");
                    else sesionVenta.setTipoTransaccion("R");
                    if(jchbx_bolConv.isSelected())
                         boletos = sesionVenta.validaBoletoACConvenio(jCboOrigen.getSelectedItem().toString(), jCboDestino.getSelectedItem().toString(),  conjuntoFolios);
                    else
                        boletos = sesionVenta.buscaBoletoAbiertoMult(jCboOrigen.getSelectedItem().toString(), conjuntoFolios, 
                            sesionVenta.getVectorServiciosReal(jCboServicio.getSelectedItem().toString()), jCboEmpresas.getSelectedItem().toString().substring(2),
                            jClsSintaxis.getVectorFoliosBoletos().size());
                    if(boletos==null){
                        DialogoAceptar.mostrarDialogo("¡Imposible realizar canje!","<html>Puede ser que los criterios de busqueda son incorrectos o<br>" +
                                "el boleto no es abierto o ya fue canjeado o<br>la vigencia de canje ya caduco.</html>", Color.RED);
                            jTxtFolioPreimpreso.setText("");
                            jCboEmpresas.setSelectedIndex(0);
                            jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                            if(!this.COAnt.equals(jCboOrigen.getSelectedItem().toString())){
                                sesionVenta.getDBLinkClaveOrigen(jCboOrigen.getSelectedItem().toString());
                                sesionVenta.cargarODServicios(jCboOrigen.getSelectedItem().toString());
                                cbmServicio = new DefaultComboBoxModel(sesionVenta.getSs());
                                jCboServicio.setModel(cbmServicio);
                                this.COAnt=jCboOrigen.getSelectedItem().toString();
                            }
                            if(jchbx_bolRef.isSelected())
                                jTxtFolioPreimpreso.requestFocusInWindow();
                            else    
                                jCboOrigen.requestFocusInWindow();
                            return;
                        }
                    
                    if(!sonBoletosIgualCorrida()){
                        DialogoAceptar.mostrarDialogo("Canje de boleto abierto.","<html>Todos los boletos deben ser del mismo<br>origen, destino y servicio.</html>", Color.RED);
                        jTxtFolioPreimpreso.setText("");
                        jCboServicio.setSelectedIndex(0);
                        jCboEmpresas.setSelectedIndex(0);
                        jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                        if(jchbx_bolRef.isSelected())
                            jTxtFolioPreimpreso.requestFocusInWindow();
                        else    
                            jCboOrigen.requestFocusInWindow();
                        return;
                    }
                    
                    sesionVenta.setTipoTransaccionAuxiliar(sesionVenta.getTipoTransaccion());
                    sesionVenta.setDBLinkAuxiliar(sesionVenta.getDBLink());
                    
                    String tipoPasajeACanjear="";
                    for(int i=0; i<sesionVenta.getVariosTmsBoletosVentaTbl().size(); i++){
                        tipoPasajeACanjear = sesionVenta.getVariosTmsBoletosVentaTbl().get(i).getTipoPasajero();
                        if(tipoPasajeACanjear.equals("E") || tipoPasajeACanjear.equals("P")){
                            if(!sesionVenta.sonVacaciones()){
                                DialogoAceptar.mostrarDialogo("Canje de boleto abierto.","<html>Tipo de pasajero "+tipoPasajeACanjear+" solo esta habilitado<br>en periodo vacacional.</html>", Color.RED);
                                chOk=false;
                                this.dispose();
                                return;
                            }
                        }
                    }
                    
                    importeBolOriginalAdulto = sesionVenta.getTmsBoletosVentaTbl().getImporteBoleto();
                    tipoPasajero = sesionVenta.getTmsBoletosVentaTbl().getTipoPasajero();
                    EmpresaCBA = sesionVenta.getTmsBoletosVentaTbl().getEmpresa();
                    ServicioCBA = sesionVenta.getTmsBoletosVentaTbl().getServicio();
                    OrigenCBA = sesionVenta.getTmsBoletosVentaTbl().getOrigen();
                    DestinoCBA = sesionVenta.getTmsBoletosVentaTbl().getDestino();
                    CiudadCorridaCBA = (sesionVenta.ConexionRealBAX(OrigenCBA, DestinoCBA, ServicioCBA)!=null ? OrigenCBA : jCboOrigen.getSelectedItem().toString());
                    
                    if(!existenCorridasDeEmpresaParaCanjear()){
                        chOk=false;
                        this.dispose();
                        return;
                    }
                    
                    chOk=true;

                    xTabla.setDataVector(boletos, encabezado);
                    AnchoColumnas();
                    jTblBoletoOriginal.setRowSelectionInterval(0,0);
                    jTblBoletoOriginal.requestFocusInWindow();
                return;
            case KeyEvent.VK_LEFT:
                    jCboServicio.requestFocusInWindow();
                break;
            case KeyEvent.VK_RIGHT:
                    jCboOrigen.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jCboEmpresasKeyPressed

    private void jCboServicioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCboServicioKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE:
                chOk=false;
                this.dispose();
                break;
            case KeyEvent.VK_ENTER:
                    if(!validaCampos()) return;
                    if(!valMultiTx(jTxtFolioPreimpreso.getText())) return;
                    ConstruyeMultiBa();
                    if(jCboOrigen.getSelectedItem().toString().equals(sesionVenta.getUserCon().getTerminalNombre())) sesionVenta.setTipoTransaccion("L");
                    else sesionVenta.setTipoTransaccion("R");
                    if(jchbx_bolConv.isSelected())
                         boletos = sesionVenta.validaBoletoACConvenio(jCboOrigen.getSelectedItem().toString(), jCboDestino.getSelectedItem().toString(),  conjuntoFolios);
                    else
                        boletos = sesionVenta.buscaBoletoAbiertoMult(jCboOrigen.getSelectedItem().toString(), conjuntoFolios, 
                            sesionVenta.getVectorServiciosReal(jCboServicio.getSelectedItem().toString()), jCboEmpresas.getSelectedItem().toString().substring(2),
                            jClsSintaxis.getVectorFoliosBoletos().size());
                    if(boletos==null){
                        DialogoAceptar.mostrarDialogo("¡Imposible realizar canje!","<html>Puede ser que los criterios de busqueda son incorrectos o<br>" +
                                "el boleto no es abierto o ya fue canjeado o<br>la vigencia de canje ya caduco.</html>", Color.RED);
                        jTxtFolioPreimpreso.setText("");
                        jCboEmpresas.setSelectedIndex(0);
                        jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                        if(!this.COAnt.equals(jCboOrigen.getSelectedItem().toString())){
                            sesionVenta.getDBLinkClaveOrigen(jCboOrigen.getSelectedItem().toString());
                            sesionVenta.cargarODServicios(jCboOrigen.getSelectedItem().toString());
                            cbmServicio = new DefaultComboBoxModel(sesionVenta.getSs());
                            jCboServicio.setModel(cbmServicio);
                            this.COAnt=jCboOrigen.getSelectedItem().toString();
                        }
                        if(jchbx_bolRef.isSelected())
                            jTxtFolioPreimpreso.requestFocusInWindow();
                        else    
                            jCboOrigen.requestFocusInWindow();
                        return;
                    }
                    
                    if(!sonBoletosIgualCorrida()){
                        DialogoAceptar.mostrarDialogo("Canje de boleto abierto.","<html>Todos los boletos deben ser del mismo<br>origen, destino y servicio.</html>", Color.RED);
                        jTxtFolioPreimpreso.setText("");
                        jCboServicio.setSelectedIndex(0);
                        jCboEmpresas.setSelectedIndex(0);
                        jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                        if(jchbx_bolRef.isSelected())
                            jTxtFolioPreimpreso.requestFocusInWindow();
                        else    
                            jCboOrigen.requestFocusInWindow();
                        return;
                    }
                    
                    sesionVenta.setTipoTransaccionAuxiliar(sesionVenta.getTipoTransaccion());
                    sesionVenta.setDBLinkAuxiliar(sesionVenta.getDBLink());
                    
                    String tipoPasajeACanjear="";
                    for(int i=0; i<sesionVenta.getVariosTmsBoletosVentaTbl().size(); i++){
                        tipoPasajeACanjear = sesionVenta.getVariosTmsBoletosVentaTbl().get(i).getTipoPasajero();
                        if(tipoPasajeACanjear.equals("E") || tipoPasajeACanjear.equals("P")){
                            if(!sesionVenta.sonVacaciones()){
                                DialogoAceptar.mostrarDialogo("Canje de boleto abierto.","<html>Tipo de pasajero "+tipoPasajeACanjear+" solo esta habilitado<br>en periodo vacacional.</html>", Color.RED);
                                chOk=false;
                                this.dispose();
                                return;
                            }
                        }
                    }
                    
                    importeBolOriginalAdulto = sesionVenta.getTmsBoletosVentaTbl().getImporteBoleto();
                    tipoPasajero = sesionVenta.getTmsBoletosVentaTbl().getTipoPasajero();
                    EmpresaCBA = sesionVenta.getTmsBoletosVentaTbl().getEmpresa();
                    ServicioCBA = sesionVenta.getTmsBoletosVentaTbl().getServicio();
                    OrigenCBA = sesionVenta.getTmsBoletosVentaTbl().getOrigen();
                    DestinoCBA = sesionVenta.getTmsBoletosVentaTbl().getDestino();
                    CiudadCorridaCBA = (sesionVenta.ConexionRealBAX(OrigenCBA, DestinoCBA, ServicioCBA)!=null ? OrigenCBA : jCboOrigen.getSelectedItem().toString());
                    //CiudadCorridaCBA = (existeOrigenComoCiudadConexion(jCboOrigen.getSelectedItem().toString()) ? OrigenCBA : jCboOrigen.getSelectedItem().toString());
                    
                    if(!existenCorridasDeEmpresaParaCanjear()){
                        chOk=false;
                        this.dispose();
                        return;
                    }
                    
                    chOk=true;

                    xTabla.setDataVector(boletos, encabezado);
                    AnchoColumnas();
                    jTblBoletoOriginal.setRowSelectionInterval(0,0);
                    jTblBoletoOriginal.requestFocusInWindow();
                return;
            case KeyEvent.VK_LEFT:
                    jTxtFolioPreimpreso.selectAll();
                    jTxtFolioPreimpreso.requestFocusInWindow();
                break;
            case KeyEvent.VK_RIGHT:
                    jCboEmpresas.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jCboServicioKeyPressed

    private void jTxtFolioPreimpresoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtFolioPreimpresoKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE:
                chOk=false;
                this.dispose();
                break;
            case KeyEvent.VK_ENTER:
                    if(!validaCampos()) return;
                    if(!valMultiTx(jTxtFolioPreimpreso.getText())) return;
                    if(!jchbx_bolRef.isSelected())
                    {
                        ConstruyeMultiBa();
                        if(jCboOrigen.getSelectedItem().toString().equals(sesionVenta.getUserCon().getTerminalNombre())) sesionVenta.setTipoTransaccion("L");
                        else sesionVenta.setTipoTransaccion("R");
                        if(jchbx_bolConv.isSelected())
                             boletos = sesionVenta.validaBoletoACConvenio(jCboOrigen.getSelectedItem().toString(), jCboDestino.getSelectedItem().toString(),  conjuntoFolios);
                        else
                            boletos = sesionVenta.buscaBoletoAbiertoMult(jCboOrigen.getSelectedItem().toString(), 
                                conjuntoFolios, 
                                sesionVenta.getVectorServiciosReal(jCboServicio.getSelectedItem().toString()), jCboEmpresas.getSelectedItem().toString().substring(2),
                                jClsSintaxis.getVectorFoliosBoletos().size());
                    }
                    else
                    {
                        conjuntoFolios = jTxtFolioPreimpreso.getText().trim();
                        if(vectorTerminal.get(1).toString().equals(sesionVenta.getUserCon().getTerminalNombre())) sesionVenta.setTipoTransaccion("L");
                        else sesionVenta.setTipoTransaccion("R");
                        sesionVenta.setDBLink(vectorTerminal.get(3).toString());
                        boletos = sesionVenta.buscaBoletoAbiertoMultRef(vectorTerminal.get(1).toString(), conjuntoFolios);
                    }
                    if(boletos==null){
                        DialogoAceptar.mostrarDialogo("¡Imposible realizar canje!","<html>Puede ser que los criterios de busqueda son incorrectos o<br>" +
                                "el boleto no es abierto o ya fue canjeado o<br>la vigencia de canje ya caduco.</html>", Color.RED);
                       if(jchbx_bolRef.isSelected())
                       {
                            jTxtFolioPreimpreso.selectAll();
                            jTxtFolioPreimpreso.requestFocusInWindow();
                       }
                       else
                        {
                            jTxtFolioPreimpreso.setText("");
                            jCboEmpresas.setSelectedIndex(0);
                            jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                            if(!this.COAnt.equals(jCboOrigen.getSelectedItem().toString())){
                                sesionVenta.getDBLinkClaveOrigen(jCboOrigen.getSelectedItem().toString());
                                sesionVenta.cargarODServicios(jCboOrigen.getSelectedItem().toString());
                                cbmServicio = new DefaultComboBoxModel(sesionVenta.getSs());
                                jCboServicio.setModel(cbmServicio);
                                this.COAnt=jCboOrigen.getSelectedItem().toString();
                            }
                            jCboOrigen.requestFocusInWindow();
                       }
                        return;
                    }
                    
                    if(!sonBoletosIgualCorrida()){
                        DialogoAceptar.mostrarDialogo("Canje de boleto abierto.","<html>Todos los boletos deben ser del mismo<br>origen, destino y servicio.</html>", Color.RED);
                        jTxtFolioPreimpreso.setText("");
                        jCboServicio.setSelectedIndex(0);
                        jCboEmpresas.setSelectedIndex(0);
                        jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                        if(jchbx_bolRef.isSelected())
                            jTxtFolioPreimpreso.requestFocusInWindow();
                        else    
                            jCboOrigen.requestFocusInWindow();
                        return;
                    }
                    
                    sesionVenta.setReferenciaCanjeBA(jTxtFolioPreimpreso.getText());
                    sesionVenta.setTipoTransaccionAuxiliar(sesionVenta.getTipoTransaccion());
                    sesionVenta.setDBLinkAuxiliar(sesionVenta.getDBLink());
                    
                    String tipoPasajeACanjear="";
                    for(int i=0; i<sesionVenta.getVariosTmsBoletosVentaTbl().size(); i++){
                        tipoPasajeACanjear = sesionVenta.getVariosTmsBoletosVentaTbl().get(i).getTipoPasajero();
                        if(tipoPasajeACanjear.equals("E") || tipoPasajeACanjear.equals("P")){
                            if(!sesionVenta.sonVacaciones()){
                                DialogoAceptar.mostrarDialogo("Canje de boleto abierto.","<html>Tipo de pasajero "+tipoPasajeACanjear+" solo esta habilitado<br>en periodo vacacional.</html>", Color.RED);
                                chOk=false;
                                this.dispose();
                                return;
                            }
                        }
                    }
                    
                    importeBolOriginalAdulto = sesionVenta.getTmsBoletosVentaTbl().getImporteBoleto();
                    tipoPasajero = sesionVenta.getTmsBoletosVentaTbl().getTipoPasajero();
                    EmpresaCBA = sesionVenta.getTmsBoletosVentaTbl().getEmpresa();
                    ServicioCBA = sesionVenta.getTmsBoletosVentaTbl().getServicio();
                    OrigenCBA = sesionVenta.getTmsBoletosVentaTbl().getOrigen();
                    DestinoCBA = sesionVenta.getTmsBoletosVentaTbl().getDestino();
                    CiudadCorridaCBA = (sesionVenta.ConexionRealBAX(OrigenCBA, DestinoCBA, ServicioCBA)!=null ? OrigenCBA : jCboOrigen.getSelectedItem().toString());
                    //CiudadCorridaCBA = (existeOrigenComoCiudadConexion(jCboOrigen.getSelectedItem().toString()) ? OrigenCBA : jCboOrigen.getSelectedItem().toString());
                    
                    if(!existenCorridasDeEmpresaParaCanjear()){
                        chOk=false;
                        this.dispose();
                        return;
                    }
                    
                    chOk=true;
                    if(!jchbx_bolRef.isSelected())
                    {
                        xTabla.setDataVector(boletos, encabezado);
                        AnchoColumnas();
                    }
                    else
                    {
                        xTabla.setDataVector(boletos, encabezado2);
                        AnchoColumnas2();
                    }   
                    jTblBoletoOriginal.setRowSelectionInterval(0,0);
                    jTblBoletoOriginal.requestFocusInWindow();
                return;
            case KeyEvent.VK_LEFT: case KeyEvent.VK_UP:
                if(jCboDestino.isVisible())
                    jCboDestino.requestFocus();
                else
                  jchbx_bolConv.requestFocusInWindow();
                break;
            case KeyEvent.VK_RIGHT: case KeyEvent.VK_DOWN:
                 if(!jCboServicio.isEnabled()) return;
                 if(jCboServicio.isVisible())
                    jCboServicio.requestFocusInWindow();
                 else
                     jCboOrigen.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jTxtFolioPreimpresoKeyPressed

    private void jCboOrigenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCboOrigenKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE:
                chOk=false;
                this.dispose();
                break;
            case KeyEvent.VK_ENTER:
                    if(!this.COAnt.equals(jCboOrigen.getSelectedItem().toString())){
                        sesionVenta.getDBLinkClaveOrigen(jCboOrigen.getSelectedItem().toString());
                        sesionVenta.cargarODServicios(jCboOrigen.getSelectedItem().toString());
                        cbmServicio = new DefaultComboBoxModel(sesionVenta.getSs());
                        jCboServicio.setModel(cbmServicio);
                        this.COAnt=jCboOrigen.getSelectedItem().toString();
                    }
                    if(!validaCampos()) return;
                    if(!valMultiTx(jTxtFolioPreimpreso.getText())) return;
                    ConstruyeMultiBa();
                    if(jCboOrigen.getSelectedItem().toString().equals(sesionVenta.getUserCon().getTerminalNombre())) sesionVenta.setTipoTransaccion("L");
                    else sesionVenta.setTipoTransaccion("R");
                    if(jchbx_bolConv.isSelected())
                         boletos = sesionVenta.validaBoletoACConvenio(jCboOrigen.getSelectedItem().toString(), jCboDestino.getSelectedItem().toString(),  conjuntoFolios);
                    else
                        boletos = sesionVenta.buscaBoletoAbiertoMult(jCboOrigen.getSelectedItem().toString(), conjuntoFolios, 
                            sesionVenta.getVectorServiciosReal(jCboServicio.getSelectedItem().toString()), jCboEmpresas.getSelectedItem().toString().substring(2),
                            jClsSintaxis.getVectorFoliosBoletos().size());
                    if(boletos==null){
                        DialogoAceptar.mostrarDialogo("¡Imposible realizar canje!","<html>Puede ser que los criterios de busqueda son incorrectos o<br>" +
                                "el boleto no es abierto o ya fue canjeado o<br>la vigencia de canje ya caduco.</html>", Color.RED);
                        jTxtFolioPreimpreso.setText("");
                        jCboEmpresas.setSelectedIndex(0);
                        jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                        if(!this.COAnt.equals(jCboOrigen.getSelectedItem().toString())){
                            sesionVenta.getDBLinkClaveOrigen(jCboOrigen.getSelectedItem().toString());
                            sesionVenta.cargarODServicios(jCboOrigen.getSelectedItem().toString());
                            cbmServicio = new DefaultComboBoxModel(sesionVenta.getSs());
                            jCboServicio.setModel(cbmServicio);
                            this.COAnt=jCboOrigen.getSelectedItem().toString();
                        }
                        if(jchbx_bolRef.isSelected())
                            jTxtFolioPreimpreso.requestFocusInWindow();
                        else    
                            jCboOrigen.requestFocusInWindow();
                        return;
                    }
                    
                    if(!sonBoletosIgualCorrida()){
                        DialogoAceptar.mostrarDialogo("Canje de boleto abierto.","<html>Todos los boletos deben ser del mismo<br>origen, destino y servicio.</html>", Color.RED);
                        jTxtFolioPreimpreso.setText("");
                        jCboServicio.setSelectedIndex(0);
                        jCboEmpresas.setSelectedIndex(0);
                        jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
                        if(jchbx_bolRef.isSelected())
                            jTxtFolioPreimpreso.requestFocusInWindow();
                        else    
                            jCboOrigen.requestFocusInWindow();
                        return;
                    }
                    
                    sesionVenta.setTipoTransaccionAuxiliar(sesionVenta.getTipoTransaccion());
                    sesionVenta.setDBLinkAuxiliar(sesionVenta.getDBLink());
                    
                    String tipoPasajeACanjear="";
                    for(int i=0; i<sesionVenta.getVariosTmsBoletosVentaTbl().size(); i++){
                        tipoPasajeACanjear = sesionVenta.getVariosTmsBoletosVentaTbl().get(i).getTipoPasajero();
                        if(tipoPasajeACanjear.equals("E") || tipoPasajeACanjear.equals("P")){
                            if(!sesionVenta.sonVacaciones()){
                                DialogoAceptar.mostrarDialogo("Canje de boleto abierto.","<html>Tipo de pasajero "+tipoPasajeACanjear+" solo esta habilitado<br>en periodo vacacional.</html>", Color.RED);
                                chOk=false;
                                this.dispose();
                                return;
                            }
                        }
                    }
                    
                    importeBolOriginalAdulto = sesionVenta.getTmsBoletosVentaTbl().getImporteBoleto();
                    tipoPasajero = sesionVenta.getTmsBoletosVentaTbl().getTipoPasajero();
                    EmpresaCBA = sesionVenta.getTmsBoletosVentaTbl().getEmpresa();
                    ServicioCBA = sesionVenta.getTmsBoletosVentaTbl().getServicio();
                    OrigenCBA = sesionVenta.getTmsBoletosVentaTbl().getOrigen();
                    DestinoCBA = sesionVenta.getTmsBoletosVentaTbl().getDestino();
                    CiudadCorridaCBA = (sesionVenta.ConexionRealBAX(OrigenCBA, DestinoCBA, ServicioCBA)!=null ? OrigenCBA : jCboOrigen.getSelectedItem().toString());
                    //CiudadCorridaCBA = (existeOrigenComoCiudadConexion(jCboOrigen.getSelectedItem().toString()) ? OrigenCBA : jCboOrigen.getSelectedItem().toString());
                    
                    if(!existenCorridasDeEmpresaParaCanjear()){
                        chOk=false;
                        this.dispose();
                        return;
                    }
                    
                    chOk=true;

                    xTabla.setDataVector(boletos, encabezado);
                    AnchoColumnas();
                    jTblBoletoOriginal.setRowSelectionInterval(0,0);
                    jTblBoletoOriginal.requestFocusInWindow();
                return;
            case KeyEvent.VK_LEFT:
                    if(!this.COAnt.equals(jCboOrigen.getSelectedItem().toString())){
                        sesionVenta.getDBLinkClaveOrigen(jCboOrigen.getSelectedItem().toString());
                        sesionVenta.cargarODServicios(jCboOrigen.getSelectedItem().toString());
                        cbmServicio = new DefaultComboBoxModel(sesionVenta.getSs());
                        jCboServicio.setModel(cbmServicio);
                        this.COAnt=jCboOrigen.getSelectedItem().toString();
                    }
                    if(jCboEmpresas.isVisible())
                        jCboEmpresas.requestFocusInWindow();
                    else
                    {
                        jTxtFolioPreimpreso.selectAll();;
                        jTxtFolioPreimpreso.requestFocusInWindow();
                    }
                break;
            case KeyEvent.VK_RIGHT:
                    if(!this.COAnt.equals(jCboOrigen.getSelectedItem().toString())){
                        sesionVenta.getDBLinkClaveOrigen(jCboOrigen.getSelectedItem().toString());
                        sesionVenta.cargarODServicios(jCboOrigen.getSelectedItem().toString());
                        cbmServicio = new DefaultComboBoxModel(sesionVenta.getSs());
                        jCboServicio.setModel(cbmServicio);
                        this.COAnt=jCboOrigen.getSelectedItem().toString();
                    }
//                    jTxtFolioPreimpreso.selectAll();
//                    jTxtFolioPreimpreso.requestFocusInWindow();
                    jchbx_bolRef.requestFocus();
                break;
        }
    }//GEN-LAST:event_jCboOrigenKeyPressed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
// TODO add your handling code here:
        jCboEmpresas.setSelectedIndex(0);
        jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre());
        jCboOrigen.requestFocusInWindow();
    }//GEN-LAST:event_formComponentShown
    
    private boolean validaCampos(){
        if(jCboOrigen.getSelectedItem()==null){
            DialogoAceptar.mostrarDialogo("¡Importante!","Seleccione un origen.", Color.RED);
            jCboOrigen.setSelectedItem(sesionVenta.getUserCon().getTerminalNombre()); jCboOrigen.requestFocusInWindow(); return false;
        }
        if(jTxtFolioPreimpreso.getText().equals("")){
            if(jchbx_bolRef.isSelected())
                DialogoAceptar.mostrarDialogo("¡Importante!","Ingrese la referencia del boleto.", Color.RED);
            else
                DialogoAceptar.mostrarDialogo("¡Importante!","Ingrese Folio Preimpreso del Boleto.", Color.RED);
            jTxtFolioPreimpreso.requestFocusInWindow(); return false;
        }
        if(jCboServicio.getSelectedItem()==null){
            DialogoAceptar.mostrarDialogo("¡Importante!","Ingrese Servicio.", Color.RED);
            jCboServicio.requestFocusInWindow(); return false;
        }
        if(jCboEmpresas.getSelectedItem()==null){
            DialogoAceptar.mostrarDialogo("¡Importante!","Seleccione una empresa.", Color.RED);
            jCboEmpresas.setSelectedIndex(0); return false;
        }
        return true;
    }
    
    private boolean existenCorridasDeEmpresaParaCanjear(){
        sesionVenta.getDBLinkClaveOrigen(CiudadCorridaCBA);
        if(CiudadCorridaCBA.equals(sesionVenta.getUserCon().getTerminalNombre())) sesionVenta.setTipoTransaccion("L");
        else sesionVenta.setTipoTransaccion("R");
        System.out.println("existen corridas de empresa o "+OrigenCBA+" d "+DestinoCBA+" s "+ServicioCBA+" ciudad "+CiudadCorridaCBA+" dblink "+sesionVenta.getDBLink()+" tipot "+sesionVenta.getTipoTransaccion());
        boolean zz = sesionVenta.busqCorridaVentaBA(CiudadCorridaCBA, OrigenCBA, DestinoCBA, new Timestamp(horaSistema), 
                                                 new Timestamp(horaSistemaHasta), ServicioCBA, "%");
                                                //new Timestamp(horaSistemaHasta), ServicioCBA, EmpresaCBA);
        if(!zz){
            DialogoAceptar.mostrarDialogo("¡Imposible realizar canje!","<html>No se dispone de corridas para la empresa<br>"+EmpresaCBA+" del servicio "+ServicioCBA+".</html>",Color.RED);
            return false;
        }
        return true;
    }
    
    private void ordenaListaEmpresas(){
        Object[] objs= new Object[objEmpresas.length];
        int i, j, vA, vB; String valor;
        for(i=0; i<objEmpresas.length; i++){
            for(j=0; j<objEmpresas.length-1; j++){
                valor=objEmpresas[j+1].toString();
                vA=Integer.valueOf(objEmpresas[j].toString().substring(0,1));
                vB=Integer.valueOf(objEmpresas[j+1].toString().substring(0,1));
                if(vA>vB){
                    objEmpresas[j+1] = objEmpresas[j].toString();
                    objEmpresas[j] = valor;
                }
            }
        }
    }
 
    private boolean valMultiTx(String folios) {
        if(!jchbx_bolRef.isSelected())
        {
            int r=jClsSintaxis.Valfolios(folios);
            if(r!=0){
                if(r==-1) DialogoAceptar.mostrarDialogo("Folios incorrectos","<html>Ingrese correctamente los folios.<br>" +
                                                        "Ejemplo, 21448001-21448005 21448009.</html>",Color.RED);
                else if(r==1) DialogoAceptar.mostrarDialogo("Folios incorrectos",
                                "<html>Algun folio tiene mas de 12 digitos.</html>",Color.RED);
                else  DialogoAceptar.mostrarDialogo("Folios incorrectos","<html>Folio inicial no puede ser<br>mayor o igual que folio final</html>",Color.RED);
                jTxtFolioPreimpreso.selectAll();
                jTxtFolioPreimpreso.requestFocusInWindow();
                return false;
            }

            return true;
        }
        else
        {
            int nter = 0;
            try {
                nter = Integer.parseInt(folios.substring(0, 2), 16);
            } catch (NumberFormatException ex) {
                ex.printStackTrace();
            }
            Vector vter = sesionVenta.buscaTerminalRef(nter) ;
            if(vter.size()==0){
                DialogoAceptar.mostrarDialogo("¡Imposible realizar canje!","<html>Puede ser que la referencia sea incorrecta o<br>" +
                        "el boleto(s) ya fue canjeado.</html>", Color.RED);
                jTxtFolioPreimpreso.selectAll();
                jTxtFolioPreimpreso.requestFocusInWindow();
                return false;
            }
            this.vectorTerminal = (Vector) vter.get(0);
            return true;
        }
    }
    
    private void ConstruyeMultiBa(){
        conjuntoFolios="'"+jClsSintaxis.getVectorFoliosBoletos().get(0).toString()+"'";
            for(int i=1; i<jClsSintaxis.getVectorFoliosBoletos().size(); i++)
                conjuntoFolios=conjuntoFolios+",'"+jClsSintaxis.getVectorFoliosBoletos().get(i).toString()+"'";
    }
    
    private void AnchoColumnas() {
        int anchoContenedor = jScpBoletoOriginal.getWidth();
        TableColumn column;
        for (int i = 0; i < jTblBoletoOriginal.getColumnCount(); i++) {
            column = jTblBoletoOriginal.getColumnModel().getColumn(i);
            switch (i) {
                case 0: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.12)); break;
                case 1: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.15)); break;
                case 2: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.04)); break;
                case 3: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.04)); break;
                case 4: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.35)); break;
                case 5: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.14)); break;
                case 6: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.08)); break;
                case 7: column.setPreferredWidth(Math.round(anchoContenedor*(float)0.08)); break;
            }
            column.setResizable(false);
        }
    }
    
     private void AnchoColumnas2() {
        int anchoContenedor = jScpBoletoOriginal.getWidth();
        TableColumn column;
        for (int i = 0; i < jTblBoletoOriginal.getColumnCount(); i++) {
            column = jTblBoletoOriginal.getColumnModel().getColumn(i);
            switch (i) {
                case 0: column.setMinWidth( 120 );column.setMaxWidth( 120 );column.setPreferredWidth(120); break;
                case 1: column.setMinWidth( 110 );column.setMaxWidth( 110 );column.setPreferredWidth(110); break;
                case 2: column.setMinWidth( 20 );column.setMaxWidth(20  );column.setPreferredWidth(20); break;
                case 3: column.setMinWidth( 20 );column.setMaxWidth( 20 );column.setPreferredWidth(20); break;
                case 4: column.setMinWidth( 60 );column.setMaxWidth( 60 );column.setPreferredWidth(60); break;
                case 5: column.setMinWidth( 60 );column.setMaxWidth( 50 );column.setPreferredWidth(50); break;
                case 6: column.setMinWidth( 50 );column.setMaxWidth( 60 );column.setPreferredWidth(60); break;
                case 7: column.setMinWidth( 220 );column.setMaxWidth( 220 );column.setPreferredWidth(220); break;
                case 8: column.setMinWidth( 220 );column.setMaxWidth( 220 );column.setPreferredWidth(220); break;
                case 9: column.setMinWidth( 60 );column.setMaxWidth( 60 );column.setPreferredWidth(60); break;
                case 10: column.setMinWidth( 180 );column.setMaxWidth( 180 );column.setPreferredWidth(180); break;
            }
            column.setResizable(false);
        }
        jTblBoletoOriginal.getColumnModel().getColumn(10).setCellEditor(new DefaultCellEditor(jtxtNombre));
    }    
    
    private boolean sonBoletosIgualCorrida(){
        for(int i=1; i<sesionVenta.getVariosTmsBoletosVentaTbl().size(); i++)
            if(!sesionVenta.getTmsBoletosVentaTbl().getServicio().equals(sesionVenta.getVariosTmsBoletosVentaTbl().get(i).getServicio()) ||
                !sesionVenta.getTmsBoletosVentaTbl().getOrigen().equals(sesionVenta.getVariosTmsBoletosVentaTbl().get(i).getOrigen()) ||
                !sesionVenta.getTmsBoletosVentaTbl().getDestino().equals(sesionVenta.getVariosTmsBoletosVentaTbl().get(i).getDestino()) ||
                !sesionVenta.getTmsBoletosVentaTbl().getCiudadVenta().equals(sesionVenta.getVariosTmsBoletosVentaTbl().get(i).getCiudadVenta()))
                return false;
        return true;
    }
    
    private void interfazColor(){
        jPanel1.setBackground(ColoresInterfaz.cFondoDialogo);
        /*jLabel4.setOpaque(true);
        jLabel4.setBackground(ColoresInterfaz.cFondoPieEncabezado2);*/
        jLabel4.setForeground(ColoresInterfaz.cTextoAyuda1);
        
        setFont(ColoresInterfaz.fuente1);
        jLabel1.setFont(ColoresInterfaz.fuente1);
        jCboOrigen.setFont(ColoresInterfaz.fuente1);
        jCboDestino.setFont(ColoresInterfaz.fuente1);
        jlbl_folRef.setFont(ColoresInterfaz.fuente1);
        jchbx_bolRef.setFont(ColoresInterfaz.fuente1);
        jchbx_bolConv.setFont(ColoresInterfaz.fuente1);
        
        jTxtFolioPreimpreso.setFont(ColoresInterfaz.fuente1);
        jLabel3.setFont(ColoresInterfaz.fuente1);
        jCboServicio.setFont(ColoresInterfaz.fuente1);
        jLabel6.setFont(ColoresInterfaz.fuente1);
        jCboEmpresas.setFont(ColoresInterfaz.fuente1);
        
        jLabel4.setFont(ColoresInterfaz.fuente1);
    }
    
    public boolean isReferenciado()
    {
        return jchbx_bolRef.isSelected();
    }
    
    public boolean isBoletoConvenio(){
        return jchbx_bolConv.isSelected();
    }
    
    public String getFoliosAbiertos()
    {
         return ","+conjuntoFolios;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCboDestino;
    private javax.swing.JComboBox jCboEmpresas;
    private javax.swing.JComboBox jCboOrigen;
    private javax.swing.JComboBox jCboServicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScpBoletoOriginal;
    private javax.swing.JTable jTblBoletoOriginal;
    private javax.swing.JTextField jTxtFolioPreimpreso;
    private javax.swing.JCheckBox jchbx_bolConv;
    private javax.swing.JCheckBox jchbx_bolRef;
    private javax.swing.JLabel jlbl_folRef;
    private javax.swing.JLabel jlblestino;
    // End of variables declaration//GEN-END:variables
    public Object[][] boletos = null;
    public static boolean chOk;
    public double importeBolOriginalAdulto;
    public String tipoPasajero="";
    public String EmpresaCBA="";
    public String ServicioCBA="";
    public String OrigenCBA="";
    public String DestinoCBA="";
    public String CiudadCorridaCBA="";
    private SesionVenta sesionVenta = null;
    private JDlgAceptar DialogoAceptar = new JDlgAceptar();
    private Vector Origenes;
    private DefaultComboBoxModel cbmServicio;
    //private Vector canjeServicios = new Vector();
    private String COAnt;
    private Object[] CiudadesConexion;
    private Object[] objEmp;
    private Object[] objEmpresas;
    private long horaSistema, horaSistemaHasta;
    private JClsColoresInterfaz ColoresInterfaz = new JClsColoresInterfaz();
    private JClsSintaxis jClsSintaxis=null;
    private String conjuntoFolios; // 0             1           2    3      4         5        6          7 
    private Object[] encabezado = {"CORRIDA", "FECHA CORRIDA", "#", "T", "NOMBRE", "ORIGEN", "DESTINO", "COSTO"};
    private Object[] encabezado2 = {"CORRIDA","FECHA CORRIDA", "#", "T", "ORIGEN", "DESTINO","COSTO"  , "NOMBRE PASAJERO","NOMBRE AUTORIZADO","CANJEAR","DOCUMENTO"};
    private DefaultTableModel xTabla = new DefaultTableModel(null,encabezado){
        public boolean isCellEditable(int row, int col){
            if(col == 10)
                return true;
            else
                return false;
        }
    };
    private Color xorColorFondo = new Color(156, 179, 201);
    private Vector vectorTerminal;
    private JTextTextFieldMaxCharAlfa jtxtNombre = new JTextTextFieldMaxCharAlfa(30);
}