/*
 * Jdlg_CorteFinDia.java
 *
 * Created on 21 de agosto de 2007, 06:42 PM
 */

package tms_cortetaquilla.util;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ItemEvent;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import tms_TextFields.JDateTextField;

/**
 *
 * @author  ocruz
 */
public class Jdlg_Corte extends javax.swing.JDialog{
    
    /** Creates new form Jdlg_CorteFinDia */
    public Jdlg_Corte(java.awt.Frame parent, boolean modal, String Titulo) {
        super(parent, modal);
        initComponents();
        this.setTitle(Titulo);
        centrar();
    }
    
    private void centrar(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension DialogSize = this.getSize();
        if (DialogSize.height > screenSize.height) {
            DialogSize.height = screenSize.height;
        }
        if (DialogSize.width > screenSize.width) {
            DialogSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - DialogSize.width ) / 2, ( screenSize.height - DialogSize.height ) / 2 );
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLblMensaje = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLblMensaje.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLblMensaje.setText("\u00bfQue desea hacer?");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel1.setText("<html><font color=ff0000>F7</font> Imprimir Corte<html>");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("<html><font color=ff0000>F8</font> Imprimir Corte con detallado<html>");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel3.setText("<html><font color=ff0000>ESC</font> Cancelar Corte<html>");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel1))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel2))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel3))
                    .add(layout.createSequentialGroup()
                        .add(35, 35, 35)
                        .add(jLblMensaje)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLblMensaje)
                .add(14, 14, 14)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel3)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_F7:
                Detallado="N"; this.dispose();
                break;
            case KeyEvent.VK_F8:
                Detallado="S"; this.dispose();
                break;
            case KeyEvent.VK_ESCAPE:
                Detallado=""; this.dispose();
                break;
        }
    }//GEN-LAST:event_formKeyPressed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
// TODO add your handling code here:
        this.requestFocusInWindow();
    }//GEN-LAST:event_formComponentShown

    public String getDetalle(){
        return Detallado;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLblMensaje;
    // End of variables declaration//GEN-END:variables
    private String Detallado="N";
}
