/*
 * jdl_nombreArchivoExcel.java
 *
 * Created on 29 de febrero de 2008, 07:34 PM
 */

package tmsroles;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JDialog;
import javax.swing.JRootPane;
import javax.swing.JTextField;

/**
 *
 * @author  vgonzalez
 */
public class jdl_nombreArchivoExcel extends javax.swing.JDialog {
    
    /** Creates new form jdl_nombreArchivoExcel */
    public jdl_nombreArchivoExcel(javax.swing.JDialog parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Nombre de Archivo a generar");
        jtxt_nombreArchivo.setFocusTraversalKeysEnabled(false);
        jlbl_barraEstado.setFocusTraversalKeysEnabled(false);
        jlbl_barraEstado.setText("<html>  <font color=FF0000>ENTER: </font> Si                 <font color=FF0000>             ESC: </font> No  </html>");        
        jlbl_barraEstado.setHorizontalAlignment( JTextField.CENTER );
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            Dimension DilaogSize = this.getSize();
            if (DilaogSize.height > screenSize.height) {
                DilaogSize.height = screenSize.height;
            }
            if (DilaogSize.width > screenSize.width) {
                DilaogSize.width = screenSize.width;
            }
            this.setLocation( ( screenSize.width - DilaogSize.width ) / 2, ( screenSize.height - DilaogSize.height ) / 2 );            this.setDefaultLookAndFeelDecorated(true);
            this.getRootPane().setWindowDecorationStyle(JRootPane.QUESTION_DIALOG);
        jtxt_nombreArchivo.requestFocus();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxt_nombreArchivo = new javax.swing.JTextField();
        jlbl_barraEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("El Archivo se guardar\u00e1 en la ruta c:\\");

            jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
            jLabel2.setText("Nombre del Archivo:");

            jtxt_nombreArchivo.addKeyListener(new java.awt.event.KeyAdapter() {
                public void keyPressed(java.awt.event.KeyEvent evt) {
                    jtxt_nombreArchivoKeyPressed(evt);
                }
                public void keyReleased(java.awt.event.KeyEvent evt) {
                    jtxt_nombreArchivoKeyReleased(evt);
                }
            });

            jlbl_barraEstado.setFont(new java.awt.Font("Tahoma", 1, 12));
            jlbl_barraEstado.setText("jLabel3");
            jlbl_barraEstado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

            org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                        .add(layout.createSequentialGroup()
                            .addContainerGap()
                            .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 279, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(layout.createSequentialGroup()
                            .add(19, 19, 19)
                            .add(jLabel2)
                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                            .add(jtxt_nombreArchivo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .addContainerGap(24, Short.MAX_VALUE))
                .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(layout.createSequentialGroup()
                    .addContainerGap()
                    .add(jLabel1)
                    .add(34, 34, 34)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLabel2)
                        .add(jtxt_nombreArchivo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 35, Short.MAX_VALUE)
                    .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 27, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            );
            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jtxt_nombreArchivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_nombreArchivoKeyPressed
      if(evt.getKeyCode() == evt.VK_ESCAPE)
      {
          this.setNombre("salida");
          this.dispose();
      }
      if(evt.getKeyCode() == evt.VK_ENTER)
      {
          if(jtxt_nombreArchivo.getText().equals(""))
          {
              new jdlg_error("¡Debes ecribir un nombre!","","Campo nombre vacio").setVisible(true);
              return;
          }
          else
          {
              this.setNombre(jtxt_nombreArchivo.getText());
              this.dispose();
          }  
      }

    }//GEN-LAST:event_jtxt_nombreArchivoKeyPressed

    private void jtxt_nombreArchivoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxt_nombreArchivoKeyReleased
            
    }//GEN-LAST:event_jtxt_nombreArchivoKeyReleased
    
    /**
     * @param args the command line arguments
     */

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jlbl_barraEstado;
    private javax.swing.JTextField jtxt_nombreArchivo;
    // End of variables declaration//GEN-END:variables
    private String nombre = "";

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
}
