/*
 * JIFAbrirRolMaestro.java
 *
 * Created on 29 de octubre de 2007, 11:41 AM
 */

package tmsroles;

import java.awt.Component;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.StringTokenizer;
import java.util.Vector;
import javax.swing.JComponent;
import javax.swing.JRootPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;
import javax.swing.text.JTextComponent;
import tmsroles.entidad.TmsEmpresasTbl;
import tmsroles.entidad.TmsFlotillasTbl;
import tmsroles.entidad.TmsRolesBaseLineasTbl;
import tmsroles.entidad.TmsRolesBaseTbl;
import tmsroles.entidad.TmsRolesMaestroTbl;
import tmsroles.entidad.TmsRutasTbl;
import tmsroles.entidad.TmsServiciosTbl;

/**
 *
 * @author  vgonzalez
 */
public class JIFAbrirRolMaestro extends javax.swing.JDialog { // javax.swing.JInternalFrame {// 
    
    /**
     * Creates new form JIFAbrirRolMaestro
     */
    public JIFAbrirRolMaestro(List<TmsRolesMaestroTbl> plistaRolesMaestro) {
        this.listaRolesMaestro = plistaRolesMaestro;
        initComponents();
        this.setModal(true);
        //((javax.swing.plaf.basic.BasicInternalFrameUI)this.getUI()).setNorthPane(null);
        jcmb_rolesMaestro.removeAllItems();
        for(int i=0; i<listaRolesMaestro.size();i++)
            jcmb_rolesMaestro.addItem(listaRolesMaestro.get(i).getRolMaestroNombre());
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension DilaogSize = this.getSize();
        if (DilaogSize.height > screenSize.height) {
            DilaogSize.height = screenSize.height;
        }
        if (DilaogSize.width > screenSize.width) {
            DilaogSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - DilaogSize.width ) / 2, ( screenSize.height - DilaogSize.height ) / 2 );    
        jtbl_rolesBase.setModel(modeloRolesBase);
        jtbl_rolesBase.setSurrendersFocusOnKeystroke(true);
        jtbl_rolesBase.setFocusTraversalKeysEnabled(false);
        jtbl_rolesBase.registerKeyboardAction( new ActionListener() { public void actionPerformed(ActionEvent e) { ; }},KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0),JComponent.WHEN_FOCUSED);
        resizeColumnasRoles();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jcmb_rolesMaestro = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jlbl_fechaInicial = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jlbl_fechaFinal = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPaneroles = new javax.swing.JScrollPane();
        jtbl_rolesBase = new javax.swing.JTable();
        jtbl_rolesBase = new JTable()
        {
            public Component prepareEditor(
                TableCellEditor editor, int row, int column)
            {

                Component c = super.prepareEditor(editor, row, column);
                if (c instanceof JTextComponent)
                {
                    ((JTextField)c).selectAll();
                }
                return c;
            }
        };
        jlbl_barraEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Roles Maestro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12)));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel2.setText("Rol Maestro:");

        jcmb_rolesMaestro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Roles Maestro" }));
        jcmb_rolesMaestro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jcmb_rolesMaestroFocusGained(evt);
            }
        });
        jcmb_rolesMaestro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jcmb_rolesMaestroKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jcmb_rolesMaestroKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Fecha Inicial:");

        jlbl_fechaInicial.setText("  ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel4.setText("Fecha Final:");

        jlbl_fechaFinal.setText("  ");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jcmb_rolesMaestro, 0, 249, Short.MAX_VALUE)
                .add(47, 47, 47)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jlbl_fechaInicial, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(35, 35, 35)
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jlbl_fechaFinal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 67, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(jcmb_rolesMaestro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4)
                    .add(jlbl_fechaFinal)
                    .add(jLabel1)
                    .add(jlbl_fechaInicial))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Roles Base", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12)));
        jtbl_rolesBase.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbl_rolesBase.setEnabled(false);
        jScrollPaneroles.setViewportView(jtbl_rolesBase);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPaneroles, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jScrollPaneroles, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 197, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jlbl_barraEstado.setFont(new java.awt.Font("Tahoma", 1, 12));
        jlbl_barraEstado.setText("jLabel3");
        jlbl_barraEstado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jlbl_barraEstado, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 43, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcmb_rolesMaestroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcmb_rolesMaestroKeyReleased
        if(evt.getKeyCode() == evt.VK_UP || evt.getKeyCode() == evt.VK_DOWN){
            SimpleDateFormat formatfc = new SimpleDateFormat ("dd/MM/yyyy");
            TmsRolesMaestroTbl rolmestro = listaRolesMaestro.get(jcmb_rolesMaestro.getSelectedIndex());//busquedas.rolesMaestroTblFacadeRemote.find(rolma.getRolMaestroId());
            jlbl_fechaInicial.setText(""+formatfc.format(rolmestro.getFechaInicial()));
            jlbl_fechaFinal.setText(""+formatfc.format(rolmestro.getFechaFinal()));
            List<TmsRolesBaseTbl> listadoRolesBase = busquedas.rolesBaseTblFacadeRemote.buscaRolBasePorRolMaestroI(rolmestro.getRolMaestroId().longValue());
            Object[][] datos = new Object[listadoRolesBase.size()][9];
             for(int i=0; i<listadoRolesBase.size(); i++){
               TmsRolesBaseTbl rolesbases =listadoRolesBase.get(i);
                 datos[i][0] = rolesbases.getRolBaseCategoria();
                 if(rolesbases.getAplicaLunes().equals("S"))
                    datos[i][1] = true;
                 else
                    datos[i][1] = false;
                 if(rolesbases.getAplicaMartes().equals("S"))
                    datos[i][2] = true;
                 else
                    datos[i][2] = false;
                 if(rolesbases.getAplicaMiercoles().equals("S"))
                    datos[i][3] = true;
                 else
                    datos[i][3] = false;
                 if(rolesbases.getAplicaJueves().equals("S"))
                    datos[i][4] = true;
                 else
                    datos[i][4] = false;
                 if(rolesbases.getAplicaViernes().equals("S"))
                    datos[i][5] = true;
                 else
                    datos[i][5] = false;
                 if(rolesbases.getAplicaSabado().equals("S"))
                    datos[i][6] = true;
                 else
                    datos[i][6] = false;
                 if(rolesbases.getAplicaDomingo().equals("S"))
                    datos[i][7] = true;
                 else
                    datos[i][7] = false;
                 datos[i][8] = rolesbases.getCantidadAutobuses().intValue();
                 //i++;
            }            
                 modeloRolesBase.setDataVector(datos,encabezadosRolesBase);
                 resizeColumnasRoles();
        }
            
    }//GEN-LAST:event_jcmb_rolesMaestroKeyReleased

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        jcmb_rolesMaestro.requestFocusInWindow();
    }//GEN-LAST:event_formComponentShown

   
    
      private void resizeColumnasRoles(){
        TableColumn columinv = jtbl_rolesBase.getColumnModel().getColumn(0); columinv.setMinWidth( 250 );columinv.setMaxWidth( 250 );columinv.setPreferredWidth(250);
        columinv = jtbl_rolesBase.getColumnModel().getColumn(1); columinv.setMinWidth(55);columinv.setMaxWidth(55);columinv.setPreferredWidth(55);
        columinv = jtbl_rolesBase.getColumnModel().getColumn(2); columinv.setMinWidth(55);columinv.setMaxWidth(55);columinv.setPreferredWidth(55);
        columinv = jtbl_rolesBase.getColumnModel().getColumn(3); columinv.setMinWidth(55);columinv.setMaxWidth(55);columinv.setPreferredWidth(55);
        columinv = jtbl_rolesBase.getColumnModel().getColumn(4); columinv.setMinWidth(55);columinv.setMaxWidth(55);columinv.setPreferredWidth(55);
        columinv = jtbl_rolesBase.getColumnModel().getColumn(5); columinv.setMinWidth(55);columinv.setMaxWidth(55);columinv.setPreferredWidth(55);
        columinv = jtbl_rolesBase.getColumnModel().getColumn(6); columinv.setMinWidth( 55 );columinv.setMaxWidth(55);columinv.setPreferredWidth(55);
        columinv = jtbl_rolesBase.getColumnModel().getColumn(7);columinv.setMinWidth(55);columinv.setMaxWidth(55);columinv.setPreferredWidth(55);        
        columinv = jtbl_rolesBase.getColumnModel().getColumn(8);columinv.setMinWidth(90);columinv.setMaxWidth(90);columinv.setPreferredWidth(90);        
        }
    
    
    
      private void jcmb_rolesMaestroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jcmb_rolesMaestroKeyPressed
         if(evt.getKeyCode() == evt.VK_ENTER){
            rolmestroseleccionado = listaRolesMaestro.get(jcmb_rolesMaestro.getSelectedIndex());//busquedas.rolesMaestroTblFacadeRemote.find(rolma.getRolMaestroId());
            System.out.println("Rol Maestro Seleccionado: "+rolmestroseleccionado.getRolMaestroNombre());
            this.dispose();
         }
        
         if(evt.getKeyCode() == evt.VK_ESCAPE)
         {
             respuestaSN = false;
             this.dispose();
         }
      }//GEN-LAST:event_jcmb_rolesMaestroKeyPressed

    private void jcmb_rolesMaestroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jcmb_rolesMaestroFocusGained
        jlbl_barraEstado.setText("<html>  <font color=FF0000> ESC </font> Cerrar | <font color=FF0000>ABAJO </font> Desplegar Roles Maestro | <font color=FF0000> ENTER </font> Seleccionar Rol Maestro  </html>"); 
    }//GEN-LAST:event_jcmb_rolesMaestroFocusGained
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPaneroles;
    private javax.swing.JComboBox jcmb_rolesMaestro;
    private javax.swing.JLabel jlbl_barraEstado;
    private javax.swing.JLabel jlbl_fechaFinal;
    private javax.swing.JLabel jlbl_fechaInicial;
    private javax.swing.JTable jtbl_rolesBase;
    // End of variables declaration//GEN-END:variables
    private TmsRolesManagedBean busquedas = new TmsRolesManagedBean();
    List<TmsServiciosTbl> listaServicios;
    private Object[] encabezadosRolesBase = {"Categoria","Lunes","Martes","Miercoles","Jueves","Viernes","Sabado","Domingo","No Autobuses"};
    private DefaultTableModel modeloRolesBase = new DefaultTableModel(null,encabezadosRolesBase){
            public boolean isCellEditable(int row, int column) {
            if (column == 0 ||column == 1 )
               return false;
            return true;
            }
            public Class getColumnClass(int c) { 
               return getValueAt(0, c).getClass(); }
        };
    private boolean respuestaSN = true;
    private Timestamp fecha_servidor= null;     
    private long usuarioId;
    private long sesionId;
    private long servicioId=0;
    private String nombreOferta="";
    private List<TmsRolesMaestroTbl> lrolesMaestro;
    private TmsRolesMaestroTbl rolmestroseleccionado;
    private List<TmsRolesMaestroTbl> listaRolesMaestro;
        
        
        
        
      

    public TmsRolesMaestroTbl getRolmestroseleccionado() {
        return rolmestroseleccionado;
    }

    public boolean isRespuestaSN() {
        return respuestaSN;
    }
}
