/*
 * JDlgSelOperador.java
 *
 * Created on 26 de octubre de 2007, 01:52 PM
 */

package tms_estadosoperador;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import javax.swing.JComponent;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import tms_psd.SesionVenta;
import tms_psd.util.BarraMensajes;
import tms_psd.util.JDlgAceptar;

/**
 *
 * @author  ocruz
 */
public class JDlgSelOperador extends javax.swing.JDialog {
    
    /**
     * Creates new form JDlgSelOperador
     */
    public JDlgSelOperador(SesionVenta pSesionVenta) {
        this.sesionVenta = pSesionVenta;
        initComponents();
        this.setModal(true);
        this.setTitle("Busqueda de Operador");
        centrarJDialogo();
        inhabilitarF10();
    }
    
    public int getFilaAutobusSeleccionado(){ return this.Fila; }
    
    private void inhabilitarF10() {
        this.jTxtClaveOperador.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
        this.jTblOperadores.registerKeyboardAction(new ActionListener() { 
        public void actionPerformed(ActionEvent e) { ; }}, KeyStroke.getKeyStroke(KeyEvent.VK_F10, 0), JComponent.WHEN_FOCUSED);
    }
    
    private void AnchoColumnas(){
        TableColumn column = null;
        int anchoContenedor = jScpOperadores.getWidth();
        for (int i = 0; i < 2; i++) {
            column = jTblOperadores.getColumnModel().getColumn(i);
            // "Clave", "Nombre"
            switch(i){
                case 0:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.25)); break;
                case 1:  column.setPreferredWidth(Math.round(anchoContenedor*(float)0.75)); break;
            }
            column.setResizable(false);
        }
    }
    
    private void centrarJDialogo(){
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize = this.getSize();
        if (frameSize.height > screenSize.height) {
            frameSize.height = screenSize.height;
        }
        if (frameSize.width > screenSize.width) {
            frameSize.width = screenSize.width;
        }
        this.setLocation( ( screenSize.width - frameSize.width ) / 2, ( screenSize.height - frameSize.height ) / 2 );
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLblEco = new javax.swing.JLabel();
        jTxtClaveOperador = new javax.swing.JTextField();
        jScpOperadores = new javax.swing.JScrollPane();
        jTblOperadores = new javax.swing.JTable();
        jLblBarraEstado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jLblEco.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLblEco.setText("Clave Operador:");

        jTxtClaveOperador.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTxtClaveOperador.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTxtClaveOperador.setText("%");
        jTxtClaveOperador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTxtClaveOperadorKeyPressed(evt);
            }
        });

        jScpOperadores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Autobuses", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), java.awt.Color.black));
        jTblOperadores.setFont(new java.awt.Font("Tahoma", 1, 11));
        jTblOperadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTblOperadores.setModel(xListado);
        jTblOperadores.setFocusTraversalKeysEnabled(false);
        jTblOperadores.getTableHeader().setReorderingAllowed(false);
        jTblOperadores.setSelectionMode(ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jTblOperadores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTblOperadoresKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTblOperadoresKeyReleased(evt);
            }
        });

        jScpOperadores.setViewportView(jTblOperadores);

        jLblBarraEstado.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLblBarraEstado.setText("ok");
        jLblBarraEstado.setFocusable(false);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLblBarraEstado, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScpOperadores, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(jLblEco)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTxtClaveOperador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 68, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLblEco)
                    .add(jTxtClaveOperador, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScpOperadores, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLblBarraEstado))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTblOperadoresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblOperadoresKeyReleased
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_UP: case KeyEvent.VK_DOWN: 
                case KeyEvent.VK_PAGE_UP: case KeyEvent.VK_PAGE_DOWN: 
                    this.Fila=jTblOperadores.getSelectedRow();
                break;
        }
    }//GEN-LAST:event_jTblOperadoresKeyReleased

    private void jTxtClaveOperadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtClaveOperadorKeyPressed
// TODO add your handling code here:
        switch(evt.getKeyCode()){
            case KeyEvent.VK_ESCAPE: this.Fila=-1; this.dispose(); break;
            case KeyEvent.VK_ENTER: 
                if(jTxtClaveOperador.getText().equals("")){
                    DialogoAceptar = new JDlgAceptar("¡Ingrese un criterio de busqueda!", "Si desea cancelar presione ESC.", Color.RED);
                    return;
                }
                datos = sesionVenta.listaOperadores(jTxtClaveOperador.getText());
                if(datos==null){
                    DialogoAceptar = new JDlgAceptar("¡La consulta no genero resultados!", "Intentelo con otro criterio.", Color.RED);
                    jTxtClaveOperador.selectAll();
                    jTxtClaveOperador.requestFocusInWindow();
                    return;
                }
                xListado.setDataVector(datos, encabezado);
                AnchoColumnas();
                jLblBarraEstado.setText(barraMensajes.getMsgEstadosOperador(2));
                this.Fila=0;
                jTblOperadores.setColumnSelectionInterval(0,0);
                jTblOperadores.setRowSelectionInterval(0,0);
                jTblOperadores.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jTxtClaveOperadorKeyPressed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
// TODO add your handling code here:
        jLblBarraEstado.setText(barraMensajes.getMsgEstadosOperador(1));
        AnchoColumnas();
        jTxtClaveOperador.setText("%");
        jTxtClaveOperador.selectAll();
        jTxtClaveOperador.requestFocusInWindow();
    }//GEN-LAST:event_formComponentShown

    private void jTblOperadoresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTblOperadoresKeyPressed
// TODO add your handling code here:
        if(jTblOperadores.getSelectedRow()==-1) return;
        switch(evt.getKeyCode()){
            case KeyEvent.VK_F8: this.dispose(); break;
            case KeyEvent.VK_ESCAPE: this.Fila=-1; this.dispose(); break;
            case KeyEvent.VK_ENTER:
                xListado.setDataVector(null, encabezado);
                AnchoColumnas();
                this.Fila=-1;
                jLblBarraEstado.setText(barraMensajes.getMsgEstadosOperador(1));
                jTxtClaveOperador.setText("%");
                jTxtClaveOperador.selectAll();
                jTxtClaveOperador.requestFocusInWindow();
                break;
        }
    }//GEN-LAST:event_jTblOperadoresKeyPressed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLblBarraEstado;
    private javax.swing.JLabel jLblEco;
    private javax.swing.JScrollPane jScpOperadores;
    private javax.swing.JTable jTblOperadores;
    private javax.swing.JTextField jTxtClaveOperador;
    // End of variables declaration//GEN-END:variables
    private Object[] encabezado = {"Clave", "Nombre"};
    private DefaultTableModel xListado = new DefaultTableModel(null, encabezado){
            public boolean isCellEditable(int row, int col) {
                return false;
            }   
    };
    private Object[][] datos;
    private SesionVenta sesionVenta;
    private BarraMensajes barraMensajes = new BarraMensajes();

    private JDlgAceptar DialogoAceptar;
    private int Fila=-1;
}
